### ISSUE TITLE
Provide commands `up` and `down`

### ISSUE THREAD

**Issue by theHamsta** [mfussenegger/nvim-dap#10]
I have a question about a spot in the code of `nvim-dap`

https://github.com/mfussenegger/nvim-dap/blob/0426d8427b2b407c7ae16f3d05090cea59d55ec5/lua/dap.lua#L287
```
      for _, frame in pairs(frames_resp.stackFrames) do
        if not current_frame then
          current_frame = frame
          self.current_frame = frame
        end
        frames[frame.id] = frame
      end
```
Why is pairs instead of `ipairs` used and `frames.id` instead of `i` doesn't this cause us to loose track of the order of the frames?

I would love to  have the commands `up` and `down` in repl where you can quickly switch between the different stack levels without any stepping. When using a stepping command, the debugger would first return to the current frame before the actual stepping command is applied. So `step_over` `step_out` is always relative to the current stack frame. gdb and pdb both provide those two commands and I really missed them when using vscode for debugging.

**Comment by mfussenegger** [comment]
> Why is pairs instead of ipairs used 

For arrays `pairs` and `ipairs` behave the same. E.g. `pairs({'one', 'two', 'three'})` and `ipairs({'one', 'two', 'three'})` returns the same. It only makes a difference with associative tables.

> frames.id instead of i

No real reason I guess. I think in my tests the frame id happened to be in the right order, so it worked but probably by accident. 
Could/should be changed to something like:

```
--- a/lua/dap.lua
+++ b/lua/dap.lua
@@ -291,7 +291,7 @@ function Session:event_stopped(stopped)
           current_frame = frame
           self.current_frame = frame
         end
-        frames[frame.id] = frame
+        table.insert(frames, frame)
       end
       if not current_frame then
         return
```


> I would love to have the commands up and down in repl where you can quickly switch between the different stack levels without any stepping. 

Sounds great to me. Do you want to make that addition?

**Comment by theHamsta** [comment]
I can do it. But I don't know when I find time for it. Maybe tomorrow.

**Comment by mfussenegger** [comment]
Closed via https://github.com/mfussenegger/nvim-dap/commit/c12968857825f97c3b0d293b8531ec4d4762f4a3
