### ISSUE TITLE
Nvim-Dap and debugpy fail to debug python files

### ISSUE THREAD

**Issue by xuyastc** [mfussenegger/nvim-dap#1009]
### Problem Statement

**Why do I fail to debug python files? Please help me，tell me why why why**

![](https://user-images.githubusercontent.com/37319368/260318910-6bfa4088-e84f-442f-9cd7-0215149f6c69.png)

![](https://user-images.githubusercontent.com/37319368/260318975-d00bbe49-8d97-4d90-883c-42fe510efa56.png)

-- python config
local dap = require('dap')
dap.adapters.python = {
type = "executable";
command = '/usr/local/bin/python3';
args = { '-m', 'debugpy.adapter' };
}

local get_args = function()
local cmd_args = vim.fn.input('CommandLine Args:')
local params = {}
local sep = "%s"
for param in string.gmatch(cmd_args, "[^%s]+") do
table.insert(params, param)
end
return params
end;

dap.configurations.python = {
{
type = 'python';
request = 'launch';
name = 'launch file';
program = '${file}';
args = get_args;
pythonpath = function()
return '/usr/local/bin/python3'
end;
},
}

![](https://user-images.githubusercontent.com/37319368/260319023-7a09ee25-0da2-4bdc-8438-662c64c6d4c4.png)

![](https://user-images.githubusercontent.com/37319368/260319038-000d709c-02d0-432c-af07-6e3e448d0712.png)

![](https://user-images.githubusercontent.com/37319368/260319050-31ac6c69-30b8-4008-95fa-c795ba76c87a.png)

**Comment by mfussenegger** [comment]
I suspect that mason doesn't install debugpy globally. So your `/usr/local/bin/python3` interpreter can't find it.

Check the logs and install debugpy correctly. Either check mason docs or follow the wiki.

This is a bug tracker, not a support forum
