### ISSUE TITLE
require'dap.utils'.pick_process does not work with filter name

### ISSUE THREAD

**Issue by codeprefect** [mfussenegger/nvim-dap#1015]
### Debug adapter definition and debug configuration

```[lua]
dap.adapters = {                 
  coreclr = {
    args = { "--interpreter=vscode" },
    command = "/Users/***/.local/share/nvim/mason/bin/netcoredbg",
    type = "executable"
  },
}

dap.configurations = {
    cs = {
    {
      name = "Attach to process (DAP)",
      processId = require'dap.utils'.pick_process { filter = "AppName" },
      request = "attach",
      type = "coreclr"
    }
}
```

### Steps to Reproduce

Start a .NET Core project from the command line
Modify the name in the configuration filter to match the app name
Start dap and choose "Attach to process (DAP)"
Picker shows a list of matching processes (usually 1 if the name is an exact match)

### Expected Result

Debugger is attached to running application

### Actual Result

Dap fails to attach debugger.

NOTE: The same exact configuration works if the filter is removed.

**Comment by mfussenegger** [comment]
You're calling the function eagerly on definition. You need to call it on use

```lua
dap.configurations.cs = {
    {
      name = "Attach to process (DAP)",
      processId = function() return require'dap.utils'.pick_process { filter = "AppName" } end,
      request = "attach",
      type = "coreclr"
    },
}
```

**Comment by codeprefect** [comment]
Hi @mfussenegger,

It also fails with when wrapped in the function like shown in your example.
It fails with the error

```
Failed command 'configurationDone' : 0x80131c08
```

Like I said earlier, it works without the filter, but then I have to scan through the long list of all running processes.
