### ISSUE TITLE
Wiki edit: dotnet

### ISSUE THREAD

**Issue by Zeioth** [mfussenegger/nvim-dap#1017]
### Problem Statement

https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#dotnet

Under `dap.configurations.cs` add

```lua
dap.configuration.fsharp = dap.configurations.cs
```

To make it compatible with fsharp. [Tested and it works](https://github.com/Zeioth/compiler.nvim/wiki/DAP-support-F%23).

**Comment by mfussenegger** [comment]
The wiki is open for edits by anyone
