### ISSUE TITLE
codelldb with remote debugging only starts in REPL. Integrated terminal or external terminal does not work anymore.

### ISSUE THREAD

**Issue by maikelmeyers** [mfussenegger/nvim-dap#1018]
### Debug adapter definition and debug configuration

This seems to be a regression. It did work some time ago that the stdio was in the integrated terminal, but now it only outputs to the REPL.

Installed the adapter via Mason (newest version available)

Configuration is as follow:

```
dap.adapters.codelldb = {
  type = 'server',
  host = '127.0.0.1',
  port = 13000,
  executable = {
    command = os.getenv("HOME") .. '/.local/share/nvim/mason/bin/codelldb',
    args = { "--port", "13000" },
  }
}
dap.configurations.cpp = {
  {
    name = "Remote Debug with LLDB (clang)",
    type = "codelldb",
    request = "launch",
    program = "/path/to/local/built/executable",
    initCommands = {
      "platform select remote-linux",
      "platform connect connect://169.254.234.195:13000",
      "platform settings -w /path/to/bin/on/target",
      "settings set target.inherit-env false",
    },
    stopOnEntry = false,
    terminal = "integrated"
  }
}
```

### Debug adapter version

codelldb V1.92

### Steps to Reproduce

Start a debug session in a cpp file

### Expected Result

Output from stdout should be in the integrated terminal

### Actual Result

Output is shown in the REPL

**Comment by mfussenegger** [comment]
If you believe this is a regression please also specify in which version it worked. You could even use git bisect to find the commit that broke it. 

And please also provide _complete_ reproduction steps.  I need to be able to follow them.  "Start a debug session in a cpp file" does _not_ reproduce the issue.

The only recent change in this area was https://github.com/mfussenegger/nvim-dap/commit/2f28ea843bcdb378b171a66ddcd568516e431d55

If it also doesn't work before that,  the change may have happened in codelldb.
