### ISSUE TITLE
mac os m1 codelldb install with mason casue `Couldn't connect to localhost:xxx: ECONNREFUSED`, how to debug on macos arm cpu M1?

### ISSUE THREAD

**Issue by cxwx** [mfussenegger/nvim-dap#1031]
### Debug adapter definition and debug configuration

    dap.adapters.codelldb = {
      type = "server",
      host = "localhost",
      --port = "${port}",
      port = "13777",
      executable = {
        command = "codelldb",
        args = {
          "--port",
          "13777",
        },
      },
    }
 dap.configurations.cpp =  {
name = 'launch codelldb',
        type = 'codelldb',
        request = 'launch',
        program = function()
          return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
        end,
        cwd = '${workspaceFolder}',
        stopOnEntry = false,
        args = {},
}

### Debug adapter version

install by mason

### Steps to Reproduce

try a simple code 
```
#include <iostream>
#include <vector>


int main() {
  int a = 6;
  for (int i = 0; i <3; i++) {
    a++;
  }
  std::cout<<a<<std::endl;
}
```
g++ main.cpp -o main

try to debug 
```
lua require('dap').continue() 
```

### Expected Result

loaded

### Actual Result

Couldn't connect to localhost:xxx: ECONNREFUSED

try to change ports but still not work?

**Comment by qlibp** [comment]
@cxwx How you get it to work? I encounter the same problem

**Comment by ShuaiQA** [comment]
May I ask how you solved it?

**Comment by cxwx** [comment]
failed, change to lldb-vscode

> @cxwx How you get it to work? I encounter the same problem

**Comment by angles-n-daemons** [comment]
I spent some time looking at this today, the issue I found was that `localhost` was being translated at some point to the ipv6 address `::1`, while codelldb wasn't binding to it. I used instead `127.0.0.1` as the host and it worked fine.

`localhost` -> `127.0.0.1`

**Comment by FiCacic** [comment]
I also have the same problem. 
I have basic setup, installed codelldb through Mason, simple configuration but I get ECONNREFUSED. Same thing I ran on linux, and it is working fine.

Tried changing to 127.0.0.1, but that did not help
