### ISSUE TITLE
Debugger terminal does not work

### ISSUE THREAD

**Issue by rensftw** [mfussenegger/nvim-dap#1033]
### Debug adapter definition and debug configuration

Environment:
- `nvim-dap` version: 0e6b7c4
- `nvim-dap-ui` version: [`85b16ac`](https://github.com/rcarriga/nvim-dap-ui/commit/85b16ac2309d85c88577cd8ee1733ce52be8227e)
- `js-debug-adapter` aka [microsoft/vscode-js-debug](https://github.com/microsoft/vscode-js-debug): `v1.82.0`
- installed via `mason`: [`ee6a7f1`](https://github.com/williamboman/mason.nvim/commit/ee6a7f179ebf8aa9da9d53b1cf1b57d292ea0182)

Configuration:
```lua
local dap = require('dap')

dap.adapters['node-terminal'] = {
    type = 'executable',
    -- Because of mason we can use this command directly
    command = 'js-debug-adapter',
}

dap.configurations.javascript = {
        {
            type = 'node-terminal',
            request = 'launch',
            protocol = 'inspector',
            console = 'integratedTerminal',
            runtimeArgs = { '--inspect-brk', 'test.js' },
            name = 'Launch debug terminal',
            cwd = '${workspaceFolder}',
            autoAttachChildProcesses = true,
        }
}
```

<details>
<summary>For sake of completeness, here are a couple of **working** DAP configurations using the same adapter and plugin versions.
</summary>

```lua
dap.adapters['pwa-node'] = {
    type = 'server',
    host = 'localhost',
    port = '${port}',
    executable = {
        -- Because of mason we can use this command
        command = 'js-debug-adapter',
        args = { '${port}' },
    }
}

dap.configurations.javascript = {
        {
            type = 'pwa-node',
            request = 'launch',
            name = 'Launch file',
            program = '${file}',
            cwd = '${workspaceFolder}',
        },
        {
            type = 'pwa-node',
            request = 'attach',
            name = 'Attach to process',
            processId = require 'dap.utils'.pick_process,
            cwd = '${workspaceFolder}',
        },

}
```

</details>

### Debug adapter version

v1.82.0

### Steps to Reproduce

Example file to debug:
```js
function greet(name) {
    console.log('🏀  Hello', name);
}

function foo() {
    greet('world');
}

foo()
```
1. Place a breakpoint on line 6 -> `greet('world');`
2. Begin debugging with `lua require('dap').continue()` and choose `Launch debug terminal` configuration
3. Observe the messages: `Debug adapter didn't respond. (...)`

### Expected Result

A new debugger terminal is spun up where I can type `node test.js` and begin debugging the script.
I'm assuming this would be the console that `nvim-dap-ui` already provides?

### Actual Result

A new Node server gets spun up with an **IPv6** address and is listening to port `:8123`, however Neovim reports that the DAP debug adapter never responds. 

<img width="1800" alt="image" src="https://github.com/mfussenegger/nvim-dap/assets/22574186/699750a8-b513-401d-bb9d-852b9e91d16f">

Here's the full trace-level log from`~/.cache/nvim/dap.log`
```sh
[ DEBUG ] 2023-09-08T17:05:30Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1361 ]	"Spawning debug adapter"	{
  command = "js-debug-adapter",
  type = "executable"
}
[ DEBUG ] 2023-09-08T17:05:30Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1672 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsProgressReporting = true,
    supportsRunInTerminalRequest = true,
    supportsStartDebuggingRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
```

Also, the IPv6 Node server does not get properly closed even after `require('dap').terminate({ terminateDebugee = true })` - could this be related to #446 ?

**Comment by rensftw** [comment]
Forgot to add:

I experimented with `mxsdev/nvim-dap-vscode-js` and bumped in the same issue as [mxsdev/nvim-dap-vscode-js/issues/53]( https://github.com/mxsdev/nvim-dap-vscode-js/issues/53)

I have other `vscode-js-debug` configs that work without `nvim-dap-vscode-js` (see <details> tag in the description above ☝️) , so it's probably safe to eliminate it as a factor in this issue

**Comment by rensftw** [comment]
I kept experimenting and made some progress:
The issue persists, but using `type = 'server'` for the `node-terminal` DAP adapter yields more comprehensive logs. Here's the new iteration of the config:
```lua
local dap = require('dap')

dap.adapters['node-terminal'] = {
    type = 'server',
    host = 'localhost',
    port = '${port}',
    executable = {
        -- Because of mason we can use this command
        command = 'js-debug-adapter',
        args = { '${port}' },
    }
}

dap.configurations.javascript = {
    dap.adapters['node-terminal'] = {
        type = 'server',
        host = 'localhost',
        port = '${port}',
        executable = {
            -- Because of mason we can use this command
            command = 'js-debug-adapter',
            args = { '${port}' },
        }
    }
}
```

This time there are 8 messages going back and forth, ultimately it looks like after the launch request (message 6) is sent the session is immediately terminated (message 7); I'm attaching the full log below 👇 

<details>
<summary>Full log for <code>~/.cache/nvim/dap.log</code></summary>
<pre><code>

[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1165 ]	"Starting debug adapter server executable"	{
  args = { "58829" },
  command = "js-debug-adapter"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1290 ]	"Debug adapter server executable started, listening on 58829"
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1294 ]	"Connecting to debug adapter"	{
  executable = {
    args = { "58829" },
    command = "js-debug-adapter"
  },
  host = "localhost",
  port = 58829,
  type = "server"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1672 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsProgressReporting = true,
    supportsRunInTerminalRequest = true,
    supportsStartDebuggingRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:950 ]	1	{
  body = {
    additionalModuleColumns = {},
    completionTriggerCharacters = { ".", "[", '"', "'" },
    exceptionBreakpointFilters = { {
        conditionDescription = 'error.name == "MyError"',
        default = false,
        description = "Breaks on all throw errors, even if they're caught later.",
        filter = "all",
        label = "Caught Exceptions",
        supportsCondition = true
      }, {
        conditionDescription = 'error.name == "MyError"',
        default = false,
        description = "Breaks only on errors or promise rejections that are not handled.",
        filter = "uncaught",
        label = "Uncaught Exceptions",
        supportsCondition = true
      } },
    supportTerminateDebuggee = true,
    supportedChecksumAlgorithms = {},
    supportsBreakpointLocationsRequest = true,
    supportsClipboardContext = true,
    supportsCompletionsRequest = true,
    supportsConditionalBreakpoints = true,
    supportsConfigurationDoneRequest = true,
    supportsDebuggerProperties = false,
    supportsDelayedStackTraceLoading = true,
    supportsEvaluateForHovers = true,
    supportsEvaluationOptions = false,
    supportsExceptionFilterOptions = true,
    supportsExceptionInfoRequest = true,
    supportsExceptionOptions = false,
    supportsFunctionBreakpoints = false,
    supportsGotoTargetsRequest = false,
    supportsHitConditionalBreakpoints = true,
    supportsLoadedSourcesRequest = true,
    supportsLogPoints = true,
    supportsModulesRequest = false,
    supportsReadMemoryRequest = true,
    supportsRestartFrame = true,
    supportsRestartRequest = true,
    supportsSetExpression = true,
    supportsSetSymbolOptions = false,
    supportsSetVariable = true,
    supportsStepBack = false,
    supportsStepInTargetsRequest = true,
    supportsTerminateRequest = false,
    supportsTerminateThreadsRequest = false,
    supportsValueFormattingOptions = true,
    supportsWriteMemoryRequest = true
  },
  command = "initialize",
  request_seq = 0,
  seq = 1,
  success = true,
  type = "response"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1672 ]	"request"	{
  arguments = {
    cwd = "/Users/benihime/.dotfiles",
    name = "Launch debug terminal",
    request = "launch",
    type = "node-terminal"
  },
  command = "launch",
  seq = 1,
  type = "request"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:950 ]	1	{
  body = vim.empty_dict(),
  event = "initialized",
  seq = 2,
  type = "event"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1672 ]	"request"	{
  arguments = {
    breakpoints = { {
        line = 6
      } },
    lines = { 6 },
    source = {
      name = "test.js",
      path = "/Users/benihime/.dotfiles/test.js"
    },
    sourceModified = false
  },
  command = "setBreakpoints",
  seq = 2,
  type = "request"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:950 ]	1	{
  body = {
    breakpoints = { {
        id = 1,
        message = "breakpoint.provisionalBreakpoint",
        verified = false
      } }
  },
  command = "setBreakpoints",
  request_seq = 2,
  seq = 3,
  success = true,
  type = "response"
}
[ INFO ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:888 ]	"Server rejected breakpoint"	{
  id = 1,
  message = "breakpoint.provisionalBreakpoint",
  verified = false
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1672 ]	"request"	{
  arguments = {
    filters = {}
  },
  command = "setExceptionBreakpoints",
  seq = 3,
  type = "request"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:950 ]	1	{
  body = vim.empty_dict(),
  command = "setExceptionBreakpoints",
  request_seq = 3,
  seq = 4,
  success = true,
  type = "response"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1672 ]	"request"	{
  command = "configurationDone",
  seq = 4,
  type = "request"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:950 ]	1	{
  body = vim.empty_dict(),
  command = "configurationDone",
  request_seq = 4,
  seq = 5,
  success = true,
  type = "response"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:950 ]	1	{
  body = {
    category = "telemetry",
    data = {
      adapterVersion = "1.82.0",
      nodeVersion = "v18.16.0",
      os = "darwin arm64",
      parameters = '{"type":"node-terminal","name":"<string>","request":"launch","trace":false,"outputCapture":"console","timeout":10000,"timeouts":{},"showAsyncStacks":{"onceBreakpointResolved":16},"skipFiles":["<string>"],"smartStep":true,"sourceMaps":true,"sourceMapRenames":true,"pauseForSourceMap":false,"resolveSourceMapLocations":null,"outFiles":["<string>"],"sourceMapPathOverrides":{"webpack:///./~/*":"<string>","webpack:////*":"<string>","webpack://@?:*/?:*/*":"<string>","webpack://?:*/*":"<string>","webpack:///([a-z]):/(.+)":"<string>","meteor://💻app/*":"<string>"},"enableContentValidation":true,"cascadeTerminateToConfigurations":[],"__workspaceFolder":"<string>","__breakOnConditionalError":false,"cwd":"<string>","env":{},"envFile":null,"localRoot":null,"remoteRoot":null,"autoAttachChildProcesses":true,"runtimeSourcemapPausePatterns":[]}',
      request = "launch",
      type = "node-terminal"
    },
    output = "js-debug/launch"
  },
  event = "output",
  seq = 6,
  type = "event"
}
[ INFO ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:744 ]	"Telemetry"	"js-debug/launch"
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:950 ]	1	{
  body = {
    restart = false
  },
  event = "terminated",
  seq = 7,
  type = "event"
}
[ DEBUG ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:950 ]	1	{
  body = vim.empty_dict(),
  command = "launch",
  request_seq = 1,
  seq = 8,
  success = true,
  type = "response"
}
[ ERROR ] 2023-09-08T21:15:59Z+0300 ] ...hime/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:958 ]	"No callback found. Did the debug adapter send duplicate responses?"	{
  body = vim.empty_dict(),
  command = "launch",
  request_seq = 1,
  seq = 8,
  success = true,
  type = "response"
}

</code></pre>

</details>

**Comment by TylerBarnes** [comment]
@rensftw I'm trying to understand this as well. What's the difference betwen pwa-node and node-terminal? I can get pwa-node working no problem, but not node-terminal. What are you trying to achieve? Are you looking to debug from nvim's integrated terminal and not from dap-ui's repl view?

**Comment by rensftw** [comment]
>What are you trying to achieve?

@TylerBarnes I am trying to debug `package.json` scripts without adding a new config for each command.
My usecase is for projects where an individual `package.json` script calls multiple Node scripts, or debugging a process launched by an abstraction over Node eg `yarn build` or `nx serve`.

Ideally I want to give DAP a command to run and debug.

>Are you looking to debug from nvim's integrated terminal and not from dap-ui's repl view?

I don't have preferences about which terminal is used, the point is to be able to provide the command to be debugged.

Btw, I have been trying out the direction of this guide https://zignar.net/2023/02/17/debugging-neovim-with-neovim-and-nvim-dap/ by @mfussenegger because seems to achieve what I described by spawning a new Alacritty terminal. 
I haven't had any luck yet, but you might find it useful @TylerBarnes :)

**Comment by mfussenegger** [comment]
It looks like the vscode extension contains special logic for the terminal:

https://github.com/microsoft/vscode-js-debug/blob/eb545faf20e798ca6abcd9a11cc89af4422b4467/src/ui/debugTerminalUI.ts#L37
https://github.com/microsoft/vscode-js-debug/blob/eb545faf20e798ca6abcd9a11cc89af4422b4467/src/targets/delegate/delegateLauncher.ts#L22


I suspect this isn't going to work with a plain DAP client but requires custom terminal logic. 
Maybe you can ask in the vscode-js-debug repository for more details on how it works and what's required for other clients to support it. 

For now I consider this out of scope for nvim-dap, but I'm open to talk about extension points once someone can give a high level description of how it works and what would be required for a nvim-dap extension to support it.
