### ISSUE TITLE
REPL autocompletion is a bit messy with vscode-cpptools.

### ISSUE THREAD

**Issue by Alexey104** [mfussenegger/nvim-dap#1037]
### Debug adapter definition and debug configuration

```
local home=os.getenv( "HOME" )
local gdb_path = home .. "/.config/nvim/gdb/extension/debugAdapters/bin/OpenDebugAD7"

local dap = require('dap')

dap.adapters.cppdbg = {
  id = 'cppdbg',
  type = 'executable',
  command = gdb_path,
}

dap.configurations.cpp = {
  {
    name = "Launch file",
    type = "cppdbg",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopAtEntry = true,
  },
  {
    name = 'Attach to gdbserver :1234',
    type = 'cppdbg',
    request = 'launch',
    MIMode = 'gdb',
    miDebuggerServerAddress = 'localhost:1234',
    miDebuggerPath = '/usr/bin/gdb',
    cwd = '${workspaceFolder}',
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
  },
}

setupCommands = {
  {
     text = '-enable-pretty-printing',
     description =  'enable pretty printing',
     ignoreFailures = false
  },
}
```

### Debug adapter version

vscode-cpptools v1.17.5

### Steps to Reproduce

1) Create a functions called `some_function()`.
2) Open the REPL window, switch to it and enter insert mode.
3) Type `-exec b some`:
![repl](https://github.com/mfussenegger/nvim-dap/assets/38672094/536700cf-80f0-4048-8e6c-4916ea13aa99)
4) Press `<C-x><C-o>` to trigger autocompletion:
![completion](https://github.com/mfussenegger/nvim-dap/assets/38672094/048b1f43-a3e1-4c5f-8981-ea014438fe91)

### Expected Result

The completed suggestion should overwrite the entire line:
`-exec b some_function()`

### Actual Result

The completed suggestion is appended to what was typed before triggering the completion:
`-exec b -exec b some_function()`

**Comment by mfussenegger** [comment]
Can you try with https://github.com/mfussenegger/nvim-dap/pull/1038 ?  It should fix this.

**Comment by Alexey104** [comment]
Confirm, this fix works.
Thank you so much!
