### ISSUE TITLE
REPL autocompletion - some minor bugs still occur after merging #1038.

### ISSUE THREAD

**Issue by Alexey104** [mfussenegger/nvim-dap#1039]
### Debug adapter definition and debug configuration

```
local home=os.getenv( "HOME" )
local gdb_path = home .. "/.config/nvim/gdb/extension/debugAdapters/bin/OpenDebugAD7"

local dap = require('dap')

dap.adapters.cppdbg = {
  id = 'cppdbg',
  type = 'executable',
  command = gdb_path,
}

dap.configurations.cpp = {
  {
    name = "Launch file",
    type = "cppdbg",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopAtEntry = true,
    setupCommands = {
        {
            text = '-enable-pretty-printing',
            description =  'enable pretty printing',
            ignoreFailures = false
        },
        {
            text = 'set follow-fork-mode parent',
            description =  'follow parent process',
            ignoreFailures = false
        },
        {
            text = 'set detach-on-fork off',
            description =  'disable detach on fork',
            ignoreFailures = false
        },
    },
  },
}
```

### Debug adapter version

vscode-cpptools v1.17.5

### Steps to Reproduce

1) In the REPL window type `-exec i bre`:
![repl](https://github.com/mfussenegger/nvim-dap/assets/38672094/0ddd7f8d-5fd6-4c38-9fce-bb502090822f)
2) Press `<C-x><C-o>` to trigger autocompletion:
![completion](https://github.com/mfussenegger/nvim-dap/assets/38672094/8faf866f-8225-4634-a7f6-8814f8e1f64b)
3) Press `<CR>` to confirm the suggestion:
![2023-09-15_10-59](https://github.com/mfussenegger/nvim-dap/assets/38672094/cd8085b4-754c-4a7c-87a5-5cb71c774a45)

### Expected Result

The completed command should be `exec -i breakpoints`.

### Actual Result

An additional random(?) character is appended to the end of the command.

**Comment by mfussenegger** [comment]
What are your `complete` and `completeopt` settings? I'm not seeing any additional characters. `-exec i bre` completes to `-exec i breakpoints` for me.

**Comment by Alexey104** [comment]
> What are your `complete` and `completeopt` settings?

```
complete=.,w,b,u,t
completeopt=menu,preview
```



> `-exec i bre` completes to `-exec i breakpoints` for me.

Yes, it completes correctly for me too, but after pressing `Return` a garbage character is appended at the end. I also see this behavior when setting breakpoints at some (but not all) functions.

**Comment by Alexey104** [comment]
Hmm...
Maybe any of my other plugins causes this. When I have more time I'll try to disable everything besides nvim-dap and test. I'll report back if I find anything.

**Comment by Alexey104** [comment]
Ok, Coc.nvim plugin was a culprit, specifically these lines:
```
if exists('*complete_info')
    inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
    inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif
```
Sorry for wasting your time, I should've checked with clean config right away before reporting a bug.
