### ISSUE TITLE
Calling `toggle` multiple times on a widget causes the new text to get appended instead of replaced

### ISSUE THREAD

**Issue by TheLeoP** [mfussenegger/nvim-dap#1042]
### Debug adapter definition and debug configuration

Install any adapter and use any valid nvim-dap configuration.

### Steps to Reproduce

1. Create the following mapping to toggle a widget (any widget is fine, not only scopes)

```lua
local scopes = require("dap.ui.widgets").scopes
local sidebar_scopes = require("dap.ui.widgets").sidebar(scopes)
vim.keymap.set("n", "<F5>", function()
  sidebar_scopes.toggle()
end)
```

2. Start a debugging session (with any adapter)
3. Press `<F5>` three times (open it, close it and open it again)

### Expected Result

The widget content should be shown only one time.

### Actual Result

The widget content is shown two times (and if we keep toggling the widgets, each time it gets opened it's content is appended one more time).

**Comment by NSteinhoff** [comment]
Hi @TheLeoP, does this work as expected for you? With this change my scope sidebar never updates.

```
local ui = require("dap.ui.widgets")
local scopes_sidebar = ui.sidebar(ui.scopes, { width = 30 }, "leftabove vertical split")

-- and then in a mapping/command
scopes_sidebar.open()
```

**Comment by TheLeoP** [comment]
@NSteinhoff . Yeah, this does work as expected for me. Do you have a minimal reproduction? What do you mean by "never updates"? Is it not updating when the debugger passes to a new frame? If you call `scopes_sidebar.open()` multiple times? Something entirely different?

**Comment by NSteinhoff** [comment]
Hi @TheLeoP, 

The problem wasn't that it isn't updating, but that by setting `lnum` end `end`, it always overwrites. When you have multiple scopes, then only the last one will be visible. It simply looked like nothing was changing for me.

https://github.com/mfussenegger/nvim-dap/pull/1060

**Comment by ktakiman** [comment]
@NSteinhoff @TheLeoP I'm seeing a similar regression on REPL window.  `.scopes` command now clears the buffer, and only the last scope is displayed.  Previously, the buffer wasn't cleared and all the scopes are displayed under REPL window.  I'm also seeing scopes gadget (both sidebar and floating window) only shows the last scope.  The same observation as @NSteinhoff .  Thanks!!

**Comment by ktakiman** [comment]
Hi @NSteinhoff , yes #1060 fixes the issues I'm seeing :+1:
