### ISSUE TITLE
nvim-dap is immediately closed after starting.

### ISSUE THREAD

**Issue by harisonkhlil** [mfussenegger/nvim-dap#1048]
### Debug adapter definition and debug configuration

```lua
-- Dap for c/c++
dap.adapters.codelldb = {
  type = "server",
  port = "${port}",
  executable = {
    command = "/Users/xxx/.vscode/extensions/vadimcn.vscode-lldb-1.10.0/adapter/codelldb",
    args = { "--port", "${port}" },
  },
}

dap.configurations.cpp = {
  {
    name = "Launch file",
    type = "codelldb",
    request = "launch",
    program = function()
      return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/build/", "file")
    end,
    cwd = "${workspaceFolder}",
    stopOnEntry = false,
  },
}
```

### Debug adapter version

1.10

### Steps to Reproduce

Please watch the video below:

![video](https://s2.loli.net/2023/10/07/zEDBcM4drboq2f6.gif)

### Expected Result

Successfully run to breakpoint.

### Actual Result

Crash

[dap.log](https://github.com/mfussenegger/nvim-dap/files/12837672/dap.log)

**Comment by mfussenegger** [comment]
Make sure you compile your program with debug symbols, otherwise it cannot resolve the breakpoints.

See also https://github.com/mfussenegger/nvim-dap/wiki/Debug-symbols-in-various-languages-and-build-systems
