### ISSUE TITLE
Saving current configurations to launch json

### ISSUE THREAD

**Issue by asmodeus812** [mfussenegger/nvim-dap#1051]
### Problem Statement

Would be cool if we could save the current set of configs to a launch json file, or have an api to which we can pass a list of configs we would like to save. 

### Considered Alternatives

Serializing the lua tables to files, instead of json, but it won't be very portable i.e for vscode users.

**Comment by MahboobMMonza** [comment]
I had a similar suggestion to this. Plugins like `nvim-jdtls` do quite a bit of setup for the debug configs, but I want to add additional changes to that as well inside the `launch.json` on a per-project basis.

**Comment by mfussenegger** [comment]
Thanks for the suggestion but I won't be adding this.

- nvim-dap by default contains no configuration generation. Saving configurations you couldn't generate seems odd.
- Lua is a superset of JSON as JSON can't represent the functions
- Some of the plugins which can generate configurations are also dynamically adding properties. You probably don't want to include these in the persisted JSON config. nvim-dap by itself doesn't know what properties would get dynamically resolved or not. For example. nvim-jdtls always generates `javaExec`, `classpath` and `modulePaths` entries. In most cases you wouldn't want to include them.


If you can ignore those two aspects, it's pretty simple to do anyways:


```lua
local f = assert(io.open(".vscode/launch.json", "w"))
local launch = {
    version = "0.2.0",
    configurations = require("dap").configurations.java
}
f:write(vim.json.encode(launch))
f:close()
```

And to format it using `jq`, add:

```lua
local obj = vim.system({"jq", ".", ".vscode/launch.json"}, { text = true }):wait()
f = assert(io.open(".vscode/launch.json", "w"))
f:write(obj.stdout)
f:close()
```
