### ISSUE TITLE
codelldb automatically launch fail

### ISSUE THREAD

**Issue by qlibp** [mfussenegger/nvim-dap#1057]
### Debug adapter definition and debug configuration

use the configuration from this [repo link](https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(via--codelldb)#ccrust-via-codelldb)

verified that commit e71da68e59eec1df258acac20dad206366506438 works, but master commit fail.

error due to `${port}` not parsed successfully.

### Debug adapter version

1.10.0

### Steps to Reproduce

1. `:DAPcontinue`
2. `connect() #2 argument invalid, error return nil, expected number`

### Expected Result

stated above

### Actual Result

stated above

**Comment by mfussenegger** [comment]
Works fine for me. Can't reproduce and the reproduction steps are not nearly enough

**Comment by qlibp** [comment]
Not sure the reason why, but I could confirm that for now, when I switch back the master branch, dap works fine. The only difference is that I also use dap-ui, which is quite weird...
