### ISSUE TITLE
Local variables are not shown in widgets.scopes after applying 92dc531.

### ISSUE THREAD

**Issue by Alexey104** [mfussenegger/nvim-dap#1066]
### Debug adapter definition and debug configuration

```
local home=os.getenv( "HOME" )
local gdb_path = home .. "/.config/nvim/gdb/extension/debugAdapters/bin/OpenDebugAD7"

local dap = require('dap')

dap.adapters.cppdbg = {
  id = 'cppdbg',
  type = 'executable',
  command = gdb_path,
}

dap.configurations.cpp = {
  {
    name = "Launch file",
    type = "cppdbg",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopAtEntry = true,
    setupCommands = {
        {
            text = 'set debuginfod enabled on',
            description =  'enable debuginfod',
            ignoreFailures = false
        },
        {
            text = '-enable-pretty-printing',
            description =  'enable pretty printing',
            ignoreFailures = false
        },
    },
  },
}
```

### Debug adapter version

vscode-cpptools v1.17.5

### Steps to Reproduce

1) Inside any cpp function call `widgets.centered_float(widgets.scopes)`.

### Expected Result

In addition to the content of registers, you should be able to see local variables from the current scope:
![Before](https://github.com/mfussenegger/nvim-dap/assets/38672094/99df42a4-2d2f-47b5-a52a-7890550feb4a)

### Actual Result

Starting with commit 92dc531eea2c9a3ef504a5c8ac0decd1fa59a6a3 and later there are no locals listed anymore, but only the registers:
![After](https://github.com/mfussenegger/nvim-dap/assets/38672094/79c70390-f9dc-45c7-afd3-aa0d0f56f392)

**Comment by Fabian-programmer** [comment]
Having the same problem. Thanks for investigating, was about to do the same

**Comment by Alexey104** [comment]
@mfussenegger, #1060 fixed the problem.
Thank you a lot!
