### ISSUE TITLE
LLDB terminate without exception

### ISSUE THREAD

**Issue by jasuramme** [mfussenegger/nvim-dap#1075]
### Debug adapter definition and debug configuration

installed adapter: lldb-vscode, installed via pacman manager pacman -S lldb (version 16.0.6-1 package)
configuration:
local dap = require('dap')
dap.adapters.lldb = {
  type = 'executable',
  command = '/usr/bin/lldb-vscode', -- adjust as needed, must be absolute path
  name = 'lldb'
}

local dap = require('dap')
dap.adapters.lldb = {
  type = 'executable',
  command = '/usr/bin/lldb-vscode', -- adjust as needed, must be absolute path
  name = 'lldb'
}

### Debug adapter version

16.0.6

### Steps to Reproduce

g++ ./main.cpp -g
nvim 
:e main.cpp
:lua require'dap'.continue()
Path to executable: /mnt/sda5/workspace/nvim-training/bug/a.out
:lua require'dap'.continue()

### Expected Result

Debug session running

### Actual Result

lldb terminate without exception and log message to create a bug
See log in the file:
[dap.log](https://github.com/mfussenegger/nvim-dap/files/13223824/dap.log)
All project files including compiled binary and settings:
[files.zip](https://github.com/mfussenegger/nvim-dap/files/13223828/files.zip)

**Comment by mfussenegger** [comment]
> lldb terminate without exception and log message to create a bug

It says to create the bug report at https://github.com/llvm/llvm-project/issues/

Judging from the log, the client works correctly.
