### ISSUE TITLE
Cortex Debug Support

### ISSUE THREAD

**Issue by VaheDanielyan** [mfussenegger/nvim-dap#1086]
### Problem Statement

The only thing keeping me from ditching vscode fully is support for cortex debug in nvim dap. To debug my stm32 projects I go back to vscode which I hate.
Is it possible to support this properly? https://github.com/Marus/cortex-debug

**Comment by mfussenegger** [comment]
See https://github.com/jedrzejboczar/nvim-dap-cortex-debug
