### ISSUE TITLE
Feature Idea: nvim-treesitter integration

### ISSUE THREAD

**Issue by theHamsta** [mfussenegger/nvim-dap#11]
Just writing down here some ideas to evaluate whether an integration with the abstraction layer https://github.com/nvim-treesitter/nvim-treesitter or just the built-in tree-sitter might be worth considering. Treesitter can parser our files and could help with DAP's ui.

E.g.

* Display virtual text with the current values of the locals where the locals are used in the code
* Find current scope of frame and locals
* Help with things like "Evaluate expression" under cursor (this might also be possible by an evaluate textobj, nvim-treesitter provides a textobj for the currently selected syntax node)

**Comment by mfussenegger** [comment]
I think using treesitter for those things would be feasible. But I wouldn't go with the `nvim-treesitter` abstractions, but rather with the built-in's direclty. Depending on another plugin would close the door to https://github.com/neovim/neovim/issues/11732

> Help with things like "Evaluate expression" under cursor

I think as a first step `dap` could provide a low-level function that interacts well with selections and textobj. So it would be up for users to define their textobjs (or use plugins that define them) and `dap` wouldn't depend on any concrete implementations.
