### ISSUE TITLE
Hover evaluates the expression with `context = 'repl'` instead of `hover`

### ISSUE THREAD

**Issue by aikixd** [mfussenegger/nvim-dap#1107]
### Debug adapter definition and debug configuration

Any config. I've discovered it with rust-tools using lldb.
The issue is that the evaluation is called with `context = 'repl'` [here](https://github.com/mfussenegger/nvim-dap/blob/62b0beadbc468501a2384fb184167d66a88a3143/lua/dap/session.lua#L1771), invoked [here](https://github.com/mfussenegger/nvim-dap/blob/62b0beadbc468501a2384fb184167d66a88a3143/lua/dap/ui/widgets.lua#L350), through the [widget](https://github.com/mfussenegger/nvim-dap/blob/62b0beadbc468501a2384fb184167d66a88a3143/lua/dap/ui/widgets.lua#L496C33-L496C33)
It should be called with 'hover' as stated in the [spec](https://microsoft.github.io/debug-adapter-protocol/specification)

### Steps to Reproduce

1. Pause somewhere
2. Use `require('dap.ui.widgets').hover()`

### Expected Result

A hover window with the evaluation result.

### Actual Result

The float contains `Cannot evaluate "xxx"!`

**Comment by mfussenegger** [comment]
Changed it in https://github.com/mfussenegger/nvim-dap/pull/1108, but from what I can tell the evaluation should've worked with `repl` as well and in my tests it worked with both codelldb and lldb-dap

**Comment by aikixd** [comment]
Much love!
