### ISSUE TITLE
Input in .vscode/launch.json can be asked multiple times

### ISSUE THREAD

**Issue by Diaoul** [mfussenegger/nvim-dap#1112]
### Debug adapter version

bbe2c6f3438542a37cc2141a8e385f7dfe07d87d

### Steps to Reproduce

1. Have a `.vscode/launch.json` file with the following content:
```json
{
  "tasks": [
    {
      "label": "Echo input",
      "type": "shell",
      "command": "echo ${input:echoPrompt}",
      "env": {
        "TEST_ENV": "${input:echoPrompt}"
      }
    }
  ],
  "inputs": [
    {
      "id": "echoPrompt",
      "description": "Please enter a value",
      "default": "default echo text",
      "type": "promptString"
    }
  ]
}
```

2. Run DAP

### Expected Result

I am prompted only once for the value of `echoPrompt`

### Actual Result

I am prompted twice for the value of `echoPrompt`

_Feature initially introduced with https://github.com/mfussenegger/nvim-dap/issues/551_

**Comment by mfussenegger** [comment]
Should be solved by https://github.com/mfussenegger/nvim-dap/pull/1119 but your given example launch json won't work, nvim-dap doesn't handle tasks.

**Comment by Diaoul** [comment]
Ah right, sorry for the shitty example 😬 
Thanks for fixing despite this 🙏
