### ISSUE TITLE
extmark-based sign instead of the legacy sign?

### ISSUE THREAD

**Issue by ofseed** [mfussenegger/nvim-dap#1118]
### Problem Statement

Discussions in https://github.com/neovim/neovim/pull/26193#issuecomment-1859057662 made me realize that the benefit of the extmark-based sign is you can set `line_hl_group`, which is very useful for nvim-dap.

### Possible Solutions

A noticeable highlight for the current executed line like vscode.
![image](https://github.com/mfussenegger/nvim-dap/assets/61115159/eacac1be-6c4a-42fd-a34b-5f3e6c3b3ff4)

**Comment by mfussenegger** [comment]
I don't really understand.

Signs already allow to set linehl and numhl and nvim-dap sets linehl to `debugPC` for the stopped sign / program counter.
If you set up a highlight for `debugPC` you can get a highlight for the current executed line.

Please phrase the problem statement as problem statement with a focus on end-user behavior, not on implementation details.
