### ISSUE TITLE
[Debug Config] Allow the debugger to read environment variables from "envFile" in launch.json

### ISSUE THREAD

**Issue by thanhdatvo** [mfussenegger/nvim-dap#1128]
### Problem Statement

Currently the debugger is unable to read environment variables from "envFile" in launch.json

### Possible Solutions

Please help to get environment variables from "envFile" in launch.json at set it before debugger runs, or show me where can I start to make change and create a pr.

**Comment by mfussenegger** [comment]
Duplicate of https://github.com/mfussenegger/nvim-dap/issues/543
