### ISSUE TITLE
Breakpoint symbol is not using sign column background color by default

### ISSUE THREAD

**Issue by shmerl** [mfussenegger/nvim-dap#1137]
### Steps to Reproduce

My color scheme defines one color for **Normal** and a different color for **[SignColumn](https://neovim.io/doc/user/syntax.html#hl-SignColumn)**. 

When simply placing a breakpoint, it uses background color of the editor pane (`Normal`) rather than sign column (`SignColumn`) color.

See example below (note background around symbol B):

![dap_nvim_colors](https://github.com/mfussenegger/nvim-dap/assets/310927/7f198c47-edbe-4743-8dfa-c3d23ba0505c)

### Expected Result

It would make sense for the breakpoint and other nvim-dap signs to use the background of `SignColumn` by default.

### Actual Result

Color used for breakpoint signs matches `Normal` color of the scheme.

I can work around it by setting the matching color for `SignColumn` through configuration for `DapBreakpoint`, `DapStopped` and etc. but it's not ideal and would break every time the color schema is changed.

**Comment by shmerl** [comment]
I can try fixing it, but would appreciate if you can please give any pointers where in the code the color is being set (or not set).

Thanks!

**Comment by mfussenegger** [comment]
nvim-dap doesn't define the background at all for the signs.

It is just:

```lua
DapBreakpoint = { text = "B", texthl = "", linehl = "", numhl = "" },
```

**Comment by shmerl** [comment]
Well, somehow with my theme it fell back to Normal instead of staying what was already defined, so there is some disconnect there. Using the above workaround ensures that theme defined value is used.

**Comment by shmerl** [comment]
Hm, tested it with changing your code to:

```
local signs = {
  DapBreakpoint = { text = "B", texthl = "", linehl = "SignColumn", numhl = "" },
```
And it's still wrong without the workaround!  I'd assume it's some kind of bug in neovim itself in `sign_define` possibly.

**Comment by shmerl** [comment]
OK, this fixes the bug in your code itself:

```
local signs = {
  DapBreakpoint = { text = "B", texthl = "SignColumn", linehl = "", numhl = "" },
  DapBreakpointCondition = { text = "C", texthl = "SignColumn", linehl = "", numhl = "" },
  DapBreakpointRejected = { text = 'R', texthl = 'SignColumn', linehl = '', numhl = '' },
  DapLogPoint = { text = 'L', texthl = 'SignColumn', linehl = '', numhl = '' },
  DapStopped = { text = '→', texthl = 'SignColumn', linehl = 'debugPC', numhl = '' },
}
```

Somehow setting texthl to empty doesn't use current value but simply falls back to `Normal` which is not correct.

**Comment by shmerl** [comment]
Thanks for fixing it on your side.
