### ISSUE TITLE
Linux (centos 8 with GDB 14.1) native GDB debugging session hangs

### ISSUE THREAD

**Issue by rm374** [mfussenegger/nvim-dap#1140]
### Debug adapter definition and debug configuration

dap.adapters.gdb = {
    type = "executable",
    command = "gdb",
    -- args = { "-i", "dap" } -- NOTE: this gives interpretter error in dap.log
    args = { "-i", "mi" } -- NOTE: this simply hangs in neovim
}

### Steps to Reproduce

Upgraded to latest NeoVim (0.95). Upgraded DAP and DAP-UI to latest using Lazy. I noticed that on Linux running gdb 14.1, the args -i dap result in 'Interpreter `dap` unrecognized' error. I switched to ("-i", "mi") and while that doesnt causes the gdb to exit, it goes unresponsive. I do see gdb running in terminal though.

Pasting the log from dap.out below -

[ DEBUG ] 2024-01-17T12:26:21Z-0500 ] ...1995/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1366 ]        "Spawning debug adapter"        {
  args = { "-i", "mi" },
  command = "gdb",
  type = "executable"
}
[ DEBUG ] 2024-01-17T12:26:21Z-0500 ] ...1995/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1676 ]        "request"       {
  arguments = {
    adapterID = "nvim-dap",
    clientID = "neovim",
    clientName = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsProgressReporting = true,
    supportsRunInTerminalRequest = true,
    supportsStartDebuggingRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 1,
  type = "request"
}

### Expected Result

Debugging session should continue and breakpoint should hit.

### Actual Result

nvim-dap hangs with no further errors.

**Comment by rm374** [comment]
Figured this out. Its an issue with GDB. It needs to be compiled with python support otherwise -i dap will not work. You can check if your gdb has python support by executing - gdb --config and verity that --with-python/libdir have values in them.

**Comment by mfussenegger** [comment]
Using `-i mi` does of course not work because then you're not using the debug adapter protocol.
