### ISSUE TITLE
Ability to Disable logging for repl

### ISSUE THREAD

**Issue by skela** [mfussenegger/nvim-dap#1141]
### Problem Statement

The console logs for Android can be a bit verbose + excessive, and will most often keep running when you are paused at a break point, rendering the repl function via dap useless. Unless yer insanely fast, you won't be able to type the thing you want to run, before the logs overwrite and clear the repl line.

### Possible Solutions

I typically have the logs in a completely different terminal or app anyway, so was wondering if you could add a way to disable the logging in repl, leaving it purely for repl stuff.

I'm not suggesting making it the default, just add a config flag or something where u can disable logs in repl.

If its already possible to do this, I apologize for the noise. Have looked at the help pages, without any luck.

**Comment by mfussenegger** [comment]
So far it wasn't possible - at least not without monkey patching. The only real option was to use the integrated terminal feature, which causes most debug adapters to rarely send any output events.


Given this has come up a few times I created a PR that would allow output handling customization: https://github.com/mfussenegger/nvim-dap/pull/1175

Could you try that and give some feedback?

**Comment by skela** [comment]
Sure ill give it a go as soon as I can, if i can figure out how to do it ;D

**Comment by skela** [comment]
I did give it a go, but i think im prob not putting it in the right place, could you give me a hint as to where im to add this on_output fn ?

![image](https://github.com/mfussenegger/nvim-dap/assets/58268/328fa33c-4f7a-49ae-91c8-4ff619d698b7)

**Comment by serranomorante** [comment]
> I did give it a go, but i think im prob not putting it in the right place, could you give me a hint as to where im to add this on_output fn ?
> 
> ![image](https://private-user-images.githubusercontent.com/58268/313424733-328fa33c-4f7a-49ae-91c8-4ff619d698b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzE3NDMsIm5iZiI6MTcxMDYzMTQ0MywicGF0aCI6Ii81ODI2OC8zMTM0MjQ3MzMtMzI4ZmEzM2MtNGY3YS00OWFlLTkxYzgtNGZmNjE5ZDY5OGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDIzMjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NjcwYjdkZDgxYjU3NjJhZWFiNGUwNGRkYmU1Y2Y3OGQ4NTM2Y2RiYjk1ZjU0MThmYzc5NzM1ZDNhYjJmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PncRy6g8wzfs54u9uuGyEQlGOrj7Zos71xMVtaDL4mA)

This plugin doesn't take `opts` like others. You need to explicitly add this option inside your `config = function()` like this:

```lua
local dap = require("dap")
dap.defaults.fallback.on_output = function(session, output_event) end -- this will set the option globally (all languages)

or 

dap.defaults.java.on_output = function(session, output_event) end -- this will set the option just for java
```

**Comment by icholy** [comment]
Can the `on_output` callback be used to filter events? Something like:

``` lua
local dap = require("dap")
dap.defaults.fallback.on_output = function(session, output_event)
    if not output_event:match("Could not read source map for file") then
        // output to repl
    end
end
```

I want to filter out these logs:

![image](https://github.com/mfussenegger/nvim-dap/assets/943597/809d6d37-eccd-4878-a717-64bef956e6a3)

**Comment by skela** [comment]
Works perfectly!

**Comment by icholy** [comment]
I was able to implement filtering like this:

``` lua
local dap = require("dap")
local repl = require("dap.repl")

dap.defaults.fallback.on_output = function(session, event)
	if event.category == "stdout" and not string.find(event.output, "Could not read source map for file") then
		repl.append(event.output, "$", { newline = false })
	end
end
```
