### ISSUE TITLE
Lowercase `dap` global is a bit confusing

### ISSUE THREAD

**Issue by tjdevries** [mfussenegger/nvim-dap#115]
So I know you have the `dap` global here:

```
dap = {} -- luacheck: ignore 111 - to support v:lua.dap... uses
```

But I don't think you actaully need to use `v:lua` to do the things you want to do. You could instead do:

```
let g:example_in_viml = luaeval('require("dap").do_something()')
```

or others. I know `v:lua` is a bit conveninent, but I find the global a bit confusing.

**Comment by mfussenegger** [comment]
The main reason for the global is the omnifunc in https://github.com/mfussenegger/nvim-dap/blob/6dbb5924dfecb28127171648115f2a9d8675bf0e/lua/dap/repl.lua#L233

As far as I know `luaeval` cannot be used in that context and `v:lua` is the only option, or is there another way?
Would be happy to remove it.

**Comment by tjdevries** [comment]
ah, it's a bit more complicated for that case, but I think you could do something like just making some autoload function that calls omnifunc

**Comment by tjdevries** [comment]
```vim
function dap#omnifunc(findstart, base)
  return luaeval('require("dap").omnifunc(_A.findstart, _A.base)', { "findstart": a:findstart, "base": a:base })
endfunction
```

**Comment by mfussenegger** [comment]
Do you think we could have some kind of `v:lua.require.<module>` functionality in neovim core?
