### ISSUE TITLE
Not working with php

### ISSUE THREAD

**Issue by Mte90** [mfussenegger/nvim-dap#118]
I am trying to use https://github.com/xdebug/vscode-php-debug
So I found that someone else added that support: https://github.com/tk-shirasaka/develop/blob/c9cccb92689b8a09fa02a6490cdf90e25dc37bf9/nvim/lua/plugin_settings/nvim-dap.lua#L26

So I added the code https://github.com/Mte90/dotfiles/blob/master/.config/nvim/lua/plugin/dap.lua

But I am able just to add a breakpoint if I try to run the `continue` there is the error about `No stopped thread`

**Comment by mfussenegger** [comment]
I think you've to be careful not to re-use `dap.lua` for your configuration, as it could mess with the `require('dap')` imports from nvim-dap.


Could you try setting the log level to trace (`:lua require('dap').set_log_level('trace')`) and post the outputs of on attempt to launch a debug session?
The log file is in the stdpath/cache folder (`:lua print(vim.fn.stdpath('cache'))`)

**Comment by Mte90** [comment]
Ok seems that there is something in the log: https://pastebin.com/psGNzbrB
This is what I get on nvim, nothing.
![Screenshot_20210309_161242](https://user-images.githubusercontent.com/403283/110492324-5d425000-80f2-11eb-8573-8bd44ec02516.png)

There is no panel about the state of the application.

**Comment by Mte90** [comment]
```
new connection 3

<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'started', threadId: 3 }
}


<- initializedEvent
InitializedEvent { seq: 0, type: 'event', event: 'initialized' }


-> setBreakpointsRequest
{
  seq: 8,
  arguments: {
    source: {
      path: '/home/www/VVV/www/glossary/public_html/wp-content/plugins/glossary/glossary.php',
      name: 'glossary.php'
    },
    breakpoints: [ { line: 30 } ],
    lines: [ 30 ]
  },
  type: 'request',
  command: 'setBreakpoints'
}


<- setBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 8,
  command: 'setBreakpoints',
  success: true,
  body: { breakpoints: [ { verified: true, line: 30 } ] }
}


-> setExceptionBreakpointsRequest
{
  seq: 9,
  arguments: { filters: [ '*' ] },
  type: 'request',
  command: 'setExceptionBreakpoints'
}


<- setExceptionBreakpointsResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 9,
  command: 'setExceptionBreakpoints',
  success: true
}


-> configurationDoneRequest
{ seq: 10, type: 'request', command: 'configurationDone' }


<- configurationDoneResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 10,
  command: 'configurationDone',
  success: true
}


<- threadEvent
ThreadEvent {
  seq: 0,
  type: 'event',
  event: 'thread',
  body: { reason: 'exited', threadId: 3 }
}
```

Also testing seems that if I change `stopOnEntry` as true, the file is changed in neovim, so I think that is a php-debug issue and not from dap.
Anyway I will keep you updated.

**Comment by Mte90** [comment]
Looking at what is happening is like php-debug starts the connection and after closing it.
Also in xdebug there is the log for the stop command so is not dap at all.

**Comment by Mte90** [comment]
Just for documentation I opened a ticket https://github.com/xdebug/vscode-php-debug/issues/521

**Comment by anoopd** [comment]
@Mte90  How you are debugging PHP right now ? I was using Vdebug and it was working great . Tried to switch to nvim-dap but couldn't get it working . Would like to know about your workflow .

**Comment by anoopd** [comment]
@Mte90  Ty , I am a neovim user , so that is not an option .

**Comment by Mte90** [comment]
I don't understand, I followed the readme and used with that tool.
Check my https://github.com/mte90/dotfiles in case you need to check the code.

**Comment by BenceBakos** [comment]
Setting `serverSourceRoot` and `localSourceRoot` properly made my configuration work, as well as this lil magic may be useful for others too:
```
localSourceRoot = vim.fn.expand("%:p:h").."/"
```

**Comment by shadyalfred** [comment]
I've tried setting `localSourceRoot` and `serverSourceRoot` to `vim.fn.expand("%:p:h").."/"` but it still doesn't work. It shows an error `No stopped thread`

Anyone knows why? I don't have an apache server configured, just the php package isntalled.

**Comment by LiamKearn** [comment]
Just having some issues with event listeners with PHP here. Probably just a case of me not really reading the DAP spec properly.

I checked the logs at tracing level and I can see the init event but not the termination one when I run  a terminate through dap ui.

Is this something I should bring up with the adaptor authors? Logs below.

<details>
<summary>Logs</summary>

eg. When I start I correctly get the following which triggers my listeners.
```lua
{
  event = "initialized",
  seq = 3,
  type = "event"
}
```

Whereas when I terminate by calling `:lua require('dap').continue()` and then selecting 1 to terminate an existing session I only see the following request to the adaptor and response (no event).
```lua
{{
  arguments = {
    restart = false,
    terminateDebuggee = true
  },
  command = "disconnect",
  seq = 4,
  type = "request"
},
{
  command = "disconnect",
  request_seq = 4,
  seq = 6,
  success = true,
  type = "response"
}}
```

</details>

For context I'm trying to close dap ui on termination. I've tried the following lua snips (none of which fire):
```lua
dap.listeners.before['event_terminated']['xyz'] = function(session, body)
  print('Session terminated', vim.inspect(session), vim.inspect(body))
end
dap.listeners.after['event_terminated']['xyz'] = function(session, body)
  print('Session terminated', vim.inspect(session), vim.inspect(body))
end

dap.listeners.after.event_terminated['xyz'] = function()
    dapui.close()
end
```

Cheers for the excellent plugin, It's working flawlessly for me so far (minus this which I don't think is nvim-dap's fault).

**Comment by mfussenegger** [comment]
You could listen to the `disconnect`, e.g. I use something like:


```lua
local after_session = function()
  -- do stuff
end
dap.listeners.after.event_terminated['me.dap'] = after_session
dap.listeners.after.disconnected['me.dap'] = after_session
```

**Comment by LiamKearn** [comment]
That's exactly what I was after. got confused by `disconnected` and not `disconnect` longer than I'd like to admit but works wonderfully now :^)
