### ISSUE TITLE
The backspace key works in a strange way on repl buffer.

### ISSUE THREAD

**Issue by pittcat** [mfussenegger/nvim-dap#119]
https://user-images.githubusercontent.com/22888402/110602154-a8c32f80-81c0-11eb-8a85-8f209bbd3c08.mp4

**Comment by pittcat** [comment]
Enter key and <C-w> do not work as well as they do in terminal.

**Comment by theHamsta** [comment]
I think most of this is due to vim's weird/borken implementation of `prompt_buffer`s that aren't really user friendly. The behavior of backspace might be due to setting `unmodified` `on_lines`??? I personally never could these prompt buffer make working with the look and feel of a normal terminal buffer.

**Comment by pittcat** [comment]
When you enter a variable and then reuse it by pressing `<Up>` key, the `<C-w>` won't take effect on deleting characters. The problem with the enter key is that even if you don't enter any variables, it will still act as if you entered the last variable.

**Comment by theHamsta** [comment]
> The problem with the enter key is that even if you don't enter any variables, it will still act as if you entered the last variable.

It will repeat the last command that you gave it. Many command line debugger have this behavior for stepping command. However, pdb does not repeat an eval request just commands. GDB repeats every command.

```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./a.out...
(gdb) break main
Breakpoint 1 at 0x11c9: file main.cpp, line 17.
(gdb) 
Note: breakpoint 1 also set at pc 0x11c9.
Breakpoint 2 at 0x11c9: file main.cpp, line 17.
(gdb) w
Missing arguments.
(gdb) f
No stack.
(gdb) l
warning: Source file is more recent than executable.
3        * Copyright (C) 2021 Stephan Seitz <stephan.seitz@fau.de>
4        *
5        * Distributed under terms of the GPLv3 license.
6        */
7
8       #include <cstdlib>
9       #include <iostream>
10
11      struct Foo {
12        int x = 2;
(gdb) n
The program is not being run.
(gdb) r
Starting program: /home/stephan/a.out 

Breakpoint 1, main (argc=21845, argv=0x5555555552b0 <__libc_csu_init>) at main.cpp:17
17        std::cout << a << std::endl;
(gdb) n
18        return a + b + 2;
(gdb) argc
Undefined command: "argc".  Try "help".
(gdb) p argc
$1 = 1
(gdb) 
$2 = 1
(gdb) 
```

**Comment by mfussenegger** [comment]
@pittcat could you try with https://github.com/mfussenegger/nvim-dap/pull/123 ?

**Comment by pittcat** [comment]
I have tried #123, and the patch  can make backspace work.But continuous backspace pressing seems turn vim to normal mode.

**Comment by pittcat** [comment]
`<C-w>` still can't delete characters after pressing `Up` key to reuse previous input

**Comment by kabouzeid** [comment]
Wouldn't it be possible to use the `terminal` buffer type for this? Happy to help with this if somebody points me in the right direction :)

**Comment by mfussenegger** [comment]
> Wouldn't it be possible to use the `terminal` buffer type for this? 

I think you'd need some kind of stub executable that could be launched in the terminal. That would then handle the input and send it back to `nvim-dap` for processing.

Doing that feels more like a workaround to me and I think it would make more sense to extend/fix `buftype` within vim/neovim core instead.

**Comment by kabouzeid** [comment]
This is exactly what I suspected, thanks for confirming :)
I'll have a look at neovim core, but I probably lack the expertise for this; terminal emulation is not easy.

**Comment by mfussenegger** [comment]
I had already raised this in neovim, see https://github.com/neovim/neovim/issues/14116 
I like the suggested `buftype=prompt,nofile` but I didn't follow up on bringing this up in vim. If you feel like it, go for it :)

**Comment by kabouzeid** [comment]
I don't care about vim, and I'm not looking forward to argue with Bram.

**Comment by mfussenegger** [comment]
Looks like removing the modified hack (https://github.com/mfussenegger/nvim-dap/commit/1cf8babf4e29b58b5df31cdd48ddb32e7ff821fb) didn't fix this completely but not sure what else could be done within nvim-dap to fix the backspace behavior.

This seems like a vim/neovim prompt buftype oddity.

**Comment by mfussenegger** [comment]
Looks like removing the modified hack (https://github.com/mfussenegger/nvim-dap/commit/1cf8babf4e29b58b5df31cdd48ddb32e7ff821fb) didn't fix this completely but not sure what else could be done within nvim-dap to fix the backspace behavior.

This seems like a vim/neovim prompt buftype oddity.

**Comment by cogig** [comment]
I think the issue should be reopened. Some of the repl buffer still have bug with some keys not working properly, which affects the normal use experience.

**Comment by mfussenegger** [comment]
Until vim/neovim adds an option to control it or modifies the behavior there's nothing reasonable that we can do about it within nvim-dap. I try to keep only issues open that are actionable.

**Comment by pfeiferj** [comment]
I'm currently running the following vimscript as a workaround, it's not fool proof but it works for my use case, and probably many others. You could probably change it to only set for dap-repl as well but I have the same problem in other prompts so I just set it for any prompt buffer.

```vim
fun! PromptBackspace()
  let currentPos = getline('.')[col('.')-1]
  let beforePos = getline('.')[col('.')-2]
  if !(currentPos == " " && beforePos == ">")
    if col(".") == col("$")-1
      normal x
      startinsert!
    else
      normal x
      startinsert
    endif
  else
    startinsert!
  endif
endfun

fun! PromptBackspaceSetup()
    if v:option_new == 'prompt'
      inoremap <buffer> <backspace> <esc>:call PromptBackspace()<cr>
    endif
endfun

autocmd OptionSet * call PromptBackspaceSetup()
```

**Comment by pfeiferj** [comment]
I decided to fix some of the issues with my workaround, I don't know of any issue with it now other than it being a bit hacky.

```lua
function PromptBackspace() --Expects to have entered normal mode before entering function, will return to insert mode
  local currentLineNumber = vim.fn["line"](".")
  local currentColumnNumber = vim.fn["col"](".")
  local currentLineLength = vim.fn["col"]("$")
  local currentLine = vim.api.nvim_buf_get_lines(0, currentLineNumber-1, currentLineNumber, false)[1]
  local _, endPrompt = string.find(currentLine, "> ")

  if endPrompt == nil then
    endPrompt = 0
  end

  if currentColumnNumber ~= endPrompt then --Not beginning of the prompt
    if currentColumnNumber == currentLineLength - 1 then --Not beginning of prompt and is the end of the line
      vim.cmd([[normal x]])
      vim.cmd([[startinsert!]])
    else --Not beginning of prompt and is not the end of the line
      vim.cmd([[normal x]])
      vim.cmd([[startinsert]])
    end
  else --Beginning of prompt
    vim.cmd([[startinsert]])
  end
end

vim.cmd([[
fun! PromptBackspaceSetup()
    if v:option_new == 'prompt'
      inoremap <buffer> <backspace> <esc>:lua PromptBackspace()<cr>
    endif
endfun

autocmd OptionSet * call PromptBackspaceSetup() "not using a lua function here because of error when accessing :help
]])
```
