### ISSUE TITLE
launch.json doesn't reload when using custom path with load_launchjs()

### ISSUE THREAD

**Issue by amitlevy21** [mfussenegger/nvim-dap#1193]
### Debug adapter definition and debug configuration

Hi,
I'm using Lazyvim, which comes nvim-dap installed by default.

### Debug adapter version
from lazy-lock.json
"nvim-dap": { "branch": "master", "commit": "6ae8a14828b0f3bff1721a35a1dfd604b6a933bb" },

### Steps to Reproduce

1. add the following to `~/.config/nvim/plugins/dap.lua`:
```lua
return {
  {
    "mfussenegger/nvim-dap",
    config = function()
      require("dap.ext.vscode").load_launchjs('launch.json')
    end,
  },
}
```
2. create a `launch.json` file in any project root dir with the following:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "python",
      "request": "launch",
      "name": "debug from launch file",
      "program": "python",
      "cwd": "<some-path-that-does-not-exist>",
      "args": ["main.py"]
    }
  ]
}
```
3. exit neovim
4. trigger nvim-dap-> run with args -> `choose debug from launch file`
5. you will get error saying no such file `<some-path-that-does-not-exist>`
6. change cwd to the correct path
7. repeat 4
### Expected Result

the file should be auto reloaded and debugging should work

### Actual Result

you get the same error as before `<some-path-that-does-not-exist>` does not exist
the error will be fixed once you exist and restart neovim

Thank you!

**Comment by mfussenegger** [comment]
If you use a custom location you have to setup your own reload handling, E.g.:

```lua
vim.api.nvim_create_autocmd('BufWritePost', {
  group = vim.api.nvim_create_augroup('my-dap-launch.json', { clear = true }),
  pattern = "*/launch.json",
  callback = function(args)
    require('dap.ext.vscode').load_launchjs(args.file)
  end
})
```

**Comment by mfussenegger** [comment]
After thinking some more about this, I also don't think I'll change anything in that regard.

- Changing the default `BufWritePost` pattern to `launch.json` is likely too invasive.
- Having `load_launchjs` change the default handler could be surprising and undesired side-effect.

I'm open to other arguments, but for now I'm closing this.
