### ISSUE TITLE
Breakpoints get rejected when the project is created in a symbolic link directory

### ISSUE THREAD

**Issue by LeonardoDiCappuccino** [mfussenegger/nvim-dap#1197]
### Debug adapter definition and debug configuration

Installed codelldb via [mason.nvim](https://github.com/williamboman/mason.nvim) and the configuration is getting done by [mason-nvim-dap.nvim](https://github.com/jay-babu/mason-nvim-dap.nvim)

### Steps to Reproduce

1. cd into a symbolic link and create a new project there(`mkdir Test && cd Test && nvim`)
2. Compile a test file (for example main.cpp) with debug symbols (In my case with [cmake-tools.nvim](https://github.com/Civitasv/cmake-tools.nvim) via `:CMakeGenerate` + `:CMakeBuild` but with `clang++ --debug main.cpp -o main` it is the same)
3. Set a breakpoint somewhere in main.cpp
4. Debug the executable via `:CMakeDebug` or `:DapContinue` followed by the executable path

### Expected Result

The debugger should stop at the breakpoint that was set before, like in any other project that was not created/compiled in a symbolic link directory

### Actual Result

The debugger just runs the executable without stopping at the breakpoint and the breakpoint gets rejected.
The repl window of the [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui) says:

_Console is in 'commands' mode, prefix expressions with '?'.
Could not resolve any locations for breakpoint at /media/lasse/58924D7C924D601C/src/C++/Test/main.cpp:10, but found a valid location at /home/lasse/src/C++/Test/main.cpp:10
Launching: /media/lasse/58924D7C924D601C/src/C++/Test/out/Debug/test_exe
Launched process 1296237
Process exited with code 0._

**Comment by mfussenegger** [comment]
Seems a bit like a codelldb issue to me. `gdb` handles that just fine.

nvim-dap is sending the resolved source path and I don't really see a way to change that, given that that's returned by `api.nvim_buf_get_name(bufnr)` - there's no way to unresolve it.

**Comment by mfussenegger** [comment]
See also https://github.com/vadimcn/codelldb/issues/151

Closing this for now, but please add any info that would indicate this is indeed a client problem instead of a problem in the adapter
