### ISSUE TITLE
Switching repl between multiple sessions

### ISSUE THREAD

**Issue by freezlite** [mfussenegger/nvim-dap#1222]
### Problem Statement

Right now repl buf shows all output from all sessions. It would be nice to switch between sessions to see different output.

**Comment by mfussenegger** [comment]
The recommended way to work with multiple session is to make use of the terminal feature (`:help dap-terminal`).
Otherwise you could override the output handler (`:help dap.defaults`, see `on_output)

I currently have no plans to split up the repl per session.
