### ISSUE TITLE
need help: GDB on Windows (`\r\n` problem)

### ISSUE THREAD

**Issue by KevinNitroG** [mfussenegger/nvim-dap#1227]
### Debug adapter definition and debug configuration

```lua
local dap = require "dap"
dap.adapters.gdb = {
  type = "executable",
  command = "gdb",
  args = { "-i", "dap" },
}

dap.configurations.cpp = {
  {
    name = "Launch",
    type = "gdb",
    request = "launch",
    program = function()
      return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
    end,
    cwd = "${workspaceFolder}",
    stopAtBeginningOfMainSubprogram = false,
  },
}
```

### Debug adapter version

sorry idk but my GDB version is 14.1 (installed with scoop)

### Steps to Reproduce

1. Open cpp file
2. Start the dap

### Expected Result

Run normally, like, debugging my beautiful cpp code

### Actual Result

![image](https://github.com/mfussenegger/nvim-dap/assets/86353526/7a78c848-2cb6-4b20-ad31-2b7e55290340)

Log via `:DapShowLog`
```log
[ ERROR ] 2024-05-27T18:46:20Z+0700 ] .../nvim-alexis12119-data/lazy/nvim-dap/lua/dap/session.lua:1455 ]	"stderr"	{
  args = { "-i", "dap" },
  command = "gdb",
  type = "executable"
}	"Interpreter `dap' unrecognized\r\n"
[ INFO ] 2024-05-27T18:46:20Z+0700 ] .../nvim-alexis12119-data/lazy/nvim-dap/lua/dap/session.lua:1428 ]	"Process closed"	23472
```

> [!NOTE]
>
> My `NVIM_APPNAME` = `nvim-alexis2119`

Btw I run with the `.cpp` file. IDK if I need to run the compiled file _(`.exe`)_ or not.

**Comment by luftaquila** [comment]
Rebuild gdb with `--with-python=/path/to/python` fixed the issue. Thank you for the hint.
