### ISSUE TITLE
Less verbose scopes output

### ISSUE THREAD

**Issue by simonmclean** [mfussenegger/nvim-dap#1252]
### Problem Statement

I'm working on a Scala project, and the REPL output for `.scopes` is so verbose that it's practically unusable. Below are screenshots of the output as shown in nvim-dap vs IntelliJ (values redacted because work)

**nvim-dap**
<img width="928" alt="vim" src="https://github.com/mfussenegger/nvim-dap/assets/14262306/75536a10-1e84-439a-9de0-ce8199e3e602">
(I know the screenshot is using nvim-dap-ui, but the result is basically the same with vanilla nvim-dap)

**IntelliJ**

<img width="957" alt="intellij" src="https://github.com/mfussenegger/nvim-dap/assets/14262306/bd79f36f-873d-494d-bedd-4def20af3a59">

As you can see, IntelliJ prints out much less in the way of type information. All that `scala$collection$immutable$RedBlackTree$Tree$$ left RedBlackTree$Tree` is essentially noise.

### Possible Solutions

A config option added to nvim-dap, either:

- A boolean to toggle concise/verbose output, or
- A `format` function that the user provides to format/filter the output themselves

**Comment by mfussenegger** [comment]
This is kinda tracked with: https://github.com/mfussenegger/nvim-dap/issues/737 and https://github.com/mfussenegger/nvim-dap/issues/1062

But part of this is also up to the debug adapter
