### ISSUE TITLE
Python `print()` statements in the REPL are duplicated

### ISSUE THREAD

**Issue by carschandler** [mfussenegger/nvim-dap#1255]
### Debug adapter definition and debug configuration

Installed via Lazy. Minimal plugin config:
```lua
return {
  'mfussenegger/nvim-dap',

  config = function()
    local dap = require('dap')

    dap.adapters.python = {
      type = 'executable',
      command = 'python',
      args = { '-m', 'debugpy.adapter' };
    }

    dap.configurations.python = {
      {
        name = 'Launch file',
        type = 'python',
        request = 'launch',
        program = '${file}',
        pythonPath = 'python',
      },
    }
  end
}

```

### Debug adapter version

debugpy v1.8.1

### Steps to Reproduce

In any project, start DAP, open the REPL, and `print("anything")`.

### Expected Result

The object is printed once

### Actual Result

The object is printed twice

**Comment by mfussenegger** [comment]
Although confusing this is actually expected.
debugpy returns `10` as result of the expression, but also prints 10 as side-effect to stdout/reports it as output event.

If you use the integrated terminal you'll only see it once in the REPL, and once in the terminal.

Not much to do about that on the client side. You could override `on_output` and customized it if you wanted to (see `dap.defaults`)

**Comment by carschandler** [comment]
I figured this wasn't actually a bug, but had been irking me since I started using DAP a few months back... thank you for the tip on the integrated terminal!
