### ISSUE TITLE
Can nvim-dap add function to replace 'dap'.run_last ?

### ISSUE THREAD

**Issue by pittcat** [mfussenegger/nvim-dap#127]
If the debugging process is not completely finished, at this time we want to restart the debugging.If the direct call to 'dap'.run_last, we may encounter strange behavior. We need to close the previous debugging process by dap.disconnect() first and then run the function dap.run_last.

**Comment by pittcat** [comment]
```
  local dap = require('dap') 
  local ndap_state= dap.session()
  if ndap_state==nil then
    dap.run_last()
  else 
    dap.disconnect()
    dap.run_last()
  end
```
The snippets seems can work well  for me.

**Comment by nyngwang** [comment]
>     if ndap_state==nil then
>       dap.run_last()
>     else 
>       dap.disconnect()
>       dap.run_last()
>     end

@pittcat Do we still need this?
