### ISSUE TITLE
Sidebar like vista.vim

### ISSUE THREAD

**Issue by Mte90** [mfussenegger/nvim-dap#128]
It is possible to integrate a sidebar like vista.vim https://github.com/liuchengxu/vista.vim?

In this way I can have an IDE ui like that is more easy to use to me (I don't remember often the hotkeys).

**Comment by mfussenegger** [comment]
Yes a sidebar is something that I still would like to get in eventually.

**Comment by mfussenegger** [comment]
Meanwhile you could check out https://github.com/rcarriga/nvim-dap-ui which contains ui extensions and adds a sidebar.
