### ISSUE TITLE
When a breakpoint is hit use the window with the breakpoint instead of changing the current one

### ISSUE THREAD

**Issue by wojciech-kulik** [mfussenegger/nvim-dap#1286]
### Problem Statement

Currently, when I set a breakpoint, nvim-dap jumps to it using the current window.

### Possible Solutions

It would be much better if nvim-dap could check if the buffer associated with the breakpoint is already open and switch to it, instead of changing the current window.

This would provide a very nice experience. Please consider adding it.

**Comment by mfussenegger** [comment]
See the `switchbuf` option under `:h dap.defaults`.

You can set something like:

```lua
local dap = require("dap")
dap.defaults.fallback.switchbuf = 'usetab,uselast'`
```

To have it prioritize already open buffers

**Comment by wojciech-kulik** [comment]
Wow, thank you! It works
