### ISSUE TITLE
Enhanced support when debugging in a multi-threaded setup

### ISSUE THREAD

**Issue by 5reep4thy** [mfussenegger/nvim-dap#1287]
### Problem Statement

Unable to step after hitting break points in different threads. Would be a feature benefitting a lot of users :)

### Possible Solutions

Uses: 
1. When a thread hits a break point, we can perform basic debugging there (Step into, out, run to cursor etc)
2. When it's stepped through the other threads also execute in parallel till one of its own break point is hit, simulating a proper multi-threaded application.

**Comment by mfussenegger** [comment]
See https://github.com/search?q=repo%3Amfussenegger%2Fnvim-dap+auto_continue_if_many_stopped
