### ISSUE TITLE
[Feature] Support multiple session switch

### ISSUE THREAD

**Issue by chaozwn** [mfussenegger/nvim-dap#1288]
### Problem Statement

When I am debugging go microservices, I may need to give multiple service break points. I need a session that can be flexibly switched and decided to close.

### Possible Solutions

i can switch multiple session through api.

**Comment by mfussenegger** [comment]
You can switch sessions via the session widget, e.g.:


```
:lua local w = require("dap.ui.widgets"); w.sidebar(w.sessions, {}, "5 sp | setl winfixheight").toggle()
```

And then hit enter on the session you want to switch to.
Other commands like terminate/continue/, etc always operate on the currently focused session.
