### ISSUE TITLE
Trouble setting up with python

### ISSUE THREAD

**Issue by AckslD** [mfussenegger/nvim-dap#129]
I just getting started with nvim-dap and am having troubles setting it up with python. I have the following config
```lua
local dap = require('dap')
dap.adapters.python = {
    type = 'executable',
    command = 'python',
    args = {'-m', 'debugpy.adapter'}
}
dap.configurations.python = {
    {
        type = 'python',
        require = 'launch',
        name = "Launch file",
        program = "${file}",
        pythonPath = function() return '/usr/bin/python' end,
    },
}
```
which `debugpy` installed in my base python environment.

As I test I'm trying to debug the following file
```py
def some():
    print("hello")

if __name__ == '__main__':
    some()
```
if I go the to line with the print statement and do `:lua require"dap".toggle_breakpoint()` I get a `B` in the margin. However when I do `:lua require"dap".continue()` nothing happens and if I do it again I get `No stopped thread. Cannot move`. Any idea what I'm doing wrong?

**Comment by mfussenegger** [comment]
The configuration looks alright. Which `debugpy` version is installed?
Could you enable trace logging (see `:help dap.set_log_level()`) and post the log outputs?

**Comment by AckslD** [comment]
Thanks for your response @mfussenegger! My `debugpy` version is `1.2.1`.

Here's the log output:
<details>
```

[ DEBUG ] 2021-03-23T09:29:03Z+0100 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:1058 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsRunInTerminalRequest = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
[ DEBUG ] 2021-03-23T09:29:03Z+0100 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:853 ]	{
  body = {
    category = "telemetry",
    data = {
      packageVersion = "1.2.1"
    },
    output = "ptvsd"
  },
  event = "output",
  seq = 1,
  type = "event"
}
[ DEBUG ] 2021-03-23T09:29:03Z+0100 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:853 ]	{
  body = {
    category = "telemetry",
    data = {
      packageVersion = "1.2.1"
    },
    output = "debugpy"
  },
  event = "output",
  seq = 2,
  type = "event"
}
[ DEBUG ] 2021-03-23T09:29:03Z+0100 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:853 ]	{
  body = {
    exceptionBreakpointFilters = { {
        default = false,
        filter = "raised",
        label = "Raised Exceptions"
      }, {
        default = true,
        filter = "uncaught",
        label = "Uncaught Exceptions"
      } },
    supportsClipboardContext = true,
    supportsCompletionsRequest = true,
    supportsConditionalBreakpoints = true,
    supportsConfigurationDoneRequest = true,
    supportsDebuggerProperties = true,
    supportsDelayedStackTraceLoading = true,
    supportsEvaluateForHovers = true,
    supportsExceptionInfoRequest = true,
    supportsExceptionOptions = true,
    supportsGotoTargetsRequest = true,
    supportsHitConditionalBreakpoints = true,
    supportsLogPoints = true,
    supportsModulesRequest = true,
    supportsSetExpression = true,
    supportsSetVariable = true,
    supportsTerminateDebuggee = true,
    supportsValueFormattingOptions = true
  },
  command = "initialize",
  request_seq = 0,
  seq = 3,
  success = true,
  type = "response"
}
[ DEBUG ] 2021-03-23T09:29:03Z+0100 ] ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:1058 ]	"request"	{
  arguments = {
    name = "Launch file",
    program = "tmp.py",
    pythonPath = "/usr/bin/python",
    require = "launch",
    type = "python"
  },
  seq = 1,
  type = "request"
}
```
</details>

**Comment by mfussenegger** [comment]
This is strange.

I tried it with the exact same configuration and the same file and for me it works without problems.
Which python version are you using?


After the launch request there should be a response coming back from the debug adapter. (event initialized).


What system are you using?

**Comment by AckslD** [comment]
Hmm, weird. Am I doing it right by first setting a breakpoint by:
```
:lua require"dap".toggle_breakpoint()
```
and then running it by
```
:lua require"dap".continue()
```
?
Just to make sure :)

My setup is:
python 3.9.2
nvim v0.5.0-dev+1166-g070e084a6
zsh 5.8
arch linux 5.11.7-arch1-1

**Comment by mfussenegger** [comment]
> Just to make sure

Yes, setting a breakpoint and running continue is alright to start the debug session. 

I've a similar environment. Maybe something odd about your debugpy installation? Could you try installing it in a separate virtualenv?

**Comment by AckslD** [comment]
Sure thing, I'll try that tomorrow! Currently I just have it in my base environment.

**Comment by AckslD** [comment]
Just tried with `debugpy` in a fresh virtual environment but still the same behaviour.

**Comment by mfussenegger** [comment]
I'm a bit out of ideas. The config looks right. You're using the same version. The logs indicate that the client is trying to initiate/start the debug session.

You could try with the adapter definition and configurations from https://github.com/mfussenegger/nvim-dap-python but not sure if that will help.

**Comment by AckslD** [comment]
Thanks anyway @mfussenegger, I appreciate the help! I'll let you if I figure out what's going on.

**Comment by AckslD** [comment]
Finally found the issue @mfussenegger, it was a very stupid one 😊 I had written `require = 'launch',` instead of `request = 'launch',` for some reason
