### ISSUE TITLE
Replace vim.fn.sign_define since it is deprecated and will be removed

### ISSUE THREAD

**Issue by augustocdias** [mfussenegger/nvim-dap#1292]
`vim.fn.sign_define` will be removed in 0.12 and it already shows warnings when called. From what I could see in the help pages it should now call `vim.diagnostic.config`. 

I'm still not sure how to translate the old call to the new as the parameters are all different now. And there's a namespace, so the plugin probably has to define it somewhere.

**Comment by mfussenegger** [comment]
`vim.fn.sign_define` won't be removed in 0.12.

What's changing is that the signs for `vim.diagnostic` cannot be defined anymore via `vim.fn.sign_define` but that's entirely unrelated to the signs used by nvim-dap.
