### ISSUE TITLE
[Feature] Set the debug name when starting debug.

### ISSUE THREAD

**Issue by chaozwn** [mfussenegger/nvim-dap#1293]
### Problem Statement

In our actual development process, we may encounter situations where we debug multiple microservices, and the default debug1, debugxxx, etc. names may not be so friendly.

### Possible Solutions

Gets the name can be set according to the file name of the startup.

**Comment by mfussenegger** [comment]
I don't really understand. The debug names come from your configurations? nvim-dap doesn't create `debug1` or `debugxxx` names.
