### ISSUE TITLE
vscode-cpptools missing features.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [mfussenegger/nvim-dap#1305]
### Problem Statement

There are two features not supported in the vscode-cpptools' adapter:
- step_back()
- goto_() -> "AKA set next statement"

It seems this VS extension on its own doesn't support these, but I have seem other extensions that integrate with it to provide these two features.

I don't know how I could make these integration on neovim.

### Possible Solutions

I don't know how I can integrate these two extensions with the adapter. If you think it's feasible, I ask you for a direction on how I could make it at least.

**Comment by mfussenegger** [comment]
You'd better ask in the vscode-cpptools repository to add these capabilities.

nvim-dap supports them on the client side if the debug adapter has the capabilities.
