### ISSUE TITLE
Deleting the dap-terminal buffer would not re-invoke the fallback terminal_win_cmd

### ISSUE THREAD

**Issue by asmodeus812** [mfussenegger/nvim-dap#1321]
### Debug adapter definition and debug configuration

This is a general issue i have noticed that if after a dap-terminal buffer was created, and you forcefuly delete it, dap would never attempt to again call the terminal_win_cmd, seems like dap is attempting to extract the terminal win cmd from the session the second time it is started, but the dap configured fallbacks are never set in the session possibly ? (`dap().defaults[lsession.config.type]`) the first time the terminal buffer is created it works just fine, however if you delete it and restart the session it would never be re-created, the session starts and debugging is working though.

```lua

local function make_terminal_view()
        local tid = vim.api.nvim_create_buf(true, true)
        vim.print('make_term_command', tid)
        return tid
end

-- dap is configured with the following defaults
        defaults = {
            fallback = {
                focus_terminal = false,
                exception_breakpoints = "default",
                terminal_win_cmd = make_terminal_view,
            },
        }
```

### Debug adapter version

master

### Steps to Reproduce

1. start a debug session (for any adapter)
2. checkout that dap-terminal is present
3. stop the session
4. bd! the dap-terminal buffer
5. re-start **_the same session_**
6. the dap-terminal buffer is not re-created, the custom command is never re-invoked.

### Expected Result

The terminal will always be created if there is none created for the current session.

### Actual Result

Terminal is not re-created

**Comment by mfussenegger** [comment]
Doesn't reproduce for me. The custom function is called each time.

Are you also using nvim-dap-ui? That takes control of the `terminal_win_cmd` setting and likely overrides your function.

**Comment by asmodeus812** [comment]
Yeah, dap-ui was the issue indeed, the console element is sourced after my nvim dap config,. It is indeed overriding it.
