### ISSUE TITLE
Add support for alternate row colors in stack/scope UI

### ISSUE THREAD

**Issue by sigasigasiga** [mfussenegger/nvim-dap#1322]
### Problem Statement

Scope UI is not that readable:
<img width="918" alt="image" src="https://github.com/user-attachments/assets/de1c5d5e-004e-4d11-b7b2-a0b6a64d9325">

Frames UI is even less readable, as it lacks any highlighting:
<img width="859" alt="image" src="https://github.com/user-attachments/assets/e394ac03-ee19-4bff-a739-6cb6347939d0">

### Possible Solutions

I think it could be improved with alternate row colors. This way one line could be easily distinguished with another.
I've made two models in GIMP that illustrate the idea
![chroma](https://github.com/user-attachments/assets/31692dc1-2b64-4169-8564-f27af63c26ee)
![grain_merge](https://github.com/user-attachments/assets/b382c376-784f-4923-999e-e6ba88b45e7b)

**Comment by sigasigasiga** [comment]
Maybe related to https://github.com/mfussenegger/nvim-dap/issues/1062

**Comment by sigasigasiga** [comment]
Damn, I've leaked my token :D
I've already revoked it if you're curious

**Comment by mfussenegger** [comment]
Given that there haven't been any upvotes so far I assume that there isn't really much interest in this and I'm also sceptical if zebra highlighting is the right approach to address the issue here, so I'm closing this for now
