### ISSUE TITLE
Stopped at line xx but `switchbuf` setting prevented jump to location. Target buffer x not open in any window?

### ISSUE THREAD

**Issue by RaviRahar** [mfussenegger/nvim-dap#1327]
### Debug adapter definition and debug configuration

```lua
require("dap").defaults.fallback.switchbuf = 'useopen'   <------ this here

dap.adapters.gdb = {
    type = "executable",
    command = "gdb",
    args = { "--interpreter=dap", "--eval-command", "set print pretty on" }
}

dap.configurations.c = {
    {
        name = "Launch",
        type = "gdb",

        -- irrelevant parts --

        stopAtBeginningOfMainSubprogram = true,   <------------- here
        stopOnEntry = false,
    } }
```

### Debug adapter version

gdb: 15.1  
nvim-dap: 281a2e4cd1e7a17ce

### Steps to Reproduce

1. Open a C project
2. Open some file that does not contain `main()`
3. Do not open file containing `main()`
4.` stopAtBeginningOfMainSubprogram = true` and `require("dap").defaults.fallback.switchbuf = 'useopen'`
5. Start debugging

### Expected Result

Should open file containing `main()` in current window replacing current buffer

### Actual Result

Shows error:

`Stopped at line xx but `switchbuf` setting prevented jump to location. Target buffer x not open in any window?`

When I use:
`require("dap").defaults.fallback.switchbuf = 'useopen,newtab'`

Then it works fine and opens the file containing `main()` in newtab.

**Comment by mfussenegger** [comment]
That's expected behavior and matches its description:

> 	Possible values (comma-separated list):
>   useopen	If included, jump to the first open window in the
>		current tab page that contains the specified buffer
>		(if there is one).  Otherwise: Do not examine other
>		windows.

If you want it to change the active window you can use `'usetab,uselast'`

**Comment by RaviRahar** [comment]
> That's expected behavior and matches its description:
> 
> > Possible values (comma-separated list):
> > useopen	If included, jump to the first open window in the
> > current tab page that contains the specified buffer
> > (if there is one).  Otherwise: Do not examine other
> > windows.
> 
> If you want it to change the active window you can use `'usetab,uselast'`

Okay thanks.  
I dug around a bit, I guess the rumours are true. switchbuf's help is perplexing. At least it was for me.
