### ISSUE TITLE
Error message when step through debugging

### ISSUE THREAD

**Issue by xy-lin** [mfussenegger/nvim-dap#1332]
### Debug adapter definition and debug configuration

      require("dap").adapters["codelldb"] = {
        type = "server",
        host = "127.0.0.1",
        port = "${port}",
        executable = {
          command = "codelldb",
          args = {
            "--port",
            "${port}",
          },
        },
  }

### Debug adapter version

latest nightly build

### Steps to Reproduce

1. Set break point
2. Start debugging
3. When Step over any line, the error message will pop up

### Expected Result

No error message 

### Actual Result

![dapDebug](https://github.com/user-attachments/assets/3a69d385-ef10-4735-a453-3bfd3d90f931)

Not sure this is issue from Treesitter or nvim-dap or nvim-dap-ui.

**Comment by mfussenegger** [comment]
The error is triggered from nvim-dap-virtual-text. Could be related to a recent change in neovim master: https://github.com/neovim/neovim/commit/6913c5e1d975a11262d08b3339d50b579e6b6bb8

In any case - not related to nvim-dap itself.

**Comment by xy-lin** [comment]
Thanks for replay and the hint for possible cause.

**Comment by mfussenegger** [comment]
Looks like there's also a PR to fix it up already: https://github.com/theHamsta/nvim-dap-virtual-text/pull/87

**Comment by xy-lin** [comment]
> Looks like there's also a PR to fix it up already: [theHamsta/nvim-dap-virtual-text#87](https://github.com/theHamsta/nvim-dap-virtual-text/pull/87)

Thanks a lot! After upgrading that plugin, it is back to normal.
