### ISSUE TITLE
[Feature] DebugAdapterInlineImplementation

### ISSUE THREAD

**Issue by okwasniewski** [mfussenegger/nvim-dap#1339]
### Problem Statement

Hey,

I want to write a `nvim-dap` adapter in Lua that communicates with a WebSocket server and reports events back to nvim-dap. 

Namely, an adapter for the React Native Debugger (https://github.com/facebook/react-native/tree/main/packages/dev-middleware), here is an  implementation for VSCode: https://github.com/software-mansion/radon-ide/blob/main/packages/vscode-extension/src/debugging/DebugAdapter.ts

### Possible Solutions

Quoting vscode issue (https://github.com/microsoft/vscode/issues/85544)

> Currently we have extension API to run a debug adapter session:
> 
> as an external process:
> ```js
> vscode.debug.registerDebugAdapterDescriptorFactory('mock', {
>   createDebugAdapterDescriptor: (_session) => {
>     return new vscode.DebugAdapterExecutable('mockDebug.exe');
>   }
> });
> ```

> as a network session:

> ```js
> vscode.debug.registerDebugAdapterDescriptorFactory('mock', {
>   createDebugAdapterDescriptor: (_session) => {
>     return new vscode.DebugAdapterServer(12345, 'localhost');
>   }
> });
> ```

> With this API request we want to add a third option where an 'inline' implementation can be provided:

> ```js
> vscode.debug.registerDebugAdapterDescriptorFactory('mock', {
>   createDebugAdapterDescriptor: (_session) => {
>     return new vscode.DebugAdapterImplementation(new MockDebugSession());
>   }
> });
> ```

VSCode docs: https://vscode-api.js.org/classes/vscode.DebugAdapterInlineImplementation.html

### Considered Alternatives

Implementing it without the DebugAdapterInlineImplementation

AdapterFactory passes in the `Dap.Session`: 

```
---@alias Dap.AdapterFactory fun(callback: fun(adapter: dap.Adapter), config: dap.Configuration, parent?: dap.Session)
```

This could be a potential solution but I couldn't get this to work. But the `parent` parameter was nil for me. And Im not sure if this is the best approach

Thanks in advance for suggestions on how to implement this.

**Comment by mfussenegger** [comment]
You'd have to implement an adapter that either talks via tcp or pipe.
The test suite actually contains a stub adapter implementation: https://github.com/mfussenegger/nvim-dap/blob/master/spec/server.lua

Example usages are here:

https://github.com/mfussenegger/nvim-dap/blob/master/spec/integration_spec.lua


So the client adapter configuration would end up looking like either:

```lua
local adapter = {
  type = "server",
  host = "127.0.0.1",
  port = 1234,
  options = {
    disconnect_timeout_sec = 0.1
  }
}
```

Or a variant with `type = "pipe"`.


---

That said, I'd actually recommend not doing this but instead implement an adapter as a standalone executable to make it usable for other editors too.

**Comment by okwasniewski** [comment]
@mfussenegger Thank you for the hint! I guess making the DAP adapter reusable is a better idea. 

Closing this 🙏
