### ISSUE TITLE
Feature Request: Customizable Icons and Colors for Breakpoints

### ISSUE THREAD

**Issue by niekdomi** [mfussenegger/nvim-dap#1341]
### Problem Statement

Hey,

I am an avid user of `nvim-dap` for debugging in Neovim and appreciate the functionality it provides. However, I've encountered an issue with visibility of the breakpoint indicator, especially when using different color themes where the default icon (`B`) sometimes blends into the background, making it hard to see.

**Feature Request**:
I would like to propose an enhancement that allows users to customize the icon and color of breakpoints. This feature would greatly improve the user experience by making breakpoints more visible and aesthetically pleasing according to the user's theme and preferences.

### Possible Solutions

**Example Configuration**:
```lua
require('dap').setup({
  breakpoints = {
    icon = '',
    color = '#ff0000',  -- bright red for high visibility
  }
})
```

**Comment by mfussenegger** [comment]
See the sign configuration section in the docs:


> SIGNS CONFIGURATION
> 
> 
> nvim-dap uses five signs:
> 
> - `DapBreakpoint` for breakpoints (default: `B`)
> - `DapBreakpointCondition` for conditional breakpoints (default: `C`)
> - `DapLogPoint` for log points (default: `L`)
> - `DapStopped` to indicate where the debugee is stopped (default: `→`)
> - `DapBreakpointRejected` to indicate breakpoints rejected by the debug
>   adapter (default: `R`)
> 
> You can customize the signs by setting them with the |sign_define()| function.
> For example:
> 
> >
> >lua
>   vim.fn.sign_define('DapBreakpoint', {text='🛑', texthl='', linehl='', numhl=''})
>

**Comment by MadeInShineA** [comment]
I had the same issue... it seems I don't know how to read doc :(  (I won't trust GPT anymore)

Thanks!

**Comment by mairs8** [comment]
but there's no description of what texthl, linehl and numhl do. My guess is that this change the breakpoint icon color, line highlight color for debug currently on and relative line number highlight in gutter, but i am guessing all of these. what do these options do?

**Comment by blehrer** [comment]
●○◦⭕︎⚪︎⚫︎🞄🞅🞆🞇🞈🞉⦿◉◎🞊🞋◌🞜⚙︎𝠀⌮⌭⌬〉⎄⌀⨸⨷⨶⨳⫸⧭⧰⧱⧲⧳

**Comment by reybits** [comment]
Unfortunately, `vim.fn.sign_define` is deprecated and should be replaced with something like `vim.diagnostic.config`.

**Comment by mfussenegger** [comment]
`sign_define` is NOT deprecated.

Using `sign_define` to configure the signs used by the `vim.diagnostic` module is. But that has nothing to do with `sign_define` itself or how nvim-dap uses it.
