### ISSUE TITLE
doesn't seem to load adapters from .vscode/launch.json

### ISSUE THREAD

**Issue by GopherJ** [mfussenegger/nvim-dap#1342]
### Steps to Reproduce

N/A

### Expected Result

N/A

### Actual Result

N/A

**Comment by GopherJ** [comment]
configurations can be successfully loaded, but adapters need to be manually configured in neovim

**Comment by mfussenegger** [comment]
A `.vscode/launch.json` doesn't declare adapters. It only references them - so yes they need to be configured elsewhere.
That's intentional
