### ISSUE TITLE
Error when breaking in code at breakpoint

### ISSUE THREAD

**Issue by PrinceDeveloperOf** [mfussenegger/nvim-dap#1343]
### Debug adapter definition and debug configuration
mason-nvim-dap.nvim

### Debug adapter version
2.4.0

### Steps to Reproduce

1. Make new python file
2. Write some code
3. Add breakpoint to code
4. Run Debugger
5. When the debugger gets to that line an breaks this error will show twice

### Expected Result

To not have errors displayed when breaking.

### Actual Result

When a breakpoint is hit during the execution of the program the following error is displayed.

```Error executing vim.schedule lua callback: ...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:130: bad argument #1 to 'pairs' (table expected, got userdata)
stack traceback:
	[C]: in function 'pairs'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:130: in function 'fn'
	...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:345: in function 'for_each_tree'
	...-virtual-text/lua/nvim-dap-virtual-text/virtual_text.lua:125: in function 'set_virtual_text'
	...lazy/nvim-dap-virtual-text/lua/nvim-dap-virtual-text.lua:114: in function 'c'
	...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1031: in function <...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1025>```

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-dap/issues/1332
