### ISSUE TITLE
Document the necessary configuration to pass command line argumets to the debugee.

### ISSUE THREAD

**Issue by de-abreu** [mfussenegger/nvim-dap#1346]
### Problem Statement

I would like to know of a way that command line arguments could be passed on to the executable I'm currently debugging, in the C programming language but not only.

### Possible Solutions

Specify the necessary configuration to enable such functionality.

**Comment by mfussenegger** [comment]
Check the wiki + documentation of the debug adapter you're using.

The issue tracker isn't a support forum but for bug reports or feature requests
