### ISSUE TITLE
Is it possible to make delve to use external terminal ?

### ISSUE THREAD

**Issue by pittcat** [mfussenegger/nvim-dap#135]

**Comment by mfussenegger** [comment]
Doesn't look like it's supported.

vscode-go has [docs for the launch configuration](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#launch-configurations), but it doesn't mention a console/terminal setting.

The experimental DAP API support in delve itself also doesn't seem to support it - at least I couldn't find anything in the docs about it.

I'd suggest to create a feature request upstream for it.
