### ISSUE TITLE
${command:pickProcess} and lazy.utils.pick_process behave differently

### ISSUE THREAD

**Issue by angles-n-daemons** [mfussenegger/nvim-dap#1360]
### Debug adapter definition and debug configuration

This has been mentioned in #918, but ${command:pickprocess} and lazy.utils.pick_process behave differently. More concretely, the former returns a string, and the latter returns a number. I'd expect them to return values of the same type since it seems like the utility is being swapped in for the string template. Init.lua below:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	-- bootstrap lazy.nvim
	-- stylua: ignore
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
		lazypath })
end
vim.opt.rtp:prepend(lazypath)

-- Setup lazy.nvim
require("lazy").setup({
	{
		'williamboman/mason.nvim',
		cmd = 'Mason',
		build = ':MasonUpdate',
		lazy = false,
		config = function() require("mason").setup() end,
	},
	{
		'mfussenegger/nvim-dap',
		dependencies = {
			'folke/neoconf.nvim',
			'leoluz/nvim-dap-go',
			config = true,
		},
		config = function()
			require('dap-go').setup()
		end,
	}
})
```

### Debug adapter version

dcc85d12d6e2c18c5fa0f9a304d9f5e767e1401a

### Steps to Reproduce

Create a simple main.go:

```go
package main

import "fmt"

func main() {
	fmt.Println("hello")
}
```

and add the following launch.json:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "go",
      "name": "Debug Launch.json",
      "request": "attach",
      "processId": "${command:pickProcess}"
    }
  ]
}
```

Then, using the above init.lua, open nvim and run the following commands to start a debugging session:
 * `:MasonInstall delve` - install the debugger
 * `:lua require('dap').set_log_level('TRACE')` - enable verbose logging
 * `:lua require('dap').continue()` - select "Debug Launch.json" option, pick any process

The system will error because it's fed a string for processId instead of a number. Note that the same configuration in lua, using `pick_process` will cause no such error.

### Expected Result

Note processId type below:
```
[ DEBUG ] 2024-11-13T08:52:29Z-0500 ] ...mann/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1711 ]        "request"       {
  arguments = {
    buildFlags = "",
    mode = "local",
    name = "Attach",
    processId = 1,
    request = "attach",
    type = "go"
  },
  command = "attach",
  seq = 2,
  type = "request"
}
```

### Actual Result

```
[ DEBUG ] 2024-11-13T08:52:06Z-0500 ] ...mann/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1711 ]        "request"       {
  arguments = {
    name = "Attach to Process",
    processId = "1",
    request = "attach",
    type = "go"
  },
  command = "attach",
  seq = 2,
  type = "request"
}
```

**Comment by mfussenegger** [comment]
it's a string because `${...}` are just placeholders used _within_ a string.
If you need to have an integer, you'll need to add some post-processing logic using either `enrich_config` or `:h dap-providers-config`.

**Comment by angles-n-daemons** [comment]
Hmm.. I see, it seems like vscode's `pickProcess` impl is pushed down to the individual language adapters ([link](https://github.com/golang/vscode-go/blob/master/docs/debugging.md)). It's nice that nvim-dap covers that common func.

Is it possible to specify a `enrich_config` for a `launch.json` configuration file? A cursory look at the source seems to indicate no, but I may be missing something.

**Comment by mfussenegger** [comment]
`enrich_config` is specific to an adapter but applies to any configuration - independent of where it's coming from - so yes it would apply to `launch.json`.

Also - I gave the wrong pointer with `dap-providers-config` I meant to link to `dap-listeners-on_config`.

I think you could do something like this:

```lua
local dap = require("dap")
dap.listeners.on_config["pick-process-as-number"] = function(config)
  if config.processId == "${command:pickProcess}" then
    local copy = vim.deepcopy(config)
    copy.processId = require("dap.utils").pick_process()
    return copy
  end
  return config
end
```

**Comment by angles-n-daemons** [comment]
I think I can use the listeners here:

```lua
-- new listener function
local function convertProcessIdToInt(oldConfig)
  config = vim.deepcopy(oldConfig)
  for k, v in pairs(oldConfig) do
    if k == 'processId' then
      if v == '${command:pickProcess}' then
        config[k] = require('dap.utils').pick_process()
      elseif type(v) == 'string' then
        config[k] = tonumber(v)
      end
    end
  end
end

-- then, where dap is setup
local dap = require('dap')
-- convert processId values to integer
dap.listeners.on_config['custom.processIdToInt'] = convertProcessIdToInt

```
