### ISSUE TITLE
cpp tools conditional breakpoint

### ISSUE THREAD

**Issue by leosmaia21** [mfussenegger/nvim-dap#1367]
### Debug adapter definition and debug configuration

dap.adapters.cppdbg = {
  id = 'cppdbg',
  type = 'executable',
  command = vim.fn.stdpath("data") .. '/mason/bin/OpenDebugAD7'
}

dap.configurations.c = {
	{
name = "Launch file",
    type = "cppdbg",
    request = "launch",
	program =function() return  programName end,
	cwd = '${workspaceFolder}',
	},
	

### Steps to Reproduce

Try do set a conditional breakpoint with cpp tools instead of lldb, with function like strcmp, it doens't work. with codellbd it works

### Expected Result

Expected to break when the condition is true, including when using functions like strcmp

### Actual Result

It just eval as false and don't stop.

**Comment by leosmaia21** [comment]
I found the issue, the strlen is not loaded until the program is running, therefore the breakpoint needs to be set up after run, i nice feature would be reload breakpoints after running

**Comment by mfussenegger** [comment]
Evaluating breakpoints is up to the debug adapter, not the client
