### ISSUE TITLE
Fatal Python error: _enter_buffered_busy 

### ISSUE THREAD

**Issue by xuyaojianfei** [mfussenegger/nvim-dap#1370]
### Debug adapter definition and debug configuration

I think the problem is caused by upgrading my Mac OS, because I saw similar issues in the nvim-dap-python project where they also had problems caused by upgrading macOS.
https://github.com/mfussenegger/nvim-dap-python/issues/146 
However, I believe the problem is caused by this project, because I stopped nvim-dap-python and still got the same error.
Here is my config,the simplest configuration

dap.adapters
```
dap.adapters.python = {
  type = 'executable',
  command = 'python',
  args = { '-m', 'debugpy.adapter' }
}
```
dap.configurations
```
dap.configurations.python = {
  {
    type = 'python',
    request = "launch",
    name = "Launch file",
    program = "${file}",
  }
}
```

### Debug adapter version

0.8.0

### Steps to Reproduce

100% reproduce
just run continue()

### Expected Result

Normal operation

### Actual Result

The program executes normally before exiting, but after exiting, the following error appears in DapShowLog
```
[ ERROR ] 2024-11-20T02:49:53Z+0800 ] ...uhao/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1524 ]	"stderr"	{
  args = { "-m", "debugpy.adapter" },
  command = "python",
  type = "executable"
}	"Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedReader name='<stdin>'> at interpreter shutdown, possibly due to daemon threads\nPython runtime state: finalizing (tstate=0x"
[ ERROR ] 2024-11-20T02:49:53Z+0800 ] ...uhao/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1524 ]	"stderr"	{
  args = { "-m", "debugpy.adapter" },
  command = "python",
  type = "executable"
}	"00000001035fbba0)\n\nCurrent thread 0x00000001fd8f7840 (most recent call first):\n  <no Python frame>\n"
[ INFO ] 2024-11-20T02:49:53Z+0800 ] ...uhao/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1497 ]	"Process closed"	52164
```

**Comment by mfussenegger** [comment]
> I think the problem is caused by upgrading my Mac OS

Then your python install is likely messed up in some way. 
Either that, or it's a debugpy issue.

Not a client bug
