### ISSUE TITLE
session.lua doesn't exist

### ISSUE THREAD

**Issue by AadiWaghray** [mfussenegger/nvim-dap#1396]
### Debug adapter definition and debug configuration

dap.configurations is located within function passed to  config in lazy.nvim plugin deceleration for nvim-dap
```lua 
local dap = require('dap')
dap.configurations = {
	c = {
		{
			name = "Launch",
			type = "codelldb",
			request = "launch",
			program = function()
				return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
			end,
		},
	}
}
```
dap.adapter is located in after/ftpluging/c.lua
```lua
local dap = require('dap')
dap.adapters.codelldb = {
	type = 'server',
	port = "${port}",
	executable = {
		command = '~/Users/aadiwaghray/.config/nvim/extension/adapter/codelldb',
		args = {"--port ${port}"},
	}
}
```

### Steps to Reproduce

1. Open C file with bare minimal main function 
(i.e. 
int main() {
    int a = 3;
    return a;
})
2. Compile with desired compiler
3. Run :lua require'dap'.set_breakpoint on variable decleration 
4. Run :lua require'dap'.continue

### Expected Result

nvim-dap to start up normally (since ui plug-in is configured have that boot up as well.)

### Actual Result

Error 
...hray/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1281: ENOENT: no such file or directory                                           
stack traceback:                                                                                                                                                                                             
^I[C]: in function 'error'                                                                                                                                                                                   
^I...hray/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1281: in function 'spawn_server_executable'                                                                                                    
^I...hray/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1395: in function 'connect'                                                                                                                    
^I.../aadiwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:1190: in function 'attach'                                                                                                                     
^I.../aadiwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:441: in function 'run_adapter'                                                                                                                 
^I.../aadiwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:473: in function 'maybe_enrich_config_and_run'                                                                                                 
^I.../aadiwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:595: in function 'fn'                                                                                                                          
^I...aghray/.local/share/nvim/lazy/nvim-dap/lua/dap/async.lua:9: in function 'run'                                                                                                                           
^I.../aadiwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:621: in function 'run'                                                                                                                         
^I.../aadiwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:510: in function 'cb'                                                                                                                          
^I...diwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap/ui.lua:38: in function 'pick_if_many'                                                                                                                 
^I.../aadiwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:504: in function <.../aadiwaghray/.local/share/nvim/lazy/nvim-dap/lua/dap.lua:481>                                                             
^I[C]: in function 'xpcall'                                                                                                                                                                                  
^I...aghray/.local/share/nvim/lazy/nvim-dap/lua/dap/async.lua:12: in function <...aghray/.local/share/nvim/lazy/nvim-dap/lua/dap/async.lua:11> 

The only thing in the log folder (level is trace) is 
[ DEBUG ] 2024-12-09T20:22:42Z-0500 ] ...hray/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1260 ]	"Starting debug adapter server executable"	{
  args = { "--port 1300" },
  command = "~/Users/aadiwaghray/.config/nvim/extension/adapter/codelldb"
}

I have ensured that nvim-dap is installed correctly (i.e. files are where they should be) and specifically that session.lua exists. The stack trace doesn't make sense to me be because previous functions are calling from the file the error says doesn't exist.  I apologize if this is a skill issue on my part or that I overlooked something.

**Comment by mfussenegger** [comment]
See `:checkhealth dap` 

You need to use the full path to the command and the args are wrong too

```lua
  dap.adapters.codelldb = {
    type = 'server',
    port = "${port}",
    executable = {
      command = vim.fn.expand('~/Users/aadiwaghray/.config/nvim/extension/adapter/codelldb'),
      args = { "--port", "${port}" },
    }
  }
```
