### ISSUE TITLE
Tailing commas and comments in launch.json

### ISSUE THREAD

**Issue by adilJamshad** [mfussenegger/nvim-dap#1410]
### Debug adapter definition and debug configuration

I am using neovim .9 in kitty terminal. Everything works fine. It is just if the launch.json has tailing commas or comments in it, it fails to load. can we sanitize it?

### Steps to Reproduce

- add some comments in launch.json file
- add a trailing comma in launch.json file

the file will fail to parse

### Expected Result

the file should be parsed.

### Actual Result

json error for trailing commas and comments.

**Comment by mfussenegger** [comment]
`:help dap-launch.json`
