### ISSUE TITLE
Skip "Press ENTER or type command to continue"

### ISSUE THREAD

**Issue by Shatur95** [mfussenegger/nvim-dap#150]
Hi! Thank you for the awesome plugin!

I have a suggestion. Currently on `dap.run(config)` the plugin shows message:

![изображение](https://user-images.githubusercontent.com/22453358/114906770-0df2ec00-9e23-11eb-93db-23f9af84bb83.png)

Therefore, I would like to suggest adding the option to skip this message or not require confirmation by pressing <kbd>Enter</kbd> by default.

**Comment by mfussenegger** [comment]
I've removed the messages again. Didn't realize they cause the ENTER prompt (I've `cmdheight=2` set, so for me it didn't happen).

Going to add a function that can be integrated into the statusline instead. See https://github.com/mfussenegger/nvim-dap/pull/152

**Comment by Shatur95** [comment]
Awesome, thank you!
