### ISSUE TITLE
Stop function does not stop session

### ISSUE THREAD

**Issue by Shatur95** [mfussenegger/nvim-dap#160]
**Steps to reproduce**

1. Start any session
2. Call `lua require("dap").stop()`

**Expected behavior**

Session stopped, the repl closed.

**Current behavior**

The repl and the application is still active. But any command in repl says that there i no active session.

**Comment by mfussenegger** [comment]
The naming is probably a bit confusing. `stop()` currently only stops the client. `disconnect()` would also send a message to the debug adapter to disconnect. Could you try that? That's probably closer to what you want.

> the repl closed.

Whether the repl is open or closed is currently not bound to the session, there may be reasons why you'd want to keep it open and it's easier to extend the behavior than the other way around. E.g. you can create a mapping for `:lua require('dap').disconnect(); require('dap').repl.close()`, or add a `DapStop` command that invokes both functions.

**Comment by Shatur95** [comment]
> E.g. you can create a mapping for :lua require('dap').disconnect(); require('dap').repl.close()

Thanks, just what I need.

Can we have an `exit` command in repl objec (like `.exit`)?
