### ISSUE TITLE
How do I run a specific job or task?

### ISSUE THREAD

**Issue by jsatk** [mfussenegger/nvim-dap#162]
In IntelliJ in my Scala project I can right click and set a breakpoint and then in the upper right there's a dropdown where I can choose what task/job to run and then click on the bug icon and that runs the job. I can click 'edit' on that job as well and change the params. I'm trying to accomplish the same with DAP.

So far with nvim-dap I can set a breakpoint, open the repl, and run "continue" which prompts me with `Run`, `Test File`, and `Test Target`.

So for example if I have the following in my `build.sbt`.

```sbt
addCommandAlias("foo", "runMain com.mycompany.Foo")
```

and then I have a file

```scala
package com.mycompany

object Foo extends App {
  def whatever = {
    // BREAKPOINT HERE
  }
}
```

How do I hit this breakpoint? How do I run `sbt foo` in nvim with DAP and hit this breakpoint like I can in IntelliJ?

Here's my dap config.
```lua
dap.configurations.scala = {
  {
    type = "scala",
    request = "launch",
    name = "Run",
    metalsRunType = "run",
  },
  {
    type = "scala",
    request = "launch",
    name = "Test File",
    metalsRunType = "testFile",
  },
  {
    type = "scala",
    request = "launch",
    name = "Test Target",
    metalsRunType = "testTarget",
  },
}
```

**Comment by ckipp01** [comment]
> So far with nvim-dap I can set a breakpoint, open the repl, and run "continue" which prompts me with `Run`, `Test File`, and `Test Target`.

So just to ensure it's clear, the `Run`, `Test File`, and `Test Target` are very specific to metals, and they are actually stripped out before handing the configurations to `nvim-dap`. We just use them to ensure the correct thing is being sent into Metals to start the correct type of DAP session.

In your given example, let's say you had a breakpoint put into the `whatever` method, you'd select the option to `Run`, and then it'd stop there just like it would in IntelliJ. Now what you're probably used to in IntelliJ is everything just automatically popping up and overing you different options to step in, step over, look at the variables in scope etc. Those are all still options, but all need to be mapped or manually entered into the debug repl. Whatever you prefer. Just to give a couple hints for things that you probably are looking for.

Check out `:h dap-ui-variables-api`. That api will hold some stuff you are probably looking for like `dap.ui.variables.hover()` to show the information on the variable you are over. Also explore things like `.scopes` in the repl.

**Comment by theHamsta** [comment]
I guess this project https://github.com/scalameta/nvim-metals looks like it would already help you to set up the possible start jobs for your project.


# If not:
You could also get some inspiration from https://github.com/mfussenegger/nvim-jdtls/blob/master/lua/jdtls/dap.lua

You can also use nvim-treesitter locals to find out the package and function you're currently in as you probably need them to start the specific App you want to start.

**Comment by jsatk** [comment]
What's still unclear to me is how would I run the job `sbt foo`. `addCommandAlias("foo", "runMain com.mycompany.Foo")`

When I do `Run` locally it doesn't "hit" the breakpoint or prompt me for which of my many jobs I want to run. When I open the REPL I see nothing.

How do I run a specific task?

Apologies if I'm being dumb and not getting it.

**Comment by jsatk** [comment]
Update: the metals log gives me this error when I select `Run`.

I'll be honest. I'm not sure exactly what this means or how to fix it. Will read more.

```
Apr 22, 2021 12:56:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: Invalid arguments: Buffer({"runType":"run","
path":"file:///Users/jesse.atkinson/Developer/[REDACTED]"}). Expecting: DebugSessionParameters object
Example:
```json
{
  "targets": ["mybuild://workspace/foo/?id=foo"],
   dataKind: "scala-main-class",
   data: {
      className: "com.foo.App"
   }
}
```

or DebugUnresolvedMainClassParams object
Example:
```json
{
   mainClass: "com.foo.App",
   buildTarget: "foo",
   args: ["bar"],
   jvmOptions: ["-Dfile.encoding=UTF-16"],
   env: {"NUM" : "123"},
   envFile: ".env"
}
```

or DebugUnresolvedTestClassParams object
Example:
```json
{
   testClass: "com.foo.FooSuite",
   buildTarget: "foo"
}
```

java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid arguments: Buffer(
{"runType":"run","path":"file:///Users/jesse.atkinson/Developer/[REDACTED]}). Expecting: DebugSessionParameters object
Example:
```json
{
  "targets": ["mybuild://workspace/foo/?id=foo"],
   dataKind: "scala-main-class",
   data: {
      className: "com.foo.App"
   }
}
```

or DebugUnresolvedMainClassParams object
Example:
```json
{
   mainClass: "com.foo.App",
   buildTarget: "foo",
   args: ["bar"],
   jvmOptions: ["-Dfile.encoding=UTF-16"],
   env: {"NUM" : "123"},
   envFile: ".env"
}
```

or DebugUnresolvedTestClassParams object
Example:
```json
{
   testClass: "com.foo.FooSuite",
   buildTarget: "foo"
}
```

        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:686)
        at java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2014)
        at scala.concurrent.java8.FuturesConvertersImpl$CF.thenAccept(FutureConvertersImpl.scala:37)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java
:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java
:113)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid arguments: Buffer({"runType":"run","path":"file:/
//Users/jesse.atkinson/Developer/[REDACTED].scala"}). Expecting: DebugSessionParameters obj
Example:
```json
{
  "targets": ["mybuild://workspace/foo/?id=foo"],
   dataKind: "scala-main-class",
   data: {
      className: "com.foo.App"
   }
}
```

or DebugUnresolvedMainClassParams object
Example:
```json
{
   mainClass: "com.foo.App",
   buildTarget: "foo",
   args: ["bar"],
   jvmOptions: ["-Dfile.encoding=UTF-16"],
   env: {"NUM" : "123"},
   envFile: ".env"
}
```

or DebugUnresolvedTestClassParams object
Example:
```json
{
   testClass: "com.foo.FooSuite",
   buildTarget: "foo"
}
```

        at scala.meta.internal.metals.MetalsLanguageServer.executeCommand
1)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccess
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMeth
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(Gen
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteE
        ... 9 more
```

**Comment by ckipp01** [comment]
We're getting pretty specific into Metals territory, but that looks suspiciously like you're on an old version of metals that doesn't know how to handle `runType`. If you do a `:MetalsInfo`, what version of Metals are you using?

> What's still unclear to me is how would I run the job sbt foo. addCommandAlias("foo", "runMain com.mycompany.Foo")

So it's a tad tricky to tell without seeing how your build is defined. But as long as you trigger a `run` in the same build target that `com.mycompany.Foo` is in, and `Foo` is a valid main class, then it should auto-detect it.

Also this seems to be more of a nvim-metals/metals issue looking at those logs, so feel free to close this here if need be @mfussenegger and we can move it over to nvim-metals.

**Comment by jsatk** [comment]
Sorry to bring in Metals issues in here 😞

**Comment by jsatk** [comment]
@ckipp01 on Metals 0.10.0.

**Comment by ckipp01** [comment]
> @ckipp01 on Metals 0.10.0. Literally ran `:PackerSync` this morning so I should have the latest of the nvim-metals plugin.

Yup, that's exactly the issue. The `runType` stuff was added in 0.10.0. https://scalameta.org/metals/blog/2021/04/06/tungsten.html#smoother-main-and-test-discovery

Keep in mind that `:PackerSync` will get you the latest `nvim-metals`, but not the latest Metals. All you will need to do is `:MetalsInstall` which will re-install the latest version of Metals (0.10.2), and then try again and it should work.

**Comment by jsatk** [comment]
*Now* it's working perfectly. 😆 

I didn't realize support for this was so new. Thank you @ckipp01. Sorry to rope you into another Metals thing. 🙏 

Sorry I was barking in the wrong repo @mfussenegger.
