### ISSUE TITLE
No configuration found for cpp

### ISSUE THREAD

**Issue by kflak** [mfussenegger/nvim-dap#166]
Hi,

Most likely I am an idiot, but unfortunately I keep getting a `No configuration found for cpp` in my cpp projects. This is my configuration: 
```        use {
            'mfussenegger/nvim-dap',
            config = function()
                local dap = require'dap'
                dap.adapters.cpp = {
                    type = 'executable',
                    attach = {
                        pidProperty = "pid",
                        pidSelect = "ask"
                    },
                    command = 'lldb-vscode',
                    env = {
                        LLDB_LAUNCH_FLAG_LAUNCH_IN_TTY = "YES"
                    },
                    name = "lldb"
                }
            end
        }
``` 
in my packer configuration. 
Output of `which lldb-vscode`:
```
/usr/bin/lldb-vscode
```
System: Arch lts latest, nvim-nightly latest
Any help is greatly appreciated!

**Comment by theHamsta** [comment]
But did you set a configuration too (After a :Packer compile)? In your configuration you set the adapter (lldb-vscode) but what is your configuration (the process you want to debug)? The error message complains about a missing configuration. Did you try the example in wiki?

**Comment by kflak** [comment]
Hmmm, I did try to add this file, nvim_dap.lua to my config:
```local M = {}
local last_gdb_config

M.start_c_debugger = function(args, mi_mode, mi_debugger_path)
    local dap = require "dap"
    if args and #args > 0 then
        last_gdb_config = {
            type = "cpp",
            name = args[1],
            request = "launch",
            program = table.remove(args, 1),
            env = function()
                local variables = {}
                for k, v in pairs(vim.fn.environ()) do
                    table.insert(variables, string.format("%s=%s", k, v))
                end
                return variables
            end,
            args = args,
            cwd = vim.fn.getcwd(),
            externalConsole = true,
            MIMode = mi_mode or "gdb",
            MIDebuggerPath = mi_debugger_path
        }
    end

    if not last_gdb_config then
        print('No binary to debug set! Use ":DebugC <binary> <args>" or ":DebugRust <binary> <args>"')
        return
    end

    dap.run(last_gdb_config)
    -- dap.repl.open()
end

return M
```
and launch the debugger via `:DebugC lldb`, which seems to work, but I am not quite getting the kind of fancy behavior that I see in some of those vscode-tutorials. It is also very possible that I am just missing some very fundamental knowledge on how to debug with lldb. I am very much a noob to cpp debugging, so please bear with me...

**Comment by mfussenegger** [comment]
If you call `require('dap').continue()` within a file with filetype `cpp` it will look for a `dap.configurations.cpp` entry. You don't add a `cpp` entry, that's why you get the error message.

You could add an entry like this:


```lua
  dap.configurations.cpp = {
    {
      name = "Launch",
      type = "cpp",
      request = "launch",
      program = function()
        return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
      end,
      cwd = '${workspaceFolder}',
      env = function()
        local variables = {}
        for k, v in pairs(vim.fn.environ()) do
          table.insert(variables, string.format("%s=%s", k, v))
        end
        return variables
      end,
      stopOnEntry = false,
      args = {}
    },
  }
```

Adding this entry would cause `require('dap').continue()` to prompt you for the file you want to execute (the compiled executable with debug symobl)

If you'd like to be able to attach to a running process, you could also add an entry that looks [like this one](https://github.com/mfussenegger/dotfiles/blob/55f3b064cca18ad108dccbea7bd6456835713dd1/vim/.config/nvim/lua/me/dap/conf.lua#L181-L217)


> but I am not quite getting the kind of fancy behavior that I see in some of those vscode-tutorials

What behavior are you referring to?

**Comment by kflak** [comment]
Thanks a lot! Debugging is now happening. Now I just need to learn how to use it...
The fancy behavior refers to how people will just hover their mouse over a variable to get its value and memory address and so on.

**Comment by mfussenegger** [comment]
> The fancy behavior refers to how people will just hover their mouse over a variable to get its value and memory address and so on.

See `:help dap.ui.variables.hover()` and `:help dap.repl.open()`

**Comment by kflak** [comment]
Thanks for the tip. I guess I'll have to take a day to just deepdive into dap and see what it is and can do!
