### ISSUE TITLE
Debugpy wiki wrong

### ISSUE THREAD

**Issue by seblj** [mfussenegger/nvim-dap#174]
I recently took my time to check out this plugin, and it looks awesome! I thought I would just let you know that there is a small problem with the wiki for debugpy. In the `debugpy.configurations.python` where dap is looking for an executable, this should be compared to 1. Help page is stating that `executable` is returning either 1, 0 or -1, and all of them returns true. Just thought I would share this so others don't understand why it won't configure correctly

**Comment by theHamsta** [comment]
Would you mind to fix it?

**Comment by seblj** [comment]
Yeah sure!

**Comment by seblj** [comment]
Done

**Comment by theHamsta** [comment]
Thank you!
