### ISSUE TITLE
I've changed the wiki because rust-lldb works for me

### ISSUE THREAD

**Issue by p00f** [mfussenegger/nvim-dap#175]
The wiki said that `rust-lldb` doesn't work with `lldb-vscode`, but it does for me

![image](https://user-images.githubusercontent.com/36493671/117563039-cdecf500-b0c0-11eb-9125-5983558e73ee.png)

My function: https://github.com/p00f/dotfiles/blob/main/nvim/.config/nvim/lua/dap_functions.lua
My adapter and debug configuration setup: https://github.com/p00f/dotfiles/blob/main/nvim/.config/nvim/lua/dap_setup.lua
My `DebugRust` command: `lua require 'dap_functions'.start_c_debugger({<f-args>}, 'lldb', 'rust-lldb')`

**Comment by p00f** [comment]
@mfussenegger

**Comment by p00f** [comment]
https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation/_compare/906b7158ff9581acbb51b6d262babdfd963f0c11...e52c0cfd06e37120ee38ebda9c5cfe1da725253d

**Comment by theHamsta** [comment]
The TODO was referring to running some Python scripts of lldb for Rust to have better  introspection of some common Rust data types like hash maps.

**Comment by p00f** [comment]
Oh I'm so sorry

**Comment by p00f** [comment]
I reverted it

**Comment by theHamsta** [comment]
No worries. I don't even know whether it is really necessary
