### ISSUE TITLE
C#: Can't debug with netcoredbg without setting a breakpoint

### ISSUE THREAD

**Issue by anguye21** [mfussenegger/nvim-dap#177]
I have got installed netcoredbg using vimspector and have got it to work if I set a breakpoint. However, when I don't set a breakpoint I get the following error message and the debugger never starts.

`Error executing vim.schedule lua callback: ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:109: attempt to index field 'capabilities' (a nil value)`

Output from the log flie:

> [ WARN ] 2021-05-10T03:05:13Z-0400 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:530 ]	"No event handler for "	{
>   body = {
>     capabilities = {
>       supportTerminateDebuggee = true,
>       supportsConditionalBreakpoints = true,
>       supportsConfigurationDoneRequest = true,
>       supportsExceptionInfoRequest = true,
>       supportsFunctionBreakpoints = true,
>       supportsSetVariable = true
>     }
>   },
>   event = "capabilities",
>   seq = 1,
>   type = "event"
> }

Config that I am using:

```lua
local dap = require("dap")

local function pwd() return io.popen("pwd"):lines()() end

dap.adapters.netcoredbg = {
    type = "executable",
    command = XDG_DATA_HOME .. "/vimspector-config/gadgets/linux/netcoredbg/netcoredbg",
    args = {
        "--interpreter=vscode",
        string.format("--engineLogging=%s/netcoredbg.engine.log", XDG_CACHE_HOME),
        string.format("--log=%s/netcoredbg.log", XDG_CACHE_HOME),
    },
}

dap.configurations.cs = {
    {
        type = "netcoredbg",
        name = "launch - netcoredbg",
        request = "launch",
        program = function()
            local dll = io.popen("find bin/Debug/ -maxdepth 2 -name \"*.dll\"")
            return pwd() .. "/" .. dll:lines()()
        end,
        stopAtEntry = true,
    },
}
```

**Comment by mfussenegger** [comment]
Thanks for the report.

I think the issue should be fixed with https://github.com/mfussenegger/nvim-dap/pull/178 - could you give it a try?

**Comment by anguye21** [comment]
Yep, that fixes it. Thanks a lot.
