### ISSUE TITLE
Repl displays extra symbols

### ISSUE THREAD

**Issue by Shatur** [mfussenegger/nvim-dap#187]
I use `lldb-vscode` from LLVM and it displays ending symbols at the end of newline:
![изображение](https://user-images.githubusercontent.com/22453358/119056145-dbfd1880-b9d2-11eb-9907-28ce3131fb36.png)

Is it possible to hide it?

**Comment by theHamsta** [comment]
Those are Windows/DOS line endings. They could be filtered out with something like this in session.lua

```
function Session.event_output(_, body)
  require('dap.repl').append(body.output:gsub("\r\n", "\n"), '$')
end
```
and in more spots where we display raw content of the debugger in the REPL (e.g. on exceptions)

**Comment by theHamsta** [comment]
Should be done probably directly in `repl.append`
