### ISSUE TITLE
Feature: debug to cursor

### ISSUE THREAD

**Issue by JoseConseco** [mfussenegger/nvim-dap#188]
Nvim-dap could  add temporary breakpoint at cursor, then run code until temp breakpoint is hit, then remove temp breakpoint.  Grat plugin btw.

**Comment by mfussenegger** [comment]
Good idea. Could you try https://github.com/mfussenegger/nvim-dap/pull/195 ?

**Comment by JoseConseco** [comment]
Tanks again. It works  very well.  Closing this
