### ISSUE TITLE
Must Set projectName in java dap configuration

### ISSUE THREAD

**Issue by Spacefreak18** [mfussenegger/nvim-dap#190]
Hi there, great work, and I was able to get this working to debug in java.

I didn't see this mentioned in the documentation but for my dap java configuration I had to set projectName before it would work. I noticed in dap.lua that it passes this to the class resolver in the jdtls debug server.

This isn't terrible, but i'm trying to attach to a tomcat server, and this server has a bunch of different projects that all depend on eachother. And the debugger only works if I set the projectName for the particular java class I want to debug in the dap configuration.

I tried setting require('jdtls.dap').setup_dap_main_class_configs() but that did not seem to help.

So it seems a little inconvenient, unless I am missing something which seems highly likely.

**Comment by mfussenegger** [comment]
The projectName requirement comes from https://github.com/microsoft/vscode-java-debug. nvim-jdtls has logic that tries to automatically infer the projectName if possible, but it doesn't work in all cases.

I'm not too familiar with tomcat, but in other projects with multiple modules it works if you have some kind of "main" project that depends on all the other projects and use that to debug the application. 


There's nothing that I can do about it in nvim-dap.

**Comment by mfussenegger** [comment]
@Spacefreak18 did my answer help?
