### ISSUE TITLE
Run command before launching

### ISSUE THREAD

**Issue by tomaskallup** [mfussenegger/nvim-dap#191]
Hi, I was trying to use this plugin in a typescript plugin and wasn't able to get it running. I need to run a command (`yarn build`) before starting the application and attaching to it. Is this currently possible?

**Comment by mfussenegger** [comment]
Not sure I understand the problem. Could you elaborate on how you configured nvim-dap, which actions you take and what output you get and what output you'd expect?

**Comment by tomaskallup** [comment]
I currently can't use nvim-dap.

I would like to use the node adapter, but since the project is in typescript, I need to compile it before starting the debugging.

What I'm looking for is a equivalent of VSCodes "tasks", but simplified.
This is what the VSCode people use:


lanuch.json
```json
    {
      "type": "node",
      "request": "launch",
      "name": "Leader ⚡ - develop",
      "args": [
        "${workspaceFolder}/services/leader/build/index.js"
      ],
      "preLaunchTask": "tsc: build - services/leader/tsconfig.json",
      "runtimeArgs": [
        "--nolazy"
      ],
      "sourceMaps": true,
      "protocol": "inspector",
      "console": "integratedTerminal",
      "env": {
        "PORT": 9001,
        "GOOGLE_APPLICATION_CREDENTIALS": "${workspaceFolder}/.credentials/local.json"
      }
    }
```

tasks.json
```json
    {
      "type": "typescript",
      "tsconfig": "services/leader/tsconfig.json",
      "problemMatcher": [
        "$tsc"
      ],
      "group": "build"
    }
```

I think a very simple way of implementing this would be allowing to define a `preLaunchTask` which would just be a shell command, which is ran before starting the debugging (aborting if it exits with a non-zero code).
The final configuration could be something like this:
```lua
local dap = require'dap'

dap.adapters.node2 = {
  type = 'executable',
  command = 'node',
  args = {os.getenv('HOME') .. '/Pkg/vscode-node-debug2/out/src/nodeDebug.js'},
}

dap.configurations.leader = {
  {
    type = 'node2',
    request = 'launch',
    cwd = vim.fn.getcwd(),
    sourceMaps = true,
    protocol = 'inspector',
    console = 'integratedTerminal',
    preLaunchTask = 'yarn run build'
  },
}
```

**Comment by mfussenegger** [comment]
You could change the adapter configuration to something like this:


```lua
dap.adapters.node2 = function(cb, config)
  if config.preLaunchTask then
    vim.fn.system(config.preLaunchTask)
    config.preLaunchTask = nil
  end
  local adapter = {
    type = 'executable',
    command = 'node',
    args = {os.getenv('HOME') .. '/Pkg/vscode-node-debug2/out/src/nodeDebug.js'},
  }
  cb(adapter)
end
```


And then your `preLaunchTask` definition would be picked up.


I currently don't plan on adding something that mirrors or resembles the VSCode tasks facilities. Given the amount of extensibility of the adapter/configuration definitions - most use cases can already be scripted in one way or another.

**Comment by tomaskallup** [comment]
Ah, I had no idea I could do it like this.

I understand, VSCode tasks are way too complicated for something like this and I would not want them directly, but a simple way to run a command. What you provided is enough for my case.

**Comment by tomaskallup** [comment]
So I did what you suggested, however I can't seem to get `env` working.

Here is the configuration:
```lua
dap.configurations.typescript = {
    {
        type = "node2",
        request = "launch",
        name = "Leader ⚡ - develop",
        program = "${workspaceFolder}/services/leader/build/index.js",
        cwd = vim.fn.getcwd(),
        preLaunchTask = "yarn --cwd services/leader/ build",
        sourceMaps = true,
        protocol = "inspector",
        console = "integratedTerminal",
        env = {
            PORT = 9001,
            GOOGLE_APPLICATION_CREDENTIALS = "${workspaceFolder}/.credentials/local.json"
        }
    }
}
```

I tried to also modify the adapter, but no luck:
```lua
dap.adapters.node2 = function(cb, config)
    if config.preLaunchTask then vim.fn.system(config.preLaunchTask) end
    local adapter = {
        type = 'executable',
        command = 'node',
        args = {
            os.getenv('HOME') .. '/Pkg/vscode-node-debug2/out/src/nodeDebug.js'
        },
        env = config.env or {}
    }
    cb(adapter)
end
```

Do you have any idea what is going on?

**Comment by mfussenegger** [comment]
Not sure about vscode-node-debug2 but for other adapters the `env` option must be a list of strings where each string is a `<key>=<value>` pair:

```lua
env = {
  'PORT = 9001',
  'GOOGLE_APPLICATION_CREDENTIALS = "${workspaceFolder}/.credentials/local.json"'
}
```

**Comment by tomaskallup** [comment]
That seems to throw `Error executing vim.schedule lua callback: Vim:E475: Invalid argument: env`, does that mean the `vscode-node-debug2` doesn't accept it? It probably should, since it works in VSCode, but I don't know how it works under the hood.

**Comment by dchusovitin** [comment]
> I would like to use the node adapter, but since the project is in typescript, I need to compile it before starting the debugging.

You can run TS scripts without compilation with [ts-node](https://www.npmjs.com/package/ts-node). vscode also [supports it ](https://gist.github.com/cecilemuller/2963155d0f249c1544289b78a1cdd695).

And after this replace `adapters.command` to:
- ts-node
- node --require ts-node/register

**Comment by tomaskallup** [comment]
> > I would like to use the node adapter, but since the project is in typescript, I need to compile it before starting the debugging.
> 
> You can run TS scripts without compilation with [ts-node](https://www.npmjs.com/package/ts-node). vscode also [supports it ](https://gist.github.com/cecilemuller/2963155d0f249c1544289b78a1cdd695).
> 
> And after this replace `adapters.command` to:
> 
>     * ts-node
> 
>     * node --require ts-node/register

I know I can, but sadly the startup time can be in minutes depending on the size of the project. Building it is just way faster (as it can be done incrementally) but we were able to solve the compilation problem. Currently the app doesn't get `env` passed, which is also a blocker.

**Comment by mfussenegger** [comment]
@tomaskallup Do I understand this right that the `env` options you're setting should be passed back to your application (which is launched in the integrated terminal)?


Could you try again with the first formatting variant (as proper table) and show the log output? (see `:help dap.set_log_level()`).

I assume you are on latest neovim master? There was a fix a while ago related to supporting the `env` argument in `termopen`.

**Comment by dchusovitin** [comment]
https://github.com/mfussenegger/nvim-dap/blob/ea45f012913dd7699dda7f7d44a34964e9dc5332/lua/dap/session.lua#L76
@mfussenegger, I've found. If I pass env in format `env: { ['key'] = 'value' }` than `opts.env` (and `body.env`) which passed to `termopen` has a strange type (I think `termopen` ignore it):
```lua
-- vim.inspect(opts.env)
vim.empty_dict() {                                                                                      
  TEST = "test"                                                                                         
}
```
Just make a table copy and all works. But I don't know why.
```lua
local term_env = {}
for k, v in pairs(body.env) do                                                                  
  term_env[k] = v
end                                                                                             
opts.env = term_env 
```

**Comment by tomaskallup** [comment]
@mfussenegger Anything in particular I should show you from the log? It's an insanely large file.

I'm running neovim built from git master, last commit I have is `becbb7436f7f027f0ff1fcf440334c0b3a9a8e1a`, from a few days ago.

I found these in the log:
```log
[ DEBUG ] 2021-06-08T10:20:40Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:724 ]	"request"	{
  arguments = {
    console = "integratedTerminal",
    cwd = "/home/armeeh/Projects/Reas/reas-services",
    env = {
      PORT = 9001
    },
    name = "Leader ⚡ - develop",
    preLaunchTask = "yarn --cwd services/leader/ build",
    program = "/home/armeeh/Projects/Reas/reas-services/services/leader/build/index.js",
    protocol = "inspector",
    request = "launch",
    sourceMaps = true,
    type = "node2"
  },
  command = "launch",
  seq = 1,
  type = "request"
}
[ DEBUG ] 2021-06-08T10:20:40Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:492 ]	{
  body = {
    category = "telemetry",
    data = {
      ["Versions.DebugAdapter"] = "1.42.6",
      ["Versions.DebugAdapterCore"] = "6.8.9",
      requestType = "request",
      successful = "true",
      timeTakenInMilliseconds = "1.740546"
    },
    output = "ClientRequest/initialize"
  },
  event = "output",
  seq = 2,
  type = "event"
}
[ DEBUG ] 2021-06-08T10:20:40Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:492 ]	{
  body = {
    category = "telemetry",
    data = {
      ["Versions.DebugAdapter"] = "1.42.6",
      ["Versions.DebugAdapterCore"] = "6.8.9",
      args = { "preLaunchTask", "cwd", "console", "name", "protocol", "program", "env", "sourceMaps", "type", "request", "enableSourceMapCaching", "_suppressConsoleOutput", "sourceMapPathOverrides", "smartStep", "showAsyncStacks" },
      request = "launch"
    },
    output = "debugStarted"
  },
  event = "output",
  seq = 3,
  type = "event"
}
[ DEBUG ] 2021-06-08T10:20:40Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:492 ]	{
  arguments = {
    args = { "/home/armeeh/.nvm/versions/node/v12.18.1/bin/node", "--inspect-brk=35242", "services/leader/build/index.js" },
    cwd = "/home/armeeh/Projects/Reas/reas-services",
    env = {
      PORT = 9001
    },
    kind = "integrated",
    title = "Node Debug Console"
  },
  command = "runInTerminal",
  seq = 4,
  type = "request"
}
[ DEBUG ] 2021-06-08T10:20:40Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:48 ]	"run_in_terminal"	{
  args = { "/home/armeeh/.nvm/versions/node/v12.18.1/bin/node", "--inspect-brk=35242", "services/leader/build/index.js" },
  cwd = "/home/armeeh/Projects/Reas/reas-services",
  env = {
    PORT = 9001
  },
  kind = "integrated",
  title = "Node Debug Console"
}
[ DEBUG ] 2021-06-08T10:20:40Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:744 ]	"response"	{
  body = {
    processId = 1547797
  },
  command = "runInTerminal",
  request_seq = 4,
  seq = 2,
  success = true,
  type = "response"
}
```

**Comment by mfussenegger** [comment]
@tomaskallup Can you try running the following?

```
:lua vim.fn.termopen({ "/home/armeeh/.nvm/versions/node/v12.18.1/bin/node", "--inspect-brk=35242", "services/leader/build/index.js" }, { cwd = '/home/armeeh/Projects/Reas/reas-services', env = { PORT = 9001 }})
```

Based on the logs the `runInTerminal` request includes the environment variables, and they're passed on to `termopen`. So if they don't have any effect it would be a problem with `termopen` itself.

**Comment by tomaskallup** [comment]
> @tomaskallup Can you try running the following?
> 
> ```
> :lua vim.fn.termopen({ "/home/armeeh/.nvm/versions/node/v12.18.1/bin/node", "--inspect-brk=35242", "services/leader/build/index.js" }, { cwd = '/home/armeeh/Projects/Reas/reas-services', env = { PORT = 9001 }})
> ```
> 
> Based on the logs the `runInTerminal` request includes the environment variables, and they're passed on to `termopen`. So if they don't have any effect it would be a problem with `termopen` itself.

That seems to act weird. It opens a terminal, saying the debugger is listening, but the node app never starts. My guess is because of `--inspect-brk`, it never gets loaded since it gets paused on start. I tried to do `--inspect` instead and that seems to work. Env is passed correctly and the port is correct.

**Comment by tomaskallup** [comment]
I tried again with the `--inspect-brk`, connected manually using `node debug host:port` and resumed the app with `continue`. It loaded up with correct port, so it seems like it should work.

Maybe the point @dchusovitin made is correct? Maybe dap passes the env in some weird format and termopen ignores it.

**Comment by mfussenegger** [comment]
Is there a difference between `{ PORT = 9001 }` and `{ PORT = '9001' }` ? Could be that the values need to be strings.

**Comment by tomaskallup** [comment]
Sadly not, changing it to string has no effect.

**Comment by tomaskallup** [comment]
Perfect, now it's working! Thank you!
