### ISSUE TITLE
External app crash on dap.disconnect when using remote attach - to debugpy

### ISSUE THREAD

**Issue by JoseConseco** [mfussenegger/nvim-dap#192]
Im debugging Blender python scripts - from nvim-dap, by remote attaching from nvim-dap - to debugpy server spawned inside blender like so:
```python
debugpy.listen(("localhost", 5678))    # start debugpy server inside blender with python script
```
Works ok, I can connect to blender debugpy server and see the variables etc.,  but when running dap.disconnect()  blender always crashes - without any error.  Blender is checking if client is still connected using:
```python
debugpy.is_client_connected()
```
Any ideas how to check what is going on?  I can use dap.stop() but from dap docs it seems to be not correct way to close debuggins sessin.

**Comment by mfussenegger** [comment]
Could you try with https://github.com/mfussenegger/nvim-dap/pull/193 and `dap.disconnect({ terminateDebuggee = false })` ?

**Comment by JoseConseco** [comment]
@mfussenegger  you are the man!  It works now without crash.  Hope you will merge this asap.
