### ISSUE TITLE
Feature Request: Breakpoint priority

### ISSUE THREAD

**Issue by yingzhu146** [mfussenegger/nvim-dap#197]
Hi there,

Would be great if I could change the breakpoint priority via config - just had to change it manually in the code since some of my other plugins were not well behaved. Exposing changing this via config would be great! :)

 thanks a lot this awesome plugin.

**Comment by mfussenegger** [comment]
In general it sounds good to me. I'll see if there's a chance to make this possible via the `sign_define` override (https://github.com/vim/vim/issues/8334)

**Comment by cstsunfu** [comment]
This is very useful when the diagnostic is conflicted with the breakpoint sign.

**Comment by entropitor** [comment]
@mfussenegger Would you be open to a PR that increases the default sign priority so it's at least above LspError?

**Comment by mfussenegger** [comment]
Closing this here as it's tracked in the vim repo
