### ISSUE TITLE
Per project configuration / vscode/launch.json support ?

### ISSUE THREAD

**Issue by mfussenegger** [mfussenegger/nvim-dap#20]
I'd like to get some opinions on whether nvim-dap should support `vscode/launch.json` files for debug configurations, or have some other mechanisms for users to define per-project debug configurations.

Full `vscode/launch.json` support is likely not feasible (it supports things like accessing editor configurations via variables). But I think a reasonable subset would be fairly easy to support - and with that the majority of the existing `launch.json` files would "just work".

**Comment by pidario** [comment]
I'm trying to move my workflow from vscode to neovim and debugging is the only piece missing, so I'm really interested in this plugin. I think a subset of `launch.json` might be the best way to procede, so that people like me, who are using vscode can migrate easily.
On another topic, I'm not really a lua expert but is there a way I can support you?

**Comment by mfussenegger** [comment]
Do you have some example `launch.json` files, to get an idea of what kind of functionality you'd need?

> I'm not really a lua expert but is there a way I can support you?

I appreciate bug reports, feature requests or other kind of feedback.

**Comment by pidario** [comment]
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug",
      "env": {
        "APP_FOO": "bar",
        "NODE_ENV": "test"
      },
      "program": "${workspaceFolder}/src/index.js",
      "outputCapture": "std"
    }
  ]
}
```

```json
{
  "version": "0.2.0",
  "configurations": [
      {
          "name": "Debug",
          "type": "go",
          "request": "launch",
          "mode": "auto",
          "program": "${fileDirname}",
          "env": {
              "APP_FOO": "bar"
          }
      }
  ]
}
```
Above two example of launch.json we use at work for nodejs and go projects, it's not much, I know. It's basically just used to trigger in nodejs the possibility to start a debug session and to pass some environment variable.

It would be nice if you could provide instructions for nodejs and go debuggers as well in the wiki. I can try to look into it if you're busy.

**Comment by mfussenegger** [comment]
I added some basic support for `launch.json` files via https://github.com/mfussenegger/nvim-dap/pull/48

**Comment by pidario** [comment]
I started with something simple:

~/.config/nvim/init.vim
```lua
require('dap.ext.vscode').load_launchjs()
```

index.js
```js
let a = 1;
console.log(a);
a = 2;
console.log(a);
```

.vscode/launch.json
```json
{
	"configurations": [
		{
			"type": "javascript",
			"request": "launch",
			"name": "debug",
			"program": "${workspaceFolder}/index.js"
		}
	]
}
```
I mapped the key as you suggest in your help file and then, when I hit F5 I got that there was nil adapter issue.
So I went to my `init.vim` file and added this in my lua section:
```lua
local dap = require('dap')
dap.set_log_level('TRACE')
dap.adapters.javascript = {
	type = 'executable';
	command = '/usr/bin/node';
}
```
With this addition, when I press F5 a `/usr/bin/node` process starts, but apparently no debug session has started.

**Comment by mfussenegger** [comment]
`node` itself is not a debug adapter. You probably need to clone & build https://github.com/microsoft/vscode-node-debug2 and then add an `args` option to the adapter that includes  `path/to/out/src/nodeDebug.js` ((judging from the package.conf in the vscode-node-debug2 repo))

```lua
dap.adapters.javascript = {
	type = 'executable';
	command = '/usr/bin/node';
        args = {'path/to/out/src/nodeDebug.js',};
}
```

**Comment by pidario** [comment]
That was the problem, now it's working.
Though, I'm still having trouble with go.
I used delve (`dlv`), which should be the official go debug adapter, even the vscode extension uses it from what I understand.
In fact, if I launch from cli dlv debug in the working directory, the debug session starts without any problem.
This is the configuration:
```lua
dap.adapters.go = {
	type = 'executable';
	command = '/usr/bin/dlv';
	args = {'debug'};
}
```
`launch.json`
```json
{
	"configurations": [
		{
			"type": "go",
			"request": "launch",
			"name": "debug",
			"program": "${workspaceFolder}"
		}
	]
}
```
This is the log:
```log
[ DEBUG ] 2020-09-17T11:08:15Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:850 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.utf8",
    pathFormat = "path",
    supportsRunInTerminalRequest = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
[ ERROR ] 2020-09-17T11:08:16Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:826 ]	"stderr"	{
  args = { "debug" },
  command = "/usr/bin/dlv",
  type = "executable"
}	"Command failed: command not available\nCommand failed: command not available\n"
```

**Comment by mfussenegger** [comment]
To me it looks as if delve doesn't implement the debug adapter protocol directly, but rather exposes a different API and there needs to be a debug adapter in-between.

Looks like that adapter is part of the [vscode-go](https://github.com/golang/vscode-go) extension.

I guess you can download the [vscode go extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go) and extract it (it's a zip file)

Then you should have a `vscode/golang.go/extension/out/src/debugAdapter/goDebug.js`, which I assume you can integrate in the same way you integrated the node debugger.

**Comment by pidario** [comment]
Ok, everything revolves around vscode extensions, I finally got it. I guess that if delve team implements dap protocol natively in delve we won't need the extension anymore, at least for go (https://github.com/golang/vscode-go/issues/23).
Anyway, for some reason the extension cannot find `dlv` executable in my PATH, I even tried to make a symlink to GOPATH/bin with no results.
Anyway thanks for your patience and keep up the good work. If I find out something useful I'll post it here.

**Comment by mfussenegger** [comment]
Yep, DAP can be a bit confusing initially as there are several components to make it work:

```
+------------+       +----------------+         +-----------+       +------------+
| DAP Client |<----->| Debug Adapter  |<------->| Debugger  |<----->| Debugee    |
| (nvim-dap) |       | (DAP server)   |         |           |       | (your app) |
+------------+       +----------------+         +-----------+       +------------+
```

Delve is the debugger, vscode-go is the debug adapter.


If `dlv` is not found it could be because the debug adapter doesn't have `GOPATH` set. Could you try changing the adapter configuration to include the env variable?

From the docs:


```
command: string     -- command to invoke
args:    string[]   -- arguments for the command
options?: {
  env?: {}          -- Set the environment variables for the command
  cwd?: string      -- Set the working directory for the command
}
```


Something like the following might work:


```lua
dap.adapters.go = {
  options = {
    env = {
      'GOPATH' = os.getenv('GOPATH');
    };
  }
  ...
}
```

**Comment by mfussenegger** [comment]
Based on their code you should be able to set the path to `dlv` via `dlvToolPath`:

```
// Let users override direct path to delve by setting it in the env
// map in launch.json; if unspecified, fall back to dlvToolPath.
let dlvPath = launchArgsEnv['dlvPath'];
if (!dlvPath) {
    dlvPath = launchArgs.dlvToolPath;
}
if (!fs.existsSync(dlvPath)) {
    log(`Couldn't find dlv at the Go tools path, ${process.env['GOPATH']}${env['GOPATH'] ? ', ' + env['GOPATH'] : ''} or ${pathUtils_1.envPath}`);
    throw new Error(`Cannot find Delve debugger. Install from https://github.com/go-delve/delve/ & ensure it is in your Go tools path, "GOPATH/bin" or "PATH".`);
```


```lua
dap.adapters.go = {
  type = 'executable';
  command = 'node';

  -- I built it from src instead of using the extension, that's why my path here is different
  args = {os.getenv('HOME') .. '/dev/golang/vscode-go/dist/debugAdapter2.js'};
}
dap.configurations.go = {
  {
    type = 'go';
    name = 'Debug';
    request = 'launch';
    program = '${workspaceFolder}';
    dlvToolPath = os.getenv('GOPATH') .. '/bin/dlv'
  },
}
```

**Comment by pidario** [comment]
Yes, that was the case, anyway now it fails to set breakpoint:

```log
[ DEBUG ] 2020-09-18T08:59:16Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:850 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.utf8",
    pathFormat = "path",
    supportsRunInTerminalRequest = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
[ ERROR ] 2020-09-18T08:59:16Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:826 ]	"stderr"	{
  args = { "/home/pidario/workspace/vscode-go/dist/debugAdapter.js" },
  command = "/usr/bin/node",
  type = "executable"
}	"(node:9265) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"
[ DEBUG ] 2020-09-18T08:59:16Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  body = {
    supportsConfigurationDoneRequest = true,
    supportsSetVariable = true
  },
  command = "initialize",
  request_seq = 0,
  seq = 1,
  success = true,
  type = "response"
}
[ DEBUG ] 2020-09-18T08:59:16Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:850 ]	"request"	{
  arguments = {
    dlvToolPath = "/usr/bin/dlv",
    name = "go",
    program = "/home/pidario/workspace/tests/go",
    request = "launch",
    type = "go"
  },
  command = "launch",
  seq = 2,
  type = "request"
}
[ DEBUG ] 2020-09-18T08:59:16Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  body = {
    category = "stdout",
    output = "API server listening at: 127.0.0.1:37603\n"
  },
  event = "output",
  seq = 2,
  type = "event"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  event = "initialized",
  seq = 3,
  type = "event"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:850 ]	"request"	{
  arguments = {
    breakpoints = { {
        line = 9
      } },
    source = {
      path = "main.go"
    }
  },
  command = "setBreakpoints",
  seq = 4,
  type = "request"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  command = "launch",
  request_seq = 2,
  seq = 4,
  success = true,
  type = "response"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  body = {
    error = {
      format = 'Failed to set breakpoint: "{e}"',
      id = 2002,
      showUser = true,
      variables = {
        e = "TypeError: Cannot read property '0' of undefined"
      }
    }
  },
  command = "setBreakpoints",
  message = 'Failed to set breakpoint: "{e}"',
  request_seq = 4,
  seq = 5,
  success = false,
  type = "response"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:850 ]	"request"	{
  command = "configurationDone",
  seq = 6,
  type = "request"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  body = {
    category = "stderr",
    output = "{}\n"
  },
  event = "output",
  seq = 6,
  type = "event"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  command = "configurationDone",
  request_seq = 6,
  seq = 7,
  success = true,
  type = "response"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  body = {
    category = "stdout",
    output = "1\n2\n"
  },
  event = "output",
  seq = 8,
  type = "event"
}
[ DEBUG ] 2020-09-18T08:59:17Z+0200 ] /home/pidario/.config/nvim/bundle/nvim-dap/lua/dap.lua:681 ]	{
  event = "terminated",
  seq = 9,
  type = "event"
}
```

I don't know, maybe it's about time I opened another issue since we're kinda going OT?

**Comment by mfussenegger** [comment]
> I don't know, maybe it's about time I opened another issue since we're kinda going OT?

Agreed. I'm closing this now. For the vscode-go issue, could you try out https://github.com/mfussenegger/nvim-dap/pull/53 ?

**Comment by tuxflo** [comment]
Hi, sorry for commenting on an old, closed issue but I'm not able to figure out what exactly the type value should be.
I'm trying to debug a C++ project. My "regular" configuration looks like this:
```
local dap = require('dap')
dap.adapters.cppdbg = {
  id = 'cppdbg',
  type = 'executable',
  command = '/home/username/.local/share/extension/debugAdapters/bin/OpenDebugAD7',
}
dap.configurations.cpp = {
  {
    name = "Launch file",
    type = "cppdbg",
    request = "launch",
    cwd = '${workspaceFolder}',
    program = '${workspaceFolder}',
    stopOnEntry = true,
  },
  {
    name = 'Attach to gdbserver :1234',
    type = 'cppdbg',
    request = 'launch',
    MIMode = 'gdb',
    miDebuggerServerAddress = 'localhost:1234',
    miDebuggerPath = '/usr/bin/gdb',
    cwd = '${workspaceFolder}',
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
  },
}
```
No I'm trying to use a project based `launch.json` which looks like this:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "cppdbg",
      "request": "debug",
      "name": "Control_Service",
      "program": "${workspaceFolder}/build/bin/myproject",
      "args": [ ]
    }
  ]
}
```
However if I run `:lua require("dap.ext.vscode").load_launchjs()` it doesn't apply the config to the cpp project. If I change the key `type` in the launch.json from `cppdbg` to `cpp` it is detected but not applied.

**Comment by mfussenegger** [comment]
See `:help dap.ext.vscode.load_launchjs`:

> For the above configuration, calling `load_launchjs` adds the first entry to
> `dap.configurations.java` and the second entry to `dap.configurations.cppdbg`.
> If you wanted to add the second entry to the `c` or `cpp` configurations you
> could call `load_launchjs` like this instead:

```lua
require('dap.ext.vscode').load_launchjs(nil, { cppdbg = {'c', 'cpp'} })
```

**Comment by ipyffor** [comment]
Putting it in an init file has no effect, but when it loaded launch.json when I execute :lua require("dap.ext.vscode").load_launchjs(nil, { cppdbg = { "c", "cpp" } }), how do I set it?

**Comment by samuelabreu** [comment]
> Putting it in an init file has no effect, but when it loaded launch.json when I execute :lua require("dap.ext.vscode").load_launchjs(nil, { cppdbg = { "c", "cpp" } }), how do I set it?

I "solve" it, using this:

```lua      
      local continue = function()
        if vim.fn.filereadable('.vscode/launch.json') then
          require('dap.ext.vscode').load_launchjs()
        end  
        require('dap').continue()
      end
      lvim.lsp.buffer_mappings.normal_mode["<leader>dc"] = { continue, "Start/Continue debug" }
```

Im using lunarvim, but the idea is simple, remap nvim-dap continue keybind to check if .vscode/launch.json exists, if it does, run load_launchjs(), then call continue()

**Comment by tuxflo** [comment]
This is actually pretty useful since it automatically ensures, that the `launch.json` is always up to date. I sometimes forget to call the `load_launchjs` function after changing something in the json file.
Thanks for posting, I highly appreciate it.

**Comment by tuero** [comment]
Thanks for the fix for checking if the .vscode/launch.json exists! Does anyone have any hacks to having OS-specific debuggers? For example, vscode allows the following:
```json
{
    // ...
    "type": "cppdbg",
    "request": "launch",
    "name": "Launch file",
    "linux": {
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/bin/gdb"
    },
    "osx": {
        "MIMode": "lldb",
        "miDebuggerPath": "/usr/local/bin/lldb-mi"
    }
}
```
I can set these as defaults in `dap.configurations.cpp` by using `vim.loop.os_uname().sysname`, but these get overwritten by the `launch.json`, and it doesn't appear that the subset of features allows for the OS-specific settings.
