### ISSUE TITLE
Error executing vim.schedule lua callback: vim/shared.lua:396: t: expected table, got nil

### ISSUE THREAD

**Issue by TheBlob42** [mfussenegger/nvim-dap#204]
I just updated `nvim-dap` to the newest version and wanted to start debugging a Java class at work when I ran into the following issue:

```
Error executing vim.schedule lua callback: vim/shared.lua:396: t: expected table, got nil                                                                                                                                                        
stack traceback:
        vim/shared.lua:396: in function 'tbl_count'
        ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:78: in function 'run_in_terminal'
        ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:546: in function 'handle_body'
        ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:585: in function 'handle_body'
        ...are/nvim/site/pack/packer/start/nvim-dap/lua/dap/rpc.lua:78: in function <...are/nvim/site/pack/packer/start/nvim-dap/lua/dap/rpc.lua:77>
```

Reverting `nvim-dap` back to the commit dfacc1fb7aeb0789c4fd27004e312cf363becba5 (without changing anything else about my config) solves the issue and the test starts and runs as expected.

Since there have only been two new commits since dfacc1fb7aeb0789c4fd27004e312cf363becba5 currently (2ef7322f1157ed4c23b62a9c98f42c6557cb7209 and bc7c67a751e87e8eed7d91856df127b03932cc88) I suspect one of them is the reason for this issue, but I currently do not have enough understanding of `nvim-dap` and lua to figure it out myself. Do you have any idea how this could be related and how to fix it?

Thank you :heart:

**Comment by mfussenegger** [comment]
Thank you for the pointer. Should be fixed with https://github.com/mfussenegger/nvim-dap/commit/00b0075ded6162befc2414429c6e05facebc88f7

**Comment by TheBlob42** [comment]
Yes it is working now :slightly_smiling_face: thank you for you fast response :+1:
