### ISSUE TITLE
[Python] Debugger crashes if a breakpoint in code is found.

### ISSUE THREAD

**Issue by RonanMacF** [mfussenegger/nvim-dap#205]
```
#! usr/bin/env python

import pdb

if __name__ == "__main__":
   a = 1
   print( a )
   pdb.set_trace()
   b = 2
   print( b )
```
When the debugger hits the pdb breakpoint the debug session exits printing a `PYDEV DEBUG WARNING` linking to [this page](https://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html). Would it be possible to recover the debug session when debugs are found in code?

**Comment by mfussenegger** [comment]
This is a python/debugpy limitation. If you're using python ~3.6(?) You could set the breakpoint like this:

```python
#! usr/bin/env python

if __name__ == "__main__":
   a = 1
   print( a )
   breakpoint()
   b = 2
   print( b )
```


If you're using an earlier version, you can set it like this:


```python
#! usr/bin/env python

import debugpy

if __name__ == "__main__":
   a = 1
   print( a )
   debugpy.breakpoint()
   b = 2
   print( b )
```


There is nothing I can do about this in nvim-dap

**Comment by RonanMacF** [comment]
Ok thanks for the info, I will close this so if there is nothing that can be done about it. Cheers
