### ISSUE TITLE
lldb-vscode cannot attach to target process

### ISSUE THREAD

**Issue by btorres510** [mfussenegger/nvim-dap#210]
I'm currently trying to setup nvim-dap for C/C++/Rust. However, when I try to debug any program, I get the same error: `Error on launch: Failed to attach to the target process. Timed out trying to get messages from the runInTerminal launcher`.

![dap-error](https://user-images.githubusercontent.com/24631440/121801140-66642100-cbfb-11eb-80b6-2951e118bbc3.png)

Here is my `nvim-dap` configuration
```lua
local dap = require('dap')

dap.adapters.lldb = {
  type = 'executable',
  command = '/usr/bin/lldb-vscode',
  name = "lldb"
}

dap.configurations.cpp = {
  {
    name = "Launch",
    type = "lldb",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},
    runInTerminal = true,
  },
}

dap.configurations.c = dap.configurations.cpp
dap.configurations.rust = dap.configurations.cpp
```
Here is my test C file:
```c
#include <stdio.h>

int main() {
	int a = 1;
	int b = 1;
	printf("a + b = %d\n", a + b);
}

```

I compiled with this command : `gcc -g -Wall main.c`

I'm running neovim 0.5 on Arch Linux. lldb version is 12.0.0
```
NVIM v0.5.0-dev+1398-gd09b8ad71
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by mfussenegger** [comment]
Can you try again after running `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope` ?

**Comment by btorres510** [comment]
Yup that worked, thank you! Out of curiosity, what does that command do and why is it necessary?

**Comment by mfussenegger** [comment]
Yama is a linux security module. Depending on the settings it ensures that a process cannot access the memory/state of another process. That's usually a good thing, but for debugging it can get in the way. See https://www.kernel.org/doc/html/latest/admin-guide/LSM/Yama.html

If you set `runInTerminal = true`, then the flow is like this:


```


┌──────────┐          ┌───────────────┐
│ nvim-dap │          │ debug adapter │
└──────────┘          └───────────────┘

           launch req       
            ──────►  
          runInTerminal req
             ◄──────


starts debugee
  in terminal

          
          response with pid
           ────────►

                     tries to attach to process
```


Given that neovim will be the parent process of the application you want to debug, the debug adapter process can't read it's memory with `ptrace_scope` set to >= 1

**Comment by mfussenegger** [comment]
I've updated the wiki to mention the yama/ptrace_scope implications.

**Comment by LordMZTE** [comment]
I'm not at all an expert on this, but couldn't this theoretically work with `ptrace_scope` set to 1?

To make this work, couldn't we use a small wrapper around the debugee that calls `prctl(PR_SET_PTRACER, debugger_pid, ...)` (or `prctl(PR_SET_PTRACER_ANY, ...)` for that matter) and then `execve`s the debugee, allowing the debugger to attach regardless?

**Comment by saccarosium** [comment]
I'm having the same problem on OSX. And this doesn't exists `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`
