### ISSUE TITLE
Custom terminal

### ISSUE THREAD

**Issue by EpsilonKu** [mfussenegger/nvim-dap#214]
Is it possible to launch `dap.defaults.fallback` on terminal plugins like fterm or floaterm.

**Comment by mfussenegger** [comment]
I'm not familiar with fterm or floatterm, but the only requirement for `terminal_win_cmd` is that it is a command that creates a new unmodified buffer, so you could do something like this:

```lua
dap.defaults.fallback.terminal_win_cmd = ":lua require('dap.ui.widgets').new_centered_float_win(vim.api.nvim_create_buf(false, true))"
```

**Comment by EpsilonKu** [comment]
Guess better to close issue.
