### ISSUE TITLE
Adapter for Chrome?

### ISSUE THREAD

**Issue by danielnehrig** [mfussenegger/nvim-dap#215]
Is there a adapter for chrome that would work with dap?

**Comment by mfussenegger** [comment]
There's https://github.com/Microsoft/vscode-chrome-debug which in theory should work. 

You could try downloading the packaged vscode extension (https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome), unzip it and then configure an adapter using the executable  type in nvim-dap. It probably needs to use `node` as command and the args need to point to the `debugger-for-chrome/out/src/chromeDebug.js` file

**Comment by danielnehrig** [comment]
i'll try to make it work if i find a solution we can maybe add it to the wiki

**Comment by danielnehrig** [comment]
i can confirm it works

```
dap.adapters.chrome = {
    type = "executable",
    command = "node",
    args = {os.getenv("HOME") .. "/code/vscode-chrome-debug/out/src/chromeDebug.js"}
}

dap.configurations.typescriptreact = {
    {
        type = "chrome",
        request = "attach",
        program = "${file}",
        cwd = vim.fn.getcwd(),
        sourceMaps = true,
        protocol = "inspector",
        port = 9222,
        webRoot = "${workspaceFolder}"
    }
}
```

ofc chrome has to be started with a remote debugging port
google-chrome-stable --remote-debugging-port=9222

**Comment by danielnehrig** [comment]
- git clone https://github.com/Microsoft/vscode-chrome-debug
- cd ./vscode-chrome-debug
- npm install
- npm run build

**Comment by danielnehrig** [comment]
i've added the documentation
https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#Javascript-chrome

**Comment by mfussenegger** [comment]
Thanks for testing & extending the wiki :+1:

**Comment by 1612492** [comment]
Or can use this config to launch new chrome instance
```
dap.configurations.javascript = {
  {
    name = "Launch localhost",
    type = "chrome",
    request = "launch",
    url = "http://localhost:3000",
    webRoot = "${workspaceFolder}",
    skipFiles = {"node_modules"}
  }
}
```

**Comment by Melkster** [comment]
It looks like vscode-chrome-debug is deprecated in favor of https://github.com/microsoft/vscode-js-debug. Has anyone gotten vscode-js-debug working with nvim-dap?

**Comment by danielnehrig** [comment]
didn't test it out but i can tomorrow and report back
right now even though deprecated chrome debug does a good job

**Comment by Melkster** [comment]
Ok thanks, please do and post your config if you got it working! :)
