### ISSUE TITLE
Question: Debugging Interactive Programs

### ISSUE THREAD

**Issue by Antonio-Bennett** [mfussenegger/nvim-dap#219]
Hi! I just wanted to know if there was already a defined way to debug interactive programs. 
Ex. I need to provide values to variable at run time such as ``` cin >> ``` in c++ or ```stdin::readline()``` in rust.

Was there already a way to do that sorry if there is I haven't found it yet. Any help?

**Comment by mfussenegger** [comment]
If the debug adapter supports it, you can launch the application in an integrated or external terminal. You'll then have your application running in a regular terminal and can use stdin and see the stdout. See `:help dap-terminal`.

For C++/Rust you can do that by setting the configuration entry `runInTerminal = true`, see [the wiki](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ccrust-via-lldb-vscode) for a full example.

You can use that to debug TUI apps like neovim itself - see https://user-images.githubusercontent.com/38700/121802503-ee1e4f80-cc3c-11eb-9616-e2e9b4aa52ee.mp4 for a demo.


The second option is to start the application yourself in a terminal, and then attach the debugger to it. See https://github.com/mfussenegger/nvim-dap/wiki/Cookbook#pick-a-process for an example.

**Comment by Antonio-Bennett** [comment]
Thanks a lot!
