### ISSUE TITLE
workspaceFolder confusing values

### ISSUE THREAD

**Issue by tomaskallup** [mfussenegger/nvim-dap#228]
I have following configuration for adapters (note there is a debugging `print`):
```lua
local dap = require 'dap'

-- Allow running custom command (build) before running adapter
dap.adapters.node2 = function(cb, config)
    if config.preLaunchTask then vim.fn.system(config.preLaunchTask) end
    local adapter = {
        type = 'executable',
        command = 'node',
        args = {
            os.getenv('HOME') .. '/Pkg/vscode-node-debug2/out/src/nodeDebug.js'
        },
        env = config.env or {}
    }
    print(config.program)
    cb(adapter)
end
```

And using following configuration to launch google cloud functions locally:
```lua
local dap = require 'dap'

dap.configurations.typescript = {
    {
        type = "node2",
        request = "launch",
        name = "Functions λ - develop",
        program = "${workspaceFolder}/node_modules/.bin/functions-framework",
        args = {'--target=development', '--port=9100'},
        cwd = "${workspaceFolder}/functions/build",
        preLaunchTask = "yarn --cwd functions/ build",
        sourceMaps = true,
        protocol = "inspector",
        console = "integratedTerminal",
        env = {
            NODE_ENV = 'development',
            APP_ENV = 'development',
            GOOGLE_APPLICATION_CREDENTIALS = "${workspaceFolder}/.credentials/reasdev-kallup.json"
        }
    }
}
```

The `print` inside of the adapter configuration correctly prints `/home/armeeh/Projects/Reas/reas-services/node_modules/.bin/functions-framework`, however the debugger launch fails with following message `Error: Cannot find module '/home/armeeh/Projects/node_modules/.bin/functions-framework'`. Why does the path become messed up? It seems like `workspaceFolder` changes 2 leves up for some reason.

**Comment by mfussenegger** [comment]
Thank you for the detailed error description :+1: 

Could you try with https://github.com/mfussenegger/nvim-dap/pull/229 ?

**Comment by tomaskallup** [comment]
Thanks for the quick response, that seems to fix the original problem, however now it seems like `env` doesn't respect `workspaceFolder` as I end up with:
```
Error: The file at ${workspaceFolder}/.credentials/reasdev-kallup.json does not exist, or it is not a file. ENOENT: no such file or directory, lstat '/home/armeeh/Projects/Reas/reas-services/functions/build/$
{workspaceFolder}'
```

**Comment by mfussenegger** [comment]
> Thanks for the quick response, that seems to fix the original problem, however now it seems like `env` doesn't respect `workspaceFolder` as I end up with:
> 
> ```
> Error: The file at ${workspaceFolder}/.credentials/reasdev-kallup.json does not exist, or it is not a file. ENOENT: no such file or directory, lstat '/home/armeeh/Projects/Reas/reas-services/functions/build/$
> {workspaceFolder}'
> ```

I see. That's another problem - the variable expansion is currently not recursive for dicts.  Can you try https://github.com/mfussenegger/nvim-dap/pull/230 for that? :)

**Comment by tomaskallup** [comment]
Perfect, now it works like a charm! Thanks a lot for the quick work :)
