### ISSUE TITLE
[Question] How to debug specific test function for golang

### ISSUE THREAD

**Issue by ray-x** [mfussenegger/nvim-dap#231]
e.g.
In my test file I got 2 test functions Test1() and Test2().
The setup 
{
    type = "go",
    name = "Debug test",
    request = "launch",
    mode = "test", -- Mode is important
    program = "${file}"
  }

Will run the file and all functions. How to run a specific function, e.g Test2 and debug it?

**Comment by mfussenegger** [comment]
Based on https://github.com/rcarriga/vim-ultest/wiki/Debugging-Recipes#gotest it looks as if you can specify tests via the args property. 

Using vim-ultest directly would probably offer the most convenient interface,  as it detects the functions and can generate configurations for nvim-dap ad-hoc

**Comment by ray-x** [comment]
Thanks. Will check ultest.

**Comment by mfussenegger** [comment]
There is now also https://github.com/leoluz/nvim-dap-go

**Comment by ray-x** [comment]
Thanks. cool project with treesitter + dap
