### ISSUE TITLE
Go (using delve directly) no output

### ISSUE THREAD

**Issue by y1rn** [mfussenegger/nvim-dap#232]
as subject, i m using nvim-dap-ui,but no every log output in repl panel.

**Comment by mfussenegger** [comment]
I'll need a more detailed problem description to investigate or help

**Comment by y1rn** [comment]
![image](https://user-images.githubusercontent.com/70128797/125121676-d5fbfc00-e126-11eb-9fc4-f1b2cbadba33.png)
should be print something here, right?

**Comment by mfussenegger** [comment]
Looks like `dlv dap` currently logs the output to its own stdout instead of routing it via the debug adapter protocol.


https://user-images.githubusercontent.com/38700/125174924-fd0b0a00-e1c8-11eb-8e6b-d7b614359ed4.mp4


Ideally they'd support the `runInTerminal` request, so you could have it launch your application in a dedicated terminal. Looks like that's not yet supported: https://github.com/golang/vscode-go/issues/124 - but there is active work in that direction going on: https://github.com/go-delve/delve/pull/2566

**Comment by mfussenegger** [comment]
Actually there is something you can do, you could redirect the output of `dlv` to the repl:

```lua
dap.adapters.dlv_spawn = function(cb)
  local stdout = vim.loop.new_pipe(false)
  local handle
  local pid_or_err
  local port = 38697
  local opts = {
    stdio = {nil, stdout},
    args = {"dap", "-l", "127.0.0.1:" .. port},
    detached = true
  }
  handle, pid_or_err = vim.loop.spawn("dlv", opts, function(code)
    stdout:close()
    handle:close()
    if code ~= 0 then
      print('dlv exited with code', code)
    end
  end)
  assert(handle, 'Error running dlv: ' .. tostring(pid_or_err))
  stdout:read_start(function(err, chunk)
    assert(not err, err)
    if chunk then
      vim.schedule(function()
        --- You could adapt this and send `chunk` to somewhere else
        require('dap.repl').append(chunk)
      end)
    end
  end)
  -- Wait for delve to start
  vim.defer_fn(
    function()
      cb({type = "server", host = "127.0.0.1", port = port})
    end,
    100)
end
```



You'll have to change the `type` in your configurations to `dlv_spawn` to use this new adapter definition. For example:


```lua
dap.configurations.go = {
  {
    type = 'dlv_spawn',
    name = 'Launch dlv & file',
    request = 'launch',
    program = "${file}";
  },
}
```


You also have to be aware that the prompt buffer in neovim behaves a bit odd, and output is only visible if you enter it.

**Comment by y1rn** [comment]
thanks for you response, but i found ``` require('dap.repl').append(chunk)```  not working on first debug.

**Comment by y1rn** [comment]
> thanks for you response, but i found ` require('dap.repl').append(chunk)` not working on first debug.

that's nvim-dap-ui's issue. thx
