### ISSUE TITLE
Properly handle resizes when using runInTerminal (lldb-vscode)

### ISSUE THREAD

**Issue by igorlfs** [mfussenegger/nvim-dap#236]
When setting runInTerminal to true, resizing the terminal split throws the following error:

```error executing vim.schedule lua callback: .../nvim/site/autoload/plugged/nvim-dap/lua/dap/session.lua:220: Cursor position outside buffer```

It also changes the current buffer to `/builddir/glibc-2.32/sysdeps/unix/sysv/linux/read.c`, for some reason

**Steps to reproduce the behavior**: 
1. create a C++ program that requests user's input, for instance:
```
#include <iostream>
using namespace std;
int main() {
  int x;
  int y;
  cin >> x >> y;
  cout << "x + y: " << x + y;
  return 0;
}
```
2. set a breakpoint in a line after requesting input (for instance, the `cout` in the previous code)
3. start a debugging session
4. focus the terminal split, then move it to the right

There's also another bug that I believe is related: using runInTerminal and nvim-dap-ui together throws similar errors. I think it's also due to resizing. Might open a separate issue for that, though.

**Comment by mfussenegger** [comment]
This doesn't seem to be resize related, but for whatever reason, entering insert mode in the terminal raises an exception in the application:


```
[ DEBUG ] 2021-07-19T19:36:38Z+0200 ] ...fig/nvim/pack/plugins/start/nvim-dap/lua/dap/session.lua:510 ]	{
  body = {
    breakMode = "always",
    description = "signal SIGWINCH",
    exceptionId = "signal"
  },
  command = "exceptionInfo",
  request_seq = 7,
  seq = 0,
  success = true,
  type = "response"
}
[ ERROR ] 2021-07-19T19:36:38Z+0200 ] ...fig/nvim/pack/plugins/start/nvim-dap/lua/dap/session.lua:649 ]	"stderr"	{
  command = "/usr/bin/lldb-vscode",
  name = "lldb",
  type = "executable"
}	"error: libstdc++.so.6 {0x0039606b}: DIE has DW_AT_ranges(0x390f3) attribute, but range extraction failed (missing or invalid range list table), please file a bug and attach the file at the start of this error message\nerror: libstdc++.so.6 {0x0039609f}: DIE has DW_AT_ranges(0x39106) attribute, but range extraction failed (missing or invalid range list table), please file a bug and attach the file at the start of this error message\nerror: libstdc++.so.6 {0x0039606b}: DIE has DW_AT_ranges(0x390f3) attribute, but range extraction failed (missing or invalid range list table), please file a bug and attach the file at the start of this error message\nerror: libstdc++.so.6 {0x0039609f}: DIE has DW_AT_ranges(0x39106) attribute, but range extraction failed (missing or invalid range list table), please file a bug and attach the file at the start of this error message\nerror: libstdc++.so.6 {0x003f0e15}: DIE has DW_AT_ranges(0x3e830) attribute, but range extraction failed (missing or invalid range list table), please file a bug and attach the file at the start of this error message\nerror: libstdc++.so.6 {0x003f0e15}: DIE has DW_AT_ranges(0x3e830) attribute, but range extraction failed (missing or invalid range list table), please file a bug and attach the file at the start of this error message\nerror: libstdc++.so.6 {0x003f65b1}: DIE has DW_AT_ranges(0x3ea3b) attribute, but range extraction failed (missing or invalid range list table), please file a bug and attach the file at the start of this error message\nerror: libstdc++.so.6 {0x003f65b1}: DIE has DW_AT_ranges(0x3ea3b) attribute, but range extraction failed (missing or invalid range list table), please file a bug and attach the file at the start of this error message\n"
```


The `Cursor position outside buffer` error is a result of it trying to jump to the frame where the error occurred. (`builddir/glibc-2.32/sysdeps/unix/sysv/linux/read.c`)


What's odd is that this doesn't happen if the integrated terminal is opened in a separate tab: `dap.defaults.fallback.terminal_win_cmd = 'tabnew'`

**Comment by mfussenegger** [comment]
Could you raise this issue upstream in the llvm /lldb-vscode project?

**Comment by igorlfs** [comment]
Do you happen to know the link to llvm's repo? All I could find was [this](https://github.com/llvm/llvm-project), and it seeems to not allow issues, only PRs.

**Comment by mfussenegger** [comment]
@igorlfs Did you manage to file an upstream bug report about this?

**Comment by igorlfs** [comment]
No, I wasn't able to file a bug report. I'm sorry. I lack the technical knowledge to do so. 

However, I believe there's some change to be made regarding nvim-dap's side, as this bug doesn't happen with vimspector, for instance. But again, I'm pretty much a newbie so I don't know better.

**Comment by mfussenegger** [comment]
> as this bug doesn't happen with vimspector,

Using the exact same debug adapter / version? Do you know if vimspector also uses the `termopen` function to spawn the integrated terminal? I don't really see what I could do about it. That there is a resize event if the terminal is resized seems legitimate.

**Comment by igorlfs** [comment]
> Using the exact same debug adapter / version? 

Yes. I am using _lldb_ version 12.0.0. I just tested again: in vimspector I can resize and move the terminal split at will, at any given time in the program. Using nvim-dap however, resizing and moving only work as intended (ie, not causing similar errors as the ones in the OP) when ALL the input is given to the program.

> Do you know if vimspector also uses the `termopen` function to spawn the integrated terminal? 

I'm sorry, but I don't know that. I don't think so, though this is just a guess. There's something vimpector does that's fundamentally different when it comes to this adapter. For instance, there's no need to set the ptrace setting, the "integrated" terminal just works. 

I understand if you don't want to put a lot of effort just into this one adapter. Perhaps we can leave this issue open until a more experienced user runs into the same problem and actually manage to get some more clues.

**Comment by krishnakumarg1984** [comment]
I have this exact same issue (i.e. crashing on SIGWINCH with `std::cin` in C++). Any help to resolve this will be much appreciated.

**Comment by mfussenegger** [comment]
Could you try if this also happens with the following patch applied?

```patch
diff --git a/lua/dap/session.lua b/lua/dap/session.lua
index 51568ba..8aa1a70 100644
--- a/lua/dap/session.lua
+++ b/lua/dap/session.lua
@@ -684,11 +684,11 @@ function Session:spawn(adapter, opts)
   local spawn_opts = {
     args = adapter.args;
     stdio = {stdin, stdout, stderr};
     cwd = options.cwd;
     env = options.env;
-    detached = true;
+    detached = false;
   }
   handle, pid_or_err = uv.spawn(adapter.command, spawn_opts, onexit)
   if not handle then
     onexit()
     error('Error running ' .. adapter.command .. ': ' .. pid_or_err)
```


This wouldn't be a permanent fix as it can break other adapters (like debugpy), but it would be possible to make this configurable per adapter if it fixes the issue with lldb-vscode

**Comment by igorlfs** [comment]
> Could you try if this also happens with the following patch applied?
> 
> ```diff
> diff --git a/lua/dap/session.lua b/lua/dap/session.lua
> index 51568ba..8aa1a70 100644
> --- a/lua/dap/session.lua
> +++ b/lua/dap/session.lua
> @@ -684,11 +684,11 @@ function Session:spawn(adapter, opts)
>    local spawn_opts = {
>      args = adapter.args;
>      stdio = {stdin, stdout, stderr};
>      cwd = options.cwd;
>      env = options.env;
> -    detached = true;
> +    detached = false;
>    }
>    handle, pid_or_err = uv.spawn(adapter.command, spawn_opts, onexit)
>    if not handle then
>      onexit()
>      error('Error running ' .. adapter.command .. ': ' .. pid_or_err)
> ```
> 
> This wouldn't be a permanent fix as it can break other adapters (like debugpy), but it would be possible to make this configurable per adapter if it fixes the issue with lldb-vscode

Hello!

Applying the patch and following the instructions in the OP, I get following stack traceback:

```
Error executing vim.schedule lua callback: ...r/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:254: Cursor position outside buffer                                                      
stack traceback:                                                                                                                                                                                
        [C]: in function 'nvim_win_set_cursor'                                                                                                                                                  
        ...r/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:254: in function 'jump_to_location'                                                                                         
        ...r/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:286: in function 'jump_to_frame'                                                                                            
        ...r/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:353: in function 'callback'                                                                                                 
        ...r/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:552: in function <...r/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:548>
```

Without the patch I get the same stack.

**Comment by rekaerst** [comment]
add
```lua
postRunCommands = {'process handle -p true -s false -n false SIGWINCH'}
```
to dap.configurations.cpp should tell lldb to ignore SIGWINCH.

``` lua
[ DEBUG ] 2022-03-14T11:22:42Z+0800 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:563 ]	{
  body = {
    category = "console",
    output = "Running postRunCommands:\n(lldb) process handle -p true -s false -n false SIGWINCH\nNAME         PASS   STOP   NOTIFY\n===========  =====  =====  ======\nSIGWINCH     true   false  false\n"
  },
  event = "output",
  seq = 0,
  type = "event"
}
```

**Comment by igorlfs** [comment]
> add
> 
> ```lua
> postRunCommands = {'process handle -p true -s false -n false SIGWINCH'}
> ```
> 
> to dap.configurations.cpp should tell lldb to ignore SIGWINCH.

Thank you, you're a lifesaver! This works just as intended!

**Comment by mfussenegger** [comment]
Added the info to the wiki

**Comment by igorlfs** [comment]
> ```lua
> postRunCommands = {'process handle -p true -s false -n false SIGWINCH'}
> ```
That's no longer required thanks to the new modifications in the terminal buffer.

**Comment by pandasoli** [comment]
Does that still works for you?
For me it displays this in the terminal:
```
Running postRunCommands:
(lldb) process handle -p true -s false -n false SIGWINCH
NAME         PASS   STOP   NOTIFY
===========  =====  =====  ======
SIGWINCH     true   false  false
```
And it hands there, the debugging doesn't proceed.

**Comment by igorlfs** [comment]
Please, do not necrobump old threads. If you have any problems, create a new issue
