### ISSUE TITLE
Repl reports an error after restarting the debug session.

### ISSUE THREAD

**Issue by pittcat** [mfussenegger/nvim-dap#237]
https://user-images.githubusercontent.com/22888402/126524782-847d74d5-dc8a-47dd-b271-5a1eb0b3b10c.mp4

**Comment by pittcat** [comment]
Here is the restart function
```
M.restart_ndap_debugger = function()
	local dap = require("dap")
	local ndap_state = dap.session()
	if ndap_state == nil then
		dap.run_last()
	else
		dap.disconnect()
		dap.stop()
		dap.run_last()
	end
end
```

**Comment by pittcat** [comment]
After I changed the restart function to the following, bug info disappeared and this seems to be a workarround.
```
M.restart_ndap_debugger = function()
	local dap = require("dap")
	local ndap_state = dap.session()
	if ndap_state == nil then
		dap.run_last()
	else
		dap.disconnect()
		if dap.repl.close() then
			dap.repl.open({}, "vsplit")
		end
		dap.stop()
		dap.run_last()
	end
end
```

**Comment by mfussenegger** [comment]
It shouldn't really be necessary to close and re-open the REPL. I'm reopning this to have at least a look at it.

**Comment by mfussenegger** [comment]
I wasn't able to reproduce it - for me the issue doesn't happen with your initial restart function.

**Comment by pittcat** [comment]
I'm pretty sure the bug can be reproduced by the steps.

```
import numpy as np 
from matplotlib import pyplot as plt 
 
x = np.arange(1,11) 
y =  2  * x +  5 
plt.title("Matplotlib demo") 
plt.xlabel("x axis caption") 
plt.ylabel("y axis caption") 
plt.plot(x,y) 
plt.show()
```

Bug reproduction steps:
1. Make a break point at `plt.ylabel("y axis caption")`
2. Start debug session
3. Open repl pane when debug session is alive
4. Input `plt.plot(x,y)`
5. Restart debug session
6. Press enter key in repl pane that the state is normal.

**Comment by pittcat** [comment]
https://user-images.githubusercontent.com/22888402/126856052-965faa07-b88e-45fa-b45f-177a811b8fe8.mp4

**Comment by pittcat** [comment]
nvim config:
```
call plug#begin('~/.vim/plugged')
Plug 'mfussenegger/nvim-dap'
Plug 'mfussenegger/nvim-dap-python'
call plug#end()
```

**Comment by pittcat** [comment]
@mfussenegger Can you reproduce the bug by the steps above?

**Comment by mfussenegger** [comment]
No luck:


https://user-images.githubusercontent.com/38700/126904101-37265055-e8b6-42c0-be81-d6f730e1e7e6.mp4

**Comment by pittcat** [comment]
Did you press enter key in repl pane after after you restarted the session?

**Comment by pittcat** [comment]
When you press the enter key, the reple pane should be normal mode.

**Comment by mfussenegger** [comment]
> When you press the enter key, the reple pane should be normal mode.

Ah, thanks for the hint - I missed that. 

Could you try https://github.com/mfussenegger/nvim-dap/pull/255 ? it should fix it.

**Comment by pittcat** [comment]
It works well. Thank you.
