### ISSUE TITLE
kill current execution

### ISSUE THREAD

**Issue by kabessao** [mfussenegger/nvim-dap#238]
While debugging python, calling .quit() in lua does not kill the process, but on "[dap-repl]" buffer if you send the command "exit" it kills the process successfully. 

Would be nice to have a .kill() function on lua to forcefully end the execution while running.

I deal with a lot of api requests that take some time to execute, and sometimes I see an error while executing something, so it's nice to be able to stop, fix, and start debug all over again.

**Comment by pittcat** [comment]
You can try this code snippets.
```
M.kill_current_debug = function()
	local dap = require("dap")
	dap.disconnect()
	dap.stop()
end
```

**Comment by kabessao** [comment]
That does work, thank you.
But now I've noticed that when disconnecting and stopping it does not end the debugpy.adapeter process, and when executing again it creates another process, so it keeps building up over time 
![image](https://user-images.githubusercontent.com/22626848/126639521-75ab5aeb-2f13-49cf-bf75-837d6045e901.png)

**Comment by mfussenegger** [comment]
I think that the debugpy process remains active may be a bug in the debug adapter. I filed an upstream issue: https://github.com/microsoft/debugpy/issues/672

**Comment by mfussenegger** [comment]
I adapted the code to send a SIGTERM after the session terminated. This way the debugpy processes should exist correctly.
