### ISSUE TITLE
Unable to connect to X Server

### ISSUE THREAD

**Issue by Shatur95** [mfussenegger/nvim-dap#24]
I have an issue with `lldb-vscode`. My project is unable to connect to X server with `DebugC <path>`. But works with plain start.
I have `lldb 10.0.0` installed and `lldb-vscode` is in my PATH.
Example project: [akd](https://github.com/Shatur95/akd)
Screenshot (the message [from akd](https://github.com/Shatur95/akd/blob/5438e57b6124132636f14839cd3293a8d2563528/src/keyboarddaemon.cpp#L42), the application can't open connection to X11):
![изображение](https://user-images.githubusercontent.com/22453358/85401734-2d065180-b563-11ea-941f-3ff5c28e8670.png)

**Comment by mfussenegger** [comment]
Could you post your dap.adapters / dap.configurations settings?

**Comment by Shatur95** [comment]
Of course! I'm very sorry, I just forgot to attach it. This files in `lua` directory:
[my_debug.lua](https://pastebin.com/khghZmTc)
[dap_config.lua](https://pastebin.com/DSQmhCBN)

In my `init.vim`:

```vim
packadd nvim-dap
lua require'dap_config'
```

**Comment by mfussenegger** [comment]
Is it possible that some environment variables are not passed on to the application?

You could try extending the `last_gdb_config` with a `env` table that contains required env variables like `DISPLAY`. 

nvim-dap sends the options you've declared in your `last_gdb_config` to [vscode-lldb](https://github.com/vadimcn/vscode-lldb) - launching the application is then up to it.

**Comment by Shatur95** [comment]
Is there a way to pass current env variables automatically?
`akd` works if I launch it from terminal or Vim.

**Comment by Shatur95** [comment]
If I understand correctly, in my configuration I passed `environment = {}` to the debugger. I tried to remove this, but still have the same error.

**Comment by mfussenegger** [comment]
It seems to be an issue with [vscode-lldb] that it doesn't pass the environment variables to the debugee.  (https://github.com/vadimcn/vscode-lldb/issues/2) 

If you extend your `main.cpp` with some logic to print all environment variables you'll see that it is empty if launched via nvim-dap / vscode-lldb.

Not much I can do about that within nvim-dap as it is up to the debug-adapter implementation.

**Comment by Shatur95** [comment]
Thanks for the investigation! How VSCode hande it? It passes all environment variables manually?

**Comment by Shatur95** [comment]
Hm... Not sure that the problem in vscode-lldb itself. [It](https://github.com/vadimcn/vscode-lldb/wiki/Debugging-problems#electron-applications-fail-to-launch-under-the-debugger) says that the debugger uses all the environment variables of the child process.

**Comment by mfussenegger** [comment]
> Thanks for the investigation! How VSCode hande it? It passes all environment variables manually?

I'm not sure. I tried it in vscode as well but there it even crashed. I'm not a vscode user so I'm not sure if I did something wrong.



> Hm... Not sure that the problem in vscode-lldb itself. [It](https://github.com/vadimcn/vscode-lldb/wiki/Debugging-problems#electron-applications-fail-to-launch-under-the-debugger) says that the debugger uses all the environment variables of the child process.

This is strange. I also tried to add some env variables both with `env` and `environment` keys, but the process never received any of them.

**Comment by Shatur95** [comment]
Should I open an issue in vscode-lldb instead?

**Comment by mfussenegger** [comment]
> Should I open an issue in vscode-lldb instead?

Yes. I currently don't see anything that I could do within nvim-dap to resolve the problem.

**Comment by Shatur95** [comment]
I talked with author of `vscode-lldb` and he said that `lldb-vscode` that used here is the different project :D
I also found that `lldb` have `target.inherit-env` parameter. But this option is enabled by default, here is the output:
```
(lldb) settings show target.inherit-env 
target.inherit-env (boolean) = true
(lldb)
```
Can all environment variables overwritten by the plugin because of confusing with [vadimcn/vscode-lldb](https://github.com/vadimcn/vscode-lldb) (wiki pointed to the [lldb by llvm](https://lldb.llvm.org/index.html))?

**Comment by theHamsta** [comment]
No, at the moment you have to explicitly define the environment. If you don't set it it is not defined.

**Comment by mfussenegger** [comment]
> I talked with author of vscode-lldb and he said that lldb-vscode that used here is the different project

Oh, I mixed that up :(

The variables have to be specified as `KEY=VALUE` pairs (in a list).

You could use something as follows to pass all parent variables to the debugee:


```
dap.configurations.cpp = {
  {
    name = "Launch",
    type = "cpp",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ' .. vim.fn.getcwd() .. '/')
    end,
    console = 'integratedTerminal',
    cwd = '${workspaceFolder}',
    env = function()
      local variables = {}
      for k, v in pairs(vim.fn.environ()) do
        table.insert(variables, string.format("%s=%s", k, v))
      end
      return variables
    end,
    stopOnEntry = false,
    args = {}
  },
}
```

**Comment by Shatur95** [comment]
I tried to replace `env` with

```
env = function()
  local variables = {}
  for k, v in pairs(vim.fn.environ()) do
    table.insert(variables, string.format("%s=%s", k, v))
  end
  return variables
end,
```

but have the following error:

```
E5101: Cannot convert given lua type
Error executing vim.schedule lua callback: error converting argument 1
```

here is the full [my_debug.lua](https://pastebin.com/Sgmni9Az).

**Comment by mfussenegger** [comment]
Could you replace ` dap.launch(dap.adapters.cpp, last_gdb_config)` in `M.start_c_debugger` with `dap.run(last_gdb_config)` ?

`dap.run` makes sure that the functions are evaluated.

Otherwise you could also do something like this:

```
local function mk_env()
  local variables = {}
  for k, v in pairs(vim.fn.environ()) do
    table.insert(variables, string.format("%s=%s", k, v))
  end
  return variables
end
```

and then use `env = mk_env()`

**Comment by Shatur95** [comment]
> Could you replace dap.launch(dap.adapters.cpp, last_gdb_config) in M.start_c_debugger with dap.run(last_gdb_config) ?

With this I have the following message:

```
Invalid adapter type nil, expected `executable` or `server`
```

but the solution with `env = mk_env()` worked as expected. Thank you a lot!
