### ISSUE TITLE
Repl error for Ruby

### ISSUE THREAD

**Issue by sphynx79** [mfussenegger/nvim-dap#254]
### Debug adapter definition and debug configuration

:gem install readapt

```
local dap = require('dap')

dap.adapters.ruby = {
  type = 'executable';
  command = 'ruby.exe';
  args = {"C:\\Ruby3\\bin\\readapt", 'stdio'};
}

dap.configurations.ruby = {
  {
    type = 'ruby',
    request = 'launch',
    name = 'File',
    cwd = vim.fn.getcwd(),
    program = '${workspaceFolder}/main.rb',
  },
}
```

### Debug adapter version

readapt 1.4.1

### Steps to Reproduce

Set breakpoint
Start Debugger
Try print variable in repl 

### Expected Result

print variable in repl console

### Actual Result

https://user-images.githubusercontent.com/5004160/126904844-d7840fd3-3a7f-4096-a296-3071189609e0.mp4
```
dap>
dap> p ciao
"ciao"
"ciao"
#<Thread:0x0000000008b4e800 C:/Ruby3/lib/ruby/gems/3.0.0/gems/backport-1.2.0/lib/backport/client.rb:104 run> terminated with exception (report_on_exception is true):
C:/Ruby3/lib/ruby/gems/3.0.0/gems/readapt-1.4.1/lib/readapt/message/variables.rb:7:in `ru
n': no implicit conversion of String into Integer (TypeError)
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/readapt-1.4.1/lib/readapt/message.rb:38:in `process'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/readapt-1.4.1/lib/readapt/adapter.rb:68:in `process'
	from C
:/Ruby3/lib/ruby/gems/3.0.0/gems/readapt-1.4.1/lib/readapt/adapter.rb:39:in `block in opening'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/readapt-1.4.1/lib/readapt/data_reader.rb:51:in `parse_message_from_buffer'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/reada
pt-1.4.1/lib/readapt/data_reader.rb:29:in `block in receive'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/readapt-1.4.1/lib/readapt/data_reader.rb:24:in `each_char'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/readapt-1.4.1/lib/readapt/data_reader.rb:24:in `receive
'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/readapt-1.4.1/lib/readapt/adapter.rb:48:in `receiving'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/backport-1.2.0/lib/backport/client.rb:66:in `tick'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/backport-1.2.0/lib/backport
/server/stdio.rb:23:in `update'
	from C:/Ruby3/lib/ruby/3.0.0/observer.rb:222:in `block in notify_observers'
	from C:/Ruby3/lib/ruby/3.0.0/observer.rb:221:in `each'
	from C:/Ruby3/lib/ruby/3.0.0/observer.rb:221:in `notify_observers'
	from C:/Ruby3/lib/rub
y/gems/3.0.0/gems/backport-1.2.0/lib/backport/client.rb:124:in `read_input'
	from C:/Ruby3/lib/ruby/gems/3.0.0/gems/backport-1.2.0/lib/backport/client.rb:105:in `block in run_input_thread'
dap> 
```

**Comment by mfussenegger** [comment]
This sounds like a readapt bug.  Could you report this upstream?

**Comment by sphynx79** [comment]
Ok thanks i just open the issues in the readapt repository.

Thanks

**Comment by mfussenegger** [comment]
One thing to note is that the dap repl by default doesn't have a `p` command. All commands start with a `.`. See `:help dap.repl.open()` 

Any text that is not a command is sent verbatim to the debug adapter using an evaluate request.

**Comment by sphynx79** [comment]
I open one issues in readapt repo but don't answer [issues](https://github.com/castwide/readapt/issues/12)

I don't know how i can avule in repl for example: 1+1

In this plugin ther'isnt commad fro avalute expression?

**Comment by mfussenegger** [comment]
Any text that doesn't start with a `.` is sent to the debug adapter verbatim via the evaluate request.

So if you type `1 + 1` that should evaluate the expression.

**Comment by mfussenegger** [comment]
Closing this for now because I don't think there is anything that could be done within nvim-dap to fix or workaround the debug adapter bug.

**Comment by sphynx79** [comment]
Please can you reopen this issues, because i think that problem is with this plugin.

I try to use readapt with visual studio code, and in repl i write:
```
:1+1
=> 2
```

I edit readapt gems becuase i want print me the message that arrive. and this is the result:

![FlzNUleuEy](https://user-images.githubusercontent.com/5004160/128606065-9b3afc18-2929-41e8-a8ce-46ad6683982d.png)

Work fine!!

I try same step in Neovim with nvim-dap:

![cYD4V6C1tE](https://user-images.githubusercontent.com/5004160/128606304-93f996d3-f40e-4771-94eb-6f0bb854321e.png)

How you can see:
1) Arrive command:evalute expression: 1+1                                 => OK
2) Print result                                                                                 => OK
3) Send other message command: variables with argument: []    => WHY??

I think that problem is that this plugin send one more request and i don't know why, but the second request make problem in readapt.

I hope I have explained the problem well

Thanks

**Comment by mfussenegger** [comment]
Are you using any other extension in addition to nvim-dap? Might be that the extra variables request with empty arg is coming from that.
