### ISSUE TITLE
repl.open() opens extra buffer

### ISSUE THREAD

**Issue by Shatur95** [mfussenegger/nvim-dap#27]
When I executing `:lua require'dap'.repl.open()` I have `dap_repl` buffer and one extra empty buffer.

**Steps to reproduce**

Configuration: [dap_config.lua](https://pastebin.com/u6dbALbT)

```vim
:lua require'dap'.repl.open()
:bnext " You will see dap_repl buffer
:bnext " You will see an empty buffer
:bnext " You will see the previous buffer before opening repl
```

**Screenshot**

![изображение](https://user-images.githubusercontent.com/22453358/87364260-e01f0500-c57b-11ea-9cee-08c67eff3550.png)

**Comment by mfussenegger** [comment]
Thank you for the report. Should be fixed with https://github.com/mfussenegger/nvim-dap/commit/98cd9b8d16af5fb24aed6b4edb8c6f7bbbb36ec0

**Comment by Shatur95** [comment]
Works, thank you!
