### ISSUE TITLE
issue starting debugger 

### ISSUE THREAD

**Issue by CMorooney** [mfussenegger/nvim-dap#274]
### Debug adapter definition and debug configuration

local dap = require 'dap'

dap.adapters.chrome = {
  type = "executable",
  command = "node",
  args = {os.getenv("HOME") .. "/repos/_nvim/vscode-chrome-debug/out/src/chromeDebug.js"}
}

dap.configurations.typescriptreact = { -- change to typescript if needed
  {
    type = "chrome",
    request = "attach",
    program = "${file}",
    cwd = vim.fn.getcwd(),
    sourceMaps = true,
    protocol = "inspector",
    port = 9222,
    webRoot = "${workspaceFolder}"
  }
}

  dap.adapters.node2 = {
    type = 'executable',
    command = 'node',
    args = {os.getenv('HOME') .. '/repos/_nvim/vscode-node-debug2/out/src/nodeDebug.js'},
  }

  dap.configurations.javascriptreact = {
    {
      type = 'node2',
      request = 'launch',
      program = '${file}',
      cwd = vim.fn.getcwd(),
      sourceMaps = true,
      protocol = 'inspector',
      console = 'integratedTerminal',
    },
  }

### Steps to Reproduce

attempt to attach to running chrome react app

### Expected Result

attached/running debugger

### Actual Result

E5108: Error executing lua vim/shared.lua:152: t: expected table, got nil
stack traceback:
        vim/shared.lua:152: in function 'tbl_map'
        ...cal/share/nvim/site/pack/paqs/start/nvim-dap/lua/dap.lua:246: in function 'run'
        [string ":lua"]:1: in main chunk

**Comment by mfussenegger** [comment]
Could you properly fill out the *Steps to reproduce* ?

The error you get should only happen if `dap.run` is called with `nil` instead of a `config`.
