### ISSUE TITLE
Close the session when the debug adapter exits.

### ISSUE THREAD

**Issue by actboy168** [mfussenegger/nvim-dap#277]
### Problem Statement

If the debug adapter exits without notifying the client to close the session, then the session will not have a chance to be closed. Until the next dap.continue, manually close it.

**Comment by mfussenegger** [comment]
If the debug adapter doesn't send a terminated event, that is a bug in the debug adapter. From the protocol specification:

> In all situations where a debug adapter wants to end the debug session, a terminated event must be fired.
