### ISSUE TITLE
REPL filetype

### ISSUE THREAD

**Issue by Shatur95** [mfussenegger/nvim-dap#28]
Could you assign a filetype to REPL? This will allow to configure it layout. For example, to fix buffer height to 20 or make it unlisted.

**Comment by mfussenegger** [comment]
Yes I guess. Any suggestions for what kind of filetype?

Otherwise I think `repl.open` also take an optional callback that receives the bufnr and winnr if the repl is newly created? Not sure what's easier to use.

@theHamsta what's your take on this?

**Comment by theHamsta** [comment]
I really have no clue about this vim things but I think he just wants you to call `setfiletype dap-repl` on the buffer so that he can make his own settings based on ft and not on buffer name (which would be also be possible).

Some plugins define custom filetype for their special windows.

**Comment by Shatur95** [comment]
> Otherwise I think repl.open could also take an optional callback that receives the bufnr and winnr if the repl is newly created? Not sure what's easier to use.

Good idea too. For example, `TermDebug` provides settings to configure window.

>  call setfiletype dap-repl on the buffer

Yes, this is more common way, I think.

**Comment by Shatur95** [comment]
Thank you!

**Comment by Shatur95** [comment]
The change is very useful for configuration, but for some reason resizing by ftplugin do not work :(
Here is my `after/ftplugin/dap-repl.vim:

```vim
resize 15 " I also tried :vertical resize 15
```

What if add vertical size parameter to `repl.open()`?

Same approach used in [asyncrun](https://github.com/skywind3000/asyncrun.vim/blob/58d23e70569994b36208ed2a653f0a2d75c24fbc/plugin/asyncrun.vim#L1956)

**Comment by mfussenegger** [comment]
@Shatur95 would https://github.com/mfussenegger/nvim-dap/pull/30 solve it?

**Comment by Shatur95** [comment]
Tested, works as expected, thank you!

**Comment by mrdgo** [comment]
Hi,

I also tested the ftplugin and it failed.
I want to do a few tweaks to the REPL: `set nornu nocuc nocul`.
Sadly `~/.config/nvim/ftplugin/dap-repl.vim` is not executed when I start a REPL session.

Is there a fix to this?
Manually calling `set ft=dap-repl` is a bit annoying.

Help appreciated :)

**Comment by mfussenegger** [comment]
If you open the repl and run `:set ft`, what is returned?

The code sets the filetype to `dap-repl` and I myself also have a `~/.config/nvim/ftplugin/dap-repl.vim` that sets several options and for me it's working.

So either there is an error in your `dap-repl.vim` that prevents it from working or some other plugin/option is interferring?

You could also try running `:4verbose lua require('dap.repl').open()` to see if something is sourced. (or a higher number to get even more information on what's going on)

**Comment by mrdgo** [comment]
Hi,

thanks for your quick response!
`set ft` returns `filetype=dap-repl`.

the lua command returns: (I removed paths specific to my system)
```
 chdir(...)
chdir($HOME/.config/nvim/ftplugin)
chdir(...)
line 12: sourcing "$HOME/.config/nvim/ftplugin/dap-repl.vim"
finished sourcing $HOME/.config/nvim/ftplugin/dap-repl.vim
continuing in function <SNR>19_ftplugin
not found in 'packpath': "pack/*/start/*/ftplugin/dap-repl.vim ftplugin/dap-repl_*.vim ftplugin/dap-repl/*.vim"
not found in 'packpath': "start/*/ftplugin/dap-repl.vim ftplugin/dap-repl_*.vim ftplugin/dap-repl/*.vim"
not found in 'runtimepath': "indent/dap-repl.vim"
not found in 'packpath': "pack/*/start/*/indent/dap-repl.vim"
not found in 'packpath': "start/*/indent/dap-repl.vim"
not found in 'runtimepath': "syntax/dap-repl.vim syntax/dap-repl/*.vim"
not found in 'packpath': "pack/*/start/*/syntax/dap-repl.vim syntax/dap-repl/*.vim"
not found in 'packpath': "start/*/syntax/dap-repl.vim syntax/dap-repl/*.vim"
chdir(...)
chdir(python/tests)
chdir(...)
chdir(...)
chdir(python/tests)
chdir(...)
```

I am not too deep into these things. What does this mean?

**Comment by mfussenegger** [comment]
It looks like the filetype is set correctly and the file is sourced.

What how does your `dap-repl.vim` look like? Maybe you're setting something that is overriden by nvim-dap later on.

**Comment by mrdgo** [comment]
Thanks for your support!

`dap-repl.vim`:
```
set nonumber norelativenumber cc=-1 nocuc nocul
```
quite simple actually. And strangely it works when I manually call `:set ft=dap-repl`.
Where can I find possible overrides?

**Comment by mfussenegger** [comment]
Can you try with https://github.com/mfussenegger/nvim-dap/pull/146 ? That should fix the problem.

**Comment by mrdgo** [comment]
Thank you so much!
It now works. You dude rock :)

(yeah, I kinda felt like this was no new issue. But you are right - next time I open a new one)
