### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by David-Kunz** [mfussenegger/nvim-dap#287]
### Debug adapter definition and debug configuration

```lua
{ -- debug adapter configuration
    type = 'node2',
    request = 'launch',
    cwd = vim.fn.getcwd(),
    runtimeArgs = {'--inspect-brk', 'node_modules/.bin/jest', '--no-coverage', '-t', '$result', '--', '$file'},
    sourceMaps = true,
    protocol = 'inspector',
    skipFiles = {'<node_internals>/**/*.js'},
    console = 'integratedTerminal',
    port = 9229
  }
```
Note: `$result` and `$file` are replaced with actual values.

### Debug adapter version

1.42.5

### Steps to Reproduce

Hi,

Whenever I debug something multiple times (~20), at some point I'll get the error message 
> E5108: Error executing lua ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:638: Error running node: EMFILE: too many open files

I always perform 

```lua
 local dap = require('dap')
 dap.disconnect()
 dap.close()
```

before every new debug session. 

Is there a way to make sure that no artifacts of previous sessions remain?

Thanks and best regards,
David

### Expected Result

I expect that a fresh new session can be created.

### Actual Result

E5108: Error executing lua ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:638: Error running node: EMFILE: too many open files

**Comment by mfussenegger** [comment]
1) Can you check if the node process gets terminated after you run disconnect/close? If the debug session is started using a `launch` configuration, `close`  sends a SIGTERM signal to the process. That should cause it to exit.

2) Could you try with `dap.disconnect { terminateDebuggee = true }`

**Comment by David-Kunz** [comment]
Hi @mfussenegger ,

Thanks a lot for this insanely fast answer! 

Regarding 1.: I did a quick `ps | grep node` and didn't find any relevant node processes.
Regarding 2.: I will check if this has an effect!

Thanks and best regards,
David

**Comment by David-Kunz** [comment]
On a similar note:

Sometimes when I restart my debugger (including `dap.disconnect { terminateDebuggee = true }` and `dap.close`) I cannot navigate through my breakpoints and I get 

> No configuration found for `javascript`. You need to add configs to `dap.configuration.javascript` (See `:h dap-configuration`).

**Comment by David-Kunz** [comment]
Update: I've tried with `dap.disconnect { terminateDebuggee = true}`, unfortunately that didn't solve the problem.

**Comment by David-Kunz** [comment]
Note: If I restart my Neovim instance, everything works again.

**Comment by David-Kunz** [comment]
Note 2: It seems that starting a debug session somehow always opens a new terminal. When I receive the error message 
> E5108: Error executing lua ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:638: Error running node: EMFILE: too many open files

I can't even open a new terminal. My buffer list is (almost) empty.

**Comment by mfussenegger** [comment]
Could you try with https://github.com/mfussenegger/nvim-dap/pull/288 ?
