### ISSUE TITLE
Feature Request: Ability to highlight conditional breakpoints separately from standard breakpoints

### ISSUE THREAD

**Issue by knpwrs** [mfussenegger/nvim-dap#289]
### Problem Statement

It would be great if I could highlight breakpoints in red and conditional breakpoints in yellow.

**Comment by danielnehrig** [comment]
how would you like this to be implemented @mfussenegger
i'd do a  "DapBreakpointConditional" sign define and add that when the conditional hits

is that ok ?

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/nvim-dap/pull/312 got merged
