### ISSUE TITLE
bug: dap.status() reports nothing

### ISSUE THREAD

**Issue by danielnehrig** [mfussenegger/nvim-dap#290]
### Debug adapter definition and debug configuration

installed the adapter via pacman `pacman -S lldb`
configured for rust as described in the wiki
```lua
dap.adapters.lldb = {
    type = "executable",
    command = "/usr/bin/lldb-vscode", -- adjust as needed
    name = "lldb"
}

dap.configurations.cpp = {
    {
        name = "Launch",
        type = "lldb",
        request = "launch",
        program = function()
            return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
        end,
        cwd = "${workspaceFolder}",
        stopOnEntry = false,
        args = {},
        runInTerminal = false
    }
}

dap.configurations.rust = dap.configurations.cpp
```

### Debug adapter version

lldb version 12.0.1

### Steps to Reproduce

1. Add dap.status() to your statusline (make a nil condition check on dap.session()
2. Create a cargo project `cargo init`
2. Open the main.rs
3. Attach DAP

### Expected Result

dap.status() reports info about the debug state

### Actual Result

dap.status() reports nothing

### Video

https://user-images.githubusercontent.com/4050749/132432175-7a86236d-9c9d-499e-b749-cbfd1b7b1391.mp4

## PR
#292

**Comment by danielnehrig** [comment]
maybe i have a miss understanding on how .status() is supposed to work
but from :h dap-api i figured it has to repeort some state about the debug session

**Comment by mfussenegger** [comment]
I think this may be related to this condition:

```lua
  if not (session.config.type == vim.bo.filetype and vim.bo.buftype == '') then
    return ''
  end
```

The idea was that the status would only show up in windows that show buffers that are related to the debug session. Maybe in your case you're a miss-match between the filetype name and the config type?

You btw. shouldn't need to check dap.session - if there is no active session the status returns an empty string.
(And maybe An easier way to debug this is is to call `:lua print(require('dap').status())` at various points)

**Comment by danielnehrig** [comment]
set filetype reports rust.
the config as shown above is set as
dap.configurations.rust = dap.configurations.cpp

which correspondes to the ft

manually executing when the debugger is attached
`:lua print(require('dap').status())`
still reports a empty string

so its not a miss-match
i called it at various points still empty string


i'll go into the plugin source and do some printy bois in there and see what crackin

**Comment by danielnehrig** [comment]
maybe its worth noticing that i lazy load DAP though i don't thing that this might be a issue

**Comment by danielnehrig** [comment]
also in the video attached above you can see that i do a print on .status()
the statusline is populated with DAP Attached which is in the same scope of execution
so it's triggered but its just an empty string

**Comment by danielnehrig** [comment]
if you can not reproduce the behavior or .status() works like intended then i guess it has something todo with my config

**Comment by danielnehrig** [comment]
@mfussenegger 

i'd like to know
```
 if not (session.config.type == vim.bo.filetype and vim.bo.buftype == '') then 
   return '' 
 end 
```

why this is needed `session.config.type == vim.bo.filetype` this will never evaluate true in my case because the ft is rust and the type is lldb why is there a need to compare the ft to the adapter type

**Comment by danielnehrig** [comment]
`session.config.type == vim.bo.filetype` makes no sens to me to do this check but maybe im overlooking something i removed it and it makes no issues right now and the all works fine now

i can create a PR if you can clearify the situation about this check

**Comment by danielnehrig** [comment]
if i would call the adapter rust instead of lldb
then this would work i guess

**Comment by danielnehrig** [comment]
pr merged lgtm
