### ISSUE TITLE
Debug Windows x64 Neovim

### ISSUE THREAD

**Issue by dantearaujo1** [mfussenegger/nvim-dap#315]
### Debug adapter definition and debug configuration

Can't find any files that was informed in wiki: "....extension/debugAdapters/mono.<system-<platform> files are executable..."

After download from vscode link in the wiki and unzip it i couldn't find these mono.<system-<platform> files.... also, after i setup like the wiki shows i can't debug inside neovim.

Heres what "dap.log" files shows

[ ERROR ] 2021-09-24T14:27:56Z-0300 ] ...data\site\pack\packer\start\nvim-dap\lua\dap\session.lua:665 ]	"stderr"	{
  command = "D:\\Code\\Languages\\C++\\Debuggers\\extension\\debugAdapters\\bin\\OpenDebugAD7",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\r\n"

### Steps to Reproduce

1. In any project build with debug information
2. After configuring Adapter Definition and Adapter Configuration for gdb like nvim-dap wiki informs
3. run command :lua require'dap'.continue()
4. Choose option 1
5. Put your executable file and press Enter

### Expected Result

Some responde and information from debbuger inside vim

### Actual Result

"Debug adapter didn't respon. Either the adapter is slow (then wait and ignore this) or there is a problem with you adapter or 'cppdbg' configuration......" 

nothing happens after that and if run command again we can't disconnect or do any actions in the debbuger inside vim

**Comment by danielnehrig** [comment]
did you follow the guide to build the adapter ?

**Comment by dantearaujo1** [comment]
yeap and to me it seems that there is nomono.<system- files  inside vscode-cpptools.vsix , when i unzip it theres nothing related to that inside the folder.

**Comment by mfussenegger** [comment]
Sounds similar to the issue described here: https://github.com/mfussenegger/nvim-dap/issues/260#issuecomment-895574817

I suspect the mono file is only available in the linux package, and that it is missing shouldn't be a problem.

**Comment by mfussenegger** [comment]
Closing this here since it looks like an issue with the debug adapter and not with the client.

**Comment by mfussenegger** [comment]
vscode-cpptools should work now under windows with an updated adapter definition, see https://github.com/mfussenegger/nvim-dap/issues/260#issuecomment-1100038528
