### ISSUE TITLE
No configuration found 

### ISSUE THREAD

**Issue by tredeneo** [mfussenegger/nvim-dap#316]
### Debug adapter definition and debug configuration

I have this config

```lua
local dap = require('dap')
dap.adapters.lldb = {
  type = 'executable',
  command = '/usr/bin/lldb-vscode', -- adjust as needed
  name = "lldb"
}
dap.configurations.rust= {
  {
    name = "Launch",
    type = "lldb",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/target/debug', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},
    runInTerminal = false,
  },
}
```

### Steps to Reproduce

worked until I updated the plugin (this week) but now i get an error

I check #166 but this is different because my config worked

neovin: 0.5.0

### Expected Result

run debug

### Actual Result

```No configuration found for `rust`. You need to add configs to `dap.configurations.rust` ```

**Comment by mfussenegger** [comment]
There haven't been any changes in that area for a while. If it broke with an update you could try bisecting to see which commit broke it.

The configuration itself looks alright. Are you using some form of lazy loading and run that code too late?

**Comment by tredeneo** [comment]
you are correct, i also refactored my settings, got the previous version and it worked

I'm going to close this issue because it's not a problem with this plugin but when I find the problem I'll add the solution (or what's causing it)

**Comment by tredeneo** [comment]
the file to be imported in the ```init``` cannot be called ```debug.lua```
