### ISSUE TITLE
Program Output Buffer Resizing Options

### ISSUE THREAD

**Issue by PowerUser64** [mfussenegger/nvim-dap#319]
### Problem Statement

Currently, if you start debugging, `nvim-dap` will open a split that contains the output of the program that is being debugged which is 1/2 of the height of the window.

### Ideas or possible solutions

It would be nice if it was possible to set a default height as either a proportion of the whole window height or a total number of characters for the window to appear at.

ex:
```lua
size = 0.33 -- window would start out as 1/3 of the height of the window
size = 20   -- window would start out as 20 characters high
```
As a related side note, being able to tell `nvim-dap` where to place the output window would be neat, too (`left`, `right`, `top`, `bottom`, or maybe even `float`).

**Comment by mfussenegger** [comment]
You can configure that by setting `dap.defaults.fallback.terminal_win_cmd` to a command that creates the window. Something like `tabnew` or `10new` is supported. You could even run a lua function via `lua require('...').foo()`.

The only requirement is that after the command is run, there is a new buffer which is unmodified.

**Comment by PowerUser64** [comment]
Thank you! I was able to get everything to work just fine.
(and sorry for not closing the issue right away.)
