### ISSUE TITLE
Inline Values View﻿

### ISSUE THREAD

**Issue by adelarsq** [mfussenegger/nvim-dap#33]
With [nvim_buf_set_virtual_text()](https://github.com/neovim/neovim/blob/7b529e7912517af078e005dd7b06b3d042be9cb7/runtime/doc/api.txt#L2055) is possible to emulate the [inline values for variables](https://www.jetbrains.com/help/pycharm/inline-debugging.html).

Is it possible something like that with this plugin?

**Comment by theHamsta** [comment]
https://github.com/mfussenegger/nvim-dap/pull/13

**Comment by adelarsq** [comment]
@theHamsta Nice! Didn't see that pull request.
