### ISSUE TITLE
Remote file are opened with no filetype assigned.

### ISSUE THREAD

**Issue by BonaBeavis** [mfussenegger/nvim-dap#334]
### Debug adapter definition and debug configuration

Installed via https://github.com/mfussenegger/nvim-dap-python.

### Debug adapter version

385ede6

### Steps to Reproduce

1. Debug a remote project
2. Halt the remote process in a source file, that is not mapped to a local source file

### Expected Result

The file is opened in a  buffer with a `filetype` assigned

### Actual Result

The file is opened in a scratch buffer with no `filetype` assigned.

**Comment by mfussenegger** [comment]
Now all that's required is extending the map here: https://github.com/mfussenegger/nvim-dap/blob/ee39d5d570d07161e16eb73054c295c6561eb2b4/lua/dap/session.lua#L12-L14

**Comment by krmbzds** [comment]
> Now all that's required is extending the map here:
> 
> https://github.com/mfussenegger/nvim-dap/blob/ee39d5d570d07161e16eb73054c295c6561eb2b4/lua/dap/session.lua#L12-L14

Are you suggesting:
1. Adding a bunch of mime-filetype pairs into the `mime_to_filetype` table?
2. Changing the code so `mime_to_filetype` table can be set externally?
3. Adding some kind of mimetype library/module to do the job?
4. Something else?

I'm new to Lua so something obvious might have gone over my head.

**Comment by ko1** [comment]
> Debug adapters could show disassembly so inferring the file type based on the current buffer is not safe.

If we issue the `Source` request, there should be corresponding [`Source` data](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Source) and it can have `path` attribute. Is it difficult to use an extname of `path`?

**Comment by mfussenegger** [comment]
> If we issue the `Source` request, there should be corresponding [`Source` data](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Source) and it can have `path` attribute. Is it difficult to use an extname of `path` to infer the filetype?

If the source of a frame has a path it is loaded directly from the filesystem and the mimetype mapping is not needed. The filetype association will already work.

The mimetype mapping is needed if there is a sourceReference != 0 on the source. It will make a source request (https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Source), the response of that only contains the content and an optional mimeType, not a path.


> Are you suggesting:
> Adding a bunch of mime-filetype pairs into the mime_to_filetype table?
> Changing the code so mime_to_filetype table can be set externally?
> Adding some kind of mimetype library/module to do the job?
> Something else?

Adding an entry that is missing for the ruby case.

**Comment by ko1** [comment]
> If the source of a frame has a path it is loaded directly from the filesystem and the mimetype mapping is not needed. The filetype association will already work.

On TCP/IP connection, it can be remote machine where debuggee running on, so "loaded directly from the filesystem" is not enable every time. And Ruby's DAP adapter by debug.gem assumes different machines if it opens via TCP/IP (Using UNIX domain socket it assumes same local machine). So it returns local machine (debuggee running machine) path and "sourceReference != 0".

> The mimetype mapping is needed if there is a sourceReference != 0 on the source.

We can set MIME-type but I'm not sure how to specify it is ruby script (it seems no programming languages except js).
https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by mfussenegger** [comment]
> On TCP/IP connection, it can be remote machine where debuggee running on, so "loaded directly from the filesystem" is not enable every time. And Ruby's DAP adapter by debug.gem assumes different machines if it opens via TCP/IP (Using UNIX domain socket it assumes same local machine). So it returns local machine (debuggee running machine) path and "sourceReference != 0".

Oh I see. Thanks for the clarification.

> We can set MIME-type but I'm not sure how to specify it is ruby script

I'm also not sure what the appropriate type would be. 


I think I've come up with an alternative solution.

With https://github.com/mfussenegger/nvim-dap/pull/497  one can either set a default source filetype as adapter option - or if using a neovim nightly build it will attempt to infer the filetype from the path as you've suggested. This should work for most debuggers out of the box.

**Comment by mfussenegger** [comment]
@BonaBeavis with the latest nvim-dap & nvim-dap-python version this should now work for python

@krmbzds Can you try with the latest nvim-dap version? If you're on neovim nightly it should just work. For earlier neovim versions nvim-dap-ruby will have to change the adapter definition to include  `options = { source_filetype = 'ruby' }`

**Comment by krmbzds** [comment]
@mfussenegger I can confirm it is working. **TYVM!** :heart: 

I still think we should add mime types (in `application/x-language` format). I explained my reasoning at https://github.com/ruby/debug/issues/598#issuecomment-1086214575.

> [...] I don't think IANA will ever add programming language mime types. JavaScript is more of an exception. I _still_ think we should send mime types. I have seen `application/x-ruby` being used in many cases. It's also what is returned by `xdg-mime` command (commonly used to get mime types in Linux):
> 
> ```sh
> $ xdg-mime query filetype target.rb
> 
> application/x-ruby
> ```
> 
> I believe this format is also used by Microsoft although it is not a standard (I read this in a VSCode issue yesterday -- but cannot pull that up right now).

If everyone agrees, we can extend this map in the future with `["application/x-ruby"] = 'ruby'` when it is implemented in `debug.rb`.

@suketa I think we can add the same options in [nvim-dap-ruby](https://github.com/suketa/nvim-dap-ruby) like in here: [4c7ea25](https://github.com/mfussenegger/nvim-dap-python/commit/4c7ea25f8ff6de6fa00bf5625d2e76753cced70f). Would be an improvement for Neovim-stable users.
