### ISSUE TITLE
[Bug] Telescope project launch.json

### ISSUE THREAD

**Issue by chriztheanvill** [mfussenegger/nvim-dap#342]
### Debug adapter definition and debug configuration

Install
```vim
Plug 'mfussenegger/nvim-dap'
Plug 'rcarriga/nvim-dap-ui'
```

```lua
local dap = require'dap'

vim.fn.sign_define('DapBreakpoint', {text='', texthl='', linehl='', numhl=''})
vim.fn.sign_define('DapBreakpointCondition', {text='', texthl='', linehl='', numhl=''})
vim.fn.sign_define('DapLogPoint', {text='ﱴ', texthl='', linehl='', numhl=''})
vim.fn.sign_define('DapStopped', {text='', texthl='', linehl='', numhl=''})
vim.fn.sign_define('DapBreakpointRejected', {text='', texthl='', linehl='', numhl=''})

-- local widgets = require('dap.ui.widgets')
-- local my_sidebar = widgets.sidebar(widgets.scopes)
-- my_sidebar.open()
-- local my_sidebar = widgets.sidebar(widgets.frames)
-- my_sidebar.open()
-- widgets.centered_float(widgets.scopes)
-- require('dap.ui.widgets').hover()

dap.adapters.lldb = {
  type = 'executable',
  command = '/usr/bin/lldb-vscode-12', -- adjust as needed
  name = "lldb"
  }

dap.adapters.cppdbg = {
  type = 'executable',
  command = '/home/cris/.CppTools/cpptools-linux-1.7.1/extension/debugAdapters/bin/OpenDebugAD7',
  name = "cppdbg"
  }

-- CPP 
dap.configurations.cpp = {
  {
    name = "Launch file",
    type = "cppdbg",
    request = "launch",
    program = function()
	return vim.fn.input('Path to executable: ',  vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = true,
	-- externalTerminal = true,
  },
  {
    name = 'Attach to gdbserver :1234',
    type = 'cppdbg',
    request = 'launch',
    MIMode = 'gdb',
    miDebuggerServerAddress = 'localhost:1234',
    miDebuggerPath = '/usr/bin/gdb',
    cwd = '${workspaceFolder}',
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
  },
}

-- dap.configurations.c = dap.configurations.cpp
-- dap.configurations.rust = dap.configurations.cpp

-- To load launch.json files 
require('dap.ext.vscode').load_launchjs()

-- dap.defaults.fallback.force_external_terminal = true
-- dap.defaults.fallback.external_terminal = {
--    command = '/usr/bin/terminator';
--    args = {'-e'};
--	}

-- Split terminal Vertical
dap.defaults.fallback.terminal_win_cmd = '30vsplit new'
-- Split terminal
dap.defaults.fallback.terminal_win_cmd = '5split new'

```

### Steps to Reproduce

Launch Telescope projects.

### Expected Result

To detect/recognize "vscode/launch.json" or "launch.json" file.

### Actual Result

Cant recognize "vscode/launch.json" or "launch.json" file.

**Comment by mfussenegger** [comment]
Did my last reply solve your issue?

**Comment by chriztheanvill** [comment]
Sorry for the delayed response.
No, it does not resolve the problem.

**Comment by chriztheanvill** [comment]
I found some the solution.
This problem happens with telescope projects, and sessions, because when start Neovim, also start with load_launchjs, so when try to load a session or project, load_launch was already use it, so does not recognize the files.

To get a momentary fix, key map  "load_launchjs()".
Because I've tried to use like this:
```lua
:lua require('dap.ext.vscode').load_launchjs()<CR> :lua require'dap'.continue() require(\"dapui\").open()<CR>
```
This has a bug, if I tried again, it will add the config again the config, so, I have duplicated configs (just the .launch.json config).

I think that, load_launchjs() should detect the name of the config, if already exist, does not add it.

**Comment by mfussenegger** [comment]
> This has a bug, if I tried again, it will add the config again the config, so, I have duplicated configs (just the .launch.json config).

This is documented behavior:

> To load the configurations, add the following in `init.vim`:
> 
>   lua require('dap.ext.vscode').load_launchjs()
> 
> *This extends `dap.configurations` each time it is called, so make sure to only
> call it once*.


> I think that, load_launchjs() should detect the name of the config, if already exist, does not add it.

You could build a cached version for it. Something like this:


```lua
local loaded = {}
local function load_launchjs_once(path)
  if loaded[path] then
    return
  end
  loaded[path] = true
  return require('dap.ext.vscode').load_launchjs()
end
```

The built-in version intentionally doesn't do it. As it offers more flexibility.
