### ISSUE TITLE
Failed to launch - Golang

### ISSUE THREAD

**Issue by ITHDevelopment** [mfussenegger/nvim-dap#346]
### Debug adapter definition and debug configuration

Installed the adapter via : 
`go get -u github.com/go-delve/delve/cmd/dlv`

Configuration via nvim-dap-go:
`require('dap-go').setup()`

OS: windows 10
shell: powershell
Nvim v0.5.1

### Debug adapter version

1.7.2

### Steps to Reproduce

1. Create a golang project
2. Make folders in the project root, and make go modules within them
3. Import the external and local modules correctly, also set up go.mod files correctly
4. Run: `go run . ` and it works fine

1. In file .cmd/main.go
2. Set a breakpoint
3. Start debug session

### Expected Result

Start the debug session correctly, also build and run the code without problems just like using the `go run .` command

### Actual Result

Error on launch: Failed to launch
(It seems to not be detecting the modules correctly)
![Screenshot (7)](https://user-images.githubusercontent.com/71849483/140842009-cef73e27-ccf2-451c-8708-3df2a6c3ebec.png)

**Comment by mfussenegger** [comment]
I think this might be a problem with the default configurations in nvim-dap-go

See https://github.com/mfussenegger/nvim-dap/issues/200#issuecomment-877566539 and https://github.com/mfussenegger/nvim-dap/issues/200#issuecomment-877798483

This is what dap-go sets: 

https://github.com/leoluz/nvim-dap-go/blob/624a8b610083f8206cd3988cefb9549b8ffe2799/lua/dap-go.lua#L71

Cc @leoluz

**Comment by leoluz** [comment]
@ITHDevelopment Im not sure I understand your step 2 "Make modules inside other folders". Can you clarify what you mean by that pls?

BTW, I have a testing project that loads many different dependencies via Go Modules and I am able to run the main and debug it without issues. You can check the project here: https://github.com/leoluz/ingress-test

In order to start the debug you have to run `:lua require'dap'.continue()` (or whatever key binding you have mapped to it). You will be presented with the following options:

```
Configuration:                                                                                                                                         
1: Debug
2: Debug test
3: Debug test (go.mod)
Type number and <Enter> or click with the mouse (q or empty cancels):
```

Then you select option 1 as you are trying to debug your main module.

That should be it.

**Comment by ITHDevelopment** [comment]
Okay I see the problem now, I had the go.mod and go.sum files inside cmd folder. Moving the files outside the folder resolve the initial problem, but now the debugger don't recognize package main functions.
The thing is, it's recommended that the main package only have the main.go file, but in some cases when you want to modularize your code but the functionality its not reusable enough to make another package you want that functionality to be in the package main, inside the cmd folder.
So now I can start the debug session but it fails because it says that some function from settings.go inside cmd folder is undefined. The easy solution would be create a new module just for settings.go file, or copy that file inside main.go. Both not very good ideas in my opinion.
Btw my project structure looks something like this:
```
.projectRoot/
  cmd/ main.go - settings.go
  internal/response/ somefiles
  pkg/
    analysis/ somefiles
    binary/ somefiles
```

(Sorry about my poor english, I'm from south america)

**Comment by leoluz** [comment]
> So now I can start the debug session but it fails because it says that some function from settings.go inside cmd folder is undefined.

Go should work the way you are describing. You can put `main.go` and `settings.go` under the same `main` package. You probably have a package declaration problem in your project. Make sure you understand how Go packages work and how Go Modules are supposed to be configured. Don't skip the basics :)

**Comment by ITHDevelopment** [comment]
Ok thanks for your patience. I get the point, but then ¿Why when I do `go run ./cmd` it works just fine?

**Comment by ray-x** [comment]
The dap config setup `dap_cfg.program = "./${relativeFileDirname}"`
Does it matter in windows?  ` ./` vs `.\`

**Comment by leoluz** [comment]
@ray-x That could be an issue in Windows but unfortunately Im not able to test it myself. However what @ITHDevelopment is trying to do is debugging the main which uses this part of the configuration: https://github.com/leoluz/nvim-dap-go/blob/624a8b610083f8206cd3988cefb9549b8ffe2799/lua/dap-go.lua#L71-L77

As you can see, in this case the program is defined by the `${file}` variable and there is no hardcoded slashes in this case.

**Comment by ITHDevelopment** [comment]
Hi! Today I've installed GoLand (student license) to see if I'm doing something wrong, but the IDE let me debug the code without problems. And it's weird that such a strict program did not throw any error with my packages declaration and stuff.
I give up, I just want to know if I'm doing something wrong, and if not, where I can start investigating to fix the problem because I really don't like GoLand even with the ideavim plugin.

And thanks to everyone who has helped with this.

**Comment by leoluz** [comment]
@ITHDevelopment if you create a github repo with your project and I can give it.

**Comment by ITHDevelopment** [comment]
This is the url: [https://github.com/ITHDevelopment/simpleGoProjectThatFails](https://github.com/ITHDevelopment/simpleGoProjectThatFails)
It's an almost empty project that fails the exact same way: When I set a breakpoint on main.go and run `lua require'dap'.continue()` then option 1
This is the error:
![Screenshot (9)](https://user-images.githubusercontent.com/71849483/141212902-18bc6bc6-ae37-4e9e-b116-3151717f4856.png)
(I didn't link the actual project because the repo it's private and I also believe this is simpler)

**Comment by leoluz** [comment]
Tks. I checked out your project and ran `go run ./main.go` and got:

```
# command-line-arguments
./main.go:13:10: undefined: Product
```
Which is the exact the same error that the debugger is raising

**Comment by ITHDevelopment** [comment]
And that's a correct behavior of the compiler. For the project to run you must do `go run .` like I have being saying since the beginning.
Can you please tell me what's wrong with the code? And how looks done in the right way?
How can I achieve debugging with more than one file in package main? Is that even possible?

**Comment by leoluz** [comment]
> And that's a correct behavior of the compiler. For the project to run you must do `go run .` like I have being saying since the beginning.

If you know that this is the correct behaviour of the compiler then you already know that this is not a problem with the debugger.

> Can you please tell me what's wrong with the code? And how looks done in the right way?

There is no right or wrong way. You have to know what you are doing and what you are trying to achieve. If you run `go run .` you will make every symbol in the current directory available to the compiler. That is why it is working when you run this command. When I want to run the main program like the way you are trying to do you I put the name of the file that has the main function. This way, package problems like the one you are having are more obvious to spot and thats how the `go build` will compile and build your binary.

> How can I achieve debugging with more than one file in package main? Is that even possible?

See here: https://github.com/leoluz/simpleGoProjectThatFails This is how I would design it so it works with `go run ./cmd/simple` and also works with debug

**Comment by ITHDevelopment** [comment]
Thank u,  I was looking for solutions.
I'm going to check it out right now :)
Also I'm curious about the behavior of the debugger and the build command. Because as far as I know, if u specify the folder with the main function in it correctly, it grabs everything in that folder, then brings everything from the imports and compile it to a giant single binary. I'm right?
So if the way the debugger works is compiling the project with the `build` command and then running the `.exe` (in windows) I still can't see why it would fail.
So I'll keep investigating as I find this topic specially interesting.
Thak u all for helping with this, and thanks @leoluz for making a solution.
I think this have been all for this "issue".
