### ISSUE TITLE
Feature Request: Missing configuration of dart

### ISSUE THREAD

**Issue by changyiyao** [mfussenegger/nvim-dap#349]
### Problem Statement

https://dartcode.org/docs/launch-configuration/

As the above configuration says, just want `deviceId`, `args` to be supported.

**Comment by mfussenegger** [comment]
I don't understand the issue.  Did you try the options and they don't work,  or what's the problem?

**Comment by changyiyao** [comment]
```
dap.configurations.dart = {
  {
    type = "dart",
    request = "launch",
    name = "Launch example",
    dartSdkPath = os.getenv('HOME').."/Projects/flutter/bin/cache/dart-sdk/",
    flutterSdkPath = os.getenv('HOME').."/Projects/flutter",
    program = "${workspaceFolder}/example/lib/main.dart",
    cwd = "${workspaceFolder}/example",
    deviceId = "E71CF447-1B75-431B-899F-E7D5798BC8E0",
  },
  {
    type = "dart",
    request = "launch",
    name = "Launch main",
    dartSdkPath = os.getenv('HOME').."/Projects/flutter/bin/cache/dart-sdk/",
    flutterSdkPath = os.getenv('HOME').."/Projects/flutter",
    program = "${workspaceFolder}/lib/main.dart",
    cwd = "${workspaceFolder}",
    deviceId = "E71CF447-1B75-431B-899F-E7D5798BC8E0",
  },
}
```
I have tried the above configuration with additional `deviceId` configuration which is not mentioned in [vimspect](https://github.com/puremourning/vimspector/wiki/languages#vimspectorjson-place-in-your-project-root), but it not take effect, hence I assume the adapter(nvim-dap or vimspect) doesn't pass the `deviceId` configuration to dart-debugger properly.

**Comment by mfussenegger** [comment]
> hence I assume the adapter(nvim-dap or vimspect) doesn't pass the deviceId configuration to dart-debugger properly.

nvim-dap passes all  configuration options unfiltered to the debug adapter.
If it isn't working I'd assume that either the value you provide is wrong or maybe dartcode handles it on the client side and maps it to a different property before sending it to the debug-adapter/server side.

**Comment by changyiyao** [comment]
Thanks for your explanation.

**Comment by LinuCC** [comment]
For anyone coming across this and having the issue of `deviceId` not being passed using DartCode: 
You can use `args` instead.

```
dap.configurations.dart = {
  {
    type = "dart",
    request = "launch",
    name = "Launch flutter",
    flutterSdkPath = ...,
    dartSdkPath = ...,
    program = "${workspaceFolder}/lib/main.dart",
    cwd = "${workspaceFolder}",
    args = { '-d', 'MY-DEV-ICE' }
  }
}
```

or switch to flutter debug_adapter with Flutter 3.3 : https://github.com/Dart-Code/Dart-Code/issues/4164#issuecomment-1252498092
