### ISSUE TITLE
vscode-cpptools closes immediately

### ISSUE THREAD

**Issue by jihbuomj** [mfussenegger/nvim-dap#358]
### Debug adapter definition and debug configuration

```lua
local dap = require'dap'

dap.adapters.cppdbg = {
	type = 'executable',
	command = '/home/bvtthead/desk/OpenDebuAD7Nostderr',
}

dap.configurations.c = {
	{
		request = 'launch',
		program = '${workspaceFolder}/build/serial-flash.elf',
		cwd = '${workspaceFolder}',
		type = 'cppdbg',
		miMode = 'gdb',
		miDebuggerPath = '/opt/gcc-arm-none-eabi/10.2.1/bin/arm-none-eabi-gdb-py',
		setupCommands = {
			{
				description = 'Enable pretty-printing for gdb',
				text = '-enable-pretty-printing',
				ignoreFailures = true
			},
			{
				text = '-file-exec-and-symbols ${workspaceFolder}/build/serial-flash.elf',
				description = 'load file',
				ignoreFailures = false
			},
			{
				text = '-target-select extended-remote :3333',
				description = 'connect to target',
				ignoreFailures = false
			},
			{
				text = 'monitor reset init',
				ignoreFailures = false
			},
			{
				text = '-target-download',
				ignoreFailures = false
			}
		}
	}
}
```

### Debug adapter version

1.7.1

### Steps to Reproduce

`lua require'dap'.continue()`

### Expected Result

Debug adapter to run as normal

### Actual Result

`vscode-cpptools` prints info to stderr, which `nvim-dap`  seems to use as an indicator to kill the process
 
```
[ ERROR ] 2021-11-24T10:16:44Z-0500 ] ...e/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:706 ] "stderr"        {
  command = "/home/bvtthead/apps/cpptools/extension/debugAdapters/bin/OpenDebugAD7",
  type = "executable"
}       "waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2021-11-24T10:16:44Z-0500 ] ...e/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:674 ]  "Closed all handles"
[ INFO ] 2021-11-24T10:16:44Z-0500 ] ...e/.local/share/nvim/plugged/nvim-dap/lua/dap/session.lua:677 ]  "Process closed"        22059   false
```

Using a wrapper to redirect stderr
```bash
#!/usr/bin/env bash

~/apps/cpptools/extension/debugAdapters/bin/OpenDebugAD7 2>/dev/null
```
and modifying the adapter configuration
```lua
local dap = require'dap'

dap.adapters.cppdbg = {
	type = 'executable',
	command = '/home/bvtthead/scratchpad/OpenDebuAD7Nostderr', -- wrapper script
}
```
allows the adapter to run normally.

**Comment by mfussenegger** [comment]
This is pretty strange. Output on stderr is only logged, but shouldn't cause the process to terminate, unless the process exits by itself.

https://github.com/mfussenegger/nvim-dap/blob/4e8bb7ca12dc8ca6f7a500cbb4ecea185665c7f1/lua/dap/session.lua#L703-L708

Could you try with the following change applied:

```
diff --git a/lua/dap/session.lua b/lua/dap/session.lua
index 43cb96b..2ed62ac 100644
--- a/lua/dap/session.lua
+++ b/lua/dap/session.lua
@@ -699,11 +699,11 @@ function Session:spawn(adapter, opts)
   }
   stdout:read_start(rpc.create_read_loop(function(body)
     session:handle_body(body)
   end))
   stderr:read_start(function(err, chunk)
-    assert(not err, err)
+    --assert(not err, err)
     if chunk then
       log.error("stderr", adapter, chunk)
     end
   end)
   return session
```

**Comment by jihbuomj** [comment]
Must have been some other issue since changing that fixed it and reverting the change didn't break it again. I can't replicate the error any more.

**Comment by lsli0116** [comment]
I have the same problem, the debug window closes immediately, and the output of the dap.log is as followed:
`[ ERROR ] 2022-01-08T19:25:42Z+0800 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:715 ]	"stderr"	{
  command = "/Users/lsli/software/extension/debugAdapters/bin/OpenDebugAD7",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2022-01-08T19:25:43Z+0800 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:371 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"
[ INFO ] 2022-01-08T19:25:43Z+0800 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:683 ]	"Closed all handles"
[ INFO ] 2022-01-08T19:25:43Z+0800 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:686 ]	"Process closed"	49043	false
[ INFO ] 2022-01-08T19:25:43Z+0800 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:371 ]	"Telemetry"	"VS/Diagnostics/Debugger/DebugCompleted"
`

It is really strange and I don't know the reason, may be the bug of the cpp-tools.

And my configuration is as followed:
`
dap.adapters.cppdbg = {
	type = "executable",
	command = "/Users/lsli/software/extension/debugAdapters/bin/OpenDebugAD7",
}
dap.configurations.cpp = {
	{
		name = "Launch file",
		type = "cppdbg",
		request = "launch",
		program = function()
			return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
		end,
		cwd = "${workspaceFolder}",
		stopOnEntry = true,
		MIMode = "lldb",
		miDebuggerPath = "/Users/lsli/software/extension/debugAdapters/lldb/bin/lldb-mi",
		setupCommands = {
			{
				text = "-enable-pretty-printing",
				description = "enable pretty printing",
				ignoreFailures = false,
			},
		},
	},
}

`

**Comment by skyveil** [comment]
I have the same problem
Output of dap.log:
```log
[ ERROR ] 2022-08-14T00:49:52Z+0530 ] .../beast/.config/nvim/plugins/nvim-dap/lua/dap/session.lua:1139 ]	"stderr"	{
  command = "/home/beast/.config/nvim/debuggers/cpptools/extension/debugAdapters/bin/OpenDebugAD7",
  id = "cppdbg",
  options = {
    detached = false
  },
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2022-08-14T00:49:53Z+0530 ] .../beast/.config/nvim/plugins/nvim-dap/lua/dap/session.lua:613 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"
[ INFO ] 2022-08-14T00:49:58Z+0530 ] .../beast/.config/nvim/plugins/nvim-dap/lua/dap/session.lua:1103 ]	"Closed all handles"
[ INFO ] 2022-08-14T00:49:58Z+0530 ] .../beast/.config/nvim/plugins/nvim-dap/lua/dap/session.lua:1106 ]	"Process closed"	79502	false
[ INFO ] 2022-08-14T00:49:58Z+0530 ] .../beast/.config/nvim/plugins/nvim-dap/lua/dap/session.lua:613 ]	"Telemetry"	"VS/Diagnostics/Debugger/DebugCompleted"
```
I followed the minimal configuration from the wiki:
```lua
local dap = require('dap')
dap.adapters.cppdbg = {
    id = 'cppdbg',
    type = 'executable',
    command = '/home/beast/.config/nvim/debuggers/cpptools/extension/debugAdapters/bin/OpenDebugAD7',
}

dap.configurations.cpp = {
    {
        name = "Launch file",
        type = "cppdbg",
        request = "launch",
        program = function()
            return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
        end,
        cwd = '${workspaceFolder}',
        setupCommands = {
            {
                text = '-enable-pretty-printing',
                description = 'enable pretty printing',
                ignoreFailures = false
            },
        },
        stopOnEntry = false,
    },
    {
        name = 'Attach to gdbserver :1234',
        type = 'cppdbg',
        request = 'launch',
        MIMode = 'gdb',
        miDebuggerServerAddress = 'localhost:1234',
        miDebuggerPath = '/usr/bin/gdb',
        cwd = '${workspaceFolder}',
        setupCommands = {
            {
                text = '-enable-pretty-printing',
                description = 'enable pretty printing',
                ignoreFailures = false
            },
        },
        program = function()
            return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
        end,
    },
}
```
I also tried to setup lldb-vscode but the breakpoint got rejected same as #646

**Comment by skyveil** [comment]
It was a silly mistake from my end, I didn't setup debug symbols.
Thanks for the awesome tool 😄

**Comment by VanillaBase1lb** [comment]
> It was a silly mistake from my end, I didn't setup debug symbols. Thanks for the awesome tool smile

Hi, what do you mean by didn't setup debug symbols, do you mean you didn't set a breakpoint? I'm facing the same issue, might help. Thanks.

**Comment by GhiathAjam** [comment]
Fot what is worth, I had same issue and solved it by `sudo apt install gdb` 😶

**Comment by nyngwang** [comment]
@VanillaBase1lb Did you solve it? It means that you have to compile your program with these f\*cking symbols using the `-g` flag.

**Comment by VanillaBase1lb** [comment]
@nyngwang yup, you have to compile with -g flag

**Comment by nyngwang** [comment]
@VanillaBase1lb I just spent hours realizing this fact, lol.
