### ISSUE TITLE
Allow read and write of the repl without interacting with buffer (socket or lua api)

### ISSUE THREAD

**Issue by pfeiferj** [mfussenegger/nvim-dap#364]
### Problem Statement

Neovim/vim's prompt does not support ansi highlighting, leading to ansi highlighting control sequences being displayed in the prompt and cluttering the view. Currently a user could use the integratedTerminal option to get highlighting of the process output but this means they need seperate windows to interact with the repl and see the process output, further, not all adapters support this. This means that a user may want to interact with and see the output of the repl somewhere other than its own buffer.

### Ideas or possible solutions

Implementing a socket that the repl reads and writes to would allow a user to interact with the repl in a terminal with ansi highlighting by using something like socat. `socat READLINE UNIX-CLIENT:/tmp/dap.sock` opens an interactive shell to a socket that allows using up and down to cycle through previously sent commands and could be used from within nvim's terminal.

It may be preferred to provide functionality for interacting with the repl from inside the vim process directly, in which case an api could be added that allows another plugin to extend the functionality of the repl. In the case of creating an api it would be preferred to have both read and write event callbacks as well as read and write functions so that a plugin could update in realtime to all interactions and send input to the repl.

Another thing to note is that I looked into adding syntax highlighting for ansi escape sequences to the repl, but turns out that's both non-trivial and non-ideal. There's already some vim implementations of [ansi escape highlighting](https://github.com/powerman/vim-plugin-AnsiEsc) but you end up with a choice of either not supporting all 256 colors (let alone true color) or using up all of your highlight/syntax groups due to there being a limit of 20000 highlight/syntax groups in vim. That plugin linked somewhat get's around the issue by dynamically creating syntax groups based on what's actually in the buffer, but that means you need to constantly refresh the plugin if you're getting a live output.

**Comment by pfeiferj** [comment]
Actually, this is very possibly not needed. I realized that nvim_buf_attach probably already does what I was asking from an api perspective. Investigating if I can use it to do what I want.

**Comment by mfussenegger** [comment]
> Currently a user could use the integratedTerminal option to get highlighting of the process output but this means they need seperate windows to interact with the repl and see the process output, further, not all adapters support this. 

The option for adapters that don't support it is to start them outside in a terminal and attach the debugger.


> Implementing a socket that the repl reads and writes to would allow a user to interact with the repl in a terminal with ansi highlighting by using something like socat.

You can already use the regular neovim buffer APIs to interact with the REPL. And you could also go lower and implement a custom REPL.

You can receive the [output event](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output) from the debug adapter via the `dap.listeners` API (see `:h dap-extensions`)

To communicate with the debug adapter you can receive the active session via `dap.session()` and then send arbitrary requests via the `:request` method on the session - or by using some of the higher level methods, like `:evaluate`.

I'm not going to add an additional REPL/socket specific API or abstraction.



As to making the REPL better per default:

There is `nvim_open_term` which could be used to display the output, but then there is the same problem as you already mentioned with the `integratedTerminal` option: You'd need another window to provide the input.
(I brought this up in the neovim-dev channel, and the idea to have something like a input-prompt attached to a `nvim_open_term` buffer isn't completely absurd, so at some point that might become a solution)

**Comment by pfeiferj** [comment]
Looked over things and I agree that abstracting the repl isn't needed. The repl seems to extend the session less than I expected. Also hadn't really looked into the listeners and I've got to say, they look pretty solid and should cover my needs. Closing the ticket.
