### ISSUE TITLE
`${relativeFileDirname}` returning absolute path

### ISSUE THREAD

**Issue by leoluz** [mfussenegger/nvim-dap#369]
### Debug adapter definition and debug configuration

Im having a strange behaviour using `${relativeFileDirname}`. Depending on how I open the file the relative file is returned correctly but sometimes I get the absolute path. This makes the debugger initialization unstable.

It seems that it needs a similar fix as this one: https://github.com/mfussenegger/nvim-dap/commit/4e8bb7ca12dc8ca6f7a500cbb4ecea185665c7f1

**Comment by mfussenegger** [comment]
Yes, thanks for pointing out. Should be fixed now

**Comment by leoluz** [comment]
Tested and working fine now. Thanks to you.
