### ISSUE TITLE
DAP for R

### ISSUE THREAD

**Issue by sebffischer** [mfussenegger/nvim-dap#371]
### Problem Statement

I would like to use nvim-dap in combination with https://github.com/ManuelHentschel/vscDebugger but I have no idea how to do this. It would be great if you could help me.

**Comment by mfussenegger** [comment]
What did you try so far? I suspect they have an executable that starts the debug adapter? See `:help dap-adapter`

**Comment by mfussenegger** [comment]
Closing due to lack of feedback
