### ISSUE TITLE
too many 'appendbufline' errors output occasionally

### ISSUE THREAD

**Issue by changyiyao** [mfussenegger/nvim-dap#373]
### Debug adapter definition and debug configuration

  {
    type = "dart",
    request = "launch",
    name = "Launch main_dev",
    dartSdkPath = os.getenv('HOME').."/Projects/flutter/bin/cache/dart-sdk/",
    flutterSdkPath = os.getenv('HOME').."/Projects/flutter",
    program = "${workspaceFolder}/lib/main_dev.dart",
    cwd = "${workspaceFolder}",
  },

### Steps to Reproduce

1. In a flutter project
2. no any setups such like setting breakpoints.
3. dap.continue()
4. Open REPL window but focus on other window (use nvim-dap-ui). 

### Expected Result

no errors output.

### Actual Result

When open repl window, but focus on other window, the error shows when every std output that comes from dart:

Error executing vim.schedule lua callback: Vim:E315: ml_get: invalid lnum: 187
stack traceback:
        [C]: in function 'appendbufline'
        .../.config/nvim/plugged/nvim-dap/lua/dap/repl.lua:287: in function 'append'
        .../.config/nvim/plugged/nvim-dap/lua/dap/session.lua:373: in function 'callback'
        .../.config/nvim/plugged/nvim-dap/lua/dap/session.lua:579: in function <.../.config/nvim/plugged/nvim-dap/lua/dap/session.lua:571>

**Comment by mfussenegger** [comment]
Can you also reproduce this without nvim-dap-ui?

**Comment by mfussenegger** [comment]
Closing due to lack of feedback. I can't reproduce this.
