### ISSUE TITLE
Add a `noDebug` option to the adapter configuration

### ISSUE THREAD

**Issue by ckipp01** [mfussenegger/nvim-dap#380]
### Problem Statement

The use case I have for this in when using [Metals](https://scalameta.org/metals/), the Scala Language Server, there are various ways to start a debugging session. One of those ways is to rely on code lenses. Metals will automatically detect in your file if you have a test suite or a main class and offer a `Run` and `Debug` code lens or `Test` and `TestDebug` code lens.

<img width="392" alt="Screenshot 2021-12-13 at 22 28 46" src="https://user-images.githubusercontent.com/13974112/145891723-73050b8d-bcad-4cd7-bf7b-8a548e50c47d.png">

Attached to these are commands that pass everything in to Metals to start the debug process and then the normal DAP stuff just takes over. The choice to have two options, `Run` and `Debug` came from VS Code having a `noDebug` setting as part of the debug session options:

```ts
/**
 * Controls whether this session should run without debugging, thus ignoring breakpoints.
 * When this property is not specified, the value from the parent session (if there is one) is used.
 */
noDebug?: boolean;
```

The description is pretty clear,  but it would allow for this situation to allow the `Run` code lens to skip all the set points, and the `Debug` to pass them along. (This is all in a branch of `nvim-metals` right now since I'm first adding the debug code lens, but right now they are both just mapped to do the same and not skip them).

### Ideas or possible solutions

Some of the things I thought about doing were when the user chooses the `Run` option I clear all of the breakpoints first and then run, but I'd find that super annoying as a user, so I don't think I'll go that route. The other option would be to have a `noDebug` options like I explained above which caused me to create this feature request. Maybe there is something else I'm not thinking of or a way to already achieve this that I'm missing.

Thanks!

**Comment by mfussenegger** [comment]
Isn't it enough to add a `noDebug = true` to the launch configuration?

According to the spec, all debug adapters should support that: https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Launch

**Comment by ckipp01** [comment]
> Isn't it enough to add a `noDebug = true` to the launch configuration?

Ahhhhh of course! Sorry I totally misunderstood this and didn't realize I  could just do this. Just tried it out and this seemed to do exactly that. Thanks!
