### ISSUE TITLE
Rust variables values don't change in the UI when they're updated

### ISSUE THREAD

**Issue by emi2k01** [mfussenegger/nvim-dap#384]
### Debug adapter definition and debug configuration

Installed the adapter lldb-vscode via AUR

Copy pasted configuration from wiki

### Debug adapter version

latest

### Steps to Reproduce

Create a rust project with the following `main.rs`

```rs
fn main() {
    
    let mut hash = std::collections::HashMap::new();
*   hash.insert("10", ("a", 20));
*   hash.insert("20", ("b", 30));

    let hash2 = hash;
*   print("end");
}
```

and add breakpoints where the lines starts with an asterisk.

If you debug this file and inspect `hash` on any breakpoint, you will see that the value doesn't change but when `let hash2 = hash` is executed, we can see that `hash2` gets the actual value.

### Expected Result

`hash` value gets updated in the scopes widget after `hash.insert` is executed.

### Actual Result

`hash` value in the scopes widget gets stuck in its initial value.

**Comment by emi2k01** [comment]
This only happens with complex types like `String`, `Vec`, or `HashMap`. It doesn't happen with primitives. Maybe the formatters have something to do? I'm completely unfamiliar with how things work.

**Comment by mfussenegger** [comment]
Looks fine to me:


https://user-images.githubusercontent.com/38700/146837301-673d5aa6-0edd-47c1-bb85-0c67327af63e.mp4

This is with codelldb.
lldb-vscode from llvm package only displays the pointer

**Comment by theHamsta** [comment]
The printing of the pretty printing of the Rust structures happens via Python functions provided by the Rust installation (for normal lldb, maybe they are bundled for  code-lldb) that describe how to access the raw pointers to print meaningful values. There might be differences in the installed version. Maybe you can test whether you get the same results with VSCode.

**Comment by emi2k01** [comment]
It seems this only happens when I use `rust-tools` to get the debugging target. I didn't catch it before because I think `nvim-dap` was using `lldb-vscode` when I ran `nvim-dap` and I didn't realize.

**Comment by emi2k01** [comment]
Sorry. `rust-tools` was also using `lldb-vscode` because I passed the config to the wrong field. 😩😈😈
