### ISSUE TITLE
The debug adapter is still working after I finish debugging ?

### ISSUE THREAD

**Issue by rzksobhy78** [mfussenegger/nvim-dap#387]
### Debug adapter definition and debug configuration

I installed the adapter like how its described in the wiki
`git clone https://github.com/microsoft/vscode-node-debug2.git`
`cd vscode-node-debug2`
`npm install`
`gulp build`

My adapter configuration
`
dap.adapters.node2 = {
	type = 'executable',
	command = 'node',
	args = { '/home/sobhy/tools/vscode-node-debug2/out/src/nodeDebug.js' }
}
`

after I installed the plugin and used it many times
my computer became very heavy and couldn't use it
I restarted it so it kills all the process I tried again and same thing happened
I checked what is the problem with htop I found nodeDebug processes is working even after
I stopped debugging and they are taking too much resources of my computer and thats
what was making it crash how can I fix that

### Steps to Reproduce

What is that ?

### Expected Result

To close the adapter after I'm done debugging

### Actual Result

It is not closing it and my computer lags
and stop

**Comment by mfussenegger** [comment]
Can you share some more information on what you're debugging and how you're starting the debug session?

I can't reproduce this.

**Comment by mfussenegger** [comment]
Closing due to lack of feedback
