### ISSUE TITLE
The frame window could be self-refreshed on .up and .down

### ISSUE THREAD

**Issue by przepompownia** [mfussenegger/nvim-dap#390]
### Problem Statement

The current frame indicator (`→ `) does not move on jumping `.up` and `.down`. 

### Ideas or possible solutions

 I am fresh in Lua and use nvim-dap for two weeks (DAP is also new for me although I used the old, good Vimspector). I tried to understand what happens from the code and log perspective, especially how events from adapter look like, to resolve this and some other problems. 

It seems that any `frames` instance gets refreshed on the event defined as the value of `refresh_listener`. By default (and for `frames`) it is `stopped` and it seems that we can not attach more than one event there. 

I couldn't find (in `dap.log`) any event fired after move through the stack trace that could be used in addition to `stopped`. 

Do we need to allow attach more than one event to a widget, including non-DAP events? 

Thanks for the promising alternative for Vimspector!

**Comment by mfussenegger** [comment]
Thanks for pointing out, should be fixed with https://github.com/mfussenegger/nvim-dap/pull/391

**Comment by przepompownia** [comment]
Also thank you.
