### ISSUE TITLE
[RUST - CODELLDB] - Debugger only showing assembly when debugging starts 

### ISSUE THREAD

**Issue by black-eagle17** [mfussenegger/nvim-dap#392]
### Debug adapter definition and debug configuration

Installed the adapter via DAPInstall.nvim 

Configuration:
```

require("dapui").setup()

local dap_install = require("dap-install")
dap_install.setup({
    installation_path = vim.fn.stdpath("data") .. "/dapinstall/",
    verbosely_call_debuggers = true,
})

dap_install.config("python",{})
dap_install.config("codelldb",{
configurations={{
    name = "Launch file",
    type = "codelldb",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = true,
  },}
})

-- Update this path
local extension_path = '/home/deandre/extension/'
local codelldb_path = extension_path .. 'adapter/codelldb'
local liblldb_path = extension_path .. 'lldb/lib/liblldb.so'

lvim.lsp.override = { "rust" }
lvim.plugins = {
  {
    "simrat39/rust-tools.nvim",
    config = function()
      require("rust-tools").setup({
        dap = {
        adapter = require('rust-tools.dap').get_codelldb_adapter(
            codelldb_path, liblldb_path)
    },
        tools = {
          autoSetHints = true,
          hover_with_actions = true,
          runnables = {
            use_telescope = true,
          },
        },
        server = {
          cmd = { vim.fn.stdpath "data" .. "/lsp_servers/rust/rust-analyzer" },
          on_attach = require("lvim.lsp").common_on_attach,
          on_init = require("lvim.lsp").common_on_init,
        },
        })
    end,
    ft = { "rust", "rs" },
  },
}


```

### Steps to Reproduce

1. Create a simple rust program
2. set a break point in the program
3. start the debugger
4. Watch as the debugger only shows assembly. 

### Expected Result

I expected a normal debugging session where i can step through my code and still see the rust program. I also would like to see my variables being displayed on the ```dapui``` window.

### Actual Result

https://user-images.githubusercontent.com/37980286/147868327-2afbbe8c-7fa7-496d-90c8-4c18d0051ce7.mp4

Here is a short video showing the error while trying to start a debug sessio
![nvim-dap](https://user-images.githubusercontent.com/37980286/147868345-906ffbbf-72ad-4645-af27-1a6d23c11a35.png)
also, here is a picture just in case the video doesn't work.

**Comment by Logarithmus** [comment]
@black-eagle17 which color scheme are you using?

**Comment by black-eagle17** [comment]
@Logarithmus I think the color scheme is onedarker. Also let me apologize for closing the issue. There was no basis upon which I closed it, I just did. I had better luck with using lldb-vscode as the debug adapter.

**Comment by MattCairns** [comment]
I had this same issue and couldn't resolve it with any of the debug adapters. This is a bit hacky but I fixed it for myself by opening a split before the debugger initializes.

```lua
local dap = require('dap')
dap.listeners.before.event_initialized["split_winow"] = function() 
	vim.cmd("vs")
end
```

**Comment by Logarithmus** [comment]
> I had this same issue and couldn't resolve it with any of the debug adapters. This is a bit hacky but I fixed it for myself by opening a split before the debugger initializes.
> 
> ```lua
> local dap = require('dap')
> dap.listeners.before.event_initialized["split_winow"] = function() 
> 	vim.cmd("vs")
> end
> ```

@MattCairns Thanks for the solution!
