### ISSUE TITLE
Expose last run config

### ISSUE THREAD

**Issue by smackesey** [mfussenegger/nvim-dap#393]
### Problem Statement

I have some custom UI setup that I run when launching the debugger. This differs depending on the specifics of the debugger config.

nvim-dap exposes a convenient method `run_last` to rerun the last used configuration. However, the last used config is stored as a local variable in nvim-dap and isn't exposed to the user. This prevents me from properly being able to perform the custom UI setup before launching the debugger from the `run_last` command.

### Ideas or possible solutions

Expose `last_run` in `lua/dap.lua` on the `dap` module.

**Comment by mfussenegger** [comment]
Would it be possible to run your custom UI setup as part of the initialize event? You can get access to the configuration there:


See `:help dap-extensions`

```lua
dap.listeners.after.event_initialized['some-unique-id'] = function(session)
  local config = session.config
  -- your logic
end
```

**Comment by smackesey** [comment]
This works-- thank you for the suggestion! Guess I'll close this.
