### ISSUE TITLE
Attempt to index local 'frame' when opening an expression sidebar

### ISSUE THREAD

**Issue by gpanders** [mfussenegger/nvim-dap#404]
### Debug adapter definition and debug configuration

`lldb-vscode` is installed via the `llvm` package from Homebrew.

The `lldb` adapter is configured just as in the wiki. In addition, I have the following to set up widgets after initialization:

```lua
local widgets = require("dap.ui.widgets")
local expression = widgets.sidebar(widgets.expression)
dap.listeners.after.event_initialized.me = function()
  expression.open()
  dap.repl.open()
end
```

### Debug adapter version

LLVM 13

### Steps to Reproduce

I don't think the source matters, but in my case I'm using a simple test program:

```c
#include <stdio.h>

int add(int x, int y) {
    return 2*x + 3*y;
}

int
main(int argc, char **argv)
{
    int z = add(17, 25);
    printf("z is %d\n", z);
    return 0;
}
```

I set a breakpoint on any line and run `dap.continue()` to start DAP (launching a new process).

### Expected Result

A sidebar should appear with the expression window.

### Actual Result

```
Error executing vim.schedule lua callback: ...m/site/pack/packer/start/nvim-dap/lua/dap/ui/widgets.lua:196: attempt to index local 'frame' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/nvim-dap/lua/dap/ui/widgets.lua:196: in function 'after_open'
        ...hare/nvim/site/pack/packer/start/nvim-dap/lua/dap/ui.lua:322: in function 'open'
        /Users/greande/.local/share/nvim/site/plugin/dap.lua:56: in function 'c'
        ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:583: in function <...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:571>
```

**Comment by mfussenegger** [comment]
I think you'll want to use the scopes widget to get an overview of all variables. The expression widget is for a single expression/variable. The error should be fixed anyway, but even if it is fixed, it's probably not what you want

**Comment by gpanders** [comment]
> The expression widget is for a single expression/variable.

Ah ok, thanks for clarifying. I was looking for a widget to show the value of "watched" expressions/variables, which I thought this was for.

**Comment by mfussenegger** [comment]
There's currently no widget in nvim-dap itself where you can individually add expressions to watch. nvim-dap-ui got something like that.

widgets.scopes shows all variables in the global and local scopes.
widgets.expressions is for "show me this variable or expression under the cursor"  and internally used by `hover()`, used e.g. via

```
nnoremap <silent> <leader>dh :lua require('me.dap').widgets.hover()<CR>
vnoremap <silent> <leader>dh :lua require('me.dap').widgets.hover(require("dap.utils").get_visual_selection_text)<CR>
```

That said - it's something I wanted occasionally, so I might add it at some point.
