### ISSUE TITLE
Can't close floating window by pressing `q` or `Esc`

### ISSUE THREAD

**Issue by Logarithmus** [mfussenegger/nvim-dap#415]
### Steps to Reproduce

1. Start debugging session
2. Put the cursor over a variable
3. `:lua require("dap.ui.widgets").hover()`

### Expected Result

Packer's, Trouble.nvim's, Telescope's windows & splits can be close by pressing either `q` or `Esc`.
I'm using LunarVim, maybe it affects this behavior somehow?

### Actual Result

The only way to close the floating window is `:q`, because `q` & `Esc` don't work.

https://user-images.githubusercontent.com/29541480/149848061-a968ef48-8f8f-4f84-9d68-dcec000a0bae.mp4

**Comment by mfussenegger** [comment]
This is expected. nvim-dap is rather unopinionated and sticks to neovim defaults if they exist. The default mapping to close a window in neovim is `<C-W q>`. 

I could set a `dap-repl` filetype to make it easier to define custom mappings.

**Comment by jarviliam** [comment]
@mfussenegger Thanks for adding the filetype! 👍 
@Logarithmus After updating nvim-dap you should be able to add the mapping via an autocmd now like `autocmd FileType dap-float nnoremap <buffer><silent> q <cmd>close!<CR>`

**Comment by kraxli** [comment]
very nice! Thanks a lot for this and the whole plug-in!

**Comment by sakalys** [comment]
Here's a lua counterpart to what @jarviliam suggested, if anyone needs this:
```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = "dap-float",
    callback = function()
        vim.api.nvim_buf_set_keymap(0, "n", "q", "<cmd>close!<CR>", { noremap = true, silent = true })
    end
})
```
