### ISSUE TITLE
Trailing empty line in hover widget's floating window

### ISSUE THREAD

**Issue by Logarithmus** [mfussenegger/nvim-dap#416]
### Steps to Reproduce

1. Start debugging session
2. Put the cursor over a variable
3. `:lua require("dap.ui.widgets").hover()`

### Expected Result

No trailing empty line

### Actual Result

Trailing empty line

https://user-images.githubusercontent.com/29541480/149848061-a968ef48-8f8f-4f84-9d68-dcec000a0bae.mp4

**Comment by mfussenegger** [comment]
I kinda prefer it this way. If there is only a single digit it helps if the cursor is not over the value.

**Comment by Logarithmus** [comment]
@mfussenegger  How to override it specifically for my setup?
Also I think it would be better to put the cursor in the end of the line/hide it (nvim-cmp doesn't show a cursor in such windows)

**Comment by mfussenegger** [comment]
There is no easy way to override or customize it.

**Comment by mfussenegger** [comment]
I opened up https://github.com/mfussenegger/nvim-dap/pull/435 which would change the behavior. I'll keep the PR open for a while to see if it will get some more feedback.
