### ISSUE TITLE
Cursor looses focus when stepping into a scratch buffer

### ISSUE THREAD

**Issue by hereGittyGitty** [mfussenegger/nvim-dap#422]
### Debug adapter definition and debug configuration

Installed `vscode-node-debug2` as described in the wiki:
```
git clone https://github.com/microsoft/vscode-node-debug2.git
cd vscode-node-debug2
npm install
./node_modules/.bin/gulp build
```
My minimal configuration I used:
```lua
local dap = require('dap')
local api = vim.api
dap.adapters.node2 = {
  type = 'executable',
  command = 'node',
  args =  {'<full_path_to>/vscode-node-debug2/out/src/nodeDebug.js'},
}
dap.configurations.javascript = {
    {
        type = 'node2',
        request = 'launch',
        program = '${file}',
        cwd = vim.fn.getcwd(),
        sourceMaps = true,
        protocol = 'inspector',
        console = 'internalConsole'
    }
}
```

### Debug adapter version

1.43.0

### Steps to Reproduce

1. in a project like:
```
Promise();
```
2. add a breakpoint with `lua require'dap'.toggle_breakpoint()`
3. start debugging with `lua require'dap'.continue()`
4. step into `Promise()` with `lua require'dap'.step_into()`
5. a new buffer is opened named as `[Scratch]` with the cursor on the correct line.
6. step further with another call to `lua require'dap'.step_into()`
7. cursor disappears but buffer is unchanged

### Expected Result

The cursor is not lost when continuing `stepping` through the code.

### Actual Result

The cursor disappears but the buffer is unchanged.

Here is a gif showing the problem:
![dap](https://user-images.githubusercontent.com/2407498/151718485-c0684b82-f016-482a-bf79-56e0dc6d6b41.gif)

It was opened with the latest `neovim`, the latest `nvim-dap` using a minimal_init file:
```
set nocompatible

set runtimepath+=/usr/local/src/neovim_minimal_stuff/nvim-dap

lua << EOF
local dap = require('dap')
local api = vim.api
dap.adapters.node2 = {
  type = 'executable',
  command = 'node',
  args =  {'/usr/local/src/neovim_minimal_stuff/vscode-node-debug2/out/src/nodeDebug.js'},
}
dap.configurations.javascript = {
    {
        type = 'node2',
        request = 'launch',
        program = '${file}',
        cwd = vim.fn.getcwd(),
        sourceMaps = true,
        protocol = 'inspector',
        console = 'internalConsole'
    }
}
EOF

filetype plugin indent on
```
`neovim --version` shows:
```
NVIM v0.7.0-dev+978-g46bd48f7e
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by lorenz@chicken

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

Thanks a lot for this awesome plugin. If you need any more info just ask.

**Comment by mfussenegger** [comment]
Thank you for the detailed report. It was easy to reproduce and should be fixed with https://github.com/mfussenegger/nvim-dap/pull/425

**Comment by hereGittyGitty** [comment]
Yessss, works like a charm.
Thank you :)
