### ISSUE TITLE
Passing CLI arguments to debugger

### ISSUE THREAD

**Issue by sean-hale-dev** [mfussenegger/nvim-dap#424]
### Problem Statement

Love the project here, looking to switch over to it from vimspector. The only snag I've been hitting is passing CLI arguments to programs that I am attempting to debug, which is a core feature I need in order to use this. I was attempting to understand if there's a way to do that with an `args` field in a launch.json file but I'm either not properly understanding how to load the file or it's not supported.

### Ideas or possible solutions

Inside `select_config_and_run` or in `run` there could be permutations of these functions which allow the user to pass an array of arguments (i.e. `['foo', 'bar', '3', etc.]`)

**Comment by mfussenegger** [comment]
Whether you can pass arguments or how to pass them to the application depends on your debug adapter.

For example, for debugpy it could be done like here: https://github.com/mfussenegger/nvim-dap-python/pull/26/files
