### ISSUE TITLE
Breakpoint "lost" if buffer is closed (but execution still pauses at the line)

### ISSUE THREAD

**Issue by Abh15h3k** [mfussenegger/nvim-dap#426]
### Debug adapter definition and debug configuration

C/C++ adapter and configuration from wiki

```
local dap = require('dap')
dap.adapters.lldb = {
  type = 'executable',
  command = '/opt/homebrew/opt/llvm/bin/lldb-vscode',
  name = "lldb"
}
```

```
local dap = require('dap')
dap.configurations.cpp = {
  {
    name = "Launch",
    type = "lldb",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},
    runInTerminal = false,
  },
}
dap.configurations.c = dap.configurations.cpp
dap.configurations.rust = dap.configurations.cpp
```

### Debug adapter version

lldb-vscode (LLVM 13)

### Steps to Reproduce

main.c
```
#include <stdio.h>
#include "my-math.h"

int main (int argc, char *argv[])
{
    printf("sum of 10 and 20: %d\n", add_two_ints(10, 20));
    return 0;
}
```

my-math.h
```
int add_two_ints(int, int);
```

my-math.c
```
#include "my-math.h"

int add_two_ints(int a, int b) {
    int sum = a + b;
    return sum;
}
```

1. set breakpoint on printf line of main.c
2. start debug session with `lua require'dap'.continue()`
3. program executions pauses on printf line, now switch `my-math.c` buffer and set breakpoint on `int sum...` line. `lua require'dap'.toggle_breakpoint()`
4. close `my-math.c` buffer and reopen `my-math.c` (breakpoint symbol missing after reopen)
5. continue execution with `lua require'dap'.continue()`
6. program execution stops in `my-math.c` at `int sum...` line.

![ghost_breakpoint](https://user-images.githubusercontent.com/40197742/152631148-42b175f0-6fca-4325-95f4-cec07ec2aac1.gif)

NOTE:
this behaviour of "ghost" breakpoints only happens if the buffer is closed while the debug session is active.
if no debug session is active and a buffer with breakpoint is closed. the breakpoint is not triggered in a subsequent debug session.

### Expected Result

breakpoint indicator be present after closing and reopening buffers.

### Actual Result

breakpoint indicator disappears but breakpoint is still in effect.

**Comment by Abh15h3k** [comment]
this behaviour is not restricted to C/C++ debugging.
I first noticed it in a Java Spring Boot App

but for sanity i reproduced it in a C/C++ to make sure it was not a language/debug adapter specific issue

**Comment by mfussenegger** [comment]
This is because the client breakpoint state is currently based on signs, and signs disappear if you delete the buffer. If you merely hide it instead of deleting the breakpoint would show up again.

I agree that this should be fixed, but I am not quite sure what the better behavior would be: Implicitly delete breakpoints when a buffer is deleted or always keep them until explicitly removed?

The same issue currently also happens if you remove text that covers a breakpoint and then re-add it. The sign will be gone but the debug adapter doesn't receive the message. With a debugger that supports hot-reloading that can be confusing.

**Comment by Abh15h3k** [comment]
i guess implicitly deleting the breakpoints is better than having breakpoints that aren’t visible.
(Currently to get rid of a breakpoint thats "hidden" you have to set and and unset a breakpoint on that line, frustrating if there were more than 2-3 breakpoints in the buffer that got closed)
