### ISSUE TITLE
Dollar sign in hovered expression is lost because of using vim expansion

### ISSUE THREAD

**Issue by przepompownia** [mfussenegger/nvim-dap#427]
### Debug adapter definition and debug configuration

Configuration is standard - it doesn't seem to matter:
```lua
dap.adapters.php = {
  type = 'executable',
  command = 'node',
  args = { '.../path/to/vscode-php-debug/out/phpDebug.js' }
}
```
```lua
{
  type = 'php',
  request = 'launch',
  name = 'Listen for XDebug',
  port = 9003,
  stopOnEntry = false,
  xdebugSettings = {
    max_children = 512,
    max_data = 1024,
    max_depth = 4,
  },
  breakpoints = {
    exception = {
      Notice = false,
      Warning = false,
      Error = false,
      Exception = false,
      ['*'] = false,
    },
  },
}
```

### Debug adapter version

 v1.23.0

### Steps to Reproduce

```php
<?php                           

$x = 1;                                                     

printf("\$x = %s\n", $x);
```
Given the above script, break it at the last line and see 
```vim
lua require('dap.ui.widgets').hover('$x + 1')
```

### Expected Result

The adapter gets `$x + 1` to evaluate. 

### Actual Result

Adapters get ` + 1` as a string to evaluate as the [result of `vim.fn.expand('$x + 1')`](https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap/ui/widgets.lua#L309).

Looking two lines up I found that
```vim
lua require('dap.ui.widgets').hover(function() return '$x + 1' end)
```
can be a workaround to avoid expansion.

I do not propose any solution because there was some reason (other than `<cexpr>` which can be treated in a special case) to use such expansion, but for PHP it behaves unexpectedly.

**Comment by mfussenegger** [comment]
Are you manually invoking `lua require('dap.ui.widgets').hover('$x + 1')` ?

The behavior is kinda intention, the argument to `hover` is an expression for `expand` to be able to use things like `<cword>` or `<cexpr>` (the default)

If you want to evaluate some text, I'd setup a mapping like this:

```
vnoremap <silent> <leader>dh :lua require('me.dap').widgets.hover(require("dap.utils").get_visual_selection_text)<CR>
```

**Comment by przepompownia** [comment]
Thanks for the hint. I overlooked `get_visual_selection_text`. This function could be a part of neovim lua API. While it is not, its proposed usage could be mentioned in the documentation. Being a function, its result is not expanded and the whole command works as expected. 

While _vscode-php-debug_ does not support variable completion, using `hover` is more convenient than REPL for me. 

It seems that we can close this issue in such case.
