### ISSUE TITLE
Session remains active after the last step (ruby rdbg debug-adapter)

### ISSUE THREAD

**Issue by oats4goats** [mfussenegger/nvim-dap#429]
### Debug adapter definition and debug configuration

```
local dap = require('dap')
dap.adapters.ruby = {
  type = 'server';
  host = '127.0.0.1';
  port = 38698;
}

dap.configurations.ruby = {
  {
    type = 'ruby';
    name = 'debug current file';
    request = 'attach';
    port = 38698;
    server = '127.0.0.1';
  },
}
```

### Debug adapter version

1.4.0

### Steps to Reproduce

1. Start a debug-adapter with `rdbg --open --port 38698 target.rb` in a terminal
2. Attach to the adapter with `:lua require'dap'.continue()`
3. Continue or step over till the very end of the program. The adapter in the terminal disconnects.
4. Inspect the state by `:lua require'dap'.repl.open()`. The session is still open.

### Expected Result

The session is closed after the last step. Analogous to the behaviour of this adapter in VSCode. Otherwise, it has to be done manually before the next debug session.

### Actual Result

The session remains active after the last step.

**Comment by mfussenegger** [comment]
Does the debug adapter send a terminated event (see logs)? If it doesn't it might be an issue with the debug adapter. It is supposed to send one:

> In all situations where a debug adapter wants to end the debug session, a [terminated](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Terminated) event must be fired.

See https://microsoft.github.io/debug-adapter-protocol/overview

**Comment by mfussenegger** [comment]
I thought some more about this and I think it wouldn't hurt to handle tcp disconnects in a better way inside nvim-dap despite the required terminal event. 

Could you try with https://github.com/mfussenegger/nvim-dap/pull/436 and see if that solves the issue ?

**Comment by oats4goats** [comment]
Oh, thanks a lot for taking care of this. It works like charm now! The session is not active anymore after debug adapter disconnects. Thank you!
