### ISSUE TITLE
Codelldb starts insert mode after hitting breakpoint

### ISSUE THREAD

**Issue by p00f** [mfussenegger/nvim-dap#439]
### Debug adapter definition and debug configuration

Installed the adapter via:
Building codelldb as described here https://github.com/vadimcn/vscode-lldb/blob/master/BUILDING.md
(i.e I run [this](https://gist.github.com/p00f/b42e77af2d49c7d03df6d52183cd1afb) script from the repo cloned to `/home/p00f/tools/codelldb`)

```lua
local dap = require("dap")
dap.adapters.codelldb = function(on_adapter)
  local stdout = vim.loop.new_pipe(false)
  local stderr = vim.loop.new_pipe(false)

  local cmd = "/home/p00f/tools/codelldb/build/adapter/codelldb"

  local handle, pid_or_err
  local opts = {
    stdio = { nil, stdout, stderr },
    detached = true,
  }
  handle, pid_or_err = vim.loop.spawn(cmd, opts, function(code)
    stdout:close()
    stderr:close()
    handle:close()
    if code ~= 0 then
      print("codelldb exited with code", code)
    end
  end)
  assert(handle, "Error running codelldb: " .. tostring(pid_or_err))
  stdout:read_start(function(err, chunk)
    assert(not err, err)
    if chunk then
      local port = chunk:match("Listening on port (%d+)")
      if port then
        vim.schedule(function()
          on_adapter({
            type = "server",
            host = "127.0.0.1",
            port = port,
          })
        end)
      else
        vim.schedule(function()
          require("dap.repl").append(chunk)
        end)
      end
    end
  end)
  stderr:read_start(function(err, chunk)
    assert(not err, err)
    if chunk then
      vim.schedule(function()
        require("dap.repl").append(chunk)
      end)
    end
  end)
end
```

### Debug adapter version

1.6.10

### Steps to Reproduce

1. `foo.c`:
```c
int main() {
    int xyz = 1;
    return 0;
}
```
2. Set a breakpoint on line 1
3. `:!gcc % -g`
4. `:lua require("dap").continue`
5. Choose `a.out`

### Expected Result

Execution halts at line 2, staying in normal mode

### Actual Result

Execution halts at line 2, going into insert mode with the cursor just behind `xyz`

https://user-images.githubusercontent.com/36493671/154075047-b3093f00-4258-4e98-88cc-a37647ac9623.mp4

**Comment by mfussenegger** [comment]
Is this really without any other dap related extension?

The functions in nvim-dap that jump to the breakpoint/stopped frame are not starting insert mode.

**Comment by p00f** [comment]
I get this even after uninstalling nvim-dap-virtual-text

**Comment by p00f** [comment]
This only happens with codelldb, lldb-vscode works fine

**Comment by p00f** [comment]
I can reproduce it using the prebuilt release too, and that change doesn't fix it

**Comment by p00f** [comment]
Two more observations:
 - Insert mode starts first (at the original cursor position), the cursor moves to the breakpoint later
 - In rust,
```rust
fn main() {
    let x = 1;
    if let Some(f) = Some(2) {
        println!("{f}");
    }
}
```
-- If there is a breakpoint at line 2 the cursor stops here:

   `let x = |1;`

-- If there is a breakpoint at line 3 the cursor stops here:

   `if let Some(f) = |Some(2) {`

   as opposed to C(++) where the cursor stops here:

   `int |x = 1`

**Comment by mfussenegger** [comment]
I still suspect this may be something in your setup. I cannot reproduce it and there is nothing in the `event_stopped` logic that would switch into insert mode.

**Comment by p00f** [comment]
Ah I'm so sorry I had an `autocmd TermOpen "term://*" startinsert` autocommand.

**Comment by BlueDrink9** [comment]
This is happening to me as well (and [this reddit user](https://www.reddit.com/r/neovim/comments/wlbxh0/nvimdap_continue_drops_buffer_into_insert_mode/). While removing startinsert autocmds for termopen events is a workaround, it isn't ideal to lose that behaviour in our actual terminals. 

Are you able to shed some light on why the TermOpen autocmd might be triggered, and whether there is a pattern or guard we can use to prevent it from happening?

In my case, the autocmd is being created by a plugin; so I don't have access to changing the pattern directly. Ideally, nvim-dap just wouldn't affect generic termopen autocmds

**Comment by mfussenegger** [comment]
nvim-dap creates a terminal if the debug-adapter supports integrated terminals and if you configured it to use it.
Firing a `TermOpen` event is the default neovim behavior if `nvim_open_term` is called.

> In my case, the autocmd is being created by a plugin; so I don't have access to changing the pattern directly

I'd think that plugins shouldn't create mappings like that implicitly

> , it isn't ideal to lose that behaviour in our actual terminals.

You could make the pattern more specific. E.g. to include the shell name. The buffer name has the form of `term://{cwd}//{pid}:{cmd}` (see `:h terminal-start`)

**Comment by BlueDrink9** [comment]
Thanks for the response! Your expanation is quite clear, obviously not the fault of nvim-dap. Including shell name is a great suggestion, thank you

**Comment by AckslD** [comment]
Thanks all for this, I had the same thing! I added something like this for my autocmd:
```lua
      callback = function(opts)
        if opts.file:match('dap%-terminal') then
          return
        end
        vim.cmd('startinsert')
        vim.cmd('setlocal nonu')
      end,
```
