### ISSUE TITLE
Cursor position outside buffer when dap-ui windows are open 

### ISSUE THREAD

**Issue by przepompownia** [mfussenegger/nvim-dap#442]
### Debug adapter definition and debug configuration

As configured in the example environment https://github.com/przepompownia/dap-ui-test 
```lua
local dap = require 'dap'
local keymap = require 'vim.keymap'
local widgets = require('dap.ui.widgets')
local utils = require('dap.utils')

keymap.set({'x'}, ',dh', function() widgets.hover(utils.get_visual_selection_text) end, opts)
keymap.set({'n'}, ',dv', dap.step_over, opts)
keymap.set({'n'}, ',di', dap.step_into, opts)
keymap.set({'n'}, ',do', dap.step_out, opts)
keymap.set({'n'}, ',db', dap.toggle_breakpoint, opts)
keymap.set({'n'}, ',dc', dap.continue, opts)
keymap.set({'n'}, ',du', dap.up, opts)
keymap.set({'n'}, ',dd', dap.down, opts)

dap.set_log_level('TRACE')

dap.adapters.php = {
  type = 'executable',
  command = vim.g.initialVimDirectory .. '/bin/vscode-php-debug',
  args = { 'run' }
}

dap.configurations.php = {
  {
    log = true,
    type = 'php',
    request = 'launch',
    name = 'Listen for XDebug',
    port = 9003,
    stopOnEntry = false,
    xdebugSettings = {
      max_children = 512,
      max_data = 1024,
      max_depth = 4,
      extended_properties = 1,
    },
    breakpoints = {
      exception = {
        Notice = false,
        Warning = false,
        Error = false,
        Exception = false,
        ['*'] = false,
      },
    },
  }
}
```

### Debug adapter version

1.23.0

### Steps to Reproduce

- jump to location in other file when dap-ui interface is open before (using step into/over, up or down through the stack). 

I prepared https://github.com/przepompownia/dap-ui-test with as simple example as possible.

Run `make cursor-position-outside-buffer` to see this behaviour.

### Expected Result

Cursor is placed correctly without errors.

### Actual Result

![image](https://user-images.githubusercontent.com/11404453/154161236-5cca5c5a-fd69-4074-b65b-38d1e6b4723a.png)

**Comment by przepompownia** [comment]
Additional information: I used the current master version of neovim.

**Comment by przepompownia** [comment]
Probably dap-ui windows are considered as candidates to set the new buffer there (they have `nofile` buftype). After making the change
```diff
-    if vim.tbl_contains({'', 'nofile'}, buftype) then
+    if vim.tbl_contains({''}, buftype) then
```
problem disappears.

**Comment by mfussenegger** [comment]
Can you try with https://github.com/mfussenegger/nvim-dap/pull/443?

**Comment by przepompownia** [comment]
Confirmed on the test environment. Thanks @mfussenegger !

**Comment by sangdth** [comment]
I still have similar issue with firefox

```

  dap.adapters.firefox = {
    type = 'executable',
    command = 'node',
    args = {os.getenv('HOME') .. '/Applications/vscode-firefox-debug/dist/adapter.bundle.js'},
  }
  dap.configurations.typescriptreact = {
    {
      name = 'Debug React TypeScript with Firefox',
      type = 'firefox',
      request = 'launch',
      reAttach = true,
      url = 'http://localhost:3000',
      webRoot = '${workspaceFolder}',
      -- firefoxExecutable = '/usr/bin/firefox'
    }
  }

```

**Comment by Aatroxs** [comment]
I still have similar issue with rust 
`dap.adapters.cppdbg = {
  id = 'cppdbg',
  type = 'executable',
  command = '/home/aatrox/tools/cpptools/extension/debugAdapters/bin/OpenDebugAD7',
}
dap.configurations.cpp = {
  {
    name = "Launch file",
    type = "cppdbg",
    request = "launch",
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    miDebuggerPath = '/usr/bin/gdb',
    cwd = '${workspaceFolder}',
    stopOnEntry = true,
  },
  {
    name = 'Attach to gdbserver :1234',
    type = 'cppdbg',
    request = 'launch',
    MIMode = 'gdb',
    miDebuggerServerAddress = 'localhost:1234',
    miDebuggerPath = '/usr/bin/gdb',
    cwd = '${workspaceFolder}',
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
  },
}
dap.configurations.rust = dap.configurations.cpp
dap.configurations.c = dap.configurations.cpp

`

**Comment by Katzeee** [comment]
I still have similar issue with `codellvm`, using the tutorial setting. The excutable is up2date. It does jump to the right location, but before that, there is a vim notify says "cursor positon ...".

**Comment by mfussenegger** [comment]
Please don't post on this closed issue. If there is still a problem create a new issue with exact and minimal reproduction steps and provide logs.
