### ISSUE TITLE
Suppress "Debug adapter didn't respond" during `Session:initialize` if we received progress events

### ISSUE THREAD

**Issue by vogelsgesang** [mfussenegger/nvim-dap#477]
### Problem Statement

I am using lldb to debug some C++ programs. Loading the program and its symbol tables can take a while.
Therefore, I configured nvim-dap to display progress notifications, i.e. `event_progress{Start,Update,End}` through [this snippet](https://github.com/rcarriga/nvim-notify/issues/43#issuecomment-1066210141).

This works sufficiently well, but unfortunately still displays the "Debug adapter didn't respond.", although the debug adapter did in fact respond. The following video exemplifies the problem:

https://user-images.githubusercontent.com/6820896/158250257-eb865fa5-81dc-4f09-b75b-84fd0c1405aa.mov

Although lldb did report that it is currently loading symbol tables, nvim-dap claims that lldb didn't respond.

Judging from the source code of [Session::initialize](https://github.com/mfussenegger/nvim-dap/blob/bc7ac4864188079a6122032a75ea914c95461c1f/lua/dap/session.lua#L909), I don't see a way how I could suppress this message from an extension to nvim-dap.

### Ideas or possible solutions

I see two potential solutions:

1. Provide a way to tell nvim-dap to defer the "Debug adapter didn't respond." message by another 4 seconds. I would call this `Session:deferStartupTimeout` from my extension whenever I receive a progress notification.
2. Implement support for progress notifications directly inside nvim-dap

**Comment by mfussenegger** [comment]
You can set the timeout as part of the adapter definition via `initialize_timeout_sec`.

```lua
local myadapter = {
  type = 'executable',
  command = '...',
  options = {
    initialize_timeout_sec = 10,
  }
```

See https://github.com/mfussenegger/nvim-dap/commit/3b3027e0ca98775000e1ba727d8f292e821f9f03
