### ISSUE TITLE
Sidebar toggle doesn't toggle but continues to open new windows

### ISSUE THREAD

**Issue by ckipp01** [mfussenegger/nvim-dap#485]
### Debug adapter definition and debug configuration

I think this shouldn't actually need a configuration or anything since I can just mimic it by creating a mapping and then executing it. I'll include the mapping and steps down below.

### Steps to Reproduce

Creating a mapping that triggers the following `require("dap.ui.widgets").sidebar(require("dap.ui.widgets").scopes).toggle()`. Trigger this twice.

### Expected Result

I'd expect this to open the sidebar on the first trigger and then close the sidebar on the second trigger.

### Actual Result

It just continues to open new sidebars.

![2022-03-19 16 38 01](https://user-images.githubusercontent.com/13974112/159127805-991aa36a-0e75-46c7-bdbe-e6d6f2bd17ec.gif)

**Comment by mfussenegger** [comment]
The sidebar call creates a new `view` object on each call.  That's kind of expected as it allows you to create different kinds of bars or widget. 

You'd need to assign the result to a variable and then call toogle on that.

**Comment by ckipp01** [comment]
aaaah, ok, I totally misunderstood how this was supposed to work. Thanks.
