### ISSUE TITLE
Ability to have "skipFiles" like vscode "launch.json"

### ISSUE THREAD

**Issue by ziontee113** [mfussenegger/nvim-dap#503]
### Problem Statement

Hi, thank you for creating nvim-dap ❤️ 
I'm a total noob and I just got nvim-dap running for React & Javascript files.
My issue is that when try to debug a simple function, the debugger will go through what I'm trying to debug, then **_jump to a bunch of files that is related to NodeJS_**.

![wezterm-gui_AxBrqSo1ad](https://user-images.githubusercontent.com/102876811/161882218-4783982d-e4bf-46fa-ba60-254e0d64c1e9.png)

Is there a way to get rid (or hide) those "Module..." processes in the callstack?

Example in VSCode:
![VSCodium_DDYBeOYZ2j](https://user-images.githubusercontent.com/102876811/161882337-df25d57c-a5af-4691-b5ee-2f925063fa88.png)
![VSCodium_DlcfDwFJE9](https://user-images.githubusercontent.com/102876811/161882341-db38da38-8b92-4fa1-99b1-bb27a58bbd0f.png)

Having a "launch.json" file seems to have no effect on the matter.
[https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_attaching-to-nodejs]()

-----------

Edit: So I tried a few things to solve this, but the issue still persists:

1. I tried to put `skipFiles = { "<node_internals>/**/*.js" }` in my node2 configs.
2. I tried to create a .vscode/launch.json file, and put this config to it:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "javascript",
      "skipFiles": [
        "<node_internals>/**",
        "!**/node_modules/**",
        "**/$KNOWN_TOOLS$/**"
      ],
      "debug.javascript.terminalOptions": {
        "skipFiles": ["<node_internals>/**"]
      }
    }
  ]
}
```
I tried to call it with `require("dap.ext.vscode").load_launchjs()` but it still won't work.
Is there a way that I can solve this? Thank you.

**Comment by ziontee113** [comment]
Sorry I think I've found the solution at https://github.com/David-Kunz/vim/blob/b6dbdbe2f708e4145de63d824468bf893788c712/lua/debugHelper.lua

**Comment by mfussenegger** [comment]
nvim-dap passes the configuration 1:1 to the debug adapter, interpreting and acting on them is up to the debug adapter.
Where nvim-dap stops when stepping through code is also controlled by the debug adapter.

I added a change to mark frames differently if they've got a `subtle` presentation hint (https://github.com/mfussenegger/nvim-dap/pull/513). But it looks like you're using nvim-dap-ui anyways and afaik it already utilized the subtle hint.

I think that's the only thing I can do on the client side.

**Comment by ziontee113** [comment]
Yeah.. I just tried out Vimspector and found the same result. It's definietly the debug adapter's job. Maybe VScode has some magical sauce to it 🙄

Thank you so much for replying😄
