### ISSUE TITLE
Deprecated README on the Javascript Chrome documentation

### ISSUE THREAD

**Issue by stephaneeybert** [mfussenegger/nvim-dap#508]
### Steps to Reproduce

Reading the README file.

### Expected Result

A non deprecated resource.

### Actual Result

The https://github.com/Microsoft/vscode-chrome-debug Url links to a deprecated resource.

There is no such chromeDebug.js file in the new vscode-js-debug resource.

**Comment by mfussenegger** [comment]
vscode-js-debug is not DAP compliant,  see https://github.com/microsoft/vscode-js-debug/issues/969

There is afaik no non deprecated alternative. 

This issue tracker is mostly for potential client issues, not a wishlist for debug adapters.
