### ISSUE TITLE
DAP terminates plugin (host?) when breakpoint is triggered

### ISSUE THREAD

**Issue by mattiasbonte** [mfussenegger/nvim-dap#515]
### Debug adapter definition and debug configuration

**Adapter**
```
dap.adapters.node2 = { -- "https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#javascript"
	type = "executable",
	command = "node",
	args = { os.getenv("HOME") .. "/DEV/CONFIG/nvim/adapters/vscode-node-debug2/out/src/nodeDebug.js" },
}
```

**Config**
```
local dap = require("dap")

local function dockerNodeJS()
	print("⚙️  Attaching Node JS Docker Debugger ...")
	dap.run({
		type = "node2",
		restart = true,
		request = "attach",
		protocol = "inspector",
		localRoot = "${workspaceFolder}",
		remoteRoot = "./",
		cwd = vim.fn.getcwd(),
		skipFiles = {
			"<node_internals>/**/*.js",
			"**/node_modules/**",
		},
		runtimeArgs = {
			"--harmony",
		},
	})
end

return {
	dockerNodeJS = dockerNodeJS,
}
```

The config is called by hotkey. (which-key)
`["<leader>da23"] = { "<cmd>lua require'debug.configs'.dockerNodeJS()<CR>", "🩺 Docker Node JavaScript" },`

### Debug adapter version

1.43.0

### Steps to Reproduce

- Common JS - alpine docker container,
- Attach adapter (successfully attaches)
- Set breakpoint, run code, breakpoint gets triggered.
- Try to use plugin / plugin command / lsp (should not work anymore)

### Expected Result

Expect LSP & plugins to keep functioning after hitting a breakpoint.

### Actual Result

As soon as a breakpoint gets hit, most other settings/plugins stops working.

**Issues**
- Can't save changes to my file it pops the `E382: Cannot write, 'buftype' option is set` error in neovim.
- Can't use keybinds or commands to go to the next or previous buffer with bufferline. (unable to find buffer to move)
- The normally active LSP servers are also removed from the buffer.

Basically most of my plugins appear to have been halted / stopped.
The only solution for now is to reboot nvim after debugging, make changes, debug, reboot... repeat.

**Dap Logs**
- When running the DAP adapter for 10sec (with an empty log) i have a filled up log file (44k lines mostly containing the **WARN** message below)
- The bottom lines seems to be feedback from closing the debugging session.

```
[ WARN ] 2022-04-14T18:06:26Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:664 ]	"No event handler for "	{
  body = {
    reason = "new",
    source = {
      name = "VM1682",
      origin = "read-only content from Node.js",
      path = "<eval>/VM1682",
      sourceReference = 2519
    }
  },
  event = "loadedSource",
  seq = 1624,
  type = "event"
}
[ INFO ] 2022-04-14T18:06:35Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:448 ]	"Telemetry"	"target/notification/onPaused"
[ INFO ] 2022-04-14T18:06:35Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:448 ]	"Telemetry"	"target/notification/onScriptParsed"
[ INFO ] 2022-04-14T18:08:58Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:795 ]	"Closed all handles"
[ INFO ] 2022-04-14T18:08:58Z+0200 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:798 ]	"Process closed"	272220	false
```

I'm quite new to nvim, so if I should attach more logs please let me know..

**Comment by mfussenegger** [comment]
Can't reproduce this. I suspect it may be some weird interaction with other plugins that causes this. You could try to start out with a minimal configuration and then try to add things incrementally to see where things start to break.

**Comment by mattiasbonte** [comment]
Thanks for the feedback! I get back with my findings soon as I find the time to thoroughly test these suggestions.

**Comment by mattiasbonte** [comment]
So after testing on the [node-debug2 adapter](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#javascript=) with a minimal config (reducing plugins 1 by one) I ended up disabling all of my plugins and was not able to fix the issue. 

I did notice some strange behavior. 

- When a breakpoint is triggered, plugins stop working & LSP-servers are disconnected from the buffer.
- I enter the `:bn<CR>` command
- It moves me to the next buffer as usual and am able to utilize everything as I would normally.
- The breakpoint is also still activated but visually looks like it's inactivated.
- When I then `:lua require'dap'.step_over()<CR>` the next line is triggered and plugins + LSP servers get disconnected again.
- This repeats on each step.

And I've then tried with [another adapter](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#javascript-firefox=) and all appears to works fine.

**Comment by mfussenegger** [comment]
I suspect what happens is that there's some mismatch between your local source paths and the debug adapters source paths. Instead of re-using your buffers it is actually retrieving the sources ad-hoc from the debug adapter. That creates new scratch buffers. That would explain why the LSP server is not connected.

Maybe the `localRoot` and `remoteRoot` options are not correct. Or there are some other source map options you're missing.
You could try with a non-docker setup first, that's usually easier.

**Comment by mattiasbonte** [comment]
You are a DAP master Mathias! 

Your feedback made me doublecheck the `remoteRoot` input. 
It was `./` and had to be `/server` apparently. Which is indeed the root folder inside the actual docker container...

Thank you for your swift and accurate advice.
