### ISSUE TITLE
errors occur when lauching codelldb but debug can still work

### ISSUE THREAD

**Issue by thedawnboy** [mfussenegger/nvim-dap#525]
### Debug adapter definition and debug configuration
```
-- 💀 Adjust the path to your executable
local cmd = "/home/wx/Downloads/cppdbg/extension/adapter/codelldb"

local dap = require("dap")

dap.adapters.codelldb = function(on_adapter)
    -- This asks the system for a free port
    local tcp = vim.loop.new_tcp()
    tcp:bind("127.0.0.1", 0)
    local port = tcp:getsockname().port
    tcp:shutdown()
    tcp:close()

    -- Start codelldb with the port
    local stdout = vim.loop.new_pipe(false)
    local stderr = vim.loop.new_pipe(false)
    local opts = {
        stdio = {nil, stdout, stderr},
        args = {"--port", tostring(port)}
    }
    local handle
    local pid_or_err
    handle, pid_or_err =
        vim.loop.spawn(
        cmd,
        opts,
        function(code)
            stdout:close()
            stderr:close()
            handle:close()
            if code ~= 0 then
                print("codelldb exited with code", code)
            end
        end
    )
    if not handle then
        vim.notify("Error running codelldb: " .. tostring(pid_or_err), vim.log.levels.ERROR)
        stdout:close()
        stderr:close()
        return
    end
    vim.notify("codelldb started. pid=" .. pid_or_err)
    stderr:read_start(
        function(err, chunk)
            assert(not err, err)
            if chunk then
                vim.schedule(
                    function()
                        require("dap.repl").append(chunk)
                    end
                )
            end
        end
    )
    local adapter = {
        type = "server",
        host = "127.0.0.1",
        port = port
    }
    -- 💀
    -- Wait for codelldb to get ready and start listening before telling nvim-dap to connect
    -- If you get connect errors, try to increase 500 to a higher value, or check the stderr (Open the REPL)
    vim.defer_fn(
        function()
            on_adapter(adapter)
        end,
        800
    )
end

--dap.configurations.cpp = {
--    {
--        name = "Launch file",
--        type = "codelldb",
--        request = "launch",
--        program = function()
--            return vim.fn.input("Path to excutable: ", vim.fn.finddir("bin", ".;") "/", "file")
--        end,
--        stopOnEntry = false
--    }
--}

dap.configurations.cpp = {
    {
        name = "Launch file",
        type = "codelldb",
        request = "launch",
        program = function()
            return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
        end,
        cwd = "${workspaceFolder}",
        stopOnEntry = true
    }
}

dap.configurations.c = dap.configurations.cpp
dap.configurations.rust = dap.configurations.cpp

```

### Steps to Reproduce

1.c file looks like this
```
int main()
{
    int n;
    scanf("%d", &n);

    for (int i = 0; i < n; i++)
        {
            printf("%d\n", i);
        }

    return 0;
}
```

2.I made a breakpoint at the line of `printf()` and error occurs:

> Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:273: attempt to index local 'frame' (a number value)
stack traceback:
        ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:273: in function 'jump_to_frame'
        ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:434: in function 'callback'
        ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:642: in function <...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:638>
Press ENTER or type command to continue

after pressing `<ENTER>`

> Error executing vim.schedule lua callback: ...vim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/state.lua:153: attempt to index field 'current_frame' (a number v
alue)
stack traceback:
        ...vim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/state.lua:153: in function '_emit_refreshed'
        ...vim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/state.lua:103: in function 'c'
        ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:644: in function <...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:638>
Press ENTER or type command to continue

So I run :lua require"dap".set_log_level("DEBUG") in the neovim and the following is the content in the dap.log

> [ DEBUG ] 2022-04-18T09:17:22Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:721 ]	"Connecting to debug adapter"	{
  host = "127.0.0.1",
  port = 46297,
  type = "server"
}
[ DEBUG ] 2022-04-18T09:17:22Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:977 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "zh_CN.UTF-8",
    pathFormat = "path",
    supportsRunInTerminalRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    exceptionBreakpointFilters = { {
        default = true,
        filter = "cpp_throw",
        label = "C++: on throw"
      }, {
        default = false,
        filter = "cpp_catch",
        label = "C++: on catch"
      } },
    supportTerminateDebuggee = true,
    supportsCancelRequest = true,
    supportsCompletionsRequest = true,
    supportsConditionalBreakpoints = true,
    supportsConfigurationDoneRequest = true,
    supportsDataBreakpoints = true,
    supportsDelayedStackTraceLoading = true,
    supportsEvaluateForHovers = true,
    supportsFunctionBreakpoints = true,
    supportsGotoTargetsRequest = true,
    supportsHitConditionalBreakpoints = true,
    supportsLogPoints = true,
    supportsReadMemoryRequest = true,
    supportsRestartFrame = true,
    supportsSetVariable = true,
    supportsWriteMemoryRequest = true
  },
  command = "initialize",
  request_seq = 0,
  seq = 1,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:977 ]	"request"	{
  arguments = {
    cwd = "/home/wx/Data/code/c/cmake",
    name = "Launch file",
    program = "/home/wx/Data/code/c/cmake/bin/main",
    request = "launch",
    stopOnEntry = true,
    type = "codelldb"
  },
  command = "launch",
  seq = 1,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    output = "Console is in 'commands' mode, prefix expressions with '?'.\n"
  },
  event = "output",
  seq = 2,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  event = "initialized",
  seq = 3,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    module = {
      addressRange = "FFFFFFFFFFFFFFFF",
      id = "FFFFFFFFFFFFFFFF",
      name = "main",
      path = "/home/wx/Data/code/c/cmake/bin/main",
      symbolFilePath = "/home/wx/Data/code/c/cmake/bin/main",
      symbolStatus = "Symbols loaded."
    },
    reason = "new"
  },
  event = "module",
  seq = 4,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  arguments = {
    args = { "/home/wx/Downloads/cppdbg/extension/adapter/codelldb", "terminal-agent", "--connect=45787" },
    cwd = "",
    kind = "integrated",
    title = "Launch file"
  },
  command = "runInTerminal",
  seq = 5,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:103 ]	"run_in_terminal"	{
  args = { "/home/wx/Downloads/cppdbg/extension/adapter/codelldb", "terminal-agent", "--connect=45787" },
  cwd = "",
  kind = "integrated",
  title = "Launch file"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:994 ]	"response"	{
  body = {
    processId = 131183
  },
  command = "runInTerminal",
  request_seq = 5,
  seq = 2,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:977 ]	"request"	{
  arguments = {
    breakpoints = { {
        line = 10
      } },
    lines = { 10 },
    source = {
      name = "main.c",
      path = "/home/wx/Data/code/c/cmake/main.c"
    },
    sourceModified = false
  },
  command = "setBreakpoints",
  seq = 3,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    breakpoints = { {
        id = 1,
        line = 10,
        message = "Resolved locations: 0",
        verified = true
      } }
  },
  command = "setBreakpoints",
  request_seq = 3,
  seq = 6,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:977 ]	"request"	{
  arguments = {
    filters = { "cpp_throw" }
  },
  command = "setExceptionBreakpoints",
  seq = 4,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  command = "setExceptionBreakpoints",
  request_seq = 4,
  seq = 7,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:977 ]	"request"	{
  command = "configurationDone",
  seq = 5,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    output = "Launching: /home/wx/Data/code/c/cmake/bin/main\n"
  },
  event = "output",
  seq = 8,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    output = "Launched process 131191\n"
  },
  event = "output",
  seq = 9,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    category = "stderr",
    output = "Stop reason: signal SIGSTOP\n"
  },
  event = "output",
  seq = 10,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    allThreadsStopped = true,
    reason = "signal",
    text = "signal SIGSTOP",
    threadId = 131191
  },
  event = "stopped",
  seq = 11,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  command = "launch",
  request_seq = 1,
  seq = 12,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    module = {
      addressRange = "7FFFF7FC6000",
      id = "7FFFF7FC6000",
      name = "ld-linux-x86-64.so.2",
      path = "/usr/lib/ld-linux-x86-64.so.2",
      symbolFilePath = "/usr/lib/ld-linux-x86-64.so.2",
      symbolStatus = "Symbols loaded."
    },
    reason = "new"
  },
  event = "module",
  seq = 13,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  command = "configurationDone",
  request_seq = 5,
  seq = 14,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    module = {
      addressRange = "7FFFF7FC4000",
      id = "7FFFF7FC4000",
      name = "[vdso]",
      path = "[vdso]",
      symbolStatus = "Symbols not found"
    },
    reason = "new"
  },
  event = "module",
  seq = 15,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    breakpoint = {
      id = 1,
      line = 10,
      message = "Resolved locations: 1",
      verified = true
    },
    reason = "changed"
  },
  event = "breakpoint",
  seq = 16,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    module = {
      addressRange = "555555554000",
      id = "555555554000",
      name = "main",
      path = "/home/wx/Data/code/c/cmake/bin/main",
      symbolFilePath = "/home/wx/Data/code/c/cmake/bin/main",
      symbolStatus = "Symbols loaded."
    },
    reason = "new"
  },
  event = "module",
  seq = 17,
  type = "event"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:977 ]	"request"	{
  command = "threads",
  seq = 6,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    threads = { {
        id = 131191,
        name = '1: tid=131191 "main"'
      } }
  },
  command = "threads",
  request_seq = 6,
  seq = 18,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:977 ]	"request"	{
  arguments = {
    threadId = 131191
  },
  command = "stackTrace",
  seq = 7,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:977 ]	"request"	{
  arguments = {
    threadId = 131191
  },
  command = "stackTrace",
  seq = 8,
  type = "request"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    stackFrames = { {
        column = 0,
        id = 1001,
        line = 3,
        name = "_start",
        presentationHint = "subtle",
        source = {
          name = "@_start",
          sourceReference = 1000
        }
      } },
    totalFrames = 1
  },
  command = "stackTrace",
  request_seq = 7,
  seq = 19,
  success = true,
  type = "response"
}
[ DEBUG ] 2022-04-18T09:17:23Z+0800 ] ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:626 ]	{
  body = {
    stackFrames = { {
        column = 0,
        id = 1002,
        line = 3,
        name = "_start",
        presentationHint = "subtle",
        source = {
          name = "@_start",
          sourceReference = 1000
        }
      } },
    totalFrames = 1
  },
  command = "stackTrace",
  request_seq = 8,
  seq = 20,
  success = true,
  type = "response"
}

### Expected Result

no errors occurs when launching codelldb

### Actual Result

> Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:273: attempt to index local 'frame' (a number value)
stack traceback:
        ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:273: in function 'jump_to_frame'
        ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:434: in function 'callback'
        ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:642: in function <...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:638>
Press ENTER or type command to continue

after pressing `<ENTER>`

> Error executing vim.schedule lua callback: ...vim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/state.lua:153: attempt to index field 'current_frame' (a number v
alue)
stack traceback:
        ...vim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/state.lua:153: in function '_emit_refreshed'
        ...vim/site/pack/packer/opt/nvim-dap-ui/lua/dapui/state.lua:103: in function 'c'
        ...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:644: in function <...e/nvim/site/pack/packer/opt/nvim-dap/lua/dap/session.lua:638>
Press ENTER or type command to continue

**Comment by thedawnboy** [comment]
by the way , I am using neovim 0.7.0 in archlinux

**Comment by mfussenegger** [comment]
Thanks for the report - should be fixed with https://github.com/mfussenegger/nvim-dap/pull/527

**Comment by thedawnboy** [comment]
Thanks, works well now
