### ISSUE TITLE
DAP setup for Ruby

### ISSUE THREAD

**Issue by sunzoje** [mfussenegger/nvim-dap#54]
I'm trying to setup DAP for ruby/rails using [Readapt](https://github.com/castwide/readapt) .
I'm referencing the configuration of [vscode-ruby-debug](https://github.com/castwide/vscode-ruby-debug).
I've DAP setup as follow:
```
local dap = require('dap')

dap.adapters.ruby = {
	type = 'executable';
	command = 'bundle';
	args = {'exec', 'readapt', 'stdio'};
}

dap.configurations.ruby = {
	type = 'ruby';
	request = 'launch';
	name = 'Rails';
	program = 'bundle';
	programArgs = {'exec', 'rails', 's'};
	useBundler = true;
}
```
I got message: `No configuration found for ruby`.
What's the problem with the aforementioned setup?

**Comment by mfussenegger** [comment]
`dap.configurations.ruby` must be a list of configurations, like this:


```
dap.configurations.ruby = {
  {
    type = 'ruby';
    request = 'launch';
    name = 'Rails';
    program = 'bundle';
    programArgs = {'exec', 'rails', 's'};
    useBundler = true;
  },
}
```

**Comment by sunzoje** [comment]
Thanks. That did the trick.
