### ISSUE TITLE
Python Debugging Output Buffer not closed on terminate

### ISSUE THREAD

**Issue by justusschock** [mfussenegger/nvim-dap#542]
### Debug adapter definition and debug configuration

Installed with packer:
```lua
  use { 'mfussenegger/nvim-dap' }
  use { 'rcarriga/nvim-dap-ui' }
  use { 'theHamsta/nvim-dap-virtual-text' }
  use { 'mfussenegger/nvim-dap-python' }
```

Configured like this:

```lua
vim.fn.sign_define('DapBreakpoint', {text='', texthl='error', linehl='', numhl=''})

local dap, dapui, dapvt = require("dap"), require("dapui")
dap.listeners.after.event_initialized["dapui_config"] = function()
    dapui.open()
  end
  dap.listeners.before.event_terminated["dapui_config"] = function()
    dapui.close()
  end
  dap.listeners.before.event_exited["dapui_config"] = function()
    dapui.close()
  end

-- ADAPTERS
require('dap-python').setup('python')
require('dap-python').test_runner = 'pytest'

```

Debugpy installed with pip (version 1.6.0)

### Debug adapter version

1.6.0

### Steps to Reproduce

1. Open A debugger session (just launching a file that prints a lot)
2. terminating the session

### Expected Result

I would expect the buffer containing the program output to be closed as well after terminating the debugging session (as it is part of that session).

### Actual Result

The output buffer is still open.

**Comment by mfussenegger** [comment]
You probably need to add `dap.listeners.before.disconnect["dapui_config"] = function() dapui.close() end`
See https://github.com/mfussenegger/nvim-dap/pull/481 for more context.

**Comment by justusschock** [comment]
Thanks for the suggestion, however that unfortunately does not solve the issue.
The ui also closes correctly, just the output-buffer (containing all python warnings and prints) does not close. 

If a video would help to understand what I am trying to explain, I'd be happy to provide one :)

**Comment by mfussenegger** [comment]
Oh I think I misunderstood.  You're referring to the integrated terminal?  

One option would be to switch to console instead. Other than that there is currently no easy way.  You'd have to write some logic to find the terminal buffer and close it or something like that. 

But there's https://github.com/mfussenegger/nvim-dap/pull/535 which would allow nvim-dap-ui to gain more control over the integrated terminal window and buffer.

**Comment by justusschock** [comment]
Thanks. Yeah probably the integrated terminal is what I am looking for (just to be sure:  not the REPL as this one closes automatically).
Thanks for pointing me to that PR :)
