### ISSUE TITLE
Support for user input in .vscode/launch.json

### ISSUE THREAD

**Issue by molsenhiq** [mfussenegger/nvim-dap#551]
### Problem Statement

Hi, would it be possible to add support for user input variables when loading configurations specified in a .vscode/launch.json file?
See: https://code.visualstudio.com/updates/v1_30#_improved-user-input-variables-for-task-and-debug-configurations

**Example:**
```
{
  "tasks": [
    {
      "label": "Echo input",
      "type": "shell",
      "command": "echo ${input:echoPrompt}"
    }
  ],
  "inputs": [
    {
      "id": "echoPrompt",
      "description": "Please enter a value",
      "default": "default echo text",
      "type": "promptString"
    }
  ]
}
```
**Current behavior:**
When running debug tasks loaded from .vscode/launch.json (with `require("dap.ext.vscode").load_launchjs()`).
User input variables are ignored/not supported.

**Expected behavior:**
Vim asks for user input

**Comment by mfussenegger** [comment]
Added support for this with https://github.com/mfussenegger/nvim-dap/pull/662

Please let me know if there are any issues with the implementation
