### ISSUE TITLE
cursor position outside buffer for c++ lldb-vscode

### ISSUE THREAD

**Issue by ron0studios** [mfussenegger/nvim-dap#564]
### Debug adapter definition and debug configuration

**local dap = require('dap')
dap.adapters.lldb = {
  type = 'executable',
  command = '/usr/bin/lldb-vscode', -- adjust as needed, must be absolute path
  name = 'lldb'
}

local dap = require('dap')
dap.configurations.cpp = {
  {
    name = 'Launch',
    type = 'lldb',
    request = 'launch',
    program = function()
      return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},
    -- 💀
    -- if you change `runInTerminal` to true, you might need to change the yama/ptrace_scope setting:
    --
    --    echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
    --
    -- Otherwise you might get the following error:
    --
    --    Error on launch: Failed to attach to the target process
    --
    -- But you should be aware of the implications:
    -- https://www.kernel.org/doc/html/latest/admin-guide/LSM/Yama.html
    -- runInTerminal = false,
  },
}**

### Steps to Reproduce

create a simple c++ program (with an error, for me I tested it with a arithmetic divide-by-zero error)
use the DAP config and use continue()
error 

### Expected Result

it should debug?? I don't know what the config does, I copy-pasted it from the docs 😆 

### Actual Result

![image](https://user-images.githubusercontent.com/47331292/170933397-8f7903ad-c7d5-4327-ab4d-b242df21eaea.png)

**Comment by ron0studios** [comment]
> Are you sure your executable is up2date? The error you're seeing occurs if the debug adapter reports a stopped event in a line/column not present in the file on disk.

that was the issue sorry

**Comment by mfussenegger** [comment]
I improved the error message with https://github.com/mfussenegger/nvim-dap/pull/572 to give some hints what might be wrong.
