### ISSUE TITLE
Nvim crashes when application prints a lot of messages to the terminal

### ISSUE THREAD

**Issue by Agsayan** [mfussenegger/nvim-dap#589]
### Debug adapter definition and debug configuration

Configured the debugger via the nvim-jdtls and nvim-dap-python plugins.

### Steps to Reproduce

1. Printing a lot messages to the Terminal.
For example in java with:
```java
    for (int i = 0; i < 200000; i++) {
      System.out.println("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
    }

``` 
2. while it is printing set another breakpoint or open a new window.

### Expected Result

Sets breakpoint or open another window

### Actual Result

Crashes with the following output:
segmentation fault ( core dumped ) vim

**Comment by mfussenegger** [comment]
This looks like a neovim bug. I created an issue: https://github.com/neovim/neovim/issues/19075

**Comment by Agsayan** [comment]
Thanks, thanks it works with #592
