### ISSUE TITLE
Python adapter crashes Neovim

### ISSUE THREAD

**Issue by HiPhish** [mfussenegger/nvim-dap#59]
Hello,

I have tried to follow the examples given in the manual and I get very weird behaviour with the `debugpy` adapter.

## My configuration

```lua
dap.adapters.python = {
	type = 'executable',
	command = '/usr/bin/python3',
	args = {'-m', 'debugpy.adapter'}
}

dap.configurations.python = {
	{
		type = 'python',
		request = 'launch',
		name = 'Launch file',
		program = "${file}",
		pythonPath = function(adapter)
			return '/usr/bin/python3'
		end,
	}
}
```

## The code

Here is the Python script I want to debug

```python
#!/bin/env python3

def test_fun(x, y):
    print('This is a test function')
    print('The value of x is ' + str(x))
    print('The value of y is ' + str(y))
    sum = x + y
    print('The sum is ' + str(sum))
    print('bye')

test_fun(2, 3)
```

Whether the file is executable or not does not matter.

## What goes wrong

I set a break point on line 6, open a debug REPL, then start the debugger with `lua require"dap".continue()`. The debugger stops on the break point and the REPL shows the printed lines. Everything good so far.

However, once I press any key, even if it is just to move the cursor, Neovim gets suspended as if I had pressed `CTRL-Z`. If I try resuming it with `fg` everything is totally borked for lack of a better word, and I can only `CTRL-C` to quit.

I have not been able to test other adapters, I wanted to get this one working first because it's the easiest one to set up. While I'm at it, what are the keys to use in the `dap.configurations.<whatever>` table? Do they depend on the particular adapter?

**Comment by theHamsta** [comment]
Hi! I had the same issue. It only happens with debugpy when it's outputting the code in the integrated terminal (the dap REPL). Apparently the normal buffer is not protected against some dangerous escape code that debugpy when you're running it in a terminal.you can use a GUI to run nvim- or you select `internalConsole` which will run the output in a terminal buffer which seems to be save.

```
internalConsole",
  --"integratedTerminal",
  --"externalTerminal",
  dap.configurations.python = {
    {
      type = "python",
      request = "attach",
      name = "Launch file",
      program = "${file}",
      console = "internalConsole"
      --pythonPath = function()
      --return "/usr/bin/python3"
      --end
    },
    ```

**Comment by HiPhish** [comment]
But doesn't `request = "attach"` mean I somehow need to first launch the program manually and have the debugger hook into it? In the above example the script terminates immediately, there is no application loop.

To be honest, I don't really care about Python that much (although it would be very nice to have it). I mainly want to use the [Kotlin Debug Adapter](https://github.com/fwcd/kotlin-debug-adapter), but I need to have at least one adapter working first before I can try integrating something new. The Kotlin adapter is a bit more complicated because according to the [instructions](https://github.com/fwcd/kotlin-debug-adapter/blob/master/EDITORS.md) I need to pass it the name of the main class when starting up.

Debugging is the last instance where IDEs still have an advantage over text editors. If this works I can finally kick IntelliJ into the trash for good.

**Comment by theHamsta** [comment]
Sorry, the relevant line in the snippet is only `console = "internalConsole"`. It has nothing to do whether you `attach` or not..

The issue shouldn't happen with other debug adapter (at least I have observed it only with debugpy. I guess debugpy prints a esape character onto a regular buffer which causes nvim to render the window incorrectly. The workaround is to let debugpy print the program output into a terminal buffer which understands escape sequences. At least that's my guess what's happening.

**Comment by HiPhish** [comment]
I am getting the same problem still:

```lua
dap.configurations.python = {
	{
		type = 'python',
		request = 'launch',
		name = 'Launch file',
		program = "${file}",
		console = 'internalConsole',
	}
}
```

> llvm-vscode and debugpy are easiest to set up.

I assume you meant lldb-vscode? I'll give it a try.

**Comment by theHamsta** [comment]
Yes, lldb-vscode.

**Comment by HiPhish** [comment]
> Be careful that it is not the same as `vscode-lldb`. lldb-vscode is C++ and part of the LLVM project and the other one is a vscode node extension.

Thanks, I figured. Only one more question hopefully: where can I find the documentation? There is no man page and no `--help` text, so I have no idea what to set for the configuration table.

**Comment by theHamsta** [comment]
There should be instructions in out wiki: https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation

**Comment by HiPhish** [comment]
That's for the adapter only (`dap.adapters`), but not for the configuration (`dap.configurations`)

**Comment by theHamsta** [comment]
It's the same as for vscode-cpptools as mentioned in the text. Could you add the config for Kotlin when you managed to start it.

**Comment by HiPhish** [comment]
> It's the same as for vscode-cpptools as mentioned in the text

OK, I'm being stupid now, thank you.

> Could you add the config for Kotlin when you managed to start it?

Of course.

**Comment by theHamsta** [comment]
> OK, I'm being stupid now, thank you.

No, maybe you can just copy it to be more clear about it? I just pasted all the information that I believed to have in the order that I got it.

**Comment by mfussenegger** [comment]
Are you using the latest neovim builds? I cannot reproduce the behavior you described. It works as expected for me


>  mainly want to use the Kotlin Debug Adapter, but I need to have at least one adapter working first before I can try integrating something new. The Kotlin adapter is a bit more complicated because according to the instructions I need to pass it the name of the main class when starting up.

It's similar for Java, there you also need to have classpath and module path in addition to the classname and projectName. 
For java/eclipse.jdt.ls [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) uses the `enrich_config` functionality of an `adapter` definition to automatically enrich configuration definitions at runtime with missing information. This way the configuration can be de-coupled from classpath changes.

Here's the enrich implementation:


https://github.com/mfussenegger/nvim-jdtls/blob/e665b6157105f8003377284795dbfc6c89cd7461/lua/jdtls.lua#L645-L689


The adapter is defined as:

```lua
dap.adapters.java = start_debug_adapter
```

With the following implementation:

https://github.com/mfussenegger/nvim-jdtls/blob/e665b6157105f8003377284795dbfc6c89cd7461/lua/jdtls.lua#L692-L703


Maybe there's a similar way to do that for Kotlin.

**Comment by HiPhish** [comment]
My biggest problem is that I have no idea what I'm doing here. I understand that I need an adapter configuration, which is a table with the mandatory key `type`, and either mandatory keys `command` and `args` (for `type = 'executable'`), or mandatory key `port` (for `type = 'server'`). But then were are those other keys coming from? Are they part of the protocol? Or did people read the source code of the adapters to find out? And the same goes for the debuggee configuration.

> Are you using the latest neovim builds? I cannot reproduce the behavior you described. It works as expected for me

Yes, I downloaded the official AppImage yesterday.

**Comment by theHamsta** [comment]
No, they are not standardize. But the README say that the following parameters are required. The source code confirms that.

```
class LaunchConfiguration(
	val classpath: Set<Path>,
	val mainClass: String,
	val projectRoot: Path
)
```
There are currently a lot of SEGFAULTS on buffer kill and I am also experiencing them sometimes when a process ends

**Comment by mfussenegger** [comment]
I guess a adapter definition like the following should work:

```lua
dap.adapters.kotlin = {
  type = 'executable';
  command = os.getenv('HOME') .. '/dev/fwcd/kotlin-debug-adapter/adapter/build/install/adapter/bin/kotlin-debug-adapter';
}
```

Where the `command` path is adapted.

For the configuration you could look at the `launch.json` files, like this one https://github.com/fwcd/kotlin-debug-adapter/blob/c01e2f950f77e6e639063099ae1754e109bc1875/.vscode/launch.json#L11-L17 


I tried to use the adapter, but when I start debugging I get some errors:

```
[ERROR] server    Internal error: java.lang.reflect.InvocationTargetException
[ERROR] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[ERROR] 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
[ERROR] 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
[ERROR] 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
```

Looks like a kotlin-debug-adapter issue to me.


Regarding the original python adapter crash issue:

Which terminal are you using?
Your example script isn't producing any weird escape sequences, so I can't image why it locks up.

Could you maybe share a gif or so that shows how it acts up?
Could any other plugins be interfering?

**Comment by HiPhish** [comment]
I'm sorry, looks like there is a misunderstanding going on here. It is the Python debugger that I have trouble with (as outlined in the first post). The Kotlin debugger is what I want to get running eventually, but I just mentioned that in passing. I have not actually tried it yet, because I first want to get one of the debuggers known to work running. Otherwise I might open issues here when the fault is actually with the adapter itself, not the client. I'm going to try the lldb-vscode adapter next.

So what about this issue? The topic is the Python debugger, should I leave it open since the issue still remains?

**Comment by mfussenegger** [comment]
> So what about this issue? The topic is the Python debugger, should I leave it open since the issue still remains?

Yep, if you could provide some more information on your environment. Terminal/version, operating system and so on.

I can't reproduce the issue so currently there is not much I could do about it :(

**Comment by LarsHaalck** [comment]
I have/had the same problem. I'm using Arch Linux with kernel 5.8.14, NVIM v0.5.0-812-gd17e50879 and it crashes in the same way. I tried alacritty 0.5.0 and termite v15 with the same configurations as @HiPhish. I also tried the cpp configurations and it works as expected. I'm using Python 3.8.5 with debugpy 1.1.0 installed in a conda virtual environment with the path set in the adapters config:

```lua
local dap = require 'dap'
dap.adapters.python = {
  type = 'executable';
  command = '/home/user/.conda/envs/foo/bin/python';
  args = { '-m', 'debugpy.adapter' };
}

dap.configurations.python = {
  {
    type = 'python';
    request = 'launch';
    name = "Launch file";
    program = "${file}";
    console = "internalConsole"
  },
}
```
When I set `console` to `integratedTerminal` it works fine.

**Comment by theHamsta** [comment]
Is there a way to filter out certain escape codes before printing them to the repl, because I think that's the issue (it does not occur with `integratedTerminal` or with GUI nvim).

**Comment by mfussenegger** [comment]
@LarsHaalck thank you for the additional information. I can also reproduce it now. I had an older debugpy version (1.0 something), with that I couldn't reproduce the issue, but now with 1.1 I have the problem as well. Will take a closer look.

**Comment by mfussenegger** [comment]
@theHamsta it's not related to printing to the repl at all, also happens when nothing is printed or when the repl call is commented out.

Looks like this commit introduced the issue https://github.com/microsoft/debugpy/commit/5087603ea3db9596960d7477633ba189debda1c6

**Comment by theHamsta** [comment]
@mfussenegger I had the assumption that it is the initial "terminal clear" escape sequence that is fired on start of the debugger. Maybe I have a different issue but nvim and the debugger continued to run normally just the terminal was partially empty.

**Comment by mfussenegger** [comment]
@LarsHaalck @HiPhish Could you try with https://github.com/mfussenegger/nvim-dap/pull/68 and see if it fixes the problem for you?

**Comment by HiPhish** [comment]
I will try to get around to it during the weekend.

**Comment by LarsHaalck** [comment]
#68 fixes it for me. Nice job for fixing it so quickly and thank you.
