### ISSUE TITLE
Unexpected notifications from "DAP" for every step

### ISSUE THREAD

**Issue by dhruvmanila** [mfussenegger/nvim-dap#590]
### Debug adapter definition and debug configuration

This does not seem to be a problem of any adapter.

### Debug adapter version

Not a problem for any adapter.

### Steps to Reproduce

Using the below `minimal.lua` file, first open the editor at commit https://github.com/mfussenegger/nvim-dap/commit/688cb52d8bfbb237531056b24d727f33ff4bedfa where the notifications started appearing and then at the parent commit https://github.com/mfussenegger/nvim-dap/commit/9c783d8d2a6f776ee817281f0bf07d356524cc1f where the notifications are not coming.

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local packer_install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',

      -- Add plugins to test...
      {
        'mfussenegger/nvim-dap',
        -- commit from which the notifications started appearing
        commit = '688cb52d8bfbb237531056b24d727f33ff4bedfa',

        -- this is the parent commit of the one mentioned above where the
        -- notifications are not coming
        -- commit = '9c783d8d2a6f776ee817281f0bf07d356524cc1f',
      },
      'mfussenegger/nvim-dap-python',
    },
    config = {
      package_root = package_root,
      compile_path = packer_install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end

_G.load_config = function()
  -- Add the necessary `init.lua` settings which could include the setup
  -- functions for the plugins...
  vim.g.mapleader = ' '

  local dap = require 'dap'
  local dap_python = require 'dap-python'

  vim.keymap.set('n', '<F5>', dap.continue)
  vim.keymap.set('n', '<F10>', dap.step_over)
  vim.keymap.set('n', '<F11>', dap.step_into)
  vim.keymap.set('n', '<F12>', dap.step_out)
  vim.keymap.set('n', '<leader>db', dap.toggle_breakpoint)
  vim.keymap.set('n', '<leader>ds', dap.terminate)

  -- set this path as per your system
  dap_python.setup(vim.loop.os_homedir() .. '/.neovim/.venv/bin/python')
  dap_python.test_runner = 'pytest'
end

if vim.fn.isdirectory(packer_install_path) == 0 then
  print 'Installing plugins and dependencies...'
  vim.fn.system {
    'git',
    'clone',
    '--depth=1',
    'https://github.com/wbthomason/packer.nvim',
    packer_install_path,
  }
end

load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

1. Open any `python` file
2. Set a breakpoint using <kbd><space>db</kbd>
3. Notice there is `Reason: breakpoint` being printed at the bottom
4. Each step will print the reason

### Expected Result

There should be no message printed for each step taken.

### Actual Result

With each step, the message of the format `Reason: <reason>` is being printed.

**Comment by Shatur** [comment]
Noticed the same here. I don't think it's a bug, but it's a very annoying behavior. It would be great to remove stepping notifications, because half of my screen looks like this:

![изображение](https://user-images.githubusercontent.com/22453358/175376267-ff313e4e-59b0-46a6-98f1-fbdfd416ad2e.png)

**Comment by bew** [comment]
It would be really helpful to be able to notify, but reuse a previous notification window instead of making a new one..

Maybe passing some id information to `vim.notify` could be implemented by notification implementations, but I'm not sure who should decide the name of that option, and scope of that config & operation..

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/nvim-dap/pull/591 removed the notify call
