### ISSUE TITLE
Terminal split is not re-created if closed once

### ISSUE THREAD

**Issue by David-Kunz** [mfussenegger/nvim-dap#603]
### Debug adapter definition and debug configuration

```lua
dap.adapters.node2 = {
  type = 'executable',
  command = 'node',
  args = {os.getenv('HOME') .. '/apps/node/out/src/nodeDebug.js'},
}
```

### Steps to Reproduce

1. Execute `require'dap'.run(config)` with any configuration ✔️
2. Observe that a new split is created where you can see the terminal output ✔️
3. Close the split ✔️
4. Finish the debugging session ✔️
5. Execute `require'dap'.run(config)` with any configuration again ✔️
6. Observe that no split is being created (even though the debug session runs) 🛑

### Expected Result

In step 6., it is expected that a new split is being created. This was the behaviour in previous versions.

### Actual Result

In step 6., no split is being created. Therefore one doesn't see the terminal output anymore.

**Comment by mfussenegger** [comment]
Is it possible that you're only hiding the buffer and not deleting it? 

That it doesn't create a new buffer and window if the buffer still exists was an intentional change to enable nvim-dap-ui to have more control over the terminal window

**Comment by David-Kunz** [comment]
> Is it possible that you're only hiding the buffer and not deleting it?

Correct, in the window I execute `:q` which leaves the buffer in the `:buffers` list.

> That it doesn't create a new buffer and window if the buffer still exists was an intentional change to enable nvim-dap-ui to have more control over the terminal window

That's unfortunate because it degrades the user experience when `nvim-dap-ui` is not used (the `[dap-terminal]` buffer stays hidden in a new debugging session).
Is there a possibility to add an option to force the creation of a new split when starting another debug session?

**Comment by David-Kunz** [comment]
> I think it should be possible to setup a BufHidden autocmd that deletes the buffer

Yes, that would solve the problem for me.

**Comment by David-Kunz** [comment]
The following seems to work:

```lua
vim.api.nvim_create_autocmd('BufHidden',  {
    pattern  = '[dap-terminal]*',
    callback = function(arg)
      vim.schedule(function() vim.api.nvim_buf_delete(arg.buf, { force = true }) end)
    end
})
```

Thanks for the tip!

**Comment by David-Kunz** [comment]
So to sum up:
We need to make sure that the buffer is deleted _only_ when the session ended.

**Comment by mfussenegger** [comment]
> Unfortunately I then get the following error message when the session is over:
> 
> > lua/dap/session.lua:266: E900: Invalid channel id
> > in function nvim_chan_send
> 
> Which probably makes sense since the process is killed.

I think nvim-dap should handle that more gracefully.  That a user deletes the buffer (and kills the process with it) is always possible.  I'll create a PR a bit later

**Comment by David-Kunz** [comment]
Thanks a lot @mfussenegger , I can confirm that #604 fixes the error message!

For curios readers: The following code allows you to close the `[dap-terminal]` split window and makes sure that a new `[dap-terminal]` window is created when a new debugging session is started:

```lua
vim.api.nvim_create_autocmd('BufHidden',  {
    pattern  = '[dap-terminal]*',
    callback = function(arg)
      vim.schedule(function() vim.api.nvim_buf_delete(arg.buf, { force = true }) end)
    end
})
```
