### ISSUE TITLE
goto_() implementation differs from vscode

### ISSUE THREAD

**Issue by Dosx001** [mfussenegger/nvim-dap#609]
### Debug adapter definition and debug configuration

```lua
local dap = require("dap")

dap.adapters.python = {
	type = "executable",
	command = "python",
	args = { "-m", "debugpy.adapter" },
}

dap.configurations.python = {
	{
		type = "python",
		request = "launch",
		name = "Launch file",
		program = "${file}",
		pythonPath = function()
			local cwd = vim.fn.getcwd()
			if vim.fn.executable(cwd .. "/venv/bin/python") == 1 then
				return cwd .. "/venv/bin/python"
			elseif vim.fn.executable(cwd .. "/.venv/bin/python") == 1 then
				return cwd .. "/.venv/bin/python"
			else
				return "/usr/bin/python"
			end
		end,
	},
}
```

### Debug adapter version

python-debugpy 1.6.2-1

### Steps to Reproduce

```python
def main():
    print("hi")
    nums = []
    for i in range(10):
        nums.append(i)
    return nums


if __name__ == "__main__":
    print(main())
```

Here's some boilerplate code.

1. Set breakpoints on the for loop and return statement
2. Start debugger
3. Loop through a few times e.g. 5
4. goto_(2), the print statement

### Expected Result

Moves the cursor to line 2 and stays there waiting for your next action.

Just like this issue demonstrates microsoft/vscode#25653

### Actual Result

Go to line 2 and runs code while ignoring every single breakpoint.

**Comment by mfussenegger** [comment]
Thanks for the report. Can you try with https://github.com/mfussenegger/nvim-dap/pull/610 ?

**Comment by Dosx001** [comment]
@mfussenegger thank you so much for fixing this issue so quickly. This one change has made nvim-dap even better. Thanks for the hard work.
