### ISSUE TITLE
Allow passing of arguments debugged program

### ISSUE THREAD

**Issue by epixinvites** [mfussenegger/nvim-dap#615]
### Problem Statement

I cannot find the option that allows me to add arguments like let's say `./program --arg1 --arg2`. nvim-dap only allows me to set which file I want to execute.

I'm sure I missed something along the way, but I really can't find the option that let's me do that.

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-dap/issues/424

Many debug adapters support a `args` option but you'll have to check the debug adapters documentation to be sure
