### ISSUE TITLE
"Breakpoint ignored because generated code not found (source map problem?)"

### ISSUE THREAD

**Issue by melkster** [mfussenegger/nvim-dap#638]
### Debug adapter definition and debug configuration

Installed using [DAPInstall](https://github.com/Pocco81/DAPInstall.nvim).

```lua
require('dap').adapters.node2 = {
  type = 'executable',
  command = 'node',
  args = {
    vim.fn.stdpath('data') .. '/dapinstall/jsnode/vscode-node-debug2/out/src/nodeDebug.js',
  }
}
```

### Steps to Reproduce

When debugging Jest tests using nvim-dap and [jester](https://github.com/David-Kunz/jester/), I get a warning that seems to be wrong. I created an issue in jester, but it seems like this is an issue with nvim-dap. See the discussion [here](https://github.com/David-Kunz/jester/issues/17#issuecomment-1172129713).

**To reproduce:**

[Here's](https://github.com/Lemoncode/jest-testing-by-sample) a repo with jest tests on which you can try to reproduce the issue.

Create a breakpoint in a jest test and then run:

```vim
:lua require('jester').run()
```

### Expected Result

No warning is printed

### Actual Result

The message `"Breakpoint ignored because generated code not found (source map problem?)"` is printed.

**Comment by mfussenegger** [comment]
The error comes from the debug adapter:

https://github.com/microsoft/vscode-chrome-debug-core/blob/bf783f38c73885c39da0c5ad3eeabbea7e22a55f/src/chrome/breakpoints.ts#L174

(vscode-chrome-debug-core is used by vscode-node-debug2)

This could be a configuration issue or a bug in the debug adapter. nvim-dap only displays it.

**Comment by melkster** [comment]
The weird thing is that the debugger correctly stops at the breakpoint, so everything seems to work except for the error being printed.

**Comment by mfussenegger** [comment]
I had another quick look at vscode-node-debug2 and from what I can see the `sourceMaps` option is a boolean, but the jester plugin sets `sourceMaps = "inline",`. So maybe the issue is there after all.

In any case it is either a configuration error or debug adapter bug. There's nothing I can do on the nvim-dap side about it.
