### ISSUE TITLE
TCP connecting to codelldb needs more time

### ISSUE THREAD

**Issue by maikelmeyers** [mfussenegger/nvim-dap#641]
### Debug adapter definition and debug configuration

DIInstall codelldb (with DAPInstall.nvim)

### Debug adapter version

1.7.3

### Steps to Reproduce

I followed the instructions for codelldb and configured like this:

```
dap.adapters.codelldb = {
  type = 'server',
  port = 13000,
  executable = {
    command = os.getenv("HOME") .. '/.local/share/nvim/dapinstall/codelldb/extension/adapter/codelldb',
    args = {"--port", 13000},
  }
}
```

### Expected Result

lua require.('dap').continue() starts codelldb with port 13000 and connects to it via TCP

### Actual Result

On the first try, I get immediatly the error message:

Couldn't connect to 127.0.0.1:13000

On the second try it works. Seems that it waits not long enough before connecting via TCP and on the second try the previous codelldb is still running and it connects to that one.
Unfortunately there is no wait setting available in the plugin (initialize_timeout_sec is not what is needed here)

**Comment by mfussenegger** [comment]
Could you try with https://github.com/mfussenegger/nvim-dap/pull/647 ?

It increases the amount of retries and also exposes a setting in case the default is still not enough.

**Comment by maikelmeyers** [comment]
Great! That works. Thanks for the quick fix.
