### ISSUE TITLE
Unable to PlugInstall

### ISSUE THREAD

**Issue by Qoyyuum** [mfussenegger/nvim-dap#653]
### Debug adapter definition and debug configuration

Installed the adapter via `init.vim` with `Plug 'mfussenegger/nvim-dap'`. Reloaded my NeoVim and did `:PlugInstall`. Then unable to git clone apparently based on the error message below:

![image](https://user-images.githubusercontent.com/971309/185336503-a540388d-cc98-4927-a5ca-feb48500a537.png)

```
  x nvim-dap:
      Cloning into 'C:\Users\abdul\AppData\Local\nvim\autoload\plugged\nvim-dap'...
      remote: Support for password authentication was removed on August 13, 2021.
      remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes   6     fatal: Authentication failed for 'https://github.com/mfussengger/nvim-dap.git/'
      
```

### Steps to Reproduce

1. In `init.vim`, set `Plug 'mfussenegger/nvim-dap'`. `:wq`
2. Open Neovim and run the command `:PlugInstall`

### Expected Result

Plugin to installed successfully

### Actual Result

Unable to git clone

**Comment by mfussenegger** [comment]
This is an issue with your git setup / plugin manager setup. This repository is for nvim-dap specific issues. I can't give general plugin-installation support.

**Comment by GregoryShoemake** [comment]
Except this issue only happens with nvim-dap?
