### ISSUE TITLE
Terminate instantly

### ISSUE THREAD

**Issue by IZenithy** [mfussenegger/nvim-dap#658]
### Debug adapter definition and debug configuration

```
dap.adapters.cppdbg =
{
    id = 'cppdbg',
    type = 'executable',
    command = vim.fn.stdpath('data') .. '/mason/bin/OpenDebugAD7'
}

dap.configurations.cpp = {
    {
        setupCommands = {
            {
                text = '-enable-pretty-printing',
                description =  'enable pretty printing',
                ignoreFailures = false
            },
        },

        name = "Launch file",
        type = "cppdbg",
        request = "launch",
        program = function ()
            return utils.osExecute("fd --search-path '" .. vim.fn.getcwd() .. "/bin/'  --type executable")
        end,

        cwd = '${workspaceFolder}',
        stopOnEntry = true,
    },
    {
        name = 'Attach to gdbserver :1234',
        type = 'cppdbg',
        request = 'launch',
        MIMode = 'gdb',
        miDebuggerServerAddress = 'localhost:1234',
        miDebuggerPath = '/usr/bin/gdb',
        cwd = '${workspaceFolder}',
        program = function ()
            return utils.osExecute("fd --search-path '" .. vim.fn.getcwd() .. "/bin/'  --type executable")
        end,
    },
}
```

### Debug adapter version

Latest version

### Steps to Reproduce

Run continue()

### Expected Result

When I run continue() debugging should start

### Actual Result

It terminated instantly with this error: waiting for v8 protocol on stdin/stdout. Note that it's the same message that you will get if you run OpenDebugAD7 directly:

![2022-08-23_19:54:32](https://user-images.githubusercontent.com/82327047/186217592-9cb28440-27d2-4a3d-9a89-b2a573faeed1.jpg)

**Comment by mfussenegger** [comment]
Can you show the logs?
Are you sure your program isn't just running to completion?
Are you compiling your binary with debug symbols?

Afaik the error message is normal for vscode-cpptools

**Comment by IZenithy** [comment]
1- This is the logs:
```
[ ERROR ] 2022-08-25T09:29:55Z+0300 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:1141 ]	"stderr"	{
  command = "/home/ahmed/.local/share/nvim/mason/bin/OpenDebugAD7",
  id = "cppdbg",
  type = "executable"
}	"waiting for v8 protocol on stdin/stdout\n"
[ INFO ] 2022-08-25T09:30:00Z+0300 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:614 ]	"Telemetry"	"VS/Diagnostics/Debugger/Launch"
[ INFO ] 2022-08-25T09:30:02Z+0300 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:1105 ]	"Closed all handles"
[ INFO ] 2022-08-25T09:30:02Z+0300 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:1108 ]	"Process closed"	16355	false
[ INFO ] 2022-08-25T09:30:02Z+0300 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:614 ]	"Telemetry"	"VS/Diagnostics/Debugger/DebugCompleted"
```
2- I tried a simple hello world, and it didn't work

3: ![2022-08-25_09:34:55](https://user-images.githubusercontent.com/82327047/186592366-376db162-4c54-4a3e-bc84-889f79e88e00.jpg)

**Comment by jjiangweilan** [comment]
I have tried all three cpp adapters. Only codelldb works. If you don't mind which one to use, you can give it a try

**Comment by IZenithy** [comment]
I Tried to use it, but it shows me the code in assembly

**Comment by jjiangweilan** [comment]
> I tried to use it, but it shows the code in assembly


you mean when you start debugging? try set stopOnEntry to false
```lua
dap.configurations.cpp = {
    {
        name = "codelldb",
        type = "codelldb",
        request = "launch",
        program = function()
            return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. (vim.fn.has('win32') == 1 and '\\' or '/'), 'file')
        end,
        cwd = '${workspaceFolder}',
        stopOnEntry = false, -- <=== try set this to false if you don't want stopOnEntry
    },
}

```

**Comment by IZenithy** [comment]
Codelldb works, but if you try to put any break point it will be rejected

```
[ INFO ] 2022-08-25T19:57:38Z+0300 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:755 ]	"Server rejected breakpoint"	{
  id = 1,
  message = "Resolved locations: 0",
  verified = false
}
```
But thank you for your help, I appreciate it

**Comment by mfussenegger** [comment]
For me all 3 debug adapters work just fine.

Here's how I got them working:

`foo.c`:

```c
#include <stdio.h>

int main()
{
    printf("Hello world\n");
    return 0;
}
```

Compile with debug symbols:


```
gcc -g foo.c
```


Adapter & configurations: https://github.com/mfussenegger/dotfiles/blob/7c7a6af2d7254248125867c4bc3753a3d4f39fc7/vim/.config/nvim/lua/me/dap.lua#L91-L173
lldb installation: `pacman -S lldb`
codelldb installation: https://github.com/mfussenegger/dotfiles/blob/7c7a6af2d7254248125867c4bc3753a3d4f39fc7/playbooks/roles/codelldb/tasks/main.yml#L1-L11
cpptools installation: https://github.com/mfussenegger/dotfiles/blob/7c7a6af2d7254248125867c4bc3753a3d4f39fc7/playbooks/roles/cpptools/tasks/main.yml#L1-L16


The errors shown so far also don't indicate any client bug. The issue tracker is for bugs, not for general support as I cannot support all the different debug adapters, so I'm closing this.
