### ISSUE TITLE
Running a different command without sourcing configurations

### ISSUE THREAD

**Issue by tkolleh** [mfussenegger/nvim-dap#66]
What is the recommended approach to running a different command or sending different options to the debug adapter prior to running nvim-dap?

An example would be; while working on a python file, debug that file with a normal run of debugpy then create a test case for the file and debug it with the testing module such as `pytest`.

**Comment by mfussenegger** [comment]
I think there are several ways to accomplish what you want.

`debugpy` supports launching modules, so you could create a new configuration option like this:


```lua
require('dap').configurations.python = {
  {
    type = 'python';
    request = 'launch';
    name = "Run unittest";
    module = "unittest";
    args = function()
      local filter = vim.fn.input('Enter unittest args: ')
      return {'-v', filter}
    end
  },
  -- ... other configs
}
```

Then when you run `require('dap').continue()` it will show you the "Run unittest" option and prompt you for a additional arguments so you can narrow the tests that are run.
You'd have to replace `unittest` with `pytest` and adapt the `args` to fit `pytest`, or you can create one entry per test framework.


Another option would be to create the configurations dynamically and launch them with `require('dap').run(config)`. A full example:

```lua
local fqn = 'tests.test_modulename.YourClass.test_method_to_test'
require('dap').run({
  type = 'python',
  request = 'launch',
  module = 'unittest',
  args = {'-v', fqn}
})
```

Question is how you create them dynamically. Ideally some plugin would take care of that.
For example, I hacked together a little prototype that uses treesitter to try to extract the class name and method names:


```lua
function M.test_nearest_method()
  local ft = vim.api.nvim_buf_get_option(0, 'filetype')
  local query_str = [[
    (class_definition
      name: (identifier) @name) @definition.class

    (function_definition
      name: (identifier) @name) @definition.function
  ]]
  local query = vim.treesitter.parse_query(ft, query_str)
  assert(query, 'Could not parse treesitter query. Cannot find test method')
  local parser = vim.treesitter.get_parser(0)
  local tree = parser:parse()
  if not tree then return end

  local row, _ = unpack(api.nvim_win_get_cursor(0))
  local is_class = false
  local classname = nil
  local closest_function = nil
  for id, node in query:iter_captures(tree:root(), 0, 0, row) do
    local name = query.captures[id]
    local type = node:type()
    if name == 'definition.class' then
      is_class = true
    end
    local row1, col1, row2, col2 = node:range()
    if row1 == row2 then
      row2 = row2 +1
    end
    local lines = api.nvim_buf_get_lines(0, row1, row2, true)
    local ident = nil
    if type == 'identifier' and lines and #lines == 1 then
      ident = (lines[1]):sub(col1 + 1, col2)
    end
    if name == 'name' and type == 'identifier' then
      if is_class then
        is_class = false
        classname = ident
      else
        closest_function = ident
      end
    end
	end
  if classname and closest_function then
    local path = vim.fn.expand('%:r:s?/?.?')
    local fqn = table.concat({path, classname, closest_function}, '.')
    print(fqn)
    require('dap').run({
      type = 'python',
      request = 'launch',
      module = 'unittest',
      args = {'-v', fqn}
    })
  end
end
```


(I guess I should turn this into an extension)

**Comment by tkolleh** [comment]
Thanks for the detailed response. If you decide to create an extension please share the link. I would like to support/contribute. In the meantime I will explore the described approaches.

**Comment by mfussenegger** [comment]
> Thanks for the detailed response. If you decide to create an extension please share the link. I would like to support/contribute. In the meantime I will explore the described approaches.

I've started an extension see [nvim-dap-python](https://github.com/mfussenegger/nvim-dap-python)
