### ISSUE TITLE
No known way to have multiline expressions in dap repl

### ISSUE THREAD

**Issue by alok** [mfussenegger/nvim-dap#665]
### Steps to Reproduce

Open DAP repl in python project

### Expected Result

Was attempting to run this python code in the repl

```python
 with tf.io.gfile.GFile(filename, 'rb+') as f:
            cctx = zstandard.ZstdDecompressor()
            reader_stream = io.BufferedReader(cctx.stream_reader(f))
            reader = jsonlines.Reader(reader_stream, loads=json_parser)
            for item in reader:
                result = dict()
                if isinstance(item, str):
                    result['text'] = item
                else:
                    text = item['text']
                    if isinstance(text, list):
                        text = self.para_joiner.join(text)
                        result['text'] = text
                yield result
```		

### Actual Result

After typing the first line, I can't find a way to insert further text without running line 1, which gives a syntax error.

**Comment by mfussenegger** [comment]
I think this is a limitation of the prompt buffer type in neovim.

As an alternative you could use the `debug_selection` functionality of [nvim-dap-python](https://github.com/mfussenegger/nvim-dap-python) to execute selected code.

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-dap/pull/1250

**Comment by mfussenegger** [comment]
In addition to the `dap-eval://` buffer support, in nvim 0.12 there'll be multi-line input support using shift-enter (assuming the terminal emulator support shift-enter input): https://github.com/neovim/neovim/pull/33371
