### ISSUE TITLE
Have separate signs for "current stop" position and "current stackframe position".

### ISSUE THREAD

**Issue by zenoli** [mfussenegger/nvim-dap#668]
### Problem Statement

When I navigate the stack frame (via `dap.up(), dap.down()`, the indicator arrow moves to where am in the stack frame. Hence I lose the visual indication where the debugger is currenlty stopped. When I jump of the stackframe for a couple of steps, and then perform a "step-over", I have no idea where I will land because the arrow is not at the actual stop position but at the current stackframe position.

### Ideas or possible solutions

Provide an extra sign symbol for the currently inspected stack position and leave the stopped symbol always at the actual stop position.

**Comment by mfussenegger** [comment]
Given that this has only received two votes I'm closing this. I currently have no intention on changing this.
