### ISSUE TITLE
Intermittent Failure to Execute Test (threading issue?)

### ISSUE THREAD

**Issue by holmanb** [mfussenegger/nvim-dap#669]
### Debug adapter definition and debug configuration

I'm including a bug here in case this is an unimportant shutdown ordering issue or an indicator of some other issue.

my config
```lua
    7 " DAP - debug adapter protocol                                            
    8 lua require("dap-python").setup("~/.virtualenvs/debugpy/bin/python")      
    9 lua require("dap-python").test_runner = 'pytest'                          
   10                                                                           
   11 nnoremap dm :lua require("dap-python").test_method()<cr>                  
   12 nnoremap dn :lua require("dap-python").test_class()<cr>  
```

### Debug adapter version

0.2.0

### Steps to Reproduce

1. Configure using debug info.
2. Set up python venv and and install `debugpy`.
3. Set up a passing test class using pytest
4. Try running the tests (I'm using `.test_class()` and `.test_method()`)
5. Typically the first run succeeds, but subsequent ones are less likely to actually succeed (they just time out).

### Expected Result

When the test is run via either `.test_class()` or `.test_method()`,  the test should always run. This typically involves a small delay, the split opens, another small delay while the test runs, and then output is printed in the split.

### Actual Result

The problem:

Sometimes when `.test_class()` or `.test_method()` is executed, the split window never opens and the test output is never printed (this will sometimes succeed once on one test, and fail on the subsequent call to the exact same test).

I'm experiencing intermittent issues with nvim-dap-python/pydebug/pytest. Running the test works sometimes, but often fails (command executes, but the split never opens and it's not obvious why the test didn't run). I see a warning, but I'm not sure if this might be a symptom of the same problem or completely unrelated.

```
   4 [ WARN ] 2022-09-04T16:37:07Z-0600 ] ...olmanb/.config/nvim/plugged/nvim-dap/lua/dap/session.lua:827 ]       "No callback for "  {
   5   command = "disconnect",                                                       
   6   request_seq = 5,                                                              
   7   seq = 63,                                                                     
   8   success = true,                                                               
   9   type = "response"                                                             
  10 }       
```
and similarly:
```
  21 [ WARN ] 2022-09-04T16:37:05Z-0600 ] ...olmanb/.config/nvim/plugged/nvim-dap/lua/dap/session.lua:869 ]       "No event handler for " {
  20   body = {                                                                      
  19     connect = {                                                                 
  18       host = "127.0.0.1",                                                       
  17       port = 37319                                                              
  16     },                                                                          
  15     console = "integratedTerminal",                                             
  14     isOutputRedirected = false,                                                 
  13     module = "tox",                                                             
  12     name = "Subprocess 67179",                                                  
  11     python = { "/home/holmanb/.virtualenvs/debugpy/bin/python" },               
  10     request = "attach",                                                         
   9     subProcessId = 67179,                                                       
   8     type = "python"                                                             
   7   },                                                                            
   6   event = "debugpyAttach",                                                      
   5   seq = 60,                                                                     
   4   type = "event"                                                                
   3 }      
```        
Are these warnings in the log something to ignore? 

Theory:
=======
Poking at the code a little bit it I see `spawn()` calls - so is this potentially a shared data or shutdown ordering issue?

Let me know if this needs to get filed elsewhere, but I _think_ this is the right place to file.

**Comment by mfussenegger** [comment]
I'd need a deterministic reproduction or at least a snippet from the logs where it wasn't working (with log level set to have) to look into this.  I haven't experienced this issue myself.

The custom `debugpyAttach` event from debugpy is not supported.  But that should only be a problem if you're using multiprocessing or a framework like django with autoreload

**Comment by holmanb** [comment]
Understood, I'll try getting something more tangible to work with. Thanks!

**Comment by mfussenegger** [comment]
Closing this for now.  If you've a deterministic reproduction please let me know
