### ISSUE TITLE
Error on launch: Failed to continue: {e}

### ISSUE THREAD

**Issue by tttoad** [mfussenegger/nvim-dap#681]
### Debug adapter definition and debug configuration

require('dap.ext.vscode').load_launchjs(nil, { go = { 'go' } })
dap.adapters.go = {
	type = 'executable';
	command = 'node';
	args = { os.getenv('HOME') .. '/work/vscode-go/dist/debugAdapter.js' };
}
.vscode/launch.json
```json
{
   "version": "0.2.0",
   "configurations": [
		{
			"type": "go",
			"request": "launch",
			"name": "debug",
			"program": "${fileDirname}"
		}]
}
```
When I use the dap.configurations.xy configuration, it works fine
```
 dap.configurations.go = {
 	{
 		type = 'go';
 		name = 'Debug';
 		request = 'launch';
 		showLog = false;
 		program = "${file}";
 		dlvToolPath = vim.fn.exepath('dlv') -- Adjust to where delve is installed
 	},
 }
```

### Steps to Reproduce

Run 'continue()'

### Expected Result

{e} should show the specific error!

### Actual Result

<img width="632" alt="image" src="https://user-images.githubusercontent.com/14021602/190873076-7cea0a5a-31e0-41b5-b19e-124e95c33f02.png">

**Comment by mfussenegger** [comment]
I think the "Failed to continue: {e}" message is coming from the debug adapter. nvim-dap only prints it,  as it's supposed to

**Comment by tttoad** [comment]
![image](https://user-images.githubusercontent.com/14021602/190895449-6d189e75-63c1-4860-91cf-c02a3ee1f8a8.png)
I see the specific error in the debug log, maybe the 'variables.e' should be output when printing.

**Comment by mfussenegger** [comment]
Thanks for the pointer. I somehow thought the `error` payload was left unspecified and could be arbitrary, but I must have been mixing it up with something else. 

https://github.com/mfussenegger/nvim-dap/pull/685 should lead to better error messages.
