### ISSUE TITLE
.NET Unity Support?

### ISSUE THREAD

**Issue by PhantomCloak** [mfussenegger/nvim-dap#688]
### Problem Statement

Unity game engine has debugger for .NET and I assume it have DAP inteface already in place which is implemented by VSCode via https://github.com/Unity-Technologies/vscode-unity-debug extension
Emacs via https://github.com/emacs-lsp/dap-mode/blob/master/dap-unity.el
Is it possible with nvim-dap? if it's can we add to documentation? 

### Ideas or possible solutions

- Add documentation for Unity game engine

**Comment by mfussenegger** [comment]
I think it should be possible to use the  `/bin/UnityDebug.exe` from that project with a executable/stdio adapter configuration.  See `:help dap-adapter`

Closing this. The issue tracker is primarily for client features & bugs,  not for general debug adapter support
