### ISSUE TITLE
.clear command in REPL console

### ISSUE THREAD

**Issue by BenceBakos** [mfussenegger/nvim-dap#702]
### Problem Statement

REPL console can get big over time, hard to search inside with / and ?

### Ideas or possible solutions

```
.clear
```
I saw a `clear()` method inside `repl.lua`, that might be it? 
Calling that from my config is equally good, but I guess this might be a usefull feature as well.

**Comment by mfussenegger** [comment]
Sounds like a good idea - added it in https://github.com/mfussenegger/nvim-dap/pull/705

The existing `clear` method of the repl module could also be used, but it also clears the history.
