### ISSUE TITLE
Enhance console's exception file name with highlighted color and ability goto the file

### ISSUE THREAD

**Issue by VisionaryAppDev** [mfussenegger/nvim-dap#703]
### Problem Statement

Hello everyone,
I think it'd be great if the exception file name is highlighted as it'd be much easier to identify which file is causing the issue. Furthermore, if we could click on it to open the file directly and pointing the cusor to the line number, it'd save a lot of time.

Please check the below image showing the different between Intellij's console and current nvim-dap's console.

- intellij
![IMG_20220928_135037_485](https://user-images.githubusercontent.com/27724011/192708834-db36be86-11a2-4d50-8cf0-2af0b325c3e3.png)

- nvim-dap
![IMG_20220928_135039_465](https://user-images.githubusercontent.com/27724011/192708847-d684fa7b-df00-4fc9-a98b-7313aa961de0.png)

**Comment by mfussenegger** [comment]
> Furthermore, if we could click on it to open the file directly and pointing the cusor to the line number, it'd save a lot of time

The vim way to do that is to use `gf` or `gF`, see `:help gf` and `:help gF`.
For java you may have to set the `path` option to something like this:

```
setlocal path=.,src/main/java/**,src/test/java/**,**/src/main/java/**,**/src/test/java/**
```

As for highlighting: nvim-dap core will stay language agnostic, so adding custom stacktrace highlighting is out-of-scope.
I could imagine providing some way to intercept the output from a debug-adapter and process it instead.
