### ISSUE TITLE
Clear command for the output log console

### ISSUE THREAD

**Issue by VisionaryAppDev** [mfussenegger/nvim-dap#708]
### Problem Statement

Recently, I saw there was a feature request for the REPL console cleaning command and I am thinking about cleaning the output log console too. Because, most of the time when we debug our code  there are too many logs inside the console which make it confusing especially when we need to scroll to find out what's going on. By allowing a cleaning command, it'd make life a lot easier while debugging. :)

**Comment by mfussenegger** [comment]
You could do something like `:lua vim.bo.modifiable = true; vim.api.nvim_buf_set_lines(0, 0, -1, true, {})` in the integrated terminal window to clear it.

**Comment by VisionaryAppDev** [comment]
It does clean the console but when there is something written into the console, the last few line that is already removed come back. Not sure if it's an expected behavior.


https://user-images.githubusercontent.com/27724011/194750816-4bffb38a-e23e-4001-bbc7-3edf08d6bb2b.mp4
