### ISSUE TITLE
Let REPL change previously printed line for progress bars

### ISSUE THREAD

**Issue by huberb** [mfussenegger/nvim-dap#713]
### Problem Statement

I would like to use python progress bars (`tqdm`) with the REPL.
I stumbled across this because the `tensorflow.keras.fit` function has a very messy output.

I attached a video to make it more clear.
First you can see the output of running the program with `:!python bla.py`
compare this to the output that you see in the REPL.

https://imgur.com/a/u3hpvU3

Not sure if this is a problem with neovim or with this plugin.

**Comment by mfussenegger** [comment]
If you're using `console = 'integratedTerminal',` in your configuration that should display correctly.

The REPL is a neovim prompt buffer and in general won't handle any special terminal sequence codes.


https://user-images.githubusercontent.com/38700/194714885-06b13b71-a0a1-4086-9e1e-f54b4ae2bad8.mp4

**Comment by huberb** [comment]
Thank you, this solves my issue
