### ISSUE TITLE
attempt to get length of local 'p rev_line' (a nil value)

### ISSUE THREAD

**Issue by ccbiozhaw** [mfussenegger/nvim-dap#714]
### Debug adapter definition and debug configuration

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/80820813/194706760-630181b2-2a82-400d-b6a0-bda9edbc80ef.png">

my config:

local dap_status_ok, dap = pcall(require, "dap")
if not dap_status_ok then
  return
end

local dap_ui_status_ok, dapui = pcall(require, "dapui")
if not dap_ui_status_ok then
  return
end

require('dap-python').setup('~/.virtualenvs/debugpy/bin/python')

require("dapui").setup({
})

vim.fn.sign_define("DapBreakpoint", { text = "", texthl = "DiagnosticSignError", linehl = "", numhl = "" })

dap.listeners.after.event_initialized["dapui_config"] = function()
  dapui.open()
end

dap.listeners.before.event_terminated["dapui_config"] = function()
  dapui.close()
end

dap.listeners.before.event_exited["dapui_config"] = function()
  dapui.close()
end

### Steps to Reproduce

i open the repl with 

lua require'dap'.repl.toggle()

when i switch to the repl window and type anything, hit enter and i get the error

### Expected Result

no errors

### Actual Result

errors

**Comment by mfussenegger** [comment]
Sounds like you're using a plugin that tries to attach a LSP client to the dap-repl. The LSP client in neovim doesn't work with buffers with buftype = prompt. This isn't really a nvim-dap issue as there is nothing it can do about.

You need to configure that other plugin to prevent it from trying to attach a lsp client to the dap-repl. 
If I remember right some copilot plugin tries to do that.

**Comment by ccbiozhaw** [comment]
hey thank you for the reply. i got it working by disabling copilot for dap-repl files:

```
        require("copilot").setup({filetypes={
          ["dap-repl"] = false
        }})

```
