### ISSUE TITLE
can't start codelldb automatically

### ISSUE THREAD

**Issue by eatgrass** [mfussenegger/nvim-dap#717]
### Debug adapter definition and debug configuration

with `rust-tools.nvim` builtin codelldb adapter configuration
 ```lua
{
    type = "server",
    port = "${port}",
    host = "127.0.0.1",
    executable = {
      command = codelldb_path,
      args = { "--port", "${port}" },
    },
  }
```

### Debug adapter version

3.4.5

### Steps to Reproduce

1. RustHoverAction Debug
2. can't attach to the debug server, got error message `Couldn't connect to 127.0.0.1: xxx, ECONNREFUSED`

### Expected Result

start codelldb process and attach to it

### Actual Result

the `executable` got ignored when adapter type is `server`
https://github.com/mfussenegger/nvim-dap/blob/684f57f9d6aed53dfa349986a1038b10b759e18b/lua/dap.lua#L229-L237

**Comment by mfussenegger** [comment]
These are not minimal reproduction steps.  `executable ` is not ignored when the adapter type is server. 

Your `codelldb_path` setting could be wrong.  The adapter in general works for me and many others

**Comment by eatgrass** [comment]
@mfussenegger yes, I found the `executable` option processed in `session.lua`.
my problem is missing `LANG` env variable in `uv.spawn()`, so the code-lldb didn't start, the error message is `[debug-adapter stderr] Fatal Python error: config_get_locale_encoding: failed to get the locale encoding: nl_langinfo(CODESET) failed
Python runtime state: preinitialized
`
after added `env` in `session.lua` the problem solved, is that a bug？
```
    env = {
        LANG = "zh_CN.UTF-8"
    }
```

**Comment by mfussenegger** [comment]
Sounds like an issue with your system configuration. `uv.spawn` by default inherits the parent process environment variables. If your system has `LANG` configured it should use it.

**Comment by eatgrass** [comment]
@mfussenegger  in my terminal `echo $LANG` returns `zh_CN.UTF-8`, but in nvim I got `en_US`, it's strange

**Comment by eatgrass** [comment]
@ls-devs to solve the charset problem, you can specify it explicitly

```
vim.cmd([[
language en_US.UTF-8
]])
```
