### ISSUE TITLE
add compound launch.json configurations

### ISSUE THREAD

**Issue by aldevv** [mfussenegger/nvim-dap#728]
### Problem Statement

https://code.visualstudio.com/Docs/editor/debugging#_compound-launch-configurations

**Comment by mfussenegger** [comment]
Depends on https://github.com/mfussenegger/nvim-dap/issues/586

**Comment by magoerlich** [comment]
:+1: on this and #586 seems to be solved.
So, will this be implemented?

**Comment by mfussenegger** [comment]
There's now a DapNew command that can start many sessions at once: https://github.com/mfussenegger/nvim-dap/pull/1243

I also had a look at implementing compounds but I got the impression that the complexity is not worth it. 
The implementation is either a hack but contained, or spreads quite a bit throughout the code base. 

I'd rather use up the complexity budget for other features. I might change my mind about this at some point but for now I'm closing this.
