### ISSUE TITLE
Going up/down in the stacktrace should not cycle through

### ISSUE THREAD

**Issue by wookayin** [mfussenegger/nvim-dap#735]
### Debug adapter definition and debug configuration

Just a minimal configuration would be enough:
```
local dap = require('dap')
local dapui = require('dapui')

dapui.setup {}
require('dap-python').setup()
```

### Debug adapter version

3d0d731 (0.3.0+)

### Steps to Reproduce

```
vim.keymap.set('u', function() require "dap".up() end)
vim.keymap.set('d', function() require "dap".down() end)
```

Calling `dap.up` and `dap.down` (or via some keymaps like above) would move the stack frame up and down, but the problem is it cycles through when it pasts the topmost or bottommost frame. 

### Expected Result

As usual in normal, conventional debugers, it should not past the frame boundaries if it is already the topmost stackframe or the bottommost one (with some error/warning messages).

### Actual Result

The stackframe cycles through.

**Comment by wookayin** [comment]
Relevant lines: https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap/session.lua#L1494-L1497

My suggestion is we remove this which I think is a more sensible default behavior; but we could also introduce some configuration option to allow cycle-through, something like `frame_cyclethrough = 1`. Or, adding some opts arguments to `dap.up` or `dap.down` will be another choice (which I don't prefer though).

Which option would you prefer? Once we reach to an agreement, I can write a PR.

**Comment by mfussenegger** [comment]
I have no particular strong opinion on this.  Fine for me to remove if.  In case people ask to bring it back we can always add a setting later

**Comment by AlexSWall** [comment]
I agree that it makes the most sense to me to remove this functionality and, in the unlikely event that people want it, to then consider adding the functionality somehow in that future ticket.
