### ISSUE TITLE
Add a widget to access/show Exceptions on exception breakpoints

### ISSUE THREAD

**Issue by wookayin** [mfussenegger/nvim-dap#736]
### Problem Statement

nvim-dap is amazing! One feature I wish we had is to see more detailed information about the exception being thrown, e.g., on exception breakpoints.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/1009873/197880451-25d15677-9c32-4382-b370-9535f1906fcd.png">

Currently, as shown in the above figure, a thread will be paused at the line from which the exception is thrown. It prints the stacktrace information to REPL, but I think it'd be great if there's way to show the stacktrace in a separate floating widget.

### Considered Alternatives

For instance, pudb displays the exception in a post-mortem mode very nicely;

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/1009873/197879934-5cf2ddd0-dd81-48e0-bf6e-e0b86f4d111b.png">

On "exception breakpoints" (or a post-mortem mode in pudb), one can press `e` to open up the exception information again.

**Comment by wookayin** [comment]
@mfussenegger Is there something need to be implemented from [the DAP rpotocol](https://github.com/microsoft/debug-adapter-protocol/) side or language-specific adapters?

**Comment by wookayin** [comment]
Some research on this (for the python adapter first):

[The "Stopped" event](https://microsoft.github.io/debug-adapter-protocol/specification#Events) does not specify the detailed full exception trace information. Indeed through the listener,

```
dap.listeners.after.event_stopped[...] = function (_, event)
  ...
end
```

the `event` table would look like:

```
{
  allThreadsStopped = true,
  description = "No module named 'bar'",
  preserveFocusHint = false,
  reason = "exception",
  text = "ModuleNotFoundError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)",
  threadId = 1
}
```

How the exception can be obtained: there is a `ExceptionInfo` Request (the adapter should have `supportsExceptionInfoRequest` is true). See https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap/session.lua#L356 for reference:
```
session:request('exceptionInfo', { threadId = ...}, function(err, response) .. end
```

where the response will look like
```
{                                                                                                                                  
  breakMode = "unhandled",
  description = "No module named 'bar'",
  details = {
    message = "No module named 'bar'",
    source = ...,
    stackTrace = '  File ".../a.py", line 16, in <module>\n  ' ... -- (omitted)
    typeName = "ModuleNotFoundError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)"
  },
  exceptionId = "ModuleNotFoundError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)",
  innerException = { ... },
}
```

I got the high-level idea, so the remaining things would be all about UI and public APIs.

**Comment by mfussenegger** [comment]
I changed it to report the exception info as diagnostic: https://github.com/mfussenegger/nvim-dap/pull/750
