### ISSUE TITLE
Node / Webpack Project: paths don't map correctly

### ISSUE THREAD

**Issue by jdevries3133** [mfussenegger/nvim-dap#738]
### Debug adapter definition and debug configuration

See https://github.com/jdevries3133/nvim_config/blob/main/lua/dap_conf.lua

### Debug adapter version

vscode-node2-debug 1.43.0

### Steps to Reproduce

Create a node.js project several folders deep. Create a `launch.json` to debug that server. Create a shared library in an intermediate / adjacent folder. Use tsconfig path aliases to point to the shared library. For example:

```
<root>/.vscode/launch.json
<root>/src/lib/common/foo.js
<root>/src/main/src/index.js
<root>/src/main/package.json
<root>/src/main/webpack.config.js
<root>/src/main/dist/<output>
<root>/src/main/src/<project files>
<root/src/main/tsconfig.json
```

`launch.json` example

```json
{
  "name": "my debug",
  "type": "node",
  "request": "attach",
  "cwd": "${workspaceFolder}/src/main",
  "sourceMaps": true,
  "skipFiles": [
    "<node_internals>/**/*.js"
  ],
  "outFiles": [
    "${workspaceFolder}/src/main/dist/*"
  ]
}
```

`tsconfig.json` example

```json
{
  "compilerOptions": [
    "paths": {
        "lib/*": ["../lib/common/*"]
    }
}
```

Behavior does not change based on presence / absence of `projectRoot`.

I notice that the source map file is outputting some wacky and wild paths. For example, stuff in `lib/common` becomes `<root>/src/main/dist/lib/common/foo.js`. Stuff from the main project becomes something like `<root>/src/main/dist/:webpack:/src/index.js`. I got this information by adding log statements to the dap itself, trying to figure out what was going on. I also see malformed paths like this in the raw source mapping file. 

### Expected Result

I would like to add some heuristics to nvim-dap to try to bridge the gap between these malformed paths and the actual files, so that source mapping works.

### Actual Result

Source mapping does not work, which seems to be caused by deficiencies in node2-debug or webpack or maybe both. If there is another workaround to this problem, I would be overjoyed to hear it! If not, I'd like to try to implement a solution here because this is driving me _crazy_. Clearly, I don't really have all the details, so some help on continuing to debug this would also be awesome.

**Comment by mfussenegger** [comment]
> I would like to add some heuristics to nvim-dap to try to bridge the gap between these malformed paths and the actual files, so that source mapping works.

I'm sorry but I won't be adding debug adapter specific heuristics to nvim-dap. Certainly not for a debug adapter that's abandoned.

So unless there's a bug in nvim-dap that mangles with the paths, your best options are:

- Try https://github.com/mxsdev/nvim-dap-vscode-js. The debug adapter protocol specification recently also got an addition that should make the off-spec extension that vscode-js-debug is using unnecessary. So there's a chance that vscode-js-debug will work out of the box some time in the future.
- Fork vscode-node2-debug and add the heuristics there

**Comment by jdevries3133** [comment]
Ok that's fair enough. Thank you for your thoughtful response, I'll definitely pursue one of those solutions!
