### ISSUE TITLE
When user's terminating the session, event_terminated doesn't get fired.

### ISSUE THREAD

**Issue by wookayin** [mfussenegger/nvim-dap#742]
### Debug adapter definition and debug configuration

```
  local dap = require('dap')
  dap.configurations.cpp = {
    {
      name = "Launch this file (lldb)",
      type = "cppdbg",
      request = "launch",
      console = "integratedTerminal",
      program = function()
        return "${fileDirname}/${fileBasenameNoExtension}"
      end,
      cwd = '${workspaceFolder}',
      stopAtEntry = false,
      miDebuggerPath = vim.fn.stdpath("data") .. '/mason/packages/cpptools/extension/debugAdapters/lldb-mi/bin/lldb-mi',
      miMode = 'lldb',
    }
  }

  dap.listeners.after.event_terminated["config-test"] = function() 
      vim.notify("TERMINATED!")
  end

```

I used mason.nvim to install cpptools.

### Debug adapter version

latest HEAD

### Steps to Reproduce

1. Compile a cpp program (say `a.cpp`)

```
#include <iostream>
#include <thread>
using namespace std;

int main() {
    int n = 10;

    for (int i = 0; i < n; i++) {
        std::this_thread::sleep_for(std::chrono::milliseconds(200));  // sleep 0.2 sec
        cout << i << endl;
    }
    return 0;
}
```

`g++ a.cpp --std=c++11 -g -o a`

2. Launch the program using the existing dap configuration
3. `:DapTerminate` while the program is running (e.g. set some breakpoint during the loop)

### Expected Result

The terminated event callback should be executed. It would be executed when the program ends normally, e.g., via returns without user interruption and exits normally.

### Actual Result

The terminated event callback does not execute when terminated via `dap.terminate()` -- when the session has received a terminate request.

**Comment by mfussenegger** [comment]
Not all debug adapters support the terminate request. The `terminate` function uses `disconnect` if terminate is not supported and the client closes the connection on the disconnect response. So if a debug adapter sends the event _after_ the disconnect, the event handler won't be fired.

See https://github.com/mfussenegger/nvim-dap/commit/9a501e433841fea683bb43466bde4b144d2a7b3f for more context

Your best option is to subscribe to `disconnect` as well.

**Comment by wookayin** [comment]
Thanks. I was unable to find it because it is not part of [the DAP protocol](https://microsoft.github.io/debug-adapter-protocol/specification#Events). The following works well for me.

```
  dap.listeners.after.event_terminated["my-awesome-plugin"] = function() ... end
  dap.listeners.after.disconnect["my-awesome-plugin"] = function() ... () end
```
