### ISSUE TITLE
dap.repl is not working properly.

### ISSUE THREAD

**Issue by zetatez** [mfussenegger/nvim-dap#747]
### Debug adapter definition and debug configuration

I installed nvim-dap by packer and nearly not configured. 
I am not sure it a bug of nvim lsp or nvim-dap.

### Debug adapter version

3.4.5

### Steps to Reproduce

1. open the repl by `:lua require'dap'.repl.open()`.
2. press i into the insert mode.
3. press enter then error appears.

### Expected Result

Go to next line.

### Actual Result
```
Error executing lua callback: /usr/share/nvim/runtime/lua/vim/lsp/sync.lua:177: attempt to get length of local 'prev_line' (a nil value)
stack traceback:
        /usr/share/nvim/runtime/lua/vim/lsp/sync.lua:177: in function 'compute_start_range'
        /usr/share/nvim/runtime/lua/vim/lsp/sync.lua:408: in function 'compute_diff'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:442: in function 'incremental_changes'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:635: in function 'send_changes'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1554: in function </usr/share/nvim/runtime/lua/vim/lsp.lua:1548>
Press ENTER or type command to continue
```

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-dap/issues/562
