### ISSUE TITLE
Add a way to jump to repl window on open

### ISSUE THREAD

**Issue by LiadOz** [mfussenegger/nvim-dap#756]
### Problem Statement

When the repl window is activated it saves the current window and after it's opened it goes back to the saved window. I would like to have an option to disable this behavior and stay on the repl window after opening it.

### Possible Solutions

add a flag similar to dap.defaults.fallback.focus_terminal to indicate the wanted behavior

**Comment by mfussenegger** [comment]
I think you should be able to use something like this:

```
lua require('dap').repl.open(); vim.cmd('wincmd p');
```

Or even:

```lua
lua require('dap').repl.open(); vim.cmd('wincmd p'); vim.cmd('startinsert')
```

**Comment by LiadOz** [comment]
I liked the second option but it doesn't work nice with toggle function, I used this instead
```lua
local function toggle_dap_repl()
    require('dap').repl.toggle()
    vim.cmd('wincmd p')
    local filetype = vim.api.nvim_buf_get_option(0, "filetype")
    if filetype == 'dap-repl' then
        vim.cmd('startinsert')
    end
end
```
thanks!

**Comment by mfussenegger** [comment]
If that's working I'm closing this for now. Not completely opposed to adding some more convenient option, but that snippet doesn't seem too complex either.

If this gets asked more often I may revisit the decision.
