### ISSUE TITLE
Make signs configurable

### ISSUE THREAD

**Issue by OkanEsen** [mfussenegger/nvim-dap#76]
Hi! It'd be awesome if we could change the sign symbol and highlight defined here: 

https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap.lua#L103-L105
``` lua
vim.fn.sign_define('DapBreakpoint', {text='B', texthl='', linehl='', numhl=''})
vim.fn.sign_define('DapLogPoint', {text='L', texthl='', linehl='', numhl=''})
vim.fn.sign_define('DapStopped', {text='→', texthl='', linehl='debugPC', numhl=''})
```

I hope I can send you a PR over the weekend but I can't promise anything right now.

Much appreciated, thank you for your time!

**Comment by mfussenegger** [comment]
You could already override the sign definition. You just have to make sure that you do it *after* an initial `require('dap')`.

In your `init.vim` you could do a:


```vimL
lua <<
-- ensure module is loaded
require('dap')

-- override sign definition for fancy breakpoints
vim.fn.sign_define('DapBreakpoint', {text='🛑', texthl='', linehl='', numhl=''})
EOF
```

**Comment by OkanEsen** [comment]
Oh man, I'm stupid, thank you very much. :+1:
