### ISSUE TITLE
Breakpoints get ignored with vscode-js-debug / azure functions (missing startDebugging?)

### ISSUE THREAD

**Issue by mawkler** [mfussenegger/nvim-dap#762]
### Debug adapter definition and debug configuration

Use the following `init.lua`:

<details>
<summary><b>Click to expand</b></summary>

```lua
-- Ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand('~/.config/nvim'))
vim.opt.packpath:remove(vim.fn.expand('~/.local/share/nvim/site'))

-- Append test directory
local test_dir = vim.fn.expand('~/code-other/nvim-test-config') -- NOTE: Add the path to the location of this file here
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- Install packer
local install_path = test_dir .. '/pack/packer/start/packer.nvim'
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
  vim.cmd('packadd packer.nvim')
  install_plugins = true
end

local packer = require('packer')

packer.init({
  package_root = test_dir .. '/pack',
  compile_path = test_dir .. '/plugin/packer_compiled.lua'
})

vim.g.mapleader = ' '

packer.startup(function()
  function Use(module)
    use(require(string.format('configs.%s', module)))
  end

  -- Packer can manage itself
  packer.use 'wbthomason/packer.nvim'

  ---------------------------------------
  -- Below is the actual configuration --
  ---------------------------------------

  use { 'williamboman/mason.nvim',
    config = function() require('mason').setup() end
  }
  use { 'stevearc/overseer.nvim',
    config = function()
      require('overseer').setup({
        templates = { 'builtin' },
      })
    end
  }
  use { 'mfussenegger/nvim-dap',
    requires = {
      'mxsdev/nvim-dap-vscode-js',
    },
    config = function()
      local dap = require('dap')

      local install_location = vim.fn.stdpath('data') .. '/mason/packages'

      vim.keymap.set('n', '<leader>dc', dap.continue)
      vim.keymap.set('n', '<leader>db', dap.toggle_breakpoint)

      require('dap-vscode-js').setup({
        debugger_path = install_location .. '/js-debug-adapter',
        debugger_cmd = { 'js-debug-adapter' },
        adapters = {
          'pwa-node',
          'pwa-chrome',
          'pwa-msedge',
          'node-terminal',
          'pwa-extensionHost',
        },
      })

      for _, language in ipairs({ 'typescript', 'javascript' }) do
        require('dap').configurations[language] = {
          {
            name = 'Attach to Node Functions - from init.lua',
            type = 'pwa-node',
            request = 'attach',
            port = 9229,
            preLaunchTask = 'func: host start',
          }
        }
      end

      require('dap.ext.vscode').load_launchjs(nil, { node = {'typescript'} })
    end,
  }

  --------------------------
  -- End of configuration --
  --------------------------

  if install_plugins then
    packer.sync()
  else
    -- load plugins at your earliest convenience
    vim.defer_fn(function()
      vim.cmd('doautocmd User LoadPlugins')
    end, 1)
  end
end)
```
</details>

**Installation**

`:MasonInstall js-debug-adapter`

### Steps to Reproduce

1. `> git clone https://github.com/melkster/azure-functions-minimal.git` ([azure-functions-minimal](https://github.com/melkster/azure-functions-minimal.git) is a minimal setup for an Azure Function)
2. `> cd azure-functions-minimal`
3. `> nvim -u *path/to/init.lua* -c 'DapContinue' -c 'OverseerToggle' HttpTrigger/index.ts`
4. Choose `Attach to Node Functions` (not the one ending with ` - from init.lua`)
5. Put your cursor on the Overseer task `func: host start` and press `<C-s>` to show its output (after it has started running)
6. Navigate to line 4 in `HttpTrigger/index.ts` and create a breakpoint (`<space>db`)
7. In a second terminal session, run `curl http://localhost:7071/api/HttpTrigger` (after Overseer finishes starting up its tasks)
8. Breakpoint gets ignored and "Debugger attached" never gets printed in the output of `func: host start`

Also, if I run the task

```lua
{
  name = 'Attach to Node Functions - from init.lua',
  type = 'pwa-node',
  request = 'attach',
  port = 9229,
  preLaunchTask = 'func: host start',
}
```

that's in the DAP config in the `init.lua` above, and repeat steps 1-8 (but choose `Attach to Node Functions - from init.lua` instead on step 4), "Debugger attached" gets printed, but the breakpoint still gets ignored.

### Expected Result

DAP stops execution on the breakpoint on line 4.

### Actual Result

DAP skips any breakpoint in the file, and just executes it all.

**Comment by mfussenegger** [comment]
I didn't have a closer look yet, but this is likely related to https://github.com/mxsdev/nvim-dap-vscode-js/issues/14 & https://github.com/mxsdev/nvim-dap-vscode-js/issues/15

`startDebugging` first needs to be implemented in vscode-js-debug (see https://github.com/microsoft/vscode-js-debug/issues/1388), and then in nvim-dap.

**Comment by melkster** [comment]
Ok I see. If that's the case, does that mean that I can't use vscode-js-debug for my use case until [microsoft/vscode-js-debug#1388](https://github.com/microsoft/vscode-js-debug/issues/1388)) gets added?

**Comment by mfussenegger** [comment]
I merged `startDebugging` support and it seems to work fine for debugpy, so all that's left is support in vscode-js-debug

**Comment by mfussenegger** [comment]
Closing this here. As far as I can tell on the nvim-dap side everything that needs to be implemented is implemented.
