### ISSUE TITLE
Golang can't interactive with terminal

### ISSUE THREAD

**Issue by New-arkssac** [mfussenegger/nvim-dap#763]
### Debug adapter definition and debug configuration

This is my dadapter definition
![image](https://user-images.githubusercontent.com/70094380/203965316-48da72ae-87c7-4bd0-bb3b-2f4c307133ec.png)

This is my dap-go config
![image](https://user-images.githubusercontent.com/70094380/203965448-0f98c365-14d2-4120-9967-e4de004eb442.png)

### Debug adapter version

delve version 1.9.1  
Kali-linux version 5.19.0-kali2-amd64  
go version go1.19.2 linux/amd64  

### Steps to Reproduce

I'm using fmt.Scanln to get a string from terminal 
![image](https://user-images.githubusercontent.com/70094380/203970114-55b3fc80-8a6b-4275-aff0-60b254cbcbc1.png)

### Expected Result

![image](https://user-images.githubusercontent.com/70094380/203970330-304e50f8-3174-44d3-a5dc-1b5174f19b69.png)
There should be a terminal here that tells me to type in a string

![image](https://user-images.githubusercontent.com/70094380/203972643-a1f7177e-8972-45c8-96a7-123cc7f622f8.png)
like this

### Actual Result

but bottom buffer name is a `new name` ，not is `dap-terminal`
string I entered will not be captured by fmt.Scanln, it return a err is `EOF`

**Comment by mfussenegger** [comment]
`dap-terminal` only shows up if the debug adapter supports the "RunInTerminal" functionality.
Delve has no `console` option with `integratedTerminal` and it doesn't support the "RunInTerminal" request. See https://github.com/go-delve/delve/blob/master/Documentation/api/dap/README.md for the supported options.

There's nothing that can be done on the client side about that
