### ISSUE TITLE
Resolve program path through processId in cppdbg attach config

### ISSUE THREAD

**Issue by Fabian-programmer** [mfussenegger/nvim-dap#766]
### Problem Statement

Attaching to a process with cppdbg needs 2 keyval parameters. `processId` and `program`.
Currently I'm using 2 vim.fn.inputs to fill up these keyvals, but it is possible to resolve the program value from the PID.

This could simplify the attaching to processes in nvim-dap.

What do you think about it?

### Possible Solutions

In linux and (probably also in macos) it is possible to get the program path with 
'readlink -f /proc/<PID>/exe'

with Windows it is possible with
`Get-Process -Id <PID>| Select-Object -Property Path`

**Comment by mfussenegger** [comment]
https://github.com/mfussenegger/nvim-dap/pull/768 added the option to use a metatable with `__call` as configuration, that allows you to use one `vim.fn.input` prompt and then derive the program path and set two properties at once.

Or you could use the workaround described here to set two properties: https://github.com/mfussenegger/nvim-dap/discussions/597#discussioncomment-3098086

**Comment by Fabian-programmer** [comment]
Thank you. Looks promising

**Comment by Fabian-programmer** [comment]
@mfussenegger I'm not sure about the usage. I've got following minimal example
```
local cpp_attach = {
    name = "Attach to process",
    type = 'cppdbg',
    request = 'attach',
    program = '',
    processId = require('dap.utils').pick_process,
    __call = function()
        local result = {}
        result.program = 'hardcoded path to my binary'
        return result
    end,
}
```

Which results in 
![grafik](https://user-images.githubusercontent.com/65787013/208255086-59b00a55-e51b-4e31-9c19-d2489b3da8c2.png)

Also when I write
```
__call = function(self)
end
 -- or
 __call = function(conf)
end
```

`self` and `conf` are nil. How can I access the table variables,

Thank you

**Comment by mfussenegger** [comment]
`__call` must be part of a metatable. Something like this should work:

```lua
local cpp_attach = setmetatable(
  {
    name = "Attach to process",
    type = 'cppdbg',
    request = 'attach',
    program = '',
    processId = require('dap.utils').pick_process,
  }, {
    __call = function(config)
        local result = vim.deepcopy(config)
        result.program = 'hardcoded path to my binary'
        return result
    end,
  }
)
```

**Comment by Fabian-programmer** [comment]
Thanks I've managed to solve it!
My quite ugly but working solution. (Maybe it helps someone):
```
G_DAP_PID = nil

dap.listeners.before['disconnect']['dapui_config'] = function()
  G_DAP_PID = nil
end


local function capture(cmd)
  local handle = assert(io.popen(cmd, 'r'))
  local output = assert(handle:read('*a'))
  handle:close()
  return output
end

local cpp_attach = setmetatable(
  {
    name = "Attach to process",
    type = 'cppdbg',
    request = 'attach',
    program = '',
    processId = function()
      if G_DAP_PID == nil then
        local option = require('dap.utils').pick_process()
        local co = coroutine.running()
        vim.schedule(function()
          coroutine.resume(option, co)
        end)
        G_DAP_PID = coroutine.yield()
      end
      return G_DAP_PID
    end,
  }, {
    __call = function(config)
      local result = vim.deepcopy(config)
      result.program = capture('readlink -f /proc/' .. tostring(result.processId()) .. '/exe'):sub(1, -2)
      return result
    end,
  }
)






```
