### ISSUE TITLE
Ability to change or remove highlighting of the line at which the debugger is currently on.

### ISSUE THREAD

**Issue by DasOhmoff** [mfussenegger/nvim-dap#772]
### Problem Statement

Hello, thank you for this nice plugin :)

When the debugger is stopped at a current line, it highlights the line:
![image](https://user-images.githubusercontent.com/16063186/206007578-796cdd85-b2bc-4e15-850b-70e90084c958.png)
When I visually select text, it has the same highlighting, so when I select the text within the line, the selection cannot be seen:
![image](https://user-images.githubusercontent.com/16063186/206008229-453e6aa0-fd8d-4a4e-8b78-9799bd735bf0.png)

### Possible Solutions

Ability to change the highlighting of the current debug line. Then I could change the colors and make them distinct, or remove them out right.

Thank you for your help :)

**Comment by mfussenegger** [comment]
It already uses a separate `debugPC` highlight group. If it has the same color that's due to your color scheme.

You could even customize it by overriding the sign definition and setting `linehl`. See the "SIGN CONFIGURATION" part of `:help dap.txt`

**Comment by DasOhmoff** [comment]
ah ok perfect. Thanks :)
