### ISSUE TITLE
REPL window size

### ISSUE THREAD

**Issue by martin-braun** [mfussenegger/nvim-dap#774]
### Problem Statement

`DapShowLog` and `DapToggleRepl` will split the window by 50%. I can make it smaller on `DapShowLog` by specifying my own user command, but `DapToggleRepl` won't work with this method, as it's opening the window in a local function that accepts a `wincmd`, but will never receive such.

### Possible Solutions

`require('dap.repl').toggle()` could accept a variable that defines the `wincmd`, i.e. `require('dap.repl').toggle('botright 8split')`.

### Considered Alternatives

Resizing the new window in the keymap afterwards, but it's clunky and not reliable.

**Comment by mfussenegger** [comment]
From the docs:

```
repl.toggle({winopts}, {wincmd})                             *dap.repl.toggle()*
        Opens the REPL if it is closed, otherwise closes it.

        See |dap.repl.open| for a description of the argument.
```

```
        Parameters:  
            {winopts}  optional table which may include:
                        `height` to set the window height
                        `width` to set the window width
                        Any other key/value pair, that will be treated as window
                        option.

            {wincmd} command that is used to create the window for
                     the REPL. Defaults to 'belowright split'
```

This means you can do something like `:lua require('dap.repl').toggle({ height = 10 })`

If you want that to be the default for `DapToggleRepl` you'd have to override the user command.

**Comment by martin-braun** [comment]
@mfussenegger Thanks a lot for your quick response. How could I miss that ... it's working. :)
