### ISSUE TITLE
Pluggable repl

### ISSUE THREAD

**Issue by gminorcoles** [mfussenegger/nvim-dap#776]
### Problem Statement

Dap has a repl, but it might be an enhancement to make it possible to open more specific repls for different contexts. 

### Possible Solutions

create an abstraction layer which hides repl implementation and allows pluggability. make the existing repl the  default. 

### Considered Alternatives

I am new to Neovim so I am a bit ignorant of alternatives. I am looking for ways to improve my code run debug workflow for python and dap is a central point in that work flow, and it has a repl. there are surely other places to try to make these repp-based workflow changes.

**Comment by gminorcoles** [comment]
> I'm curious, what kind of other specific repls are you thinking about?

Um I am just making a list of repl type things - vim-slime, iron.nvim, ipython or python shell. When I debug in Pycharm I run the code in the debugger and then often interact with the program state which is in memory via the embedded command line in Pycharm. This is the workflow I would like to replicate and since the Python shell is a specialized context for python, it seems reasonable to think that a more-specific repl might be of help.

**Comment by mfussenegger** [comment]
This is all rather vague and would need a more detailed description of the problem, use-case and intended workflow

**Comment by mfussenegger** [comment]
Closing this for now.  I'm not opposed to making the repl pluggable but I'd need some better use case description to understand the requirements
