### ISSUE TITLE
CTRL-w in insert mode in dap-repl

### ISSUE THREAD

**Issue by furkanbiten** [mfussenegger/nvim-dap#786]
### Problem Statement

Hi, 
First off, this is an amazing work! Thanks for the hardwork! 

When I am in dap-repl mode and and write something, I press `CTRL-w` to delete the previous word by force of habit. 
However, in dap-repl, ~it seems to exit the insert mode inside the dap-repl~ instead of deleting the previous word. 
Not sure, if this is an intended behaviour. 

UPDATE:
It does not actually exit the insert mode, it simply waits for the next command after pressing `CTRL-w`. For example, pressing `CTRL-w + s` splits the window horizontally, both in normal and insert mode in dap-repl.

**Comment by mfussenegger** [comment]
This is default vim/neovim behaviour for prompt buffers.  See https://github.com/neovim/neovim/commit/28134f4e78819c2bbf0344326b9d44f21eb0d736

You can use shift + ctrl + w to delete a word. You could also set a keymap from ctrl+w to that. nvim-dap sets the dap-repl filetype in the repl, that allows you to use a filetype plugin to set keymaps.

**Comment by miroshQa** [comment]
Can you please help me with the code example? I can't figure out how to remap ctrl + w to delete a word

**Comment by gabs712** [comment]
> Here is the code that fixes the problem, if anyone is interested:
> 
> vim.api.nvim_create_autocmd("FileType", {
>   group = vim.api.nvim_create_augroup("PromptBufferCtrlwFix", {}),
>   pattern = {"dap-repl"},
>   callback = function()
>     vim.keymap.set("i", "<C-w>", "C-S-w>", {buffer = true})
>   end
> })
> Just add it somewhere in your config

Does that still work for you? I've tried it on 0.11.0 and it seems to ignore any remap involving C-w

**Comment by miroshQa** [comment]
> > Here is the code that fixes the problem, if anyone is interested:
> > vim.api.nvim_create_autocmd("FileType", {
> > group = vim.api.nvim_create_augroup("PromptBufferCtrlwFix", {}),
> > pattern = {"dap-repl"},
> > callback = function()
> > vim.keymap.set("i", "", "C-S-w>", {buffer = true})
> > end
> > })
> > Just add it somewhere in your config
> 
> Does that still work for you? I've tried it on 0.11.0 and it seems to ignore any remap involving C-w

For some reason, it stopped working for me. Can't figure out how to make it work again, unfortunately.
Shameless plug: You can try using my plugin, debugmaster.nvim—it covers this moment there.
Or you can use something like this to open a REPL (unless you use dap-ui); that seems to work

```
vim.keymap.set("n", "<leader>ir", function()
  local repl = require("dap.repl")
  local repl_buf, repl_win = repl.open()
  vim.keymap.set("i", "<C-w>", "<C-S-w>", { buffer = repl_buf })
end)

```
