### ISSUE TITLE
Dap: Source not available, cannot jump to frame

### ISSUE THREAD

**Issue by happy42779** [mfussenegger/nvim-dap#787]
### Debug adapter definition and debug configuration

Installed via Packer.nvim
Configured as described in wiki:
```lua

dap.adapters.lldb = {
	type = 'executable',
	command = '/usr/bin/lldb-vscode-11',
	name = 'lldb'
}
dap.configurations.cpp = {
	{
		name = "Launch",
		type = "lldb",
		request = "launch",
		program = function ()
			return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
		end,
		cwd = '${workspaceFolder}',
		stopOnEntry = true,
		args = {},
		runInTerminal = false,
		-- postRunCommands = {'process handle -p true -s false -n false SIGWINCH'}
	},
	{
		env = function()
			local variables = {}
			for k, v in paris(vim.fn.environ()) do
				table.insert(variables, string.format("%s=%s", k, v))
			end
			return variables
		end
	}
}

dap.configurations.c = dap.configurations.cpp
dap.configurations.rust = dap.configurations.cpp
```

### Steps to Reproduce

1. test code are shown below:
![image](https://user-images.githubusercontent.com/12154967/208281477-01fc2fa9-9d83-4a8c-91d0-2af258b43823.png)

2. toggle breakpoint and then run it,
![image](https://user-images.githubusercontent.com/12154967/208281508-ce088695-9cd0-4ba1-8beb-25de4125090b.png)

### Expected Result

It should work, but I could not see what's wrong. 

### Actual Result

Described above

**Comment by mfussenegger** [comment]
How are you compiling the sources?
Can you show the logs?

**Comment by happy42779** [comment]
> How are you compiling the sources?
> 
> Can you show the logs?
> 
> 
> 
> 

Hi, I simply used 
'''cpp
g++ test.cpp -o test
'''
 If that provides nothing helpful, I will try to get the log.

**Comment by mfussenegger** [comment]
You might need debug symbols. See https://github.com/mfussenegger/nvim-dap/wiki/Debug-symbols-in-various-languages-and-build-systems

**Comment by Martinits** [comment]
Hello, I met this problem, too. But I did compile with `-g`. Are there something I forget? My config:
```lua
dap.adapters.lldb = {
    type = 'executable',
    command = '/usr/bin/lldb-vscode',
}

-- configurations
local executable_prompt = function()
    return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
end

dap.configurations.c = {
  {
    name = 'lldb-c',
    type = 'lldb',
    request = 'launch',
    program = executable_prompt,
    cwd = '${workspaceFolder}',
    stopOnEntry = true,
    args = {},
  },
}
```

**Comment by happy42779** [comment]
Hi, I fixed by toggling the switches in configuration. I forgot which one I changed, but here's my dap config of cpp for reference:
```
dap.configurations.cpp = {
	{
		name = "Launch",
		type = "lldb",
		request = "launch",
		program = function ()
			return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
		end,
		cwd = '${workspaceFolder}',
		stopOnEntry = false,
		args = {},
		runInTerminal = false,
		-- postRunCommands = {'process handle -p true -s false -n false SIGWINCH'}
	},
	{
		env = function()
			local variables = {}
			for k, v in paris(vim.fn.environ()) do
				table.insert(variables, string.format("%s=%s", k, v))
			end
			return variables
		end
	}
}

dap.configurations.c = dap.configurations.cpp

```

**Comment by Martinits** [comment]
I figure it out. It's stopOnEntry. When set to true, it's stuck on some init functions in glibc, hence the error message. So we cannot set stopOnEntry in c and cpp debug.

**Comment by Martinits** [comment]
@mfussenegger
