### ISSUE TITLE
attempt to index field 'ui' (a boolean value)

### ISSUE THREAD

**Issue by wen-nan** [mfussenegger/nvim-dap#788]
### Debug adapter definition and debug configuration
Sorry, I'm a newbie for neovim.
Installed the adapter via :
`go install github.com/go-delve/delve/cmd/dlv@latest`
Configuration:
```lua
  local dap = require('dap')
  dap.adapters.delve = {
    name = 'server',
    port = '${port}',
    executable = {
      command = 'dlv',
      args = { 'dap', '-l', '127.0.0.1:${port}' },
    },
  }

  dap.configurations.go = {
    {
      type = 'go',
      name = 'Debug',
      request = 'launch',
      program = '${file}',
    },
  }
```
I set keymapping:
```lua
local map = vim.api.nvim_set_keymap
local opt = { noremap = true, silent = true }

map("n", "<leader>dc", ":lua require'dap'.continue()<CR>", opt)
map("n", "<leader>dt", ":lua require('dap').toggle_breakpoint()<CR>", opt)
```

### Debug adapter version

1.20.1

### Steps to Reproduce

1. Set breakpoint
use the shortcuts  `<leader>dt`
2. Start debug
use the shortcuts  `<leader>dc`

### Expected Result

I hope start to debug

### Actual Result

```
E5108: Error executing lua ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:313: attempt to index field 'ui' (a boolean value)
stack traceback:
        ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:313: in function 'select_config_and_run'
        ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:688: in function 'continue'
        [string ":lua"]:1: in main chunk
```
This is picture:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/41350407/208392321-4758e7f5-5861-4786-9fb7-9f7b520f573a.png">

**Comment by wen-nan** [comment]
Unfortunately, I am also a beginner in lua language, 
Firstly, I didn't use global `lazy` variable in my configuration or  a plugin(I think it's realy badly code).
I use a clumsy way of looking at this variable: `print(lazy.ui)` and it is `true`.I'm not sure if this is the correct result
<img width="954" alt="image" src="https://user-images.githubusercontent.com/41350407/208441440-60406ada-3d65-4e67-815d-e48c7c2f8391.png">
I'd be very grateful if you could give me some hints.

**Comment by mfussenegger** [comment]
It shouldn't be true,  it should be the table of the dap.ui module. 

Maybe you have another dap/ui.lua module in your runtime path that shadows it. 
In any case it's not a bug with nvim-dap, but an issue with your configuration/ installation.

The issue tracker is primarily for bugs and features, not for support

**Comment by mfussenegger** [comment]
One more thing: the type in the configuration would have to refer to the adapter name. Given that you defined `dap.adapters.delve` you have to rename the type from go to delve:

```
dap.configurations.go = {
    {
      type = 'delve',
      name = 'Debug',
      request = 'launch',
      program = '${file}',
    },
  }
```
