### ISSUE TITLE
Setting request: open repl in vertical split

### ISSUE THREAD

**Issue by mrdgo** [mfussenegger/nvim-dap#79]
This might be a very small change.
I imagine an option like this:

`:lua require'dap'.repl.open({ vsplit = true })`

Maybe with a position?
So we can choose exactly where to open REPL.
In this example we would open it in a vertical split right of the current window.

`:lua require'dap'.repl.open({ vsplit = true, pos = 'upper_right' })`

To be error proof: `[ 'upper_right', 'lower_left' ]` could indicate the desired position.

**Comment by mfussenegger** [comment]
Make sense to me to make this configurable.

What do you think of directly parameterizing the command to open the window? 

`:lua require'dap'.repl.open({ repl_win_cmd = 'belowright split' })`

**Comment by mfussenegger** [comment]
Could you have a look at https://github.com/mfussenegger/nvim-dap/pull/83 and see if that works for you?

**Comment by mrdgo** [comment]
Oh wow! I honestly didn't expect a commit this fast :)

I tried it out and it behaved exactly as expected.
Thank you so much!
