### ISSUE TITLE
Jump to next/previous breakpoint

### ISSUE THREAD

**Issue by BlueDrink9** [mfussenegger/nvim-dap#792]
### Problem Statement

Often I want to move or disable a breakpoint. It would be great to have a function I could map as a motion to to jump straight to that breakpoint.

### Possible Solutions

Map to something (like `]b`) so that I can immediately jump to where my next breakpoint is. From there I can disable it and move it one line down, for example, or modify the line that I am inspecting.

### Considered Alternatives

Could parse it out of breakpoints list myself, but I think this would be generally useful and I think it fits with a vim philosophy

**Comment by BlueDrink9** [comment]
I hadn't considered using cnext or cprev, thanks. However, I still think there should be a more specific solution. Having to clear the previous qf list and re-populate it just to jump to a breakpoint feels like very poor UX for me, where the alternative could be a single function call that leaves my qf list alone. (Is there a reason you chose qf rather than location list? The latter seems like it would have been a better suited list to me)

Side request: I often also want to jump to where the current line of execution is. Adding a way to do that would be great for quality of life.

**Comment by nyngwang** [comment]
> Having to clear the previous qf list and re-populate it just to jump to a breakpoint feels like very poor UX for me

Have the same feeling.

> [...] It would be great to have a function I could map as a motion to jump straight to [...].

I think these are some examples of what OP called "[...] map as a motion to to jump". I have keymaps like:

- `]g` to jump to the next git hunk. (provided by [lewis6991/gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim))
- `]a` to (provided by [stevearc/aerial.nvim](https://github.com/stevearc/aerial.nvim))
- `]d` to jump to the next (file) diagnostics. (by built-in `vim.diagnostic`)

It will be very nice if you could provide something similar to this.

**Comment by nyngwang** [comment]
@mfussenegger Am I correct to say that the current solution for https://github.com/mfussenegger/nvim-dap/discussions/941 is:

1. Open the quickfix list by `:lua require('dap').list_breakpoints()`.
2. Jump to the breakpoint of interest.
3. Execute `run_to_cursor`.

Is it possible to achieve the same result with one command, e.g. maybe `run_to_breakpoint`?

**Comment by chrisgrieser** [comment]
I made a small function that directly uses the breakpoint data to go to the next breakpoint, without the quickfix list as intermediary. If you are at a breakpoint, it goes to the next breakpoint, otherwise, it goes to the first breakpoint. You can bind it to something like `]p`.

```lua
local function gotoNextBreakpoint()
	local breakpoints = require("dap.breakpoints").get()
	if #breakpoints == 0 then
		vim.notify("No breakpoints set", vim.log.levels.WARN)
		return
	end
	local points = {}
	for bufnr, buffer in pairs(breakpoints) do
		for _, point in ipairs(buffer) do
			table.insert(points, { bufnr = bufnr, line = point.line })
		end
	end

	local current = {
		bufnr = vim.api.nvim_get_current_buf(),
		line = vim.api.nvim_win_get_cursor(0)[1],
	}

	local nextPoint
	for i = 1, #points do
		if points[i].bufnr == current.bufnr and points[i].line == current.line then
			local next = math.fmod(i, #points) + 1 -- fmod = modulo in lua
			nextPoint = points[next]
			break
		end
	end
	if not nextPoint then nextPoint = points[1] end

	vim.cmd(("buffer +%s %s"):format(nextPoint.line, nextPoint.bufnr))
end
```

If @mfussenegger is open to it, I could also make a PR for this.

**Comment by mfussenegger** [comment]
> If @mfussenegger is open to it, I can make a PR for this.

I won't be adding anything in that direction until the other breakpoint variants are implemented (data, function, etc.) because it will likely influence the API, and I don't want to deal with BWC hassle in that regard.
That's all kinda on my roadmap for a nvim-dap 1.0

the `dap.breakpoints` module is btw. not stable, so it can break with any commit without a deprecation warning/cycle. Only the documented functions are safe to use.

**Comment by mfussenegger** [comment]
Will be part of https://github.com/mfussenegger/nvim-dap/issues/1388
