### ISSUE TITLE
Make new window selection optional

### ISSUE THREAD

**Issue by przepompownia** [mfussenegger/nvim-dap#793]
### Problem Statement

After merging #789 I have lost control of setting the current tab after stopping at each step. 

I use a listener to `event_stopped` to possibly create and jump to a special single to avoid touching any existing window. 
I extracted it into https://github.com/przepompownia/nvim-dap-tab.

The new loop makes the new choice after this from the listener.  

### Possible Solutions

 Please make the new behavior optional.

**Comment by mfussenegger** [comment]
Would https://github.com/mfussenegger/nvim-dap/pull/803 solve this?

**Comment by przepompownia** [comment]
I have `switchbuf` set to `usetab`. With that on this branch the new selection works as expected, at least after some quick manual tests comparing it with the current `master` behavior. 

https://github.com/mfussenegger/nvim-dap/pull/803/files#diff-1c238a5ffb6d36f9412528c8783aacf498b7c4456f7ce2131779e1ea04bb98b2R506-R513

Most probably it solves the problem although I consider that inside the loop the expected window can be encountered later than the original (in other words, it would work accidentally) but currently I cannot reproduce that case.

**Comment by przepompownia** [comment]
Thanks! I'll possibly create a new issue if this approach proved insufficient.
