### ISSUE TITLE
Jump to current execution position

### ISSUE THREAD

**Issue by BlueDrink9** [mfussenegger/nvim-dap#796]
### Problem Statement

Debugging sessions often involve visiting other parts of the code to check implementations. I often find myself wanting to jump back to where I was inspecting things, but currently the only way to do that without manually finding the currently stopped line is to step forward - which may lose the information I was trying to inspect

### Possible Solutions

Add a function or Plug mapping that jumps back to the current execution place (where the arrow sign is)

### Considered Alternatives

Set a specific mark that is unlikely to otherwise change? Or let the user configure their own mark letter to always use.

**Comment by theHamsta** [comment]
Though, this might be handy built-in... At the moment, you can use this extension: `:Telescope dap frames` https://github.com/nvim-telescope/telescope-dap.nvim

**Comment by mfussenegger** [comment]
You could use .frames in the repl or open a frames widget and select the top entry to jump to the current execution place.

**Comment by BlueDrink9** [comment]
The telescope solution isn't awful, but telescope is very slow on windows so I only use it on 'nix.

The solution of getting frames in repl or ui is pretty awful imo, sorry. Having to type a bunch or change windows, navigate, and select is way worse that a single mapping, so I don't think it's a reasonable alternative.

(side note, for the issues I'm opening - if you wouldn't implement them yourself, feel free to say you'd be interested in a PR and provide pointers in the right direction)
