### ISSUE TITLE
Count repeatable mappings (esp continue)

### ISSUE THREAD

**Issue by BlueDrink9** [mfussenegger/nvim-dap#797]
### Problem Statement

Say I have a breakpoint in a loop, but I don't actually need to break until the 100th or 1000th iteration, or somewhere near there. I know of no application that has a convenient way to say 'continue 100 times'. Nvim-dap could be the trailblazer in that arena. Integrate seamlessly with how vim does things, so that when a user does `99<map>` to continue, nvim-dap will continue 99 times.

This would also be nice to have for stepping, or returning from functions.

### Possible Solutions

use the `v:count` variable to keep continuing/stepping etc multiple times.

### Considered Alternatives

User implements it within their own mapping by repeating calls to 'nvim-dap' functions.

I think this would be insufficient because it would call the function multiple times immediately, which may mean the loop hasn't completed and execution isn't paused at the time of the 2nd `continue`. I think this has to be done within the dap engine.

**Comment by mfussenegger** [comment]
> but I don't actually need to break until the 100th or 1000th iteration, or somewhere near there

You could use a conditional breakpoint to stop when the loop counter variable has a certain value or a hit_condition to stop when the breakpoint was hit a number of times. 

There's also run to cursor to step to a given position.

Those approaches have better performance as the debugger takes care of them and so it avoids round-trips through the client.  Stopping, retrieving frames and scopes and continuing a 1000 times would be slow

**Comment by BlueDrink9** [comment]
Yes, those are options, but often very inconvenient, or even infeasible - especially if I'm not totally sure what loop value I need, or if it's a loop without an explicit counter (eg while).

I figured it would be a performance hit, but even a slow loop is a whole lot faster than having to manually press the button 100 times - if it is properly slow, I could just go away and wait a bit for the initial loop. I'm still certain that is a useful feature I would use.

"Run to here" doesn't cover stepping up or out, or steps that follow any sort of non-direct control flow. It also forces you to move down first, then run. Still useful, but a different use-case to this.

Furthermore, it's intuitive for a vim user to prefix actions with counts, rather than press the button multiple times.

**Comment by BlueDrink9** [comment]
Another example is recursive functions - often there is no direct indication of how deep you are in the stack - at least, none that could be used in a conditional breakpoint. I've just encountered an issue requiring me to inspect the arguments at the 5th call - unless I change my code, easiest way to do that is 5×`continue`

**Comment by mfussenegger** [comment]
Okay convinced, those are some good use-cases. Opened https://github.com/mfussenegger/nvim-dap/pull/800
