### ISSUE TITLE
:help dap does not link to help file

### ISSUE THREAD

**Issue by pretentious7** [mfussenegger/nvim-dap#80]
:help dap links to `delete a paragraph` instead of dap.txt, (just needs to be changed in readme i think)

also it would be nice if helptags ran by default, I'll try and implement this if I can figure it out.

Using NVIM v0.5.0-dev+950-g5ce328df4

**Comment by mfussenegger** [comment]
Going to close this since https://github.com/mfussenegger/nvim-dap/pull/81 got merged. Thank you again for the PR :+1:
