### ISSUE TITLE
help setting up vscode-js-debug

### ISSUE THREAD

**Issue by pretentious7** [mfussenegger/nvim-dap#82]
[vscode-js-debug](https://github.com/microsoft/vscode-js-debug) is microsoft's new standard js debugger, it's standard in vs code. I've been trying to set it up, and I have the following config:

```lua
lua << EOF
	local dap = require('dap');
	dap.set_log_level('TRACE');
	dap.adapters.node = {
		type = "executable",
		name = "node-debug",
		command = "node",
		args= {"/home/abhishek/.local/share/debuggers/vscode-js-debug/out/src/debugServerMain.js", "45635" }
	}
	dap.configurations.javascript = {
		{
		type = "node",
		request = "launch",
		name = "Launch Program",
		program = "${workspaceFolder}/${file}",
		debugServer = 45635
		}
	}
EOF
```

when I try and run it, it gives me the following log info. Also, I'm not sure I'm setting the log level correctly, because I don't see any [TRACE] items in the logfile, how do I check what it's set to during runtime? 

```
[ DEBUG ] 2020-12-31T04:50:23Z-0500 ] ...e/nvim/site/pack/pretentious7/start/nvim-dap/lua/dap.lua:1010 ]	"request"	{
  arguments = {
    adapterID = "nvim-dap",
    clientId = "neovim",
    clientname = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_IN",
    pathFormat = "path",
    supportsRunInTerminalRequest = true
  },
  command = "initialize",
  seq = 0,
  type = "request"
}
```

presumably it's just not responding, but how do I go about debugging this? I tested with python's debug adapter and that works fine.

**Comment by pretentious7** [comment]
some debugging gives this sort of error when i try to attach to an existing instance of the dap:

```
Error: Unknown config: {"name":"Launch Program","program":"/home/abhishek/SoftDev/debugTest/test.js","type":"node","request":"attach"}
    at Object.exports.assertNever (/home/abhishek/.local/share/debuggers/vscode-js-debug/out/src/common/objUtils.js:15:11)
    at Object.applyDefaults (/home/abhishek/.local/share/debuggers/vscode-js-debug/out/src/configuration.js:131:30)
    at /home/abhishek/.local/share/debuggers/vscode-js-debug/out/src/binder.js:90:67
    at Connection._onMessage (/home/abhishek/.local/share/debuggers/vscode-js-debug/out/src/dap/connection.js:145:42)
    at /home/abhishek/.local/share/debuggers/vscode-js-debug/out/src/dap/connection.js:32:76
    at EventEmitter.fire (/home/abhishek/.local/share/debuggers/vscode-js-debug/out/src/common/events.js:37:27)
    at Socket.StreamDapTransport._handleData (/home/abhishek/.local/share/debuggers/vscode-js-debug/out/src/dap/transport.js:38:49)
```

**Comment by pretentious7** [comment]
that was a name issue, after fixing now:

```lua
require('dap').attach('127.0.0.1',38121,{ type = "node-terminal", request = "attach", name = "Launch Program", program = vim.api.nvim_eval("expand('%:p')")})
```

this fails silently, ie.` lua require('dap').session() ` is nil, but no errors.

**Comment by mfussenegger** [comment]
It looks like the debug adapter is not communicating via stdio but with TCP.
A adapter configuration using type `executable` is expecting to communicate via stdio.


I managed to get it working past the initialization step by using a configuration like this:


```lua
dap.adapters['pwa-node'] = {
  type = 'server',
  host = '127.0.0.1',
  port = 45635,
}
dap.configurations.javascript = {
  {
    type = 'pwa-node',
    request = 'launch',
    name = 'Launch program',
    program = '${file}',
  },
}
```


I then launched the debug adapter manually in a terminal with `node /path/to/vscode-js-debug/... <port>'. This could probably also be done automatically via a slightly different adapter by using something like 
```lua
dap.adapters['pwa-node'] = function(cb)
  -- Launch adapter via vim.fn.jobstart or similar
  -- Maybe let it bind to port 0 and use the port it bound to from stdout
  cb({
    type = 'server',
    host = '127.0.0.1',
    port = 45635
  })
end
```

Using `type = 'pwa-node'` also seemed to be important. Otherwise I would get an unknown configuration error.
But it then rejected all the breakpoints that I tried to set.

I wish debug adapter implementations would start documenting how you're supposed to use them outside of the visual code universe :/

**Comment by pretentious7** [comment]
```lua
lua << EOF
        local dap = require('dap');    
        dap.set_log_level('TRACE');
        dap.adapters['node-terminal'] = {
                type = "server",
                host = "127.0.0.1",
                port = 38121
        }
        dap.configurations.javascript = {
                {
                type = "node-terminal",
                request = "launch",
                name = "Launch Program",
                program = vim.api.nvim_eval("expand('%:p')"),
                }
        }
EOF
```
That seems to have made some progress! I tried it with node-terminal (had to dig around in source for the names, sigh), but I'm having some trouble starting a new thread,

```
 threads = {},
  <metatable> = <1>{
    __index = <table 1>,
    _frame_delta = <function 10>,
    _frame_set = <function 11>,
    _goto = <function 12>,
    _pause = <function 13>,
    _request_scopes = <function 14>,
    _show_exception_info = <function 15>,
    _step = <function 16>,
    close = <function 17>,
    connect = <function 18>,
    disconnect = <function 19>,
    evaluate = <function 20>,
    event_continued = <function 21>,
    event_exited = <function 22>,
    event_initialized = <function 23>,
    event_module = <function 24>,
    event_output = <function 25>,
    event_process = <function 26>,
    event_stopped = <function 27>,
    event_terminated = <function 28>,
    event_thread = <function 29>,
    handle_body = <function 30>,
    initialize = <function 31>,
    request = <function 32>,
    response = <function 33>,
    run_in_terminal = <function 34>,
    set_breakpoints = <function 35>,
    set_exception_breakpoints = <function 36>,
    spawn = <function 37>
  }
```
and im not sure if it's possible to get logs from the server cause it seems to keep quiet unless there's an ERROR error. also, in the config for the server it says has ` "main" : extension.js ` but I can't seem to run extension.js cause it requires the vscode module which doesn't seem to exist unless there's some context or something, idk.

**Comment by pretentious7** [comment]
Well, I asked the [js-debug people](https://github.com/microsoft/vscode-js-debug/issues/902), let's see how that goes.

**Comment by pretentious7** [comment]
alright, so taking a hint from [here](https://github.com/microsoft/vscode-js-debug/issues/902), 
```lua
lua << EOF
	local dap = require('dap');
	dap.set_log_level('TRACE');
	dap.adapters['node-terminal'] = {
		type = "executable",
		name = "node-terminal",
		command = "node",
		args= {"/home/abhishek/.local/share/debuggers/"..
		"vscode-js-debug/out/src/flatSessionLauncher.js"}
	}
	dap.configurations.javascript = {
		{
		type = "node-terminal",
		request = "launch",
		name = "Launch Program",
		program = '${file}'
		--program = vim.api.nvim_eval("expand('%:p')"),
		}
	}
EOF
```

**Comment by awwalker** [comment]
sorry to butt in but I was trying to get this up to debug some typescript and while I was able to get the adapter spun up and seemingly connected without errors, setting breakpoints seems impossible still:

```sh
...lots of other logs all pointing to a successful connection
[ DEBUG ] 2021-01-07T19:05:19Z-0500 ] ...s/awalker/.local/share/nvim/plugged/nvim-dap/lua/dap.lua:1010 ]    "request"   {
  arguments = {
    breakpoints = { {
        line = 144
      } },
    lines = { 144 },
    source = {
      name = "login.ts",
      path = "/Users/awalker/pdaas/src/pd2/extractor/ignite/login.ts"
    }
  },
  command = "setBreakpoints",
  seq = 8,
  type = "request"
}
[ DEBUG ] 2021-01-07T19:05:19Z-0500 ] ...s/awalker/.local/share/nvim/plugged/nvim-dap/lua/dap.lua:840 ] {
  body = {
    breakpoints = { {
        id = 1,
        message = "Unbound breakpoint",
        verified = false
      } }
  },
  command = "setBreakpoints",
  request_seq = 8,
  seq = 8,
  success = true,
  type = "response"
}
[ INFO ] 2021-01-07T19:05:19Z-0500 ] ...s/awalker/.local/share/nvim/plugged/nvim-dap/lua/dap.lua:765 ]  "Server rejected breakpoint"    {
  id = 1,
  message = "Unbound breakpoint",
  verified = false
}
[ DEBUG ] 2021-01-07T19:05:24Z-0500 ] ...s/awalker/.local/share/nvim/plugged/nvim-dap/lua/dap.lua:840 ] {
  body = {
    category = "telemetry",
    data = {
      ["!setBreakpoints.errors"] = {},
      errors = {},
      setBreakpoints = {
        avg = 1.6,
        count = 1,
        failed = 0,
        max = 1.6,
        operation = "setBreakpoints",
        totalTime = 1.6
      },
      ["setBreakpoints.errors"] = {}
    },
    output = "js-debug/dap/operation"
  },
  event = "output",
  seq = 9,
  type = "event"
}
```

For reference my config/adapter setup looks like this:

```lua
    pdaasLaunchConfig = {
        type = "node-terminal";
        request = "launch";
        name = "PDCLI";
        runtimeVersion = "12.18.2";
        cwd = vim.fn.getcwd();
        program = "/Users/awalker/pdaas/build/pd2/scripts/cli/index.js";
        args = {
            "%-%-max-http-header-size", "81920"
        };
        skipFiles = {
            "node_modules/**/*.js",
            "<node_internals>/**/*.js",
        };
    }
    pdaasLaunchAdapter = {
        type = "executable";
        name = "node-terminal";
        command = "node";
        args = { "/Users/awalker/vscode-js-debug/out/src/flatSessionLauncher.js" };
    }
```
I had to compile the flatSessionLauncher with `gulp` though which was unexpected for me so maybe that will be helpful to you too.

**Comment by mfussenegger** [comment]
> sorry to butt in but I was trying to get this up to debug some typescript and while I was able to get the adapter spun up and seemingly connected without errors, setting breakpoints seems impossible still:

Yes, based on the [comment here](https://github.com/microsoft/vscode-js-debug/issues/902#issuecomment-753222854) this seems to be expected if the client doesn't implement custom protocol extensions.

It also mentions that the `vsDebugServer` might work instead of using the `flatSessionLauncher`

**Comment by awwalker** [comment]
yeah I tried that one as well and had the same problem. but that might be more to do with sourceMaps and the fact that my code is actually typescript. I was however able to get the `node2` debugger working with something like:
```lua
    local pdaasAdapter = {
        type = "executable";
        name = "node2";
        command = "node";
        args = { "/Users/awalker/vscode-node-debug2/out/src/nodeDebug.js" };
    };
    local pdaasConfig = {
        type = "node2";
        request = "launch";
        program = "/Users/awalker/pdaas/build/pd2/scripts/cli/index.js";
        cwd = vim.fn.getcwd();
        sourceMaps = true;
        protocol = "inspector";
        console = "integratedTerminal";
   };
```
with installation of the [node-debug2](https://github.com/microsoft/vscode-node-debug2) plugin

**Comment by mfussenegger** [comment]
@awwalker ah good to know. I've added it to the Wiki.

Regarding vscode-js-debug: 

I'm currently not too keen on adding undocumented custom protocol extensions to nvim-dap. 
Unless they create an issue in the debug-adapter-protocol repo and make the sessionID managemet part of the official protocol I don't see nvim-dap supporting it out of the box.

I would consider adding missing extension hooks so that somebody could create a `nvim-dap-js-debug` extension that's build on top of `nvim-dap`

**Comment by awwalker** [comment]
I'm happy with my debug2 setup for now. I use ts very sparingly and this seems to get the job done. Thanks for the attempts with vscode-js-debug. It's too bad vscode is going off spec with a new protocol, but c'est la vie.

**Comment by mfussenegger** [comment]
Going to close this for now.

If somebody wants to create a `nvim-dap-js-debug` extension and misses some extension points in `nvim-dap` or needs some pointers on how to go about it pease create a new issue.

**Comment by entropitor** [comment]
@awwalker Can you maybe share your config on how you got debugging typescript to work?

**Comment by awwalker** [comment]
@entropitor yes: my config lives [here](https://github.com/awwalker/dotfiles/blob/master/.config/nvim/lua/debuggers.lua#L151) apologies if the line reference changes drastically

**Comment by joshpetit** [comment]
> @entropitor yes: my config lives [here](https://github.com/awwalker/dotfiles/blob/master/.config/nvim/lua/debuggers.lua#L151) apologies if the line reference changes drastically

Here's a pastebin for his typescript confinguration file:
https://pastebin.com/cft2780f

**Comment by entropitor** [comment]
To be clear the above config is using [vscode-node-debug2](https://github.com/Microsoft/vscode-node-debug2) not using [vscode-js-debug](https://github.com/microsoft/vscode-js-debug)

**Comment by stephaneeybert** [comment]
@pretentious7 Which command did you execute to obtain the `.local/share/debuggers/vscode-js-debug/out/src/debugServerMain.js` file ?

I executed the commands:
```
git clone https://github.com/microsoft/vscode-js-debug
cd vscode-js-debug/
npm i

```
But then I don't know what to do to obtain the file you have.
I logged my complete issue [there](https://stackoverflow.com/q/71810002/958373).

**Comment by stephaneeybert** [comment]
I found out about gulp, installed it and ran the gulp command. That created an out/ directory with the out/src/debugServerMain.js file in it.

**Comment by uKiJo** [comment]
> It looks like the debug adapter is not communicating via stdio but with TCP. A adapter configuration using type `executable` is expecting to communicate via stdio.
> 
> I managed to get it working past the initialization step by using a configuration like this:
> 
> ```lua
> dap.adapters['pwa-node'] = {
>   type = 'server',
>   host = '127.0.0.1',
>   port = 45635,
> }
> dap.configurations.javascript = {
>   {
>     type = 'pwa-node',
>     request = 'launch',
>     name = 'Launch program',
>     program = '${file}',
>   },
> }
> ```
> 
> I then launched the debug adapter manually in a terminal with `node /path/to/vscode-js-debug/... '. This could probably also be done automatically via a slightly different adapter by using something like
> 
> ```lua
> dap.adapters['pwa-node'] = function(cb)
>   -- Launch adapter via vim.fn.jobstart or similar
>   -- Maybe let it bind to port 0 and use the port it bound to from stdout
>   cb({
>     type = 'server',
>     host = '127.0.0.1',
>     port = 45635
>   })
> end
> ```
> 
> Using `type = 'pwa-node'` also seemed to be important. Otherwise I would get an unknown configuration error. But it then rejected all the breakpoints that I tried to set.
> 
> I wish debug adapter implementations would start documenting how you're supposed to use them outside of the visual code universe :/

how about the chrome adpater? i can't make it work.
