### ISSUE TITLE
Hover float window doesn't fit variable by default.

### ISSUE THREAD

**Issue by Fabian-programmer** [mfussenegger/nvim-dap#827]
### Debug adapter definition and debug configuration

```lua
local M = {
  "mfussenegger/nvim-dap",

  dependencies = {
    {
      "rcarriga/nvim-dap-ui",
      config = function()
        require("dapui").setup({
          layouts = {
            {
              elements = {
                -- Elements can be strings or table with id and size keys.
                { id = "scopes", size = 0.4 },
                "breakpoints",
                "stacks",
                "watches",
              },
              size = 50, -- 40 columns
              position = "left",
            },
            {
              elements = {
                "console",
              },
              size = 0.3,
              position = "bottom",
            },
          },
          controls = {
            enabled = false,
          },
        })
      end,
    },
    { "theHamsta/nvim-dap-virtual-text", config = true },
  },
}

function M.init()
  << just some keys here>>
  
  vim.keymap.set("n", "<leader>dh", function()
  require('dap.ui.widgets').hover()
  end, { desc = "Hover" })
end

function M.config()
  local dap = require("dap")
  local dapui = require("dapui")

  require("plugins.dap.cpp") <<---- uses debug configuration from wiki
end

return M

```

### Debug adapter version

Latest

### Steps to Reproduce

Compile and launch. Breakpoint at var size and hover over the variable.

`require('dap.ui.widgets').hover()`

```cpp
int main(int argc, char** argv) {

   auto size = atoi(argv[1]);
   auto loops = atoi(argv[2]);
  return 0;
}
```

### Expected Result

![grafik](https://user-images.githubusercontent.com/65787013/212485458-949dca30-e5f6-4277-9924-26641804554e.png)
(Resized this here manually )

### Actual Result

![grafik](https://user-images.githubusercontent.com/65787013/212485445-e27969a1-abf3-42b3-9954-818f378d0cfa.png)

**Comment by mfussenegger** [comment]
What's that dot marker at the end?

For me it looks alright:

![image](https://user-images.githubusercontent.com/38700/212529200-a3026f38-3ebc-4698-b7ff-ec5ea47e903f.png)

The window width is computed by taking the line length:

https://github.com/mfussenegger/nvim-dap/blob/5a1479c5d633daa0db06988ed44663f07f10f5dd/lua/dap/ui/widgets.lua#L99-L101

**Comment by Fabian-programmer** [comment]
Yes the dot looks strange. After I disabled tokyonight it vanishes. Thanks!

**Comment by folke** [comment]
That dot marker is not from Tokyonight either, no idea where that's coming from...
