### ISSUE TITLE
NASM breakpoints being skipped with lldb-vscode

### ISSUE THREAD

**Issue by noahlavelle** [mfussenegger/nvim-dap#828]
### Debug adapter definition and debug configuration

Hi,
Using Arch Linux, I installed lldb and configured an adapter as described on the wiki:
```
require("dap").adapters.lldb = {
	type = "executable",
	command = "/usr/bin/lldb-vscode", -- adjust as needed
	name = "lldb",
}

local lldb = {
	name = "Launch lldb",
	type = "lldb", -- matches the adapter
	request = "launch", -- could also attach to a currently running process
	program = function()
		return vim.fn.input(
			"Path to executable: ",
			vim.fn.getcwd() .. "/",
			"file"
		)
	end,
	cwd = "${workspaceFolder}",
	stopOnEntry = false,
	args = {},
	runInTerminal = false,
}

require('dap').configurations.asm = {
	lldb -- different debuggers or more configurations can be used here
}
```
I then compiled using:
```
nasm -f elf64 -F dwarf -g test.asm
ld test.o -o test
```

I confirmed everything is working fine by running both gdb and lldb in the terminal manually, then setting breakpoints and running. When run this way, the breakpoints are stopped at as expected. However, when run through nvim, they are skipped

The only logs relating to breakpoints are here:
```
[ DEBUG ] 2023-01-15T22:33:56Z+0000 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:1453 ]	"request"	    {
  arguments = {
    breakpoints = { {
        line = 14
      } },
    lines = { 14 },
    source = {
      name = "test.asm",
      path = "/home/.../test.asm"
    },
    sourceModified = false
  },
  command = "setBreakpoints",
  seq = 2,
  type = "request"
}
[ DEBUG ] 2023-01-15T22:33:56Z+0000 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:877 ]	    {
  body = {
    breakpoints = { {
        id = 1,
        line = 14,
        source = {
          name = "test.asm",
          path = "/home/.../test.asm"
        },
        verified = false
      } }
  },
  command = "setBreakpoints",
  request_seq = 2,
  seq = 0,
  success = true,
  type = "response"
}
[ INFO ] 2023-01-15T22:33:56Z+0000 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:813 ]	    "Server rejected breakpoint"	{
  id = 1,
  line = 14,
  source = {
    name = "test.asm",
    path = "/home/.../test.asm"
  },
  verified = false
}
```

Any help is appreciated, thanks

### Debug adapter version

lldb 14.0.6-1

### Steps to Reproduce

1. Create a project with a simple Hello World x86 NASM program
2. Compile using 
```
nasm -f elf64 -F dwarf -g test.asm
ld test.o -o test
```
3. Set a breakpoint on any of the _start lines
4. Run with continue()

### Expected Result

Debugger stops on the breakpoint

### Actual Result

Breakpoint is rejected (see above logs)

**Comment by mfussenegger** [comment]
Your best option is to either try one of the other debug adapters (cpptools or codelldb), or create an upstream issue with lldb, there is nothing the client side can do if the debug adapter cannot set a breakpoint. (which is indicated by the `verified = false` in the logs)

**Comment by mfussenegger** [comment]
Closing this since it doesn't appear to be a client issue.
