### ISSUE TITLE
Support setting remote work path.

### ISSUE THREAD

**Issue by tttoad** [mfussenegger/nvim-dap#830]
### Problem Statement

When I use remote debugging:
My local working path is `/Users/toad/work/demo3/main.go`, while the remote container is `/root/demo3/main.go`
![image](https://user-images.githubusercontent.com/14021602/212858521-9f59e186-e2eb-4e18-808d-9c680a30ea9d.png)

### Possible Solutions

Maybe we can add `remotePath` field.
![image](https://user-images.githubusercontent.com/14021602/212858722-b18ee5db-328a-4e35-aeb9-7db84c66acb5.png)

**Comment by mfussenegger** [comment]
Path mappings must be supported by the debug adapter. The client doesn't handle that. Sounds like `substitutePath` is what you're looking for in delve: https://github.com/go-delve/delve/pull/2379

The client itself has no special treatment for any configuration parameters (other than the 3 required: type, request, name). 


And while I appreciate your colorscheme, for the future you may want to post your configuration/logs as text, not as image. That would improve accessibility (people may have bad visibility) and enables copy & paste.
