### ISSUE TITLE
:help mappings should provide Lua style default suggestions as well as VimL

### ISSUE THREAD

**Issue by feoh** [mfussenegger/nvim-dap#833]
### Problem Statement

For users new to NeoVim, making the conceptual leap from VimL to Lua can be non trivial, especially since the optimal vim.keymap.set syntax is relatively new to the editor.

It would be great if both styles could be presented.

I've added this for myself so I'll generate a PR from this issue.

### Possible Solutions

Add init.lua style bindings to help mappings for new users.

**Comment by mfussenegger** [comment]
Closed by https://github.com/mfussenegger/nvim-dap/pull/834
