### ISSUE TITLE
Start debug session callback

### ISSUE THREAD

**Issue by IslamWalid** [mfussenegger/nvim-dap#848]
### Problem Statement

Many adapters don't trigger events properly.
For example `codelldb` does not always trigger the exit or terminated event, so it makes it unstable to rely on events to do things like opening or closing dap-ui.
I solve it by passing a callback to  `dap.terminate()` to close dap-ui but there's no equivalent callback to be passed to `dap.continue()` or `dap.run_last()`

### Possible Solutions

I tried to add this feature and tried it on a local repo and I found it great.
So as you mentioned in the contribution section in the readme I decided to open this discussion I make a PR with it.
If you think it will be a good idea I will make a PR with the changes in the code.
What do you think?

This is the final result will look like when using `dap.continue()` and `dap.run_last()` with callback
![image](https://user-images.githubusercontent.com/53355631/216774756-78ef93a3-70cf-4dba-a3dd-9e2272ec686a.png)

**Comment by mfussenegger** [comment]
Did you try to add listeners for the disconnect and terminate requests too? Those should be reliable,  especially on latest master with https://github.com/mfussenegger/nvim-dap/commit/03807a4682081cc2523219ef17a36a618995b36d and https://github.com/mfussenegger/nvim-dap/commit/ef44e4784ec370687c601a42c4f460d92fe02c22

`dap.continue` is overloaded with functionality so it would require multiple callback args depending on what's happening. I'd rather avoid that as it could be confusing.

**Comment by IslamWalid** [comment]
These are the listeners I'm currently using but I preferred replacing them with the `dap.terminate` callback to exit the UI and close the repl and the callback works just fine.
![image](https://user-images.githubusercontent.com/53355631/216779313-5dae7c78-4efb-40da-9fe5-1b0f8f5a6bd2.png)

what about if we invoke the `dap.continue` callback only when continue used to start the session?
I thought about it and I found myself only passing a callback to it which in turn is passed to `select_config_and_run()` which also passes it to `dap.run`, I think by this way we will be only passing a special callback to `dap.continue` which will be invoked only on `dap.run`.
I actually invoked the callback in after [this line](https://github.com/mfussenegger/nvim-dap/blob/0e376f00e7fac143e29e1017d2ac2cc3df13d185/lua/dap.lua#L455)

**Comment by IslamWalid** [comment]
In another words this special callback will be invoked only when `dap.continue` is used as the entry-point and it will be invoked by `dap.run`

**Comment by mfussenegger** [comment]
What I'm suggesting is to add another listener for `disconnect`:

```lua
local function after_session()
  dapui.close()
  dap.repl.close()
end
dap.listeners.after.event_terminated['me.dap'] = after_session
dap.listeners.after.disconnect['me.dap'] = after_session
```

**Comment by IslamWalid** [comment]
It worked well, but I get this error when I terminate a `vscode-js-debug` session
![image](https://user-images.githubusercontent.com/53355631/216815584-1c67d613-cf8e-42bf-b858-1f4538290b51.png)

I registered the events as you suggested and I don't pass any callbacks to `dap.terminate` or `dap.continue`

**Comment by mfussenegger** [comment]
> It worked well, but I get this error when I terminate a vscode-js-debug session

This error sounds like an adapter of type `server` is missing a `port`

Closing this as I don't intend to add additional callbacks to `continue` if the listeners cover the same use-case
