### ISSUE TITLE
Failed to rename buffer

### ISSUE THREAD

**Issue by bagel897** [mfussenegger/nvim-dap#857]
### Debug adapter definition and debug configuration

codelldb (sorry I mispoke saying this was clangd)
Installed via mason-dap
Configured via mason-dap
Doesn't happen with debugpy.

### Steps to Reproduce

1. Use neovim latest from git
2. Use nvim-dap and nvim-dap-ui
3. Run the debugger

### Expected Result

No error

### Actual Result

![image](https://user-images.githubusercontent.com/57874654/218332235-e4030ef4-11ab-4cd9-8d0f-2ffd40064bb1.png)

**Comment by mfussenegger** [comment]
Can't reproduce

**Comment by bagel897** [comment]
Found the error in my conifg, removed this line
```lua
vim.cmd([[autocmd TermClose * if !v:event.status | exe 'bdelete! '..expand('<abuf>') | endif]])
```
