### ISSUE TITLE
PHP adapter, RELP evaluate code in the wrong frame (always as if I were in the last frame)

### ISSUE THREAD

**Issue by n-peugnet** [mfussenegger/nvim-dap#862]
### Debug adapter definition and debug configuration

`php-debug-adapter` installed adapter via Mason.
Configured it as so:

```lua
dap.adapters.php = {
  type = 'executable',
  command = 'php-debug-adapter',
}

dap.configurations.php = {
  {
    type = 'php',
    request = 'launch',
    name = 'Listen for Xdebug',
    port = 9003
  }
}
```

### Debug adapter version

1.31.1

### Steps to Reproduce

1. In a project with at least two recursive function calls, and variables defined in the first one
2. Setup a breakpoint in the last function called
3. Change frame to parent using `.frames` and selecting the parent
4. See that `.scopes` show indeed the parent frame's scope
5. Try to evaluate a variable of this frame and get `null`

Real example:

```
dap> .scopes
Locals

  $differ: uninitialized
  $attributes: array(10)
  $ignoreWhiteSpace: uninitialized
  $oldRevision: ""
  $inlineRenderer: uninitialized
  $revisionCount: 1
  $rendererOptions: uninitialized
  $currentRevision: "Coucou  @"vincent"#2 \n\nCe truc est super. C'est génial."
  $sideBySideRenderer: uninitialized
  $compareWith: uninitialized
  $diffSubject: Illuminate\Database\Eloquent\Builder
  $this: TheTurk\Diff\Api\Serializers\DiffSerializer
  $sideBySideHtml: uninitialized
  $inlineHtml: uninitialized
  $comparisonArray: array(1)
  $diff: TheTurk\Diff\Models\Diff
  $combinedHtml: uninitialized
  $ignoreCase: uninitialized
Superglobals
  $combinedRenderer: uninitialized
  $_POST: array(0)
  $_COOKIE: array(3)
  $_FILES: array(0)
  $_ENV: array(0)
  $_REQUEST: array(1)
  $_SERVER: array(29)
  $site: Flarum\Foundation\InstalledSite
  $server: Flarum\Http\Server
  $__composer_autoload_files: array(50)
User defined constants
  $_GET: array(1)
  ARTISAN_BINARY: "flarum"
dap> $revisionCount
null
dap> $this
Flarum\Mentions\Formatter\FormatUserMentions
  slugManager: Flarum\Http\SlugManager
  translator: Flarum\Locale\Translator
```

### Expected Result

I expect that when I change the inspected frame, the REPL evaluates code in this new frame.

### Actual Result

The code keeps being evaluated in the frame of the breakpoint.

**Comment by mfussenegger** [comment]
Seems like a limitation of the php debug adapter. nvim-dap sets the frameId to the currently selected frame.
You can turn on trace logging and check the logs. You should see something like:

```
   {
  arguments = {
    context = "repl",
    expression = "settings",
    frameId = 50
  },
  command = "evaluate",
  seq = 33,
  type = "request"
}
```

And you should see that the `frameId` will change depending on the selected frame.

**Comment by mfussenegger** [comment]
Closing this since it works for other debug adapters and appears to be a problem with the php adapter.
