### ISSUE TITLE
Codelldb processes that are started automatically remain as zombie processes after the session is terminated.

### ISSUE THREAD

**Issue by tangiang0812** [mfussenegger/nvim-dap#868]
### Debug adapter definition and debug configuration

Installed adapter via mason
Configured it as described in the wiki 

```
dap.adapters.codelldb = {
  type = 'server',
  port = "${port}",
  id = "rdb",
  executable = {
    command = codelldb_path,
    args = { "--port", "${port}" },
    detached = true,
  },
}
```

### Steps to Reproduce

1. Run a debug session.
2. Run terminate() or disconnect().
3. Repeat step 1 and step 2.

### Expected Result

There should be no codelldb processes hanging around other than the process that is in current debugging session.

### Actual Result

There are so many zombie codelldb processes.
![image](https://user-images.githubusercontent.com/72957212/220186123-6b34a324-0320-4111-9572-d05186ffc42f.png)

**Comment by mfussenegger** [comment]
Thanks for the report. Should be fixed with https://github.com/mfussenegger/nvim-dap/pull/872
