### ISSUE TITLE
require("dap") returns boolean

### ISSUE THREAD

**Issue by SteveWolligandt** [mfussenegger/nvim-dap#870]
### Debug adapter definition and debug configuration

The error occurs before when indexing whatever is returned form `require('dap')`
``` lua
local dap = require('dap')
dap.adapters.cpp = { -- <- hear it happens
  type = 'executable';
  command = os.getenv('HOME') .. '/.virtualenvs/tools/bin/python';
  args = { '-m', 'debugpy.adapter' };
}
```

``` bash
$ nvim --version
NVIM v0.8.3
Build type: Debug
LuaJIT 2.1.0-beta3
```

### Debug adapter version

0.4.0

### Steps to Reproduce

``` lua
local dap = require('dap')
-- try to index dap
```

### Expected Result

should return index

### Actual Result

Prints error:
```
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value                                                                                                              stack traceback:                                                                                                                                                                                    [string ":lua"]:1: in main chunk
```

**Comment by theHamsta** [comment]
Do you have a config file called `dap.lua` that could be sourced instead of the `dap.lua` file of the repository? You could test this by placing an `error("ok. proper dap.lua was sourced.")` in the dap.lua of this repository

**Comment by SteveWolligandt** [comment]
OOH! There is actually one! Too much copy/paste from too many sources. Thanks for the quick response!
