### ISSUE TITLE
Support codelldb's `cargo` keyword 

### ISSUE THREAD

**Issue by DieracDelta** [mfussenegger/nvim-dap#880]
### Problem Statement

[Codelldb](https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#cargo-support) supports cargo and drops the requirement for a `program` keyword in the `launch.json`. However, when I load in my `launch.json` and try to run it using the codelldb adaptor, I get a error saying that `program` is required. I'm guessing this is an additional feature needed on nvim-dap's side?

For reference, I'm trying to debug tests in [this](https://github.com/EspressoSystems/HotShot) repo. The following `launch.json` works in vscode:

```json
{
        "version": "0.2.0",
        "configurations": [
                {
                        "type": "rt_lldb",
                        "request": "launch",
                        "name": "debug the test",
                        "cargo": {
                                "args": [
                                        "test",
                                        "--package=hotshot-testing",
                                        "--test",
                                        "libp2p",
                                        "--features=full-ci, channel-async-std",
                                ],
                                "filter": {
                                        "name": "hotshot-testing",
                                        "kind": "lib"
                                }
                        },
                        "cwd": "${workspaceFolder}",
                }
        ]
}
```

But when I load it into neovim with:

```
:lua require('dap.ext.vscode').load_launchjs(nil, { ["rt_lldb"] = {"rust"} })
:DapContinue
```

I get the error `Error on launch: "program" property is required for launch`.

Note: I don't believe that this a codelldb adapter configuration issue--I'm configuring it with the adapter helper function from rust-tools. Debugging works great when I hardcode in `program` to the absolute path to the compiled test. It's just when I `load_launchjs` with a `cargo` attribute instead of a `program`, I get errors.

### Possible Solutions

Not sure, probably add a hook/some logic to perform the translation in the `load_launchjs` function. I'm still working on familiarizing myself with this codebase. I'm planning to dig into this more, but just wanted to sanity check that I'm not missing something major before diving in.

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-dap/discussions/671#discussioncomment-3592258
