### ISSUE TITLE
Attempt to perform arithmetic on field 'seq' (a nil value)

### ISSUE THREAD

**Issue by gilice** [mfussenegger/nvim-dap#885]
### Debug adapter definition and debug configuration

```lua
dap.adapters.flutter = {
	type = "executable",
	command = "flutter",
	args = { "debug_adapter" }
}

dap.configurations.dart = {
{
	type = "flutter",
	request = "launch",
	name = "FlutterRun",
	program = "${file}",
	cwd = "${workspaceFolder}",
	toolArgs = { "-d", "linux" }
}

}
```

### Debug adapter version

0.5.0

### Steps to Reproduce

I am trying to run a custom command that Flutter defines, see [here](https://github.com/flutter/flutter/tree/f2f80059ff87be34f773de33400af52a00c81a1a/packages/flutter_tools/lib/src/debug_adapters#hotrestart)

I tried to run this code:

```lua
local sesh = require("dap").session();
print(vim.inspect(sesh.seq)) -- prints "4"
sesh.request(
"hotRestart", 
{reason = "manual"}, 
function(err, res)
	print("done") 
end
)
```

### Expected Result

The command gets sent and flutter does its thing.

### Actual Result

```lua
E5108: Error executing lua /home/user/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1570: attempt to perform arithmetic on field 'seq' (a nil value)
stack traceback:
        /home/user/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1570: in function 'request'
        [string ":lua"]:3: in main chunk
```

# I am not sure if this is a bug or just me doing something wrong.

**Comment by mfussenegger** [comment]
You have to call `sesh:request` or pass `sesh` along as first argument. 

See https://www.lua.org/pil/16.html
