### ISSUE TITLE
Debugger rejects breakpoint but it returns as verified

### ISSUE THREAD

**Issue by wassimk** [mfussenegger/nvim-dap#891]
### Problem Statement

I'm using [ruby/debug adapter](https://github.com/ruby/debug), and when I try to set a log type breakpoint, I get a message that the debugger doesn't have that capability, [which is true](https://github.com/ruby/debug/blob/7a37045098871a89da00641eb59bbca2d89915e2/lib/debug/server_dap.rb#LL173C16-L173C33). But the server responds that the breakpoint is verified. 

I believe this is why `nvim-dap` [doesn't change the breakpoint](https://github.com/mfussenegger/nvim-dap/blob/75a94b8b577a970c0cad25a54a64dc40fc6fa0ea/lua/dap/session.lua#L865-L866) to a rejected style. Instead, it leaves the log point style breakpoint in the gutter.

If we know the server is not capable, regardless of verified status, should the breakpoint change to rejected?

### Possible Solutions

In a fork I was tinkering with this and I set the breakpoints state as `verified = false` right [here](https://github.com/mfussenegger/nvim-dap/blob/75a94b8b577a970c0cad25a54a64dc40fc6fa0ea/lua/dap/session.lua#L809). That seems to work but maybe something more needs to be done because `nvim-dap-ui` still shows it in `DAP Breakpoints` as set.

### Considered Alternatives

If it also makes sense, write to the debugger authors and ask them to return the verified status as false. I did look at VS Code, and they do mark it as a rejected breakpoint.

**Comment by mfussenegger** [comment]
This is kinda intentional, if the debug adapter doesn't support the log point it could still accept the breakpoint as a regular breakpoint.

I guess what the client could do is drop the logpoint or condition information before sending it to the server.

**Comment by wassimk** [comment]
That does make sense. The debugger stops at the log point even though it doesn't support that type!

Coming at it from a new user to DAP and `nvim-dap` perspective, I wonder if it would be clearer to mark it as a rejected breakpoint. This way, the breakpoint remains. And if the debugger happens to stop there and treats it as a normal breakpoint, then I know why the log point feature didn't work. But, on the other hand, if it doesn't stop, I understand why because it's a rejected breakpoint.

Also, I appreciate the work you've put into `nvim-dap`. I've only recently started incorporating the Ruby debugger in my workflow, and it's pretty useful!

**Comment by mfussenegger** [comment]
I think marking it as rejected and then having it stop at the breakpoint can be equally confusing.

From the protocol perspective a logpoint is the same as a breakpoint, except with some property set. Most debug adapters will simply not read the property of they don't support it. I guess there could be some who have a strict serialization and fail if there is an unexpected property. If that is really the case nvim-dap could be changed to omit the property when sending - to always ensure that logpoints fall back to regular breakpoint if the debug adapter doesn't support them.

**Comment by wassimk** [comment]
> If that is really the case nvim-dap could be changed to omit the property when sending - to always ensure that logpoints fall back to regular breakpoint if the debug adapter doesn't support them.

This also makes sense. I like that a breakpoint still gets set, and the gutter sign that remains is true to the type of breakpoint that got set, and I got the message why it's no longer a log point. Also, this reserves the rejected breakpoint purely for those servers that flat-out reject them.
