### ISSUE TITLE
Adding vscode-js-debug

### ISSUE THREAD

**Issue by bezlant** [mfussenegger/nvim-dap#892]
### Problem Statement

Since all the supported node/chrome debuggers are deprecated. Could you add support for this one https://github.com/microsoft/vscode-js-debug ?

**Comment by mfussenegger** [comment]
It's not that nvim-dap doesn't support vscode-js-debug, it's that vscode-js-debug is currently not spec compliant. They need to implement https://github.com/microsoft/vscode-js-debug/issues/1388 to no longer rely on a custom off-spec extension.

Nothing to be done about that in nvim-dap. Once they are spec compliant it should work.

**Comment by nsoufian** [comment]
As https://github.com/microsoft/vscode-js-debug/issues/1388 is implemented should we expect the chrome support for version greater than v1.77.0, or still some blockers except 1388 .
