### ISSUE TITLE
Add support for env variables in launch.json

### ISSUE THREAD

**Issue by hgaiser** [mfussenegger/nvim-dap#895]
### Problem Statement

Currently it seems that you can't define environment variables in launch.json.

I'm working around this by running `env` with args `SOME_VAR=some_value`, followed by my program, but it would be nicer if I can define environment variables directly.

### Possible Solutions

```json
  {
      "version": "0.2.0",
      "configurations": [
          {
              "type": "cppdbg",
              "request": "launch",
              "name": "Launch CPP",
              "env": {
                  "SOME_VAR": "some_value"
              }
          }
      ]
  }
```

**Comment by mfussenegger** [comment]
The properties defined in the `launch.json` are sent 1:1 (after some processing to deal with variables) to the debug adapter. Whether `env` is supported depends on the debug adapter, not on nvim-dap.

Check your debug adapters documentation, most support some way to set environment variables, but how exactly can differ between them.

**Comment by hgaiser** [comment]
Ahh I wasn't aware of that. Thanks for your response, sorry for wasting
time! :)
