### ISSUE TITLE
Launch.json won't load for node2

### ISSUE THREAD

**Issue by jiriks74** [mfussenegger/nvim-dap#897]
### Debug adapter definition and debug configuration

Installed the adapter via [mason-nvim-dap.nvim](https://github.com/jay-babu/mason-nvim-dap.nvim).
Configured via mason-nvim-dap.nvim (this is working).

The configurations I defined in
<details>
<summary>launch.json</summary>

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node2",
      "request": "launch",
      "program": "${workspaceFolder}/src/index.js",
      "cwd": "${workspaceFolder}",
      "sourceMaps": true,
      "protocol": "inspector",
      "console": "integratedTerminal",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
      },
      "args" : ["."],
      "outputCapture": "std"
    }
  ]
}
```

</details>

are not showing up when launching the debugger.

### Debug adapter version

v1.43.0

### Steps to Reproduce

1. Initialize a new node (electron) project
2. Create a `launch.json`

<details>
<summary>`launch.json`</summary

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node2",
      "request": "launch",
      "program": "${workspaceFolder}/src/index.js",
      "cwd": "${workspaceFolder}",
      "sourceMaps": true,
      "protocol": "inspector",
      "console": "integratedTerminal",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
      },
      "args" : ["."],
      "outputCapture": "std"
    }
  ]
}
```

</details>

3. Set a keybind for loading `launch.json`
  - `["<leader>dle"] = { function() require("dap.ext.vscode").load_launchjs(nil, { node2 = { "js", "html" } }) end, desc = "Node" }`
4. Load the `launch.json` with the keybind.
5. The configurations from `launch.json` are not showing up.

### Expected Result

The configurations from launch.json showing up when starting the debugger

### Actual Result

Only default configurations from `mason-nvim-dap.nvim` are shown.

**Comment by mfussenegger** [comment]
The filetype for `.js` files is `javascript`. You probably need to call

```
require("dap.ext.vscode").load_launchjs(nil, { node2 = { "javascript", "html" } }) 
```

**Comment by jiriks74** [comment]
> The filetype for `.js` files is `javascript`. You probably need to call
> 
> ```
> require("dap.ext.vscode").load_launchjs(nil, { node2 = { "javascript", "html" } }) 
> ```

That works. thanks.

Is there another way to load the launch.json though? I don't really like creating a keybind for every single debugger/language that I'll be running something in... Couldn't something like `fyletypes` be added to the `launch.json`?

**Comment by jiriks74** [comment]
Or maybe when loading it without any arguments could load it for all files instead of what's in `"type":`? Because I really find it useless as I don't really find a use case for it. Most people will probably be useing `mason-nvim-dap.nvim` to load all the adapters and when you set type to `"type": "javascript"` it will load it but complain that there's no adapter named `javascript` but when you input `node2` to use the `node2` adapter then it doesn't load as it thinks that you're loading it for `.node2` files...
