### ISSUE TITLE
custom a command to load a gdb scripts after attaching not working

### ISSUE THREAD

**Issue by weiyshay** [mfussenegger/nvim-dap#902]
I am trying debugging C/C++ project via the plugin via different launching modes('launch', 'attach' and 'remote') and it is awesome to see that these three modes work perfectly. 

An issue is that I need to load a gdb scripts which is not listed in the default commands in remote mode.
I tried to add it to the command list in the source code but it doesn't make sense.

I added the commands to '.gdbinit' file and it can be invoked from gdb command line properly.

What am I missing?
diff:
```
diff --git a/lua/dap/repl.lua b/lua/dap/repl.lua
index de4c8cc..a8178d7 100644
--- a/lua/dap/repl.lua
+++ b/lua/dap/repl.lua
@@ -98,7 +98,10 @@ M.commands = {
   clear = {'.clear'},
   capabilities = {'.capabilities'},
   help = {'help', '.help', '.h'},
-  custom_commands = {}
+  custom_commands = {
+    loadscripts = {'.source', '.s'},
+  }
 }
```
.gdbinit
```
define loadscripts 
       printf "loading scripts...\n"
	source test-scripts
end

```

My configuration:
```
    -- attach server
    {
        name = 'Attach to gdbserver :3334',
        type = 'cppdbg',
        request = 'launch',
        MIMode = 'gdb',
        miDebuggerServerAddress = 'localhost:3334',
        miDebuggerPath = '/usr/bin/gdb', cwd = '${workspaceFolder}',
        program = function()
            return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
        end,
        setupCommands = {
            {
                text = '-enable-pretty-printing',
                description = 'enable pretty printing',
                ignoreFailures = false
            },
        },
    },


```

### Debug adapter version

master(commit(by Mar 15th, 2023): 5e1e259798d978aa92fbc467199fd5171fee4ce7)

### Steps to Reproduce

1. In a remote debug session.
2. Set a breakpoint and targeted to the remote successfully.
3. Invoke the custom command.

### Expected Result

The command in the .gdbinit should be executed.

### Actual Result

dap> help
Commands:
  .back, .b
  .reverse-continue, .rc
  exit, .exit
  .pause, .p
  help, .help, .h
  .scopes
  .next, .n
  .capabilities
  .into
  .clear
  .into-targets
  .continue, .c
  .up
  .frames
  .down
  .goto
  .threads
  .out
Custom commands:
  loadmodules
dap> loadmodules
dap> loadmodules
dap>

**Comment by mfussenegger** [comment]
Maybe check the cpptools repo - if that's the debug adapter you're using. 

The issue tracker is for client bugs or features and not for general support for debug adapters

**Comment by weiyshay** [comment]
Hi Mathias,
Thank you very much for your tips! 

'-exec loadscripts' works for me, nice!
