### ISSUE TITLE
Jump to Frame on stopped Thread breaks session

### ISSUE THREAD

**Issue by Abh15h3k** [mfussenegger/nvim-dap#904]
### Steps to Reproduce

1. trigger multiple breakpoints. ( i used a spring boot java app and called the same API twice ).
2. `DapContinue` to continue running the first breakpoint triggered (first API call).
3. Use threads widget to jump to stopped threads frame.
4. try using `DapStepOver`
5. try using `DapContinue`

### Expected Result

for point # 4 in repro. should execute currently line (statement) and break at next line (statement).
for point # 5 in repro. should continue execution for breakpoint.

### Actual Result

for point # 4 in repro. does nothing.
for point # 5 in repro. start a new debug session (current session lost on Jump to Frame ?)

**Comment by Abh15h3k** [comment]
![jump_to_frame](https://user-images.githubusercontent.com/40197742/225993090-72c6e32d-454f-4608-8e53-5916807e813c.gif)

**Comment by mfussenegger** [comment]
Looks like this was a regression introduced with the multi-session debug support. Can you try with https://github.com/mfussenegger/nvim-dap/pull/906 ?

**Comment by Abh15h3k** [comment]
Great!
working as expected now.

Thanks for the quick response.
