### ISSUE TITLE
Support sending and receiving relative paths

### ISSUE THREAD

**Issue by ciarand** [mfussenegger/nvim-dap#905]
### Problem Statement

I'm trying to debug a Go binary built with Bazel using Delve (`dlv`). Delve doesn't officially support Bazel, but I've been able to get it working fine using Delve's terminal UI (`dlv exec path/to/compiled/binary`). Unfortunately, it seems like the Bazel-built binaries store debug symbols with relative paths and nvim-dap sends `setBreakpoints` requests with absolute paths, which leads to "could not find file" errors from Delve.

I can post my configs or trace logs if it's helpful, but I'm not sure they're necessary given the nature of the issue.

### Possible Solutions

I'd like to be able to configure nvim-dap to both send and receive relative source paths instead of absolute paths.

That could be either a configuration flag (`useRelativePaths`) or some sort of transformation function.

### Considered Alternatives

I've tried to fix this naively by changing nvim-dap so that it sends relative paths (https://github.com/mfussenegger/nvim-dap/commit/2288916aea13ac8e66e509b5e9d297d4a39ad22e). That seems to work great for Delve, but nvim-dap seems to interpret the paths in the `stackTrace` response as absolute paths (so `my_dir/my_test.go` causes the non-existent file `/my_dir/my_test.go` to be opened in a new pane). The specific error being reported is: https://github.com/mfussenegger/nvim-dap/blob/5e1e259798d978aa92fbc467199fd5171fee4ce7/lua/dap/session.lua#L382-L388

But obviously the actual problem is that - at least for bazel-built binaries - dlv wants and uses relative paths, whereas nvim-dap wants and uses absolute paths.

**Comment by ciarand** [comment]
Update: With https://github.com/mfussenegger/nvim-dap/commit/2288916aea13ac8e66e509b5e9d297d4a39ad22e and  https://github.com/ciarand/nvim-dap/commit/8ac7ac0af768cb09961137399093d86d2d8ed768 I've been able to open and step through a real debugging session. It still breaks when I try and step into Go SDK source code, but that seems like a separate issue.

**Comment by mfussenegger** [comment]
I'd rather avoid adding support for this as it's simpler to reason about things if paths are always absolute internally.

I'm also not sure if this is something that the client should be responsible of. The specification would also allow to set `pathFormat = "uri"`. And URIs would always be absolute. My impression is that this should be handled by the debug adapter.

But leaving this open to get more inputs and to see if this is a more common problem.

**Comment by mfussenegger** [comment]
I think it would already be possible to create a proxy in lua by creating a TCP server. You could have a look at the test debug adapter implementation for the boilerplate: https://github.com/mfussenegger/nvim-dap/blob/master/tests/server.lua

I currently don't have plans to provide a more general means to monkey patch messages.

Did you bring this up in delve or bazel? I assume vscode and other debug adapter clients like vimspector would run into the same problem. Wouldn't it make more sense to solve this in either delve or bazel?

**Comment by ciarand** [comment]
Ok, thank you! This was really helpful. I'll take a look at the TCP server code and figure out another way of solving this. The delve project seems (understandably) somewhat reluctant to accept bazel-specific changes and the bazel folks seem to have similar thoughts on their end.

**Comment by ciarand** [comment]
For posterity, I solved this with a config like https://gist.github.com/ciarand/0769c90e16802081914d1b1aa2ddfac6
