### ISSUE TITLE
Variable doesn't get printed through -exec in repl

### ISSUE THREAD

**Issue by Fabian-programmer** [mfussenegger/nvim-dap#907]
### Debug adapter definition and debug configuration

[Config based on vscode default with logging](https://github.com/Fabian-programmer/oid_bug/blob/main/config_nvim_dap.nvim)
Within vscode [this config](https://github.com/Fabian-programmer/oid_bug/blob/main/config_vscode.json) works and produces the expected result. 

```lua
local cpptools = mason_registry.get_package("cpptools")

dap.adapters.cppdbg = {
  id = 'cppdbg',
  type = 'executable',
  command = cpptools:get_install_path() .. '/extension/debugAdapters/bin/OpenDebugAD7'
}
```

### Debug adapter version

cpptools v1.14.4

### Steps to Reproduce

This error is random, but with following minimal example I could reproduce the error at least every 2nd time. With a more complex example the error occurs all the time. When I reduce the complexity by removing catch2 the error doesn't occur.
It also uses a 3rd party gdb extension. (maybe some timing error?) **Edit:** this is optional

In vscode it works for me without error.

Now to reproduce:

1. `git clone https://github.com/Fabian-programmer/oid_bug`
2. `g++ -o oid_bug oid_bug.cpp -ggdb -O0`
3. Install openimagedebugger (optional)
```
 git clone https://github.com/OpenImageDebugger/OpenImageDebugger.git
 cd OpenImageDebugger
 git submodule init
 git submodule update
 
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=../bin
make -j4
make install

GDB integration: Edit the file ~/.gdbinit (create it if it doesn't exist) and append the following line:
source /path/to/OpenImageDebugger/oid.py
```
4. In [oid_bug.cpp](https://github.com/Fabian-programmer/oid_bug/blob/main/oid_bug.cpp) set a breakpoint in line 31.
5. Start the debugging with the provided configuration
6. if openimagedebugger is enabled, the variable should be selectable +visible in the ui. But it is also possible to execute `-exec print test` in the dap repl console, which will return `No symbol "test" in current context.`

### Expected Result

I don't know why I currently can't embed png's here.
But this is the [expected result](https://github.com/Fabian-programmer/oid_bug/blob/main/oidbug.png). It should display the variable test inside the open image debugger.

For the `-exec print test` this is the result from vscode:

```
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (10239) ->(gdb)\n"},"seq":1262}
1: (10239) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (10239) 1122: elapsed time 0\n"},"seq":1264}
1: (10239) 1122: elapsed time 0
--> R (variables-22): {"type":"response","request_seq":22,"success":true,"command":"variables","body":{"variables":[{"name":"test","value":"{...}","type":"cv::Mat","evaluateName":"test","variablesReference":1005}]},"seq":1266}
```

### Actual Result

For the actual result the Open Image Debugger window stays blank with the last line in repl:

> [OpenImageDebugger] Error: Could not plot variable
> --> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"No symbol \"test\" in current context.\n"},"seq":100}
> No symbol "test" in current context.

[repl output for nvim dap](https://github.com/Fabian-programmer/oid_bug/blob/main/debug_output_nvim_dap)

compared to working [repl output from vscode](https://github.com/Fabian-programmer/oid_bug/blob/main/debug_output_vscode)

I hope it is ok, that I've just linked everyth. into this repository. Didn't want to clutter the ticket with these outputs.

**Comment by leosmaia21** [comment]
i have the same problem, when u step in a function the reps doest update, u need for exemple type p test, it will say:-var-create: unable to create variable object, and then type -exec p test, the first command will update the repl i guess

**Comment by leosmaia21** [comment]
here some information: 
https://github.com/microsoft/vscode-cpptools/issues/5235#issuecomment-941828993

**Comment by Fabian-programmer** [comment]
I saw that ticket, too. But I was wondering, why it works for me in vscode but not in nvim + the logs look quite different.

**Comment by Fabian-programmer** [comment]
I switched to gdb 14.1, this issue isn't relevant for me anymore. 
Maybe this helps you too @leosmaia21
