### ISSUE TITLE
Keep current line centered after a step

### ISSUE THREAD

**Issue by mintelm** [mfussenegger/nvim-dap#915]
### Problem Statement

I want to setup nvim-dap so that it automatically centers the current active line after each step of the dap client. When stepping through code quickly I often lose track of the line, because it jumps around so much, so I'd prefer to keep it centered.

Basically, I want to make vim automatically press `zz` after each `step_over()`, `step_into()`, etc.

### Possible Solutions

I think it would be good if this was an opt-in configuration option .
However, if this is a niche request, I'd be more than happy if you gave me an idea, how I could do this myself.

### Considered Alternatives

Due to the async nature of the dap step calls, in my current setup I simply have a `vim.wait()` after calling `step_over()` which for sure isn't a good solution. Also, if the dap-adapter takes longer to step than my specified timeout, it won't work.
Another idea was, to solve this using the following snippet:
```
dap.listeners.after.event_stopped['auto-center'] = function()
  vim.cmd('normal zz')
end
```
However, turns out that this event is emitted too early and the screen still is not centered

**Comment by mfussenegger** [comment]
`event_stopped` is too early because when nvim-dap receives the event it first has to fetch the stacktrace to knows where to jump to.

You can try listening to the stacktrace:

```lua
dap.listeners.after.stackTrace["auto-center"] = function()
  vim.cmd.normal("zz")
end
```

Or you can setup a `CursorMoved` autocmd within `event_stopped`:

```lua
dap.listeners.after.event_stopped["auto-center"] = function()
  api.nvim_create_autocmd("CursorMoved", {
    once = true,
    callback = function()
      vim.cmd.normal("zz")
    end
  })
end
```



You might also want to setup a highlight for the `debugPC` highlight group, e.g.:

```
:lua vim.api.nvim_set_hl(0, "debugPC", { bg = "red" })
```

**Comment by mintelm** [comment]
Thank you, this works like a charm.
