### ISSUE TITLE
with lldb, print value (eval) struct with -> give syntax error

### ISSUE THREAD

**Issue by grimgort** [mfussenegger/nvim-dap#921]
### Debug adapter definition and debug configuration

with lldb, print value struct with -> give syntax error. if we use "." that s work. 

```lua
dap.adapters.cppdbg = {
  id = "cppdbg",
  type = "executable",
  --[[ command = 'C:\\absolute\\path\\to\\cpptools\\extension\\debugAdapters\\bin\\OpenDebugAD7.exe', ]]
  --[[ command = 'D:\\ftarroux\\AppData\\Local\\nvim-data\\mason\\bin\\OpenDebugAD7.cmd', ]]
  command = "D:\\ftarroux\\AppData\\Local\\nvim-data\\mason\\bin\\OpenDebugAD7.cmd",

  options = {
    detached = false,
  },
}
dap.adapters.codelldb = {
  type = "server",
  port = "${port}",
  executable = {
    -- CHANGE THIS to your path!
    command = "D:\\ftarroux\\AppData\\Local\\nvim-data\\mason\\bin\\codelldb.cmd",
    args = { "--port", "${port}" },
    -- On windows you may have to uncomment this:
    detached = false,
  },
}
```

### Steps to Reproduce

use eval on struct argument as : 

struct toto {
int arg1;
}

use eval() on toto->arg1

![image](https://user-images.githubusercontent.com/44238325/230565555-97d3dd06-91d8-4c31-8fab-6f8c1d25bbf7.png)

### Expected Result

![image](https://user-images.githubusercontent.com/44238325/230565715-b682babb-dca5-4ca4-be52-34e12d47111e.png)

### Actual Result

syntax error

**Comment by mfussenegger** [comment]
This seems like an issue with the debug adapter.  Nvim-dap only sends the expression as string and isn't aware of its syntax
