### ISSUE TITLE
Error when starting rust debugging session using lldb-vscode

### ISSUE THREAD

**Issue by Drllap** [mfussenegger/nvim-dap#928]
### Debug adapter definition and debug configuration

Mostly just copied what is in this repo:

```
dap.adapters.lldb = {
  type = 'executable',
  command = 'lldb-vscode',
  name = 'lldb'
}

dap.set_log_level('TRACE')
dap.configurations.rust = {
  {
    name = 'Launch',
    type = 'lldb',
    request = 'launch',
    program = function()
      local ret = vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
      print("return: ", ret)
      return ret
      -- return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},    -- ... the previous config goes here ...,
    initCommands = function()
      -- Find out where to look for the pretty printer Python module
      local rustc_sysroot = vim.fn.trim(vim.fn.system('rustc --print sysroot'))

      local script_import = 'command script import "' .. rustc_sysroot .. '/lib/rustlib/etc/lldb_lookup.py"'
      print("script_import: ", script_import)
      local commands_file = rustc_sysroot .. '/lib/rustlib/etc/lldb_commands'
      print("commands_file: ", commands_file)

      local commands = {}
      local file = io.open(commands_file, 'r')
      print("file: ", file)
      if file then
        for line in file:lines() do
          table.insert(commands, line)
        end
        file:close()
      end
      table.insert(commands, 1, script_import)

      return commands
    end,
    -- ...,
  }
}
```

### Steps to Reproduce

1. Open a rust project
1. Run `continue()
1. Set the target executable

### Expected Result

The debugging session should start

### Actual Result

Get error message:
``Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `lldb` configuration. Check the logs for errors (:help dap.set_log_level)``
[dap.log](https://github.com/mfussenegger/nvim-dap/files/11289976/dap.log)

I'm using Windows 10

**Comment by Drllap** [comment]
The 
`print("script_import: ", script_import)`
line in the config above prints: script_import:  command script import `"C:\ProgramData\chocolatey\lib\rust-ms\tools/lib/rustlib/etc/lldb_lookup.py"` but there is no such file

**Comment by Drllap** [comment]
`lldb.exe` exits almost instantly when I run it from command line. I find that suspicious

**Comment by Drllap** [comment]
This is probably a LLVM issue I'm running into see:
https://github.com/llvm/llvm-project/issues/59524
https://github.com/llvm/llvm-project/issues/59695#issuecomment-1416257606

**Comment by mfussenegger** [comment]
I improved the error handling a bit with https://github.com/mfussenegger/nvim-dap/pull/929 to make it clearer the process exits with an error code. 

And yes,  this looks like an issue with the adapter
