### ISSUE TITLE
Server keeps rejecting breakpoints, lldb-vscode, Rust, Windows

### ISSUE THREAD

**Issue by Drllap** [mfussenegger/nvim-dap#931]
### Debug adapter definition and debug configuration

This is a continuation issue from #928 
I have now managed to get lldb to work, it no longer returns instantly.

Still the same config:
```
dap.adapters.lldb = {
  type = 'executable',
  command = 'lldb-vscode',
  name = 'lldb'
}

dap.set_log_level('TRACE')
dap.configurations.rust = {
  {
    name = 'Launch',
    type = 'lldb',
    request = 'launch',
    program = function()
      local ret = vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
      print("return: ", ret)
      return ret
      -- return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
    end,
    cwd = '${workspaceFolder}',
    stopOnEntry = false,
    args = {},    -- ... the previous config goes here ...,
    initCommands = function()
      -- Find out where to look for the pretty printer Python module
      local rustc_sysroot = vim.fn.trim(vim.fn.system('rustc --print sysroot'))

      local script_import = 'command script import "' .. rustc_sysroot .. '/lib/rustlib/etc/lldb_lookup.py"'
      print("script_import: ", script_import)
      local commands_file = rustc_sysroot .. '/lib/rustlib/etc/lldb_commands'
      print("commands_file: ", commands_file)

      local commands = {}
      local file = io.open(commands_file, 'r')
      print("file: ", file)
      if file then
        for line in file:lines() do
          table.insert(commands, line)
        end
        file:close()
      end
      table.insert(commands, 1, script_import)

      return commands
    end,
    -- ...,
  }
}
```

### Steps to Reproduce

1. Open a rust project
2. Set a break point at the start of main.rs
1. Run continue()
1. Set the target executable

### Expected Result

The debugger should stop at the breakpoint

### Actual Result

The program just runs to end without stopping in the bp
[dap.log](https://github.com/mfussenegger/nvim-dap/files/11301940/dap.log)

**Comment by Drllap** [comment]
When I first create the bp, a red breakpoint signal appears in the gutter, as expected. But when I start running the program in debugger it changes to `R`

**Comment by mfussenegger** [comment]
Make sure you have debug symbols. See https://github.com/mfussenegger/nvim-dap/wiki/Debug-symbols-in-various-languages-and-build-systems#Rust

In any case, this is not a client bug if a debug adapter can't verify a breakpoint.
