### ISSUE TITLE
dap-repl -exec autocomplete not working for cpptools

### ISSUE THREAD

**Issue by rm374** [mfussenegger/nvim-dap#935]
### Debug adapter definition and debug configuration

Apologies in advance if this is in the wrong section.

Using latest stable version of NeoVim 0.9 with Lazy with all plugins updated to latest.

Installed the latest vscode-cpptools DAP adapter via Mason (previously using vscode-lldb).

Everything seems to be working well except there is no autocomplete in dap-repl window.

If I switch back to vscode-lldb, the autocompletion in dap-repl window starts working again.

I have autocompletion enabled for dap-repl via cmp-dap -

--cmp-dap
require("cmp").setup.filetype({ "dap-repl", "dapui_watches", "dapui_hover" }, {
┊ sources = {
┊  { name = "dap" },
┊ },
})

### Steps to Reproduce

Run a binary compiled with debug symbols with cpptools OpenDebugAD7 and setup a breakpoint. Once the breakpoint is hit, inspect the local variables in dap-repl window using -

dap> -exec p varName

### Expected Result

autocompletion should kick in when typing the variable name

### Actual Result

no autocompletion takes place even though cmp-dap has been configured for dep-repl

**Comment by mfussenegger** [comment]
Looks like cpptools doesn't define any trigger characters:

```
dap> .capabilities
{
  completionTriggerCharacters = {},
   ....
   supportsCompletionsRequest = true,
 }
 ```
 
 And also doesn't provide completions for variables:

```
[ DEBUG ] 2023-04-26T15:48:46Z+0200 ] ...fig/nvim/pack/plugins/start/nvim-dap/lua/dap/session.lua:1588 ]	"request"	{
  arguments = {
    column = 3,
    frameId = 1000,
    text = "ar"
  },
  command = "completions",
  seq = 43,
  type = "request"
}
[ DEBUG ] 2023-04-26T15:48:46Z+0200 ] ...fig/nvim/pack/plugins/start/nvim-dap/lua/dap/session.lua:935 ]	2	{
  body = {
    targets = {}
  },
  command = "completions",
  request_seq = 43,
  seq = 76,
  success = true,
  type = "response"
}
```

That's not a client issue, but a debug adapter limitation. You'll have to bring this up upstream.

**Comment by rm374** [comment]
Thank you for clarifying 👍  I'll take this up with cpptools.
