### ISSUE TITLE
The cursor is not restored correctly after entering prompt by "Launch file with arguments"

### ISSUE THREAD

**Issue by nyngwang** [mfussenegger/nvim-dap#957]
### Debug adapter definition and debug configuration

I used nvim-dap and nvim-dap-python without any modification. (only rearranged the UIs provided by nvim-dap-ui.)

### Debug adapter version

I'm not quite sure about this question. I'm using debugpy and it's version is 1.6.7. Please let me know if this is not what you asked for.

### Steps to Reproduce

1. In your project, create more than one window before starting the nvim-dap-ui. For example, I have only two splits A/B where window A(main.py, this is the entry point) is above window B(just any other module used by A), then after I started nvim-dap-ui I got the following:

<img src="https://github.com/mfussenegger/nvim-dap/assets/24765272/b94b938c-2f9f-4d68-867d-0f0ce6d4ee51" width="700">

2. Open the entry point file in window A, and put your cursor at window A too. Start debugging using the configuration "Launch file with arguments" provided by nvim-dap-python, then your cursor will be located at window B after you press Enter.
3. This causes the problem: Since the buffer of window B is not the entry point file, you will either start the debugging session from the wrong file or cannot start the debugging session.

### Expected Result

To be honest, I don't know what should be the "answer" to deal with this. It seems that nvim-dap might be designed under the assumption that one will always start the debugging session from a tabpage that contains only one window of the entry point file currently.

It will be great if, say I start the command `dap.continue()` at window A, then my cursor can be put back to exactly window A instead of any other window before the debug session starts. Or maybe one can be able to select which window is going to be used after the prompt. (I think this would be better since one can start the debugging without moving the cursor to the entry point file first.)

### Actual Result

As a workaround, I have to open the entry point file on window B so that after the prompting it can start the debugging session with the entry file in window B. (In the following image the buffer of window B had been changed to another buffer since the debug session had started.)

<img src="https://github.com/mfussenegger/nvim-dap/assets/24765272/1677848c-34d8-4410-9002-7c65daa9533e" width="700">

**Comment by mfussenegger** [comment]
Can you also reproduce this without nvim-dap-ui?

If I have split windows and use the nvim-dap-python "Launch file with arguments" configuration, the cursor remains in the window it was in. It doesn't move to a different window.
