### ISSUE TITLE
Hover does not work on PHP variables

### ISSUE THREAD

**Issue by marvielb** [mfussenegger/nvim-dap#959]
### Debug adapter definition and debug configuration

Installed adapter via [Mason](https://github.com/williamboman/mason.nvim). With the following config:
```lua
		dap.adapters.php = {
			type = "executable",
			command = "php-debug-adapter",
		}

		dap.configurations.php = {
			{
				type = "php",
				request = "launch",
				name = "Listen for Xdebug",
				port = 9003,
			},
		}
```

### Debug adapter version

0.6.0

### Steps to Reproduce

I created this sample php script then served it using ```php -S 127.0.0.1:8000```

```php
<?php
define("CONSTANT", "Hello world.");

$value = 1;
$value = CONSTANT;
echo $value;
```

1. Place the breakpoint on the last line
2. Trigger the breakpoint by pointing the browser to ```http://localhost:8000/```
3. Hover on the ```$value``` variable
4. Command: ``` :lua require("dap.ui.widgets").hover()```

### Expected Result

Show the variable value without errors

### Actual Result

When hover is called, it produces the following error:

![image](https://github.com/mfussenegger/nvim-dap/assets/50162243/0316a133-daab-417d-9710-bc8644c566ab)

Interestingly, constant variables shows just fine, only normal PHP variables shows that error

![image](https://github.com/mfussenegger/nvim-dap/assets/50162243/1933c167-f2a4-4fde-8e70-1db7e379c633)

**Comment by mfussenegger** [comment]
This seems like a debug adapter issue, not a client issue.

**Comment by davidszkiba** [comment]
@mfussenegger I'm having the same issue. Seems to be the same issue as for [Perl](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#perllanguageserver):

> There is an issue with the hover() method because the "$", "@" and "%" signs are not handled properly per default. You can fix it by adding them to iskeyword:

```
vim.opt.iskeyword:append({"$", "@-@", "%"})
```

I could create a PR to update the documentation for the PHP debug adapter installation, if you like?
