### ISSUE TITLE
Dealing with custom paths in DAP breakpoint requests

### ISSUE THREAD

**Issue by jeanlucthumm** [mfussenegger/nvim-dap#970]
### Problem Statement

`nvim-dap` seems to always send the absolute path of a file as part of a breakpoint toggle request, but unfortunately due to my work's internal build system, these are not absolute and rather relative to my given "workspace", so all my breakpoints get rejected:
`

```
[ INFO ] 2023-06-10T16:48:59Z-0700 ] ...humm/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:873 ]  "Server rejected breakpoint"    {
  message = "could not find file /[redacted_absolute_path]/main.go",
  verified = false
}
```

### Possible Solutions

I found this line:

https://github.com/mfussenegger/nvim-dap/blob/7c1d47cf7188fc31acdf951f9eee22da9d479152/lua/dap/session.lua#L844

Which I think is responsible for setting the path in the request. I'm wondering if it's possible to pass it through a customizable transformer function e.g.:

```lua
function update_path(path)
  -- custom logic to for ex. strip an absolute prefix
  return modded_path
end
```

And then somehow expose that in the config.

### Considered Alternatives

I played around with the working directory of my adapter (Delve) but it doesn't seem to affect the allowed file paths.

I'm also only able to launch Delve in `launch + exec` mode, i.e. I have to build the binary externally using our build system.

**Comment by mfussenegger** [comment]
See the conversation in https://github.com/mfussenegger/nvim-dap/issues/905

**Comment by mfussenegger** [comment]
Judging from https://github.com/mfussenegger/nvim-dap/issues/905#issuecomment-1615138269 it looks like delve already supports path substitution:

```lua
substitutePath = {
      { from = "${workspaceFolder}/bazel-${workspaceFolderBasename}/external/", to = "external/", },
      { from = "external/", to = "${workspaceFolder}/bazel-${workspaceFolderBasename}/external/", },
      { from = "GOROOT/", to = "${workspaceFolder}/bazel-${workspaceFolderBasename}/external/go_sdk/", },
      { from = "${workspaceFolder}/bazel-${workspaceFolderBasename}/external/go_sdk/", to = "GOROOT/", },
      { from = "", to = "${workspaceFolder}" },
      { from = "${workspaceFolder}", to = "" },
    },
```

Can you use that instead?

**Comment by jeanlucthumm** [comment]
Just tested it and this solved the issue thanks!

**Comment by jeanlucthumm** [comment]
Don't think I can edit the labels, otherwise I'd remove the `needs: feebdack`
