### ISSUE TITLE
Codelldb showing assembly at the end of program and when step into printf

### ISSUE THREAD

**Issue by leosmaia21** [mfussenegger/nvim-dap#976]
### Debug adapter definition and debug configuration

Hello
Is there someway of preventing showing assembly when using codelldb, its quite annoying?

### Steps to Reproduce

1 step into printf
2 needs to open the .c file and step out the printf to continue te degub

### Expected Result

Not showing the assembly, not even step into printf funtion

### Actual Result

![image](https://github.com/mfussenegger/nvim-dap/assets/77647786/e2d4f8d9-5965-4265-bfb7-17d05a74c44d)

**Comment by mfussenegger** [comment]
Where to step into is entirely controlled by the debug adapter, the client only follows that.

You'll have to check the codelldb docs for an option to tune that.

(The issues here are for bugs, not for generic support requests, please use the discussions feature in the future for general questions)
