### ISSUE TITLE
"Server rejected breakpoint" when debug linked go project

### ISSUE THREAD

**Issue by 2dogchan** [mfussenegger/nvim-dap#977]
### Steps to Reproduce

1. link /path/from/foo_project/src/go_server to ${GOPATH}/src/go_server
2. add breakpoint on the main function
3. dap continue

### Expected Result

Add breakpoint successfully

### Actual Result

[ INFO ] 2023-06-26T15:33:13Z+0800 ] ...chan/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:873 ]	"Server rejected breakpoint"	{
  message = "could not find file /Users/2dogchan/projects/unity_project/turn_based_game/GameServer/gate/main.go",
  verified = false
}

**Comment by mfussenegger** [comment]
Server rejecting breakpoints is usually a problem with the debug adapter, not with the client.

You'll have to raise an issue in the repo of the debug adapter
