### ISSUE TITLE
When jumping to a frame, prefer using open windows

### ISSUE THREAD

**Issue by LiadOz** [mfussenegger/nvim-dap#980]
### Problem Statement

Jumping to buffer seems to only use the current window. If You have a split of windows [A] | B (brackets denote current window),  when jumping to code that exists in the content of the file that B contains you will get [B] | B.
Instead I think its better to have A | [B]

Another considerations to make is whether or not to allow jumping between tabs, so some input is needed here.

I could implement it sometime in the near future.

**Comment by mfussenegger** [comment]
This should already work if you change the `switchbuf` setting.

See `:help dap.defaults` and `:help 'switchbuf'`

E.g. try:

```lua
local dap = require("dap")
dap.defaults.fallback.switchbuf = 'useopen,uselast'
```

or

```lua
dap.defaults.fallback.switchbuf = 'usetab,uselast'
```

**Comment by LiadOz** [comment]
> This should already work if you change the `switchbuf` setting.
> 
> See `:help dap.defaults` and `:help 'switchbuf'`
> 
> E.g. try:
> 
> ```lua
> local dap = require("dap")
> dap.defaults.fallback.switchbuf = 'useopen,uselast'
> ```
> 
> or
> 
> ```lua
> dap.defaults.fallback.switchbuf = 'usetab,uselast'
> ```

Didn't notice this option, but for it seems that the focus is still on the current window, instead of changing the focus to the other open window. Is there another setting that I should set?

**Comment by mfussenegger** [comment]
> it seems that after jumping to frame in window B the focus is still on window A. Is there another setting that I should set?

There is no option but I changed the behavior with https://github.com/mfussenegger/nvim-dap/pull/982

**Comment by LiadOz** [comment]
Tested it on my end, works great, thanks!

**Comment by TheBlob42** [comment]
Sorry to comment on a closed issue.

Any chance we could make this "configurable"? :thinking: 
I build myself a [small floating utility window](https://github.com/TheBlob42/nvim-config/blob/main/lua/lsp/dap.lua#L82-L133) with custom mappings to quickly step through a debug session, but now that it always jumps to affected window this has become useless :sweat_smile:

**Comment by mfussenegger** [comment]
@TheBlob42 I could imagine allowing the `switchbuf` setting to be either a string, or a function. If it's a function it would allow full customization of the jump logic.

Could you create a new issue that explains the use-case in more detail?
