### ISSUE TITLE
Configuration for codelldb with request = "custom" not working for cpp

### ISSUE THREAD

**Issue by asthana-subodh** [mfussenegger/nvim-dap#981]
### Debug adapter definition and debug configuration

Configuration for [codelldb](https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(via--codelldb)) for cpp works for `request = "launch"` but does not work for `request = "custom"`

I have tried setting it up using dap.configurations.cpp in my lua config file as well as using `launch.json` and I get the same error with both the setups.

Error: `Error on custom: Malformed message`

**Config 1:**

```lua
dap.configurations.cpp = {
	{
		name = "Custom run",
		type = "codelldb",
		request = "custom",
		targetCreateCommands = {"target create /path/to/a.out"},
		postRunCommands = {"r"},
		stopOnEntry = false,
		terminal = 'integrated',
		console = 'integratedTerminal',
	},
}
```

**Config 2:**

`dap_config.lua`

```lua
require('dap.ext.vscode').load_launchjs('path/to/launch.json', { lldb = {'c', 'cpp'} })
```

Here's a sample `launch.json`

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "custom",
            "name": "Debug",
            "targetCreateCommands": ["target create /path/to/a.out"],
            "postRunCommands": ["r"],
        }
    ]
}
```

The same `launch.json` works on vscode. Because this works on vscode I suspect if this is a nvim-dap issue and not a codelldb server issue. But please correct me if I am wrong.

### Debug adapter version

nvim-dap is locally checked out at this commit hash:
`a6d48d2 | 2023-06-14 | Karl Yngve Lervåg | Allow setting title for widgets via winopts (#974)`

codelldb: `v1.9.2`

### Steps to Reproduce

Reproduces with a simple cpp code.

```cpp
#include <iostream>

int main()
{
	int var = 10;
	std::cout << "Hello World!" << std::endl;
	std::cout << var << std::endl;
	return 0;
}
```

Compilation:

```
clang++ -std=c++17 -O0 -g hello_world.cpp
```

### Expected Result

Debugger should load when invoking `require'dap'.continue()` but it is not. It is throwing an error. 

### Actual Result

`Error on custom: Malformed message`

**Comment by mfussenegger** [comment]
Looks like `custom` is handled in the vscode client extension of codelldb:

https://github.com/vadimcn/codelldb/blob/f4b6ad6dfc20a31da922146b78cbea9543997e5d/extension/main.ts#L194

But it's only converting the properties.
Try with:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "custom": true,
            "name": "Debug",
            "targetCreateCommands": ["target create /path/to/a.out"],
            "postRunCommands": ["r"]
        }
    ]
}
```

**Comment by asthana-subodh** [comment]
Thanks. This worked but I had to remove `postRunCommands`. Both `targetCreateCommands` and `postRunCommands` are launching processes and therefore I see two pids.
I'll explore the extension implementation more. Thanks for pointing me to it.
