### ISSUE TITLE
repl lose the focus when we use some 'step' function

### ISSUE THREAD

**Issue by alanoliveira** [mfussenegger/nvim-dap#983]
### Debug adapter definition and debug configuration

Here is a rust example, but I believe it happens with any adapter using repl

```
vim.opt.rtp:append("~/Repos/nvim-dap")

local dap = require("dap")

dap.adapters.codelldb = {
  type = "server",
  port = "${port}",
  executable = {
    command = "codelldb",
    args = { "--port", "${port}" },
  },
}

dap.configurations.rust = {
  {
    name = "Launch",
    type = "codelldb",
    request = "launch",
    program = "${workspaceFolder}/target/debug/${workspaceFolderBasename}",
    cwd = "${workspaceFolder}",
    console = "internalConsole",
  },
}
```

### Debug adapter version

rust-analyzer 0.3.1583-standalone

### Steps to Reproduce

1.  open some code
2.  add a break point and start dap
3.  open repl
4.  run `.n`

### Expected Result

- dap open the file where the "next instruction" is (in the buffer defined by `switchbuf`)
- repl preserves the cursor focus

### Actual Result

- dap open the file where the "next instruction" is (in the buffer defined by `switchbuf`)
- the cursor focus changes to the place where the "next instruction" is

**Comment by alanoliveira** [comment]
It seems a desired behavior instead a bug https://github.com/mfussenegger/nvim-dap/commit/3bde6f786057fa29d8356559b2ae3a52d9317fba.
But would be nice if we could turn it off like `dap.defaults.codelldb.switchfocus = true/false` or even better if it have distinct behavior only for repl

**Comment by mfussenegger** [comment]
That it also jumps out of the REPL was unintended. Should be fixed with https://github.com/mfussenegger/nvim-dap/pull/985
