### ISSUE TITLE
Run several debuggers at same time

### ISSUE THREAD

**Issue by xovobobo** [mfussenegger/nvim-dap#984]
### Problem Statement

Is it possible to run several debuggers in one nvim?

**Comment by mfussenegger** [comment]
Yes. See `:h dap.continue()`:
You can force the selection for a new debug session with:

```
:lua require("dap").continue({ new = true })
```

If using `.run()` directly, it will start a new debug session if the name is different - if it is the same it will restart the session unless `new = true` is set as well.

There is also a `sessions` widget to display the active sessions and switch between them.


(And the issue tracker is for bugs or feature requests, not for general questions - use discussions in the future please)

**Comment by xovobobo** [comment]
> Yes. See `:h dap.continue()`: You can force the selection for a new debug session with:
> 
> ```
> :lua require("dap").continue({ new = true })
> ```
> 
> If using `.run()` directly, it will start a new debug session if the name is different - if it is the same it will restart the session unless `new = true` is set as well.
> 
> There is also a `sessions` widget to display the active sessions and switch between them.
> 
> (And the issue tracker is for bugs or feature requests, not for general questions - use discussions in the future please)

Thank you. It works. But seems like variables windows stores all variables globally.

for example:
1. launch python script. break after line: a = 10
2. launch second  different python script with new session. break after line: b = 22

Now in variables window you will see variables a and b.
