### ISSUE TITLE
make popup window border configurable

### ISSUE THREAD

**Issue by Saecki** [mfussenegger/nvim-dap#986]
### Problem Statement

The border of the hover popup window isn't configurable.

### Possible Solutions

Add a configuration option that is passed the `vim.api.nvim_open_win()` function.

**Comment by mfussenegger** [comment]
`:lua require("dap.ui.widgets").hover(nil, { border = "double" })`

**Comment by Saecki** [comment]
Somehow neovim doesn't support custom borders defined as a table in `vim.api.nvim_win_set_config()`. From what I've seen, the `opts` table could be passed directly to `vim.api.nvim_open_win()` function, and using `vim.tbl_extend()` to overwrite the default options.
