### ISSUE TITLE
Interactive input for go when using vscode-go

### ISSUE THREAD

**Issue by ayamir** [mfussenegger/nvim-dap#987]
### Debug adapter definition and debug configuration

I installed `vscode-go` by `mason`.

```lua
	dap.adapters.go = {
		type = "executable",
		command = "node",
		args = {
			require("mason-registry").get_package("go-debug-adapter"):get_install_path()
				.. "/extension/dist/debugAdapter.js",
		},
	}
	dap.configurations.go = {
		{
			type = "go",
			name = "Debug (file)",
			request = "launch",
			cwd = "${workspaceFolder}",
			program = utils.input_file_path(),
			console = "integratedTerminal",
			dlvToolPath = vim.fn.exepath("dlv"),
			showLog = true,
			showRegisters = true,
			stopOnEntry = false,
		},
		{
			type = "go",
			name = "Debug (file with args)",
			request = "launch",
			cwd = "${workspaceFolder}",
			program = utils.input_file_path(),
			args = utils.input_args(),
			console = "integratedTerminal",
			dlvToolPath = vim.fn.exepath("dlv"),
			showLog = true,
			showRegisters = true,
			stopOnEntry = false,
		},
		{
			type = "go",
			name = "Debug (executable)",
			request = "launch",
			cwd = "${workspaceFolder}",
			program = utils.input_exec_path(),
			args = utils.input_args(),
			console = "integratedTerminal",
			dlvToolPath = vim.fn.exepath("dlv"),
			mode = "exec",
			showLog = true,
			showRegisters = true,
			stopOnEntry = false,
		},
		{
			type = "go",
			name = "Debug (test file)",
			request = "launch",
			cwd = "${workspaceFolder}",
			program = utils.input_file_path(),
			console = "integratedTerminal",
			dlvToolPath = vim.fn.exepath("dlv"),
			mode = "test",
			showLog = true,
			showRegisters = true,
			stopOnEntry = false,
		},
		{
			type = "go",
			name = "Debug (using go.mod)",
			request = "launch",
			cwd = "${workspaceFolder}",
			program = "./${relativeFileDirname}",
			console = "integratedTerminal",
			dlvToolPath = vim.fn.exepath("dlv"),
			mode = "test",
			showLog = true,
			showRegisters = true,
			stopOnEntry = false,
		},
	}

```

### Debug adapter version

0.39.1

### Steps to Reproduce

Create a test project:
```shell
mkdir test_dap_io
cd test_dap_io
touch test_dap_io.go
go mod init
nvim test_dap_io.go
```
Fill the file content with:
```go
package main

import "fmt"

func main() {
	var n = 0
	fmt.Printf("Enter a number: ")
	_, err := fmt.Scanf("%d", &n)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("The enter number is n = %d\n", n)
}
```
1. Set the breakpoint at line 8.
2. Start debug.
3. Next

### Expected Result

Can input in the terminal and redirect it to dap session. 

AFAIK `vscode-go` supports this feature: 
https://github.com/golang/vscode-go/wiki/debugging#configuration
https://github.com/golang/vscode-go/wiki/debugging#handling-stdin

Thanks in advance!

### Actual Result

![image](https://github.com/mfussenegger/nvim-dap/assets/61657399/c157f2ab-82b5-44a5-8f23-2f3acd18438b)
[dap.log](https://github.com/mfussenegger/nvim-dap/files/12104538/dap.log)

**Comment by mfussenegger** [comment]
It looks like vscode-go is currently faking runInTerminal support because it is not implemented in delve:

https://github.com/golang/vscode-go/blob/3eafcb48099690dbd7f3b170b4b241020c837be7/src/goDebugFactory.ts#L433-L457

You'll have to run the debugee externally until they properly implement runInTerminal support in delve. See https://github.com/golang/vscode-go/wiki/debugging#run-debugee-externally

You may be able to create a similar workaround via a adapter function, but it's not something I intend to support.
