### ISSUE TITLE
Press `q` to trigger `dap-float` window close

### ISSUE THREAD

**Issue by eeeXun** [mfussenegger/nvim-dap#990]
### Problem Statement

I want `dap-float` window can be closed via pressing `q`. The float window, like `vim.diagnostic.open_float`, can be closed via key `q`.
Currently, I have to close it by pressing `<C-w>`+`c`, which is a bit cumbersome.

**Comment by mfussenegger** [comment]
You can setup a keymap: `au FileType dap-float nnoremap q <C-w>c`
